### ISSUE TITLE
hostname VS FQDN on the email info section

### ISSUE THREAD

**Issue by moucho** [serghey-rodin/vesta#1002]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

0.9.8 release 17

### Installed Software (what you got with the installer):

apache, nginx, mariadb, php 5.6

### Steps to Reproduce:

In the create email account and edit email account pages, there's a section with IMAP hostname and SMTP hostname, and when using the option "Use server hostname" I think it might be better to use the FQDN (fully qualified domain name) so the url will resolve correcty on the internet.

Any thoughts?

**Comment by Skamasle** [comment]
Hi

If you have a hostnme it will be FQDN so, you need change your hostname to FQDN

Sysadmin of your server need take care about that,

**Comment by dpeca** [comment]
Use `v-change-sys-hostname` command (in SSH) to change server hostname to FQDN.
If it's not FQDN - then you'll be in trouble with SMTP anyway... so you must change hostname to FQDN anyway.
