### ISSUE TITLE
Fail2ban not working correctly

### ISSUE THREAD

**Issue by madeITBelgium** [serghey-rodin/vesta#1005]
### Operating System (OS/VERSION):

CentOS 6.8

### VestaCP Version:

VestaCP installed in 2014, upgraded to v17

### Installed Software (what you got with the installer):

apache, Nginx, MySQL, PHP 5.6

### Other Notes:

2016-12-19 21:37:40 v-add-firewall-chain  'MAIL'
2016-12-19 21:37:40 v-add-firewall-ban  '220.133.39.98' 'MAIL'
2016-12-19 21:47:40 v-delete-firewall-ban  '220.133.39.98' 'MAIL'

The ban record is deleted emidiatly after it is created.

**Comment by didyouexpectthat** [comment]
It says it deleted the ban after 10 minutes, not immediately. 
For me, `/etc/fail2ban/jail.conf:bantime  = 600` -- but I don't know if this is directly related.

**Comment by pablobae** [comment]
if you check your log, the ip was unban 10 minutes after  be baned.
