### ISSUE TITLE
Attempting to enable LetsEncrypt on domain produces error in /tmp

### ISSUE THREAD

**Issue by didyouexpectthat** [serghey-rodin/vesta#1008]
### Operating System (OS/VERSION):
Debian Jessie 8.6

### VestaCP Version:
0.9.8.17

### Installed Software (what you got with the installer):
defaults + filesystem quota
force-https enabled

### Steps to Reproduce:
Previously had letsencrypt installed before it became cool (aka pre-.16)
Auto-update took place from .16 to .17
See letsencrypt option in domain now
Check the box for letsencrypt support, then apply
UI errors:
``Error: /tmp/tmp.CP6ftxhWgr/xyz.crt not found``
I do see something populate in /tmp but disappears so quickly, can't capture the output.

### Related Issues/Forum Threads:
I tried to Google this error, checked github, and but not finding anything. Not sure entirely how the new letsencrypt UI support works.
Also notice that upgrade did not add those letsencrypt cronjobs I noticed.

### Other Notes:
Didn't find anything on the documentation about letsencrypt.
I don't believe I ever installed letsencrypt-vesta. 
I did try v-add-letsencrypt-user for my admin user and other users that may need to get certificates but this did not help.
https://vestacp.com/docs/
Also not seeing what log would give me more insight to follow for this one.
```
==> error.log <==
2016-12-20 16:34:15 v-change-web-domain-sslcert  'admin' 'xyz' '/tmp/tmp.CP6ftxhWgr' 'no' [Error 3]
```
Documentation says error 3 is 3	"E_NOTEXIST	Object doesn't exist"

**Comment by didyouexpectthat** [comment]
```
==> error.log <==
2016-12-20 16:34:15 v-change-web-domain-sslcert  'admin' 'xyz' '/tmp/tmp.CP6ftxhWgr' 'no' [Error 3]
```
Documentation says error 3 is 3	"E_NOTEXIST	Object doesn't exist"

**Comment by iamra** [comment]
Getting same error on same distro version. I have previously had letsencrypt-vesta which has Letsencrypt installed. But am getting the same error after the update.

**Comment by urosg80** [comment]
Are you using apache only or nginx installation?

If you are using apache only installation make sure that the /etc/apache2/conf.d/letsencrypt.conf (I think this is the filename - please check manually) is not included in the configuration as this makes apache to try to serve acme-challenge files from a different folder as vesta creates them, this is because of the previously used letsencrypt-vesta.

**Comment by didyouexpectthat** [comment]
It's apache & nginx.

**Comment by didyouexpectthat** [comment]
Ok, so for myself, I guess about 7 months ago I installed letsencrypt-vesta. I just followed the steps to install in reverse and undid changes. I think it is working now.  

@iamra  try this.

**Comment by didyouexpectthat** [comment]
If I have proxy support enabled, I get "Error: Invalid response from http://xyz.com/acme-challenge/D5W6Ual_XbHu-TEk456FtcUVgzGm1237PJvIwZ_rm0U: \" but without proxy support on, it seems to let me create certificates.

**Comment by iamra** [comment]
@didyouexpectthat I have force-https off already (just default proxy template which other user accounts use and can issue certs successfully).
Are you suggesting that just not using the force-https template was enough to fix your error? or was reinstalling letsencrypt-vesta your solution?

**Comment by didyouexpectthat** [comment]
I am suggesting the following:
rm -rf /usr/local/letsencrypt-vesta
rm -rf /etc/letsencrypt/webroot
rm /usr/local/bin/letsencrypt-vesta
rm /etc/apache2/conf.d/letsencrypt.conf (or rm /etc/httpd/conf.d/letsencrypt.conf)
systemctl restart apache2

I didn't do the nginx configuration, but undo whatever you may have done here: https://github.com/interbrite/letsencrypt-vesta/blob/master/README.md


systemctl restart nginx

Remove any cron job from crontab.

Then, turn off SSL support on the domain.
Then turn on SSL support and letsencrypt support.

Then you should get certificates.

**Comment by iamra** [comment]
@didyouexpectthat Yes I will test. (I have an issue submitted in letsencrypt-vesta repo and for a moment there I did not realize I was in the Vesta repo for the official Letsencrypt support bug, it makes sense to have to remove the letsencrypt-vesta plugin, thank you for clarifying).

**Comment by iamra** [comment]
I can confirm this has corrected the error for me. I completely removed Letsencrypt-vesta by reversing the directions as stated by @didyouexpectthat, then I changed the proxy template back to default, disabled ssl to clear the previous cert, then checked Lets Encrypt Support and saved. Cert was issued successfully. Vesta keeps getting better!

**Comment by jimmyeao** [comment]
@didyouexpectthat Thanks, you have saved me from pulling the rest of my hair out after a frustrating morning!
