### ISSUE TITLE
PHP 7 v-add-web-domain-backend fails with error 3 when /etc/php5 exists

### ISSUE THREAD

**Issue by drsdre** [serghey-rodin/vesta#1019]
### Operating System (OS/VERSION):

Ubuntu 14.04

### VestaCP Version:

R17 upgrade from R16.

### Installed Software (what you got with the installer):

php-fpm , apache, nginx, mysql

PHP 5 from ondrej-php5-trusty (expired) upgraded to PHP 7.0 from ondrej-php-trusty

### Steps to Reproduce:

Setup new domain in web interface, and process fails with error code 3. Issue is related to script v-add-web-domain-backend which fails on finding fpm pools when both /etc/php/7.0/fpm/pool.d and /etc/php5/fpm/pool.d exists. This is debug log from v-add-web-domain-backend execution:

+ prepare_web_backend
++ find /etc/php /etc/php5 /etc/phpmyadmin -type d '(' -name pool.d -o -name '*fpm.d' ')'
+ pool='/etc/php/7.0/fpm/pool.d
/etc/php5/fpm/pool.d'
+ '[' '!' -e '/etc/php/7.0/fpm/pool.d
/etc/php5/fpm/pool.d' ']'
+ check_result 3 'php-fpm pool doesn'\''t exist'
+ '[' 3 -ne 0 ']'
+ echo 'Error: php-fpm pool doesn'\''t exist'
Error: php-fpm pool doesn't exist
+ '[' '!' -z '' ']'

### Related Issues/Forum Threads:

Other users have also experienced this http://forum.vestacp.com/viewtopic.php?f=41&t=13201&p=53188&hilit=v+add+web+domain+backend#p53188

### Other Notes:

If VestaCP will support multiple PHP versions, this bug will need to be solved.

**Comment by Skamasle** [comment]
Vestacp alredy not support multiple php versión, you do a custom changes / upgrades so this is not a vestabug

But yes, this need fix because a lot of people change to php 7 but maybe the problem is php 7 setup than is not compatible whit vestacp and need some symlinks.

I will try reproduce this error later.

**Comment by drsdre** [comment]
See also https://github.com/serghey-rodin/vesta/issues/1025 which is the same kind of issue (with a different effect). Probably the fixes from that post can be applied to this issue also.

**Comment by anton-reutov** [comment]
Vesta is not supported multi php yet
