### ISSUE TITLE
MySQL username supports up to 16 characters, but, the USER name can have more then I'm stuck.

### ISSUE THREAD

**Issue by crackdepirate** [serghey-rodin/vesta#1023]
### Operating System (OS/VERSION):

Ubuntu 16.04 (x86_64)

### VestaCP Version:

core package	
Version:0.9.8 (amd64)	
Release:17

### Installed Software (what you got with the installer):

nginx, php-fpm, exim, dovecot, php7, mysql5.7

### Steps to Reproduce:

1. create a user with 16 characters.
2. create a db with username as "a" 
then, you will receive popup message with "Error: mysql username can be up to 16 characters long"

### Related Issues/Forum Threads:

Found anything that might be related to this? It might help us find the cause.

### Other Notes:

Anything else?

thx you,

**Comment by crackdepirate** [comment]
humm. nevermind: copy here : https://github.com/serghey-rodin/vesta/issues/860

**Comment by dpeca** [comment]
16 character without prefix?

**Comment by crackdepirate** [comment]
@dpeca yes without the prefix.

**Comment by dpeca** [comment]
yes, but when we talk about 16 chars limit, we think about prefix+mysql_username length, which is 19 for 'patrickmccardiant_a'

**Comment by crackdepirate** [comment]
@dpeca  yes indeed. with that username 'patrickmccardiant_a'. I receive a pop-up msg with "Error: mysql username can be up to 16 characters long". I thought that mysql username was the part without the prefix. So could you limit the mysql username textbox in that case ? or limit character for any vesta username ?

**Comment by dpeca** [comment]
Yes, I can, but I think not everyone agreed with that idea here - https://github.com/serghey-rodin/vesta/issues/860
However, let's continue discusion there.

**Comment by crackdepirate** [comment]
Yeah! thx you for your support, have a good one, and.... happy new year. :P

**Comment by iamra** [comment]
Limiting vesta usernames, or the prefix of DB in case of mysql, is very important.
Most new Vesta users may not know that the username they choose becomes prefix for the DB user (at least I had that issue).
It would be very helpful to correct this issue in a more automated way, I currently limit my account usernames to 6-8 characters, and count down the username on the db, not very efficient.

**Comment by Luc45** [comment]
Same issue here.
