### ISSUE TITLE
migration from php fpm to Apache 

### ISSUE THREAD

**Issue by darkworks** [serghey-rodin/vesta#1033]
### Operating System (OS/VERSION):

Type here, e.g. Debian 8.6

### VestaCP Version:

Latest build 17 

### Installed Software (what you got with the installer):

Type here, e.g. php-fpm, nginx, mariadb

i have setup new vps with nginx and php-fpm   , after setting up and tweaking server when i loaded my php script i noticed that php fpm cant read htaccess files which is creating problem for me , so i was wondering that can i remove php fpm and switch back to Apache without new installation 

thanks

**Comment by Skamasle** [comment]
Actually is not posible change that in easy way

If you what do that you need install apache, edit vestacp configuartion files, move some vhost, rebuild a lot of thinks.

Is easyest convert your .htaccess rules to be compatibles whit nginx, is you use wordpress, prestashop, joomla or any well known CMS you can easy convert it, vestacp also support rewrite rules for some CMS.

If not you can buy cheap vps, make backups in it, reinstall your current server whit apache and restore your backups.

**Comment by darkworks** [comment]
ya thanks :) , i did fresh install again ..
