### ISSUE TITLE
v-add-mail-domain breaks exim4 in Debian 8.7

### ISSUE THREAD

**Issue by huloza** [serghey-rodin/vesta#1040]
### Operating System (OS/VERSION): 

Debian 8.7

### VestaCP Version:

0.9.8-17

### Installed Software (what you got with the installer):

–nginx yes –apache yes –phpfpm no –vsftpd no –proftpd yes –exim yes –dovecot yes –spamassassin yes –clamav yes –named yes –iptables yes –fail2ban yes –mysql no –postgresql no –remi yes –quota yes

### Steps to Reproduce:

Create a new mail domain

### Other Notes:

On default installation the dir **/etc/exim4/domains** is _chmod 755 or drwxr-xr-x_

in **v-add-mail-domain** after adding the mail domain the program **_chmods the dir to 771 or drwxrwx--x_**: 

```
# Set permission
    chmod 771 $HOMEDIR/$user/conf/mail/$domain
    chmod 660 $HOMEDIR/$user/conf/mail/$domain/*
    chmod 771 /etc/$MAIL_SYSTEM/domains/$domain_idn
    chmod 770 $HOMEDIR/$user/mail/$domain_idn
```

this causes the following error on exim log when trying to send mails:

```
2017-01-19 03:28:46 failed to open /etc/exim4/domains/ for directory search: Permission denied (euid=107 egid=112)
2017-01-19 03:33:03 failed to open /etc/exim4/domains/ for directory search: Permission denied (euid=107 egid=112)
2017-01-19 03:33:03 failed to open /etc/exim4/domains/ for directory search: Permission denied (euid=107 egid=112)

```

**Comment by dpeca** [comment]
If you are using latest github source, this commit broke a lot of stuff - https://github.com/serghey-rodin/vesta/commit/e5950d516d52fe4776c6527676d0823780a7f8d7

I warned people on errors in that commit.

From the error you posted, I guess that's it.
Please roll back git state one commit before that, and check if bug is still, there.
