### ISSUE TITLE
Broken code in master branch that can lead to data loss

### ISSUE THREAD

**Issue by dpeca** [serghey-rodin/vesta#1062]
After this commit -> https://github.com/serghey-rodin/vesta/commit/e5950d516d52fe4776c6527676d0823780a7f8d7 - there are several critical bugs that can lead to data loss.

`$domain_idn` is not defined in some scripts.
I noticed that in script `bin/v-delete-mail-domain` - but it's probably in other scripts too - if we carefully analyze mentioned commit - we can see in what scripts `$domain_idn` is accidentally deleted.

But lets analyze `bin/v-delete-mail-domain` for example ( https://github.com/serghey-rodin/vesta/blob/master/bin/v-delete-mail-domain ).
Firstly, `$domain_idn` is not defined at all.
Then, on line 52, we have this line:
`rm -rf $HOMEDIR/$user/mail/$domain_idn`
Since `$domain_idn` is not defined, system will execute this line as:
`rm -rf $HOMEDIR/$user/mail/`
... and it will delete ALL other domains and all their email accounts that is created under the same VestaCP user account.

Since  `$domain_idn` is not defined in many other scripts - data loss can happen in other scripts too.
If we carefully analyze mentioned commit - we can find in what scripts `$domain_idn` is accidentally deleted.

By the way, I strongly recommend people NOT to use code from github on their production machines, at least until we fix this issue.

**Comment by pcfreak30** [comment]
I believe I improved on this with #1027

**Comment by dpeca** [comment]
I know you did it - I saw elegant solution for fix in your commit ( https://github.com/serghey-rodin/vesta/pull/1027/commits/92895b095f11588b2555d43e48d80399d7eeed1a and few more comits).
But your commit is so big that only @serghey-rodin should review it and accept it - so that is why we still wait.
Maybe we should implement only fix for this critical issue - but @anton-reutov said that we should wait for Serghey.

**Comment by dpeca** [comment]
OK, I think it's enough of waiting, @serghey-rodin is obviously busy, and we should do something - because it is obviously that some people use code from broken master branch - they can easily make a hell to themself - and it's not good to just watch it - we should do something.

I carefuly went through @serghey-rodin commit, checked each file, and added missing `$domain_idn` .
Here is the commit - https://github.com/serghey-rodin/vesta/commit/6d88ca31c3fbbc5bfdc4753206a03ac3d4e6e04c

Tomorrow I'll check my commit again - just to be sure I didn't miss something or made typo (74 files are fixed, not easy to be sure that everything is correctly added missing domain_idn).

I could not aprove @pcfreak30 push request - because a much larger code is modified in that push request - and that should Serghey review and accept.
Specially because I'm not sure where we should use $domain and where $domain_idn - I think Serghey knows that better.
I'll help @pcfreak30 to resolve conflicts that happend after my commit - so PR can be accepted when/if Serghey decide it.

I hope master branch is again functional - after almost 2 months.

**Comment by dpeca** [comment]
Accidantelly deleted letter 'i' - fixed - https://github.com/serghey-rodin/vesta/commit/5965b5a88ec43c26ebd01c23c9b27e4d2f0f0be3

As I said, not easy when commit is large, accidentally type is just happening...

**Comment by dpeca** [comment]
Everything checked.
Found only one missed place - fixed - https://github.com/serghey-rodin/vesta/commit/a005c3e24a2496647dcaf017621c966acc5346b6

This issue is fixed now.
I'm closing it.

In next 15 days I'll help @pcfreak30 to merge these changes (in master) to his push-request, so it can be merged back to master when/if @serghey-rodin decide.

**Comment by dpeca** [comment]
It looks like there were only on conflict, I solved it, so his push request https://github.com/serghey-rodin/vesta/pull/1027 is mergeable.

**Comment by dpeca** [comment]
Just to put here the record about additional commits that I made (in last few days) to ensure that $domain_idn is set:
- https://github.com/serghey-rodin/vesta/commit/a005c3e24a2496647dcaf017621c966acc5346b6
- https://github.com/serghey-rodin/vesta/commit/887ac8a11b9b8c9e5ca195f2f520c035a611a329
- https://github.com/serghey-rodin/vesta/commit/56cdadbe5c9f61a0ff68c0a14a5f39fe2d7454d8

**Comment by pcfreak30** [comment]
@dpeca HACK ALERT :P

**Comment by dpeca** [comment]
?

**Comment by dpeca** [comment]
What are you talking about???

**Comment by pcfreak30** [comment]
@dpeca the means your fixing it is very hacky.

**Comment by dpeca** [comment]
Why?

It just follow Sergheys conception - I didn't change **format_domain_idn** function behavior without his confirmation.

Secondly, it's semantic - it's clearly set **$domain_idn** in each script - so when someone read the code of script he can see on the same place what is **$domain_idn** `( domain_idn=$2 )`

Thirdly, I just made a inventory in what scripts we use **format_domain_idn** without using **$domain_idn** at all - and left a notation in those scripts - so @serghey-rodin can easily see in what scripts we maybe we forgot to use **$domain_idn**

**Comment by dpeca** [comment]
Generally, it's just a bugfix commit - that does not change behavior nor improve the scripts - it's just a simple bugfix.
I left to you (to your push request) improvments with changing **$domain** to **$domain_idn**

**Comment by pcfreak30** [comment]
@dpeca it seems somehow though when pushing that you modified my 2026 branch with your changes despite me not remembering give you access as I had to pull 1st and got all of what you did. Im either tired or crazy.

**Comment by dpeca** [comment]
Huh, sorry, but the same things would provbably do anybody that would patch this issue... I didn't know that you had 2026 branches... if you want a help in clearing a conflicta, feel free to call me, I will help you as I planned to help you with https://github.com/serghey-rodin/vesta/pull/1027 to clear conflicts.

**Comment by pcfreak30** [comment]
@dpeca i already resolved them due to intellij :)

**Comment by pcfreak30** [comment]
@dpeca "Allow edits from maintainers." was checked somehow and I was not aware.
