### ISSUE TITLE
CentOS 7 Fail mount /home after install vesta

### ISSUE THREAD

**Issue by rfzh1996** [serghey-rodin/vesta#1078]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

0.9.8

### Installed Software (what you got with the installer):

nginx, apache, named, vsftpd, iptables, fail2ban, exim, dovecot, spamassassing, clamav, mysql, postgresql

### Steps to Reproduce:

1. Install vesta 
2. Reboot

### Other Notes:

I use CentOS 7 iso 1611 , 1511 in minimal

**Comment by Skamasle** [comment]
Fail mount /home ?

Is /home extra partition in your server ?

You enable quotas ?

Can you give more information, what error exactly you get ?

**Comment by rfzh1996** [comment]
@Skamasle I only install minimal CentOS 7 and after the comand: 
`bash vst-install.sh --nginx yes --apache yes --phpfpm no --vsftpd yes --proftpd no --exim yes --dovecot yes --spamassassin yes --clamav yes --named yes --iptables yes --fail2ban yes --mysql yes --postgresql yes --remi yes --quota yes` 

after this i reboot and i see this error. and CentOS dont boot

**Comment by Skamasle** [comment]
Hi, this need a debug.

if you can run in "rescue" maybe logs are needed, but if partitions is not mounted you have a quota problem.

Can you check your /etc/fstab ?

**Comment by rfzh1996** [comment]
Sure what file you need?

**Comment by SysVoid** [comment]
`cat /etc/fstab`
