### ISSUE TITLE
v-update-letsencrypt-ssl script sets ssl home dir as public_html

### ISSUE THREAD

**Issue by scorp13** [serghey-rodin/vesta#1079]
For domains with ssl root directory has been set as public_shtml. Once the v-update-letsencrypt-ssl script work out, root directory change on public_html.

**Comment by scorp13** [comment]
As I understand, scripts, that are associated with ssl-home, run in next order
v-update-letsencrypt-ssl 
	50 -> $BIN/v-add-letsencrypt-domain $user $domain $aliases 
		112	-> $BIN/v-add-web-domain-ssl $user $domain $ssl_dir
as a result - v-add-web-domain-ssl performed without SSL_HOME parameter and sets it on the default value
ssl_home = $ {4-same}
so it's necessary to determine the domain's ssl_home parameter in v-add-letsencrypt-domain and pass it when calling the v-add-web-domain-ssl

By the way, based on the proposals in the header of v-add-web-domain-ssl "If home directory  parameter (ssl_home) is not set, https domain uses public_shtml as separate documentroot directory." the default value for ssl_home seem to be "single"?

**Comment by Skamasle** [comment]
By default I think is set as public_html, I really not know some body than use public_shtml actully people only use public_html for ssl and non/ssl site I think is unecesary extra dir for ssl in this time.

**Comment by scorp13** [comment]
Regarding the default value - I assumed it from the text of the script header.
