### ISSUE TITLE
Backup error when multiple domains under user

### ISSUE THREAD

**Issue by robindirksen1** [serghey-rodin/vesta#1081]
### Operating System (OS/VERSION):

CentOS 6.5

### VestaCP Version:

0.9.8-17

### Installed Software (what you got with the installer):

default installer

### Steps to Reproduce:

-

### Related Issues/Forum Threads:

https://forum.vestacp.com/viewtopic.php?f=29&t=13803&p=56231&hilit=line+238#p56231

### Other Notes:

The backup isn't getting the data from the folder /home/*user*/web/*domain.tld*/*. The error is:
```
/usr/local/vesta/func/domain.sh: line 238: 3
40: syntax error in expression (error token is "40")
```

```
# Get config top and bottom line number
get_web_config_lines() {
    tpl_lines=$(egrep -ni "name %domain_idn%" $1 |grep -w %domain_idn%)
    tpl_lines=$(echo "$tpl_lines" |cut -f 1 -d :)
    tpl_last_line=$(wc -l $1 |cut -f 1 -d ' ')
    if [ -z "$tpl_lines" ]; then
        check_result $E_PARSING "can't parse template $1"
    fi

    vhost_lines=$(grep -niF "name $domain_idn" $2)
    vhost_lines=$(echo "$vhost_lines" |egrep "$domain_idn($| |;)") #"
    vhost_lines=$(echo "$vhost_lines" |cut -f 1 -d :)
    if [ -z "$vhost_lines" ]; then
        check_result $E_PARSING "can't parse config $2"
    fi

    top_line=$((vhost_lines + 1 - tpl_lines))                              ##line 238
    bottom_line=$((top_line - 1 + tpl_last_line))
    multi=$(sed -n "$top_line,$bottom_line p" $2 |grep ServerAlias |wc -l)
    if [ "$multi" -ge 2 ]; then
        bottom_line=$((bottom_line + multi -1))
    fi
}
```

I have to domains:
- mydomain.tld
- support.mydomain.tld

The error came after mydomain.tld, but when I changed the code in `domain.sh` to the following it processed right with no errors:

```
vhost_lines=3
top_line=$((vhost_lines + 1 - tpl_lines))
```

When the `vhost_lines` was manually assigned to 3 it worked correct, when I echo `vhost_lines` it returns: `3 40`, it looks like he isn't splitting the string when there are spaces in the string.

**Comment by Skamasle** [comment]
I cant reproduce this, in vestacp whit v17 whit multiple domains in account backup working fine.

**Comment by robindirksen1** [comment]
Can you explain what the function `get_web_config_lines()` in func/domain.sh does?

**Comment by robindirksen1** [comment]
I figger out that the config from the user (/home/user/conf/web/httpd.conf) searches for the domain in the file. But this is dubble in it (line 3 and 40). I think this came through the backup that I set back. That's why the domain is dubble in the httpd.conf file.

**Comment by Skamasle** [comment]
Try rebuild vhosts

**Comment by robindirksen1** [comment]
@Skamasle fixes the error!
