### ISSUE TITLE
pkey: Invalid format "perm" for -inform

### ISSUE THREAD

**Issue by modos189** [serghey-rodin/vesta#1085]
### Operating System (OS/VERSION):

Debian Testing
`Linux MYDOMAIN 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux`

### VestaCP Version:

0.9.8 (amd64) Release: 17

### Installed Software (what you got with the installer):

openssl version
OpenSSL 1.1.0d  26 Jan 2017

### Steps to Reproduce:

v-add-letsencrypt-domain USER DOMAIN

> pkey: Invalid format "perm" for -inform
> pkey: Use -help for summary.
> Error: LetsEncrypt account registration 400

I found, that it can be fixed, if in _/usr/local/vesta/bin/v-add-letsencrypt-user_

`exponent=$(openssl pkey -inform perm -in "$key" -noout -text_pub |\`

replace to

`exponent=$(openssl pkey -inform pem -in "$key" -noout -text_pub |\`

**Comment by Skamasle** [comment]
Hi

Officialy debian testing is not supported by vesta.

And I not see any diference in your code ?

> exponent=$(openssl pkey -inform perm -in "$key" -noout -text_pub |\
> 
> replace to
> 
> exponent=$(openssl pkey -inform pem -in "$key" -noout -text_pub |\

**Comment by modos189** [comment]
>> Officialy debian testing is not supported by vesta.
yes, so it's not pull-request :) 

perm > pem

I have to admit, I never really delved into this subject, but this change worked for me.

**Comment by Skamasle** [comment]
Oh My bad, I not see that "R" sorry

**Comment by SysVoid** [comment]
Unsupported OS.
