### ISSUE TITLE
CentOS 7 installation is broken because of latest fail2ban vesrion

### ISSUE THREAD

**Issue by dpeca** [serghey-rodin/vesta#1086]
Just to quote already posted issue (but in wrong thread) :

> adnanebrahimi commented a day ago
> 
> when i start vestacp installation on my fresh centos 7 vps in middle of installation when we proceed to installing fail2ban and starting service, fail2ban cannot start and show error:
> Job for fail2ban.service failed because the control process exited with error code.
> and vestacp installation stops.

I'm confirming this issue.
At this moment **VestaCP installation is totally broken on CentOS 7**.
I'll push in next few minutes commit that will fix this.
I'll post here solution in next 15 minutes.

**Comment by dpeca** [comment]
Background of issue:

```
tailf /var/log/messages

Feb 17 19:40:27 localhost systemd: Cannot add dependency job for unit microcode.service, ignoring: Unit is not loaded properly: Invalid argument.
Feb 17 19:40:27 localhost systemd: Starting Fail2Ban Service...
Feb 17 19:40:27 localhost fail2ban-client: ERROR  There is no directory /var/run/fail2ban to contain the socket file /var/run/fail2ban/fail2ban.sock.
Feb 17 19:40:27 localhost systemd: fail2ban.service: control process exited, code=exited status=255
Feb 17 19:40:27 localhost systemd: Failed to start Fail2Ban Service.
Feb 17 19:40:27 localhost systemd: Unit fail2ban.service entered failed state.
Feb 17 19:40:27 localhost systemd: fail2ban.service failed.
Feb 17 19:40:27 localhost systemd: fail2ban.service holdoff time over, scheduling restart.
```

and it goes in infinite loop...

**Comment by dpeca** [comment]
Fix - https://github.com/serghey-rodin/vesta/commit/309abec58f2a6601bb10b219e19f874c849691c7

**Comment by dpeca** [comment]
Since fixed installation is not yet uploaded to official Vesta repo, you can install Vesta this way:

Insted of:
```
curl -O http://vestacp.com/pub/vst-install.sh
bash vst-install.sh
```

Run:
```
curl -O https://raw.githubusercontent.com/serghey-rodin/vesta/master/install/vst-install-rhel.sh
bash vst-install.sh

```

**Comment by SysVoid** [comment]
Thank you @dpeca!

**Comment by anton-reutov** [comment]
@dpeca please show installer log with this error

**Comment by dpeca** [comment]
@anton-reutov here it is - http://pastebin.com/raw/Jp8v8Ch9
You can just try to install Vesta17 on CentOS7 and this will happen.
@skurudo confirmed on dev mailing list, my friends also.

Bug is fixed by https://github.com/serghey-rodin/vesta/commit/309abec58f2a6601bb10b219e19f874c849691c7 so this issue can be marked as fixed - but because many people will looking on github in order to find a soultion - let stay this as not fixed so it can be visible in Issues tab. 
People also asks on forum about this issue, and I'm pasting them a link to this page.

**Comment by anton-reutov** [comment]
Yes. Confirmed

**Comment by SysVoid** [comment]
:+1:

**Comment by madeITBelgium** [comment]
I think it is also fixed by centos/red hat  https://bugzilla.redhat.com/show_bug.cgi?id=1422500

**Comment by dpeca** [comment]
Let someone try to install Vesta with public installer and check if it will pass....

**Comment by skazhikadyadya** [comment]
Hello.
```
Note: Forwarding request to 'systemctl enable fail2ban.service'.
Created symlink from /etc/systemd/system/multi-user.target.wants/fail2ban.service to /usr/lib/systemd/system/fail2ban.service.
Redirecting to /bin/systemctl start  fail2ban.service
Error: user enp6s0 doesn't exist
Error: user enp6s0 doesn't exist
Note: Forwarding request to 'systemctl enable iptables.service'.
Created symlink from /etc/systemd/system/basic.target.wants/iptables.service to /usr/lib/systemd/system/iptables.service.
grep: /usr/local/vesta/data/ips/*: No such file or directory
grep: /usr/local/vesta/data/ips/*: No such file or directory
Error: no IP is available
Error: can't create myshop.eu domain
[root@CentOS-73-64-minimal ~]# 
```

With your installer and with official installer. ^(

**Comment by David-Kurniawan** [comment]
Hi...
i've same problem [centos 7.3]

installation stuck on:

`Note: Forwarding request to 'systemctl enable fail2ban.service'.
Created symlink from /etc/systemd/system/multi-user.target.wants/fail2ban.service to /usr/lib/systemd/system/fail2ban.service.
Redirecting to /bin/systemctl start fail2ban.service
Note: Forwarding request to 'systemctl enable iptables.service'.
Created symlink from /etc/systemd/system/basic.target.wants/iptables.service to /usr/lib/systemd/system/iptables.service`

i've use master installer

FYI:
if i install on vps, default installer is working fine, but if i try install in baremetal server, i get error :(

Help me...

**Comment by Luc45** [comment]
Hi! How can I fix this for my already installed Vesta? Thanks a lot!

**Comment by madeITBelgium** [comment]
@Luc45 what problem (error) do you exactly have? Have you already updated everything? (yum update)

**Comment by Luc45** [comment]
@madeITBelgium sorry for the vague comment. Fail2Ban is not banning. When I run `fail2ban-client status ssh-iptables` it returns 0 for everything:

```
[root@myserver~]# fail2ban-client status ssh-iptables
Status for the jail: ssh-iptables
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- Journal matches:  _SYSTEMD_UNIT=sshd.service + _COMM=sshd
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:
```
Even though I have thousands of failed login attempts.

 I've updated Fail2Ban that comes with Vesta 0.9.7 to 11.0.3-dev, but didn't help. These is the file `/etc/fail2ban/jail.local`:

```
[ssh-iptables]
enabled  = true
filter   = sshd
action   = vesta[name=SSH]
logpath  = /var/log/secure

[vsftpd-iptables]
enabled  = false
filter   = vsftpd
action   = vesta[name=FTP]
logpath  = /var/log/vsftpd.log
maxretry = 5

[exim-iptables]
enabled = true
filter  = exim
action  = vesta[name=MAIL]
logpath = /var/log/exim/main.log

[dovecot-iptables]
enabled = true
filter  = dovecot
action  = vesta[name=MAIL]
logpath = /var/log/dovecot.log

[mysqld-iptables]
enabled  = false
filter   = mysqld-auth
action   = vesta[name=DB]
logpath  = /var/log/mysqld.log
maxretry = 5

[vesta-iptables]
enabled = true
filter  = vesta
action  = vesta[name=VESTA]
logpath = /var/log/vesta/auth.log
maxretry = 5
```

I can't make the services fail2ban, iptables and firewalld run at the same time. If I start firewalld, iptables exits, and vice-versa.

I'm a good PHP programmer, but I'm not that into DevOps, so I'm really having a hard time with this.
