### ISSUE TITLE
Please remove this commit  b370cbf ( dns records issue )

### ISSUE THREAD

**Issue by Skamasle** [serghey-rodin/vesta#1087]
Please remove this pull -> b370cbf

There is more problems there, the issue:

Here my last added dns record from vestagui

```
	14400	IN	A		192.168.1.2
	14400	IN	A		1.1.1.1
test	14400	IN	CNAME		google.com.
	14400	IN	CNAME		google.com.
rest	14400	IN	CNAME		cle.net.
hola	14400	IN	CNAME		google.com.
noda.	14400	IN	CNAME		cle.net.
hola.	14400	IN	A		15.56.6.6
mas.	14400	IN	A		192.5.6.6
ggh	14400	IN	CNAME		google.com.
hola.net	14400	IN	A		192.168.1.96
ho.stia	14400	IN	CNAME		cle.net.
re-	14400	IN	CNAME		google.com.
holak_	14400	IN	CNAME		cle.net.
gesa--	14400	IN	CNAME		cle.net.
	14400	IN	CNAME		google.com.
```

Is posible add records whit .... and ---- and ____ also is posible do it whit A records, and empty ns are a mistery.

Is posible remove all dots whit

```
if [[ $rtype =~ A|NS|CNAME|MX|PTR|SRV ]]; then
    trailing_dot2=$(echo $record | grep "\.$")
    if [ ! -z "$trailing_dot2" ]; then
        record=$(echo "$record" | sed 's/\.*$//')
    fi
fi
```

But that not solve orther characters, this need will be fixed in is_format_valid function

**Comment by dpeca** [comment]
@SysVoid

**Comment by SysVoid** [comment]
Commit reverted.

**Comment by Skamasle** [comment]
Will be good if this stay open as issue reported because bug tracker is off.

**Comment by Skamasle** [comment]
Not worrie about that, found a solution in function is_common_format_valid

**Comment by anton-reutov** [comment]
@Skamasle the bug tracker is working now

**Comment by Skamasle** [comment]
Take a look here
https://github.com/serghey-rodin/vesta/pull/1091/files
