### ISSUE TITLE
linode centos 7 install not work

### ISSUE THREAD

**Issue by LiMoon** [serghey-rodin/vesta#1089]
### Operating System (OS/VERSION):

CentOS 7 (Linode 4.8.6 or Latest 64 bit 4.9.7)

### Installed Software (what you got with the installer):

--nginx yes --apache yes --phpfpm no --vsftpd yes --proftpd no --exim no --dovecot no --spamassassin no --clamav no --named yes --iptables yes --fail2ban yes --mysql yes --postgresql no --remi yes --quota yes

### Steps to Reproduce:

bash vst-install.sh not work.
error : fail2ban start failed

but, --fail2ban yes change --fail2ban no, install is work.

**Comment by dpeca** [comment]
Duplicated issue - https://github.com/serghey-rodin/vesta/issues/1086
Solution is also there.

**Comment by LiMoon** [comment]
thx dpeca.
