### ISSUE TITLE
Update Version of PHP and MySQL

### ISSUE THREAD

**Issue by rinkuyadav999** [serghey-rodin/vesta#1090]
### Operating System (OS/VERSION):

Ubuntu 14.04

### VestaCP Version:

 0.9.8 (amd64)

### Installed Software (what you got with the installer):

PHP 5.5.9-1ubuntu4.20, apache, nginx, mysql 5.5.53, bind9, exim4, dovecot, vsftpd, cron, iptables, fail2ban

### Steps to Reproduce:

You have PHP 5.5.9-1ubuntu4.20 - We recommend a minimum PHP version of 5.6.
You have MySQL 5.5.53 - We recommend a minimum MySQL version of 5.6.
Please update version of PHP and MySQL.

### Related Issues/Forum Threads:

--

### Other Notes:

--

**Comment by dpeca** [comment]
PHP version is related to Ubuntu version and its repo.
Update Ubuntu version or add apt repo that has PHP 5.6.
This is not related to VestaCP.
