### ISSUE TITLE
Fail2Ban Issue on Fresh Install

### ISSUE THREAD

**Issue by MikeP1990** [serghey-rodin/vesta#1095]
Getting the following error installing on a fresh CentOS 7.3.1611 64Bit
---
--2017-02-22 21:29:04--  http://c.vestacp.com/rhel/7/fail2ban.tar.gz
Resolving c.vestacp.com (c.vestacp.com)... 104.236.66.100
Connecting to c.vestacp.com (c.vestacp.com)|104.236.66.100|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 738 [application/octet-stream]
Saving to: ‘fail2ban.tar.gz’

100%[=====================================================================================================================================================>] 738         --.-K/s   in 0s      

2017-02-22 21:29:05 (62.4 MB/s) - ‘fail2ban.tar.gz’ saved [738/738]

Note: Forwarding request to 'systemctl enable fail2ban.service'.
Created symlink from /etc/systemd/system/multi-user.target.wants/fail2ban.service to /usr/lib/systemd/system/fail2ban.service.
Redirecting to /bin/systemctl start  fail2ban.service
Job for fail2ban.service failed because the control process exited with error code. See "systemctl status fail2ban.service" and "journalctl -xe" for details.
Error: fail2ban start failed

**Comment by dpeca** [comment]
https://github.com/serghey-rodin/vesta/issues/1086
Solution is also there.
