### ISSUE TITLE
Security Contact

### ISSUE THREAD

**Issue by Arinerron** [serghey-rodin/vesta#1096]
Hello,

Where should I report vulnerabilities? I'd prefer via email & pgp, but I can't find who to email. Is there some other way I'm supposed to do it?

Thanks!

**Comment by anton-reutov** [comment]
Hi,
Please send your report via info@vestacp.com

**Comment by Arinerron** [comment]
@anton-reutov They didn't respond when I emailed them asking for a pgp key. Think I should send it unencrypted?

**Comment by dpeca** [comment]
@Arinerron feel free to send it also on dev@vestacp.com so dev teams can handle it.
There is no need for pgp key.

**Comment by Arinerron** [comment]
Okay, thanks a lot guys.
