### ISSUE TITLE
Fail2Ban fails when enabling vsftpd and mysql

### ISSUE THREAD

**Issue by MikeP1990** [serghey-rodin/vesta#1103]
Hello,

When I edit the fail2ban configuration via Vesta, I try to enable vsftpd and mysql;

```
[vsftpd-iptables]
enabled  = false
filter   = vsftpd
```
to
```
[vsftpd-iptables]
enabled  = true
filter   = vsftpd
```

I do the same for mysql but Fail2Ban fails to start after doing this.

Thanks,

Mike

**Comment by pbajno** [comment]
+1

**Comment by anton-reutov** [comment]
Write more about your server configuration

**Comment by anton-reutov** [comment]
Let me know if this problem exist in 0.9.8-18
