### ISSUE TITLE
quotaon: cannot find //aquota.group on /dev/root

### ISSUE THREAD

**Issue by iandk** [serghey-rodin/vesta#1107]
### Operating System (OS/VERSION):

Debian 8

### VestaCP Version:

 Vesta 0.9.8-17

### Installed Software (what you got with the installer):

Apache, ProFTPd, exim + dovecot, Named, iptables, MySQL, Quota

### Steps to Reproduce:

When enabling quota in the vestaCP installer, the installer outputs the following:

`
quotaon: cannot find //aquota.group on /dev/root [/]
`
`
quotaon: cannot find //aquota.user on /dev/root [/]
`
The issue is caused due attempting to remount the filesystem read-only.
I fixed it in my PR:
https://github.com/serghey-rodin/vesta/pull/1098

**Comment by anton-reutov** [comment]
I cant reproduce this issue on our test servers with Debian 8

**Comment by ianklemm** [comment]
The issue only occurs on some virtual servers.
