### ISSUE TITLE
Proxy setting becomes unset by user because form element does not exist for them

### ISSUE THREAD

**Issue by webworker01** [serghey-rodin/vesta#1108]
### Operating System (OS/VERSION):

Ubuntu 16.04LTS

### VestaCP Version:

0.98-17

### Installed Software (what you got with the installer):

apache, nginx, mysql

### Steps to Reproduce:

Login as user (not masqueraded) 
Go to form for domain/web entry (template: user/edit_web.html no proxy setting exists here) 
Submit form (with or without changes)
Login as admin and check same domain entry - proxy setting is now unchecked and nginx.conf for domain has now been removed

**Comment by madeITBelgium** [comment]
fixed with #1111
