### ISSUE TITLE
ask for improvement : Exim & Dovecot with Let's Encrypt

### ISSUE THREAD

**Issue by jodumont** [serghey-rodin/vesta#1117]
> I did it; but I don't really know how to integrating it to vestacp
> so if anybody is welling to cooperate on this improvement, i'm willing to sky^^e, call, ... collaborating on it.
> 
> I think it would be a great improvement to make all mail.$Domain.tld protocol encrypted with a SSL offer by Let's Encrypt

### Steps to Reproduce:

add a website mail.$MainDomain
don't forget to specify all your others domain as an alias

#### 1' https://yourVestaCP:8083/add/web/
- Domain = mail.$MainDomain.tld
- Alias = mail.allOthers.tld
- Web Template & Backend Template no php
-  SSL Support + Lets Encrypt Support

#### 2' edit /etc/exim/exim.conf
```
[...]
#tls_certificate = /usr/local/vesta/ssl/certificate.crt
#tls_privatekey = /usr/local/vesta/ssl/certificate.key
tls_certificate = /home/admin/conf/web/ssl.mail.$MainDomain.crt
tls_privatekey = /home/admin/conf/web/ssl.mail.$MainDomain.key
[...]
```

#### 3' edit /etc/dovecot/conf.d/10-ssl.conf
```
[...]
#ssl_cert = </usr/local/vesta/ssl/certificate.crt
#ssl_key = </usr/local/vesta/ssl/certificate.key
ssl_cert = </home/admin/conf/web/ssl.mail.$MainDomain.crt
ssl_key = </home/admin/conf/web/ssl.mail.$MainDomain.key
[...]
```

#### 4' restart exim & dovecot
`systemctl restart exim dovecot
`
### Related Issues/Forum Threads:
https://loune.net/2016/02/lets-encrypt-with-exim-and-dovecot/

### Other Notes:

Anything else?

In Great Product We Trust :)

**Comment by jodumont** [comment]
or it could also be:
if addWeb +  Mail Support
then
aliases mail.$Domain.tld

and in the template pushing something like

#### template EXIM
tls_certificate = /home/admin/conf/web/ssl.mail.{lc:${domain:$h_from:}}.crt
tls_privatekey = /home/admin/conf/web/ssl.mail.{lc:${domain:$h_from:}}.key

#### template DOVECOT
ssl_cert = </home/admin/conf/web/ssl.mail.{lc:${domain:$h_from:}}.crt
ssl_key = </home/admin/conf/web/ssl.mail.mail.{lc:${domain:$h_from:}}.key

**Comment by dpeca** [comment]
Keep in mind that both exim and dovecot requires fullchain.pem instead of certificate.crt

My 3rd party script solves it - https://forum.vestacp.com/viewtopic.php?f=10&t=12617&p=50074

**Comment by madeITBelgium** [comment]
In dovecot you can do this:
/etc/dovecot/conf.d/10-ssl.conf
local_name mail.domainname.com {
  ssl_cert = </home/madeit/conf/web/ssl.mail.domainname.com.crt
  ssl_key = </home/madeit/conf/web/ssl.mail.domainname.com.key
}

with this, you can create a checkbox in the mail domain settings to add an SSL certificate per domain. So you can add the ssl_cert and ssl_key only when the files exist.

**Comment by robindirksen1** [comment]
@madeITBelgium but not all the ssl certificates are placed in the `/home/admin` directory? It's only for the domain owners account.

**Comment by madeITBelgium** [comment]
@robindirksen1 All the SSL certificates are located in the folder of the correspondent user.

**Comment by robindirksen1** [comment]
@madeITBelgium so if I'm correct exim cannot do this automatically? Or we need to make a symbolic link to the correct file?

**Comment by jodumont** [comment]
@robindirksen1 
in fact EXIM; will always just have one certificate
all other domain must be a alternative name
ref: http://www.mail-archive.com/exim-users@exim.org/msg24536.html

**Comment by jodumont** [comment]
any update on how to make this ?

would be nice to include this in the roadmap no ?

**Comment by Pleskan** [comment]
@jodumont Hi!
I've just found a superb alternative for VestaCP called [Hestia](https://github.com/hestiacp/hestiacp)
It supports 2FA OTP and SSL for mail subsystem, give it a try ;-)

**Comment by jodumont** [comment]
@Pleskan yes I know this forks, but I tought I was just temporary.

Do you use it in production ? since when ?

Could anyone confirm Hestia is a permanent project ?

**Comment by ScIT-Raphael** [comment]
@jodumont The project will be permanent, there are two companies behind (one from Canada, the other one from Switzerland). I use hestia in productive environment, but it's still "beta" - stable release will be as soon as we finished the ssl mail stack including active sync and finished beta testing.

**Comment by jodumont** [comment]
@ScIT-Raphael; I'm in as French Canadian living abroad in Switzerland this can't make me more proud :)
