### ISSUE TITLE
File Manager cant delete tar.xz archives 

### ISSUE THREAD

**Issue by darkworks** [serghey-rodin/vesta#1119]
### Operating System (OS/VERSION):

Type here, e.g. Debian 8

### VestaCP Version:

latest build 17

### Installed Software (what you got with the installer):

apache, nginx, mysql

i just noticed that file manager is not deleting tar.xz archives , it give error 

http://image.prntscr.com/image/9faa24ad3d664df4a96e86d3552fc7ea.png

file manager is very poor it need heavy upgrade before this i reported zip archive issue which it cant extract .

**Comment by Skamasle** [comment]
I try reproduce this and i not have any problem whit tar.xz files

I can reproduce this only when directory where file is placed have incorrect permisions, so for example

chmod 600 dir/
cd dir
add file
try delete

you that error in file manager.

Error: Directory
path
cant delete 

Try chood 700 as minimum to delete files.

**Comment by darkworks** [comment]
but still most of the user not know about permission if they have to delete archive and they should set it 600 ... so this is bug ..

**Comment by Skamasle** [comment]
Not is a bug IS a Linux. You need some permissions by default for delete or
modify files so same occur if you try do It from FTP ir ssh
