### ISSUE TITLE
domain.sh syntax error

### ISSUE THREAD

**Issue by developer-av** [serghey-rodin/vesta#1122]
### Operating System (OS/VERSION):

Ubuntu 16.04.2 LTS

### VestaCP Version:

0.9.8 (master branch)

### Steps to Reproduce:

`# ./v-add-web-domain-alias 'admin' 'exemple.com' 'al.exemple.com' 'no'`

`/usr/local/vesta/func/domain.sh: line 238: 3
69
102
135: syntax error
102
135")`

**Comment by Skamasle** [comment]
Try rebuild vhost and then add it again

I cant reproduce this error in ubuntu 16.04

**Comment by developer-av** [comment]
You're right, i'm sorry
