### ISSUE TITLE
file upload

### ISSUE THREAD

**Issue by cybernet** [serghey-rodin/vesta#1123]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

latest

i have a problem uploading files
```
file_put_contents(): open_basedir restriction in effect. File(/tmp/phpxe8XLA) is not within the allowed path(s): (/home/user/web/domain/public_html:/home/user/tmp)
```

i know how to fix this and what is causing it, **but i can't find the php fpm configuration** file for my domain :)

also, i want to make a pull request with those changes
in my opinion the problem is here
https://github.com/serghey-rodin/vesta/blob/e89289887414398e112e1128254dd7e11a3aa812/install/rhel/7/templates/web/php-fpm/default.tpl

it should be env[TMPDIR] = /home/%user%/tmp

**Comment by developer-av** [comment]
how about /home/user/conf/web/apache2.conf?

Installed Software?

**Comment by cybernet** [comment]
default by installer

**Comment by cybernet** [comment]
can you tell me where are the confs for httpd and nginx. i can't seem to find them anywhere on /usr/local/vesta/*

**Comment by cybernet** [comment]
/home/user/conf/web/apache2.conf is missing

**Comment by developer-av** [comment]
Try to look /etc/httpd/conf.d/vesta.conf

**Comment by cybernet** [comment]
Include /home/admin/conf/web/httpd.conf
Include /home/user/conf/web/httpd.conf
Include /home/user/conf/web/shttpd.conf


- both **user** files missing

only admin user has it

**Comment by developer-av** [comment]
Try recreate domain

**Comment by cybernet** [comment]
i did
no files under /home/user/conf/web/

**Comment by cybernet** [comment]
should've checked that dir as root :)
