### ISSUE TITLE
Backup hidden files

### ISSUE THREAD

**Issue by robindirksen1** [serghey-rodin/vesta#1127]
### Operating System (OS/VERSION):

CentOS 6

### VestaCP Version:

17

### Installed Software (what you got with the installer):

Default installer

### Steps to Reproduce:

Run the backup

### Related Issues/Forum Threads:

- 

### Other Notes:

In the backup the hidden files (like .htaccess/.env) are not included. Is this in the user settings or is this an error in vesta?

**Comment by SysVoid** [comment]
Thank you for the report.

**Comment by plutocrat** [comment]
You probably have an asterisk in the backup command
tar -cvf backup.tar directory/ 
tar -cvf backup.tar directory/. 
are OK and will pick up dot files
tar -cvf backup.tar directory/* 
is not

**Comment by anton-reutov** [comment]
@SysVoid do you checked this problem, it is reproduced?

**Comment by dpeca** [comment]
On debian8 i see .htaccess in backup files.
On centos7 i see .htaccess too in backup files.
Let somebody checks ubuntu (but it's probably the same as debian).

Maybe only centos6 affected?
Can someone check centos6?

**Comment by plutocrat** [comment]
Just unpacked a backup on Ubuntu 16 and my .htaccess files are there. 
However my first try didn't reveal any. I used
tar -tf admin.2017-03-06.tar | egrep "\/\." | more
I didn't realise that the domains are kept in a tar.gz file inside the original file, so I had to extract that first and then run the same command on the second tar file:
tar -xvf admin.2017-03-06.tar ./web/mydomain.com/domain_data.tar.gz
tar -tf domain_data.tar.gz | egrep "\/\."
That found the .htaccess files. Perhaps the original poster also didn't realise this?

**Comment by robindirksen1** [comment]
@plutocrat nop, I didn't know. I think this needs to be implemented in the core of vesta, normal users restore a backup from the GUI and not command line...

**Comment by SysVoid** [comment]
Closing issue. My initial testing was flawed and I am no longer able to reproduce the error on Ubuntu or CentOS 6 or 7.

**Comment by anton-reutov** [comment]
@SysVoid thank you for testing

**Comment by robindirksen1** [comment]
@dpeca maybe I know where it's coming from. The website I was running was a Laravel project. Therefor was not a default template (for nginx & apache). So my .env file was in `/home/user/web/domain.tld/.env` instead of `/home/user/web/domain.tld/public_html/.env`.

Is it possible we can integrate a default Laravel template for nginx & apache using the "correct" way?

**Comment by plutocrat** [comment]
Perhaps the way to handle this is to have a list of files to include as well as a list of files to exclude. Then you could put your .env file on there? And any others which aren't in the standard backup directories.

**Comment by robindirksen1** [comment]
@plutocrat a nice interface with all the folders or something? Than you can select all the files what needs to be backup. 

By default all the files needs to be in the backup, and than you can select files/folders that's need to be excluded.

**Comment by plutocrat** [comment]
I was just suggesting an easy way of implementing this. There's currently an "Exclusions" page for excluding directories, databases, mail users etc from backups. I was wondering if it might be possible to have an "Inclusions" page in the same style. 
I have a directory which isn't backed up, so I just wrote a quick script to do this for me. But it would be nice to have all your files backed up together if possible. Especially if you're a less technical user, and you're not aware exactly which files are being backed up.

**Comment by robindirksen1** [comment]
@SysVoid do you agree?
