### ISSUE TITLE
Deleting E-Mail domains in VestaCP does not delete exim4 symbolic links in /etc/exim4/domains

### ISSUE THREAD

**Issue by felix-oertel** [serghey-rodin/vesta#1128]
### Operating System (OS/VERSION):

Ubuntu 16.04

### VestaCP Version:

0.9.8-17

### Steps to Reproduce:

Delete a complete Mail domain in VestaCP frontend.

Symbolic link of the deleted domain in
`/etc/exim4/domains/my-domain.de`
is not removed.

### Other Notes:

Deleting these domain entries is crucial if you ever add again this domain under another user in VestaCP. Without deleting this links while adding the domain with another user, the credentials and configs of the new mailboxes are not saved correctly.

Re-adding domains under another user is done often in case of a domain-transfer.

**Comment by dpeca** [comment]
It could be issue https://github.com/serghey-rodin/vesta/issues/1062
Did you use master branch?
If yes - pull recently commits because I fixed that issue before 15 minutes.

**Comment by felix-oertel** [comment]
Pulled master and 6d88ca3 did it, great! THX.
