### ISSUE TITLE
conf files for nginx and apache

### ISSUE THREAD

**Issue by cybernet** [serghey-rodin/vesta#1130]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

0.9.8

### Installed Software (what you got with the installer):

by default

### Steps to Reproduce:

should users see the content of **/conf/*/** by **FTP** ?

**Comment by dpeca** [comment]
It's just important that users has no write privileges on those files.

**Comment by SysVoid** [comment]
Is this a bug report or is it a discussion?

**Comment by cybernet** [comment]
both
since the user shouldn't be able to see them or edit them, it shouldn't be there in the first place ( in my opinion )

**Comment by dpeca** [comment]
It should be there because of backup/restore system :)
And user should not be able to edit it - because syntax error in that file can prevent apache and nginx to restart - so bad user would be able to shutdown web services if they would able to edit conf files.

**Comment by cybernet** [comment]
the conf dir should also be "hidden" :)

**Comment by anton-reutov** [comment]
Users shouldn't see the config files
