### ISSUE TITLE
Changing Webmail URL

### ISSUE THREAD

**Issue by rinkuyadav999** [serghey-rodin/vesta#1133]
### Operating System (OS/VERSION):

ubuntu 16.04

### VestaCP Version:

0.9.8 (amd64) - ( it is latest )

### Installed Software (what you got with the installer):

apache2, nginx, bind9, exim4, dovecot, clamav-daemon, spamassassin, mysql, vsftpd, cron, iptables, fail2ban

### Steps to Reproduce:

1. Open VestaCP admin  and go to: SERVER > CONFIGURE > MAIL > Webmail URL 

Here i just copy past webmail link like http://-my-ip-/webmail/ and replace webmail with mail. so it is http://-my-ip-/mail/
When i access http://-my-ip-/mail/ , i land on 404 page (page not found).
AND http://-my-ip-/webmail/ still works.

Also i tried:
Rebuild user does not work.
Restarted server does not work.

### Other Notes:

Also changing phpMyAdmin URL does not work.

**Comment by Skamasle** [comment]
You may change vestacp link only, you need change alias en /etc/httpd/conf.d/phpmyadmin.conf 

You need edit path in your system, this vary if you use centos or ubuntu, also you need change config file for apache and nginx

**Comment by anton-reutov** [comment]
@rinkuyadav999
This only for another server. (external link)

**Comment by rinkuyadav999** [comment]
Okay!! Thank you.
