### ISSUE TITLE
BUG - Sub-FTP User Email

### ISSUE THREAD

**Issue by MikeP1990** [serghey-rodin/vesta#1135]
Hello,

There is a bug when creating an additional FTP user through a website configuration.  If you don't specifiy an email address, an email is sent anyway which fails to send as there is no "TO:" address;

> A message that you sent contained one or more recipient addresses that were
> incorrectly constructed:
> 
>   <>: missing or malformed local part
> 
> This address has been ignored. There were no other addresses in your
> message, and so no attempt at delivery was possible.
> 
> ------ This is a copy of your message, including all the headers. ------
> 
> To: <>
> Subject: =?utf-8?B?RlRQIGxvZ2luIGNyZWRlbnRpYWxz?=
> From: Vesta Control Panel <noreply@MY-DOMAIN-NAME> 
> X-Priority: 3 (Normal)
> CC:
> Mime-Version: 1.0
> Content-Type: text/plain; charset=utf-8 
> Content-Transfer-Encoding: 8bit
> X-Mailer: Php/libMailv1.3
> Message-Id: <E1cmgGH-0002Bj-64@MY-DOMAIN-NAME>
> Date: Sat, 11 Mar 2017 12:36:41 +0000
> 
> FTP account has been created and is ready for use.
> 
> Hostname: -----------
> Username: -----------
> Password: ------------
> 
> --
> Vesta Control Panel

Thanks,

Mike

**Comment by anton-reutov** [comment]
Cant reproduce
