### ISSUE TITLE
Failed to install with fake email address

### ISSUE THREAD

**Issue by RemiZOffAlex** [serghey-rodin/vesta#1141]
### Operating System (OS/VERSION):

All OS

### Steps to Reproduce:

```
bash /root/vesta.sh --force --email "u111@v222.kvm.u111" --hostname v222.kvm.u111 --interactive no --lang ru --password PASSWORD
...
Error: invalid email format :: u111@v222.kvm.u111
Error: can't create admin user
```

**Comment by dpeca** [comment]
offtopic: i think you can run installer without entering email (just press enter when installers asks for email)

ontopic: probably .u111 TLD makes a problem, try with .com

**Comment by Skamasle** [comment]
As stantad hostname you cant have extensions with numbers

u111@v222.kvm.u111 invalid
u111@v222.kvm.u invalid
u111@v222.kvm.ue valid
u111@v222.kvm.ussssss valid

@dpeca Is imposible install vesta whitout mail

**Comment by RemiZOffAlex** [comment]
"just press enter" - is not imposible. Install full automated server and imposible install vesta whitout mail

Not lottery: valid or not valid (that is the question /William Shakespeare/). The rules are uniquely defined by the RFC 1035.

```
use domain names (e.g., mail, TELNET).

<domain> ::= <subdomain> | " "

<subdomain> ::= <label> | <subdomain> "." <label>

<label> ::= <letter> [ [ <ldh-str> ] <let-dig> ]

<ldh-str> ::= <let-dig-hyp> | <let-dig-hyp> <ldh-str>

<let-dig-hyp> ::= <let-dig> | "-"

<let-dig> ::= <letter> | <digit>

<letter> ::= any one of the 52 alphabetic characters A through Z in
upper case and a through z in lower case

<digit> ::= any one of the ten digits 0 through 9
```

**Comment by anton-reutov** [comment]
Not a bug
You should specify your real email

**Comment by dpeca** [comment]
see screenshot - http://mycity.tech/screenshots/without-email.png

probably bad idea for production machine, but I installed many times for testing and developing without email.

**Comment by RemiZOffAlex** [comment]
Please do not have an offtopic, explaining what a production machine is and how it differs from a non-production machine. This is not the essence of the matter. The essence of the issue is the incorrect recognition of the e-mail address.

**Comment by SysVoid** [comment]
@anton-reutov although it does seem silly to me to be putting a fake email, I can see why this should be fixed.

Can someone try this with the plaintext versions of Chinese TLDs, for example? I'm sure some of those are crazy and potentially end in numbers.

**Comment by dpeca** [comment]
@SysVoid is right - https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#Internationalized_generic_top-level_domains
And not only Chinese code, all internationalized TLDs contains numbers, including cyrilic TLDs.

@anton-reutov maybe it can be consider as a bug, i'm not sure if we use this validation function only in installer.

**Comment by dpeca** [comment]
Hmm, now I remembered - email will not be converted to punny code, so again it will not contains numbers, @SysVoid

**Comment by RemiZOffAlex** [comment]
Sorry, but this is a bug and it does not depend on the opinion or finding specialist.

**Comment by anton-reutov** [comment]
@RemiZOffAlex, where do you see the bug?
u111@v222.kvm.u111 its not correct address. You should specify existing and working email address.
The installer of VestaCP will check the email addresses for validity

**Comment by RemiZOffAlex** [comment]
If I create a server on the local network and specify the zone kvm.u111, will the web service consider the address u111@v222.kvm.u111 valid for the server v222.kvm.u111?
