### ISSUE TITLE
Allow to define docroot other than /public_html.

### ISSUE THREAD

**Issue by dstorozhuk** [serghey-rodin/vesta#1143]
My index.php reside in `public_html/web/index.php`
But panel allow me serve `index.php` only from `public_html/index.php`.
Many web apps may serve index.php not only from  `public_html/`.
Some parts of application could reside out of docroot for security reasons. But still must be a part application and as a result - exists in `public_html/`.

### Operating System (OS/VERSION):

CentOS 6

### VestaCP Version:

0.9.8

### Installed Software (what you got with the installer):

apache, nginx, maria db

### Steps to Reproduce:

1. Create new domain in panel
2. index.php served only from .../public_html or .../public_shtml

### Related Issues/Forum Threads:

NONE

**Comment by Skamasle** [comment]
Hi

This is not posible yet but you can:

- Create own template
- Use rewrite in .htaccess

**Comment by SysVoid** [comment]
This can be done in templates.

**Comment by dstorozhuk** [comment]
@SysVoid , would be great if you can share working example.

**Comment by Skamasle** [comment]
@dstorozhuk 

cd /usr/local/vesta/data/templates/web/apache2
cp default.tpl custom1.tpl
cp defaults.tpl custom2.stpl

Now edit DocumentRoot %docroot% in new custom template

Select custom1 in vestacp gui

**Comment by dstorozhuk** [comment]
@Skamasle Thanks, it works!
I believe it would be great to have templates creator and editor.

**Comment by Skamasle** [comment]
Sorry for mistake:

cp default.tpl custom1.tpl
cp defaults.tpl custom2.stpl

is

cp default.tpl custom1.tpl
cp defaults.tpl custom1.stpl

:)
