### ISSUE TITLE
NginX caching template issue after user migration

### ISSUE THREAD

**Issue by tarikin** [serghey-rodin/vesta#1145]
### Operating System (OS/VERSION):
Debian 8.7

### VestaCP Version:

0.9.8-17

### Installed Software (what you got with the installer):

apache, nginx, mysql

### Steps to Reproduce:

1. Install Vesta 0.9.8-17 on host-01 with Apache + Nginx proxy
2. Create empty website
3. Enable nginx proxy
3a. Proxy Template: Caching
4. /usr/local/vesta/bin/v-backup-user admin
5. Install Vesta 0.9.8-17 on host-02 with Apache + Nginx proxy
6. scp /backup/admin.XXX.tar from host-01 to host-02
7. <HOST-02> /usr/local/vesta/bin/v-restore-user admin admin.XXX.tar

Modifying any params for a website causes the duplication of records in
/etc/nginx/conf.d/01_caching_pool.conf

nginx/error.log:
[emerg] the same path name "/var/cache/nginx/website.tld" used in /etc/nginx/conf.d/01_caching_pool.conf:3 and in /etc/nginx/conf.d/01_caching_pool.conf:5

### Manual fixing
Manually removing duplicated rows fixes the issue.

**Comment by Skamasle** [comment]
Hi

This issue alredy reported multiple times, I see also some pull to fix it :)

**Comment by madeITBelgium** [comment]
Duplicated of #1052 fixed in #1115 and #1012
