### ISSUE TITLE
Spamassassin no config file on CentOS7

### ISSUE THREAD

**Issue by jodumont** [serghey-rodin/vesta#1149]
### Operating System (OS/VERSION):
CentOS 7.3.1611

### VestaCP Version: 
Version: 0.9.8 (x86_64)
Release: 17

### Installed Software (what you got with the installer):
bash vst-install.sh --nginx yes --phpfpm yes --apache no --named yes --remi yes --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota yes --exim yes --dovecot yes --spamassassin yes --clamav no --mysql yes --postgresql yes --hostname maat.jodumont.com --email admin@jodumont.com --password

### Steps to Reproduce:
Hum! I did the command on 2 differents server (both CentOS) and on both I can't find
/etc/spamassassin;

but I up and running
```
systemctl status spamassassin
● spamassassin.service - Spamassassin daemon
   Loaded: loaded (/usr/lib/systemd/system/spamassassin.service; enabled; vendor preset: disabled)
   Active: active (running) since Die 2017-03-21 16:22:01 UTC; 10min ago
  Process: 14422 ExecStart=/usr/bin/spamd --pidfile /var/run/spamd.pid $SPAMDOPTIONS (code=exited, status=0/SUCCESS)
  Process: 14420 ExecStartPre=/sbin/portrelease spamd (code=exited, status=0/SUCCESS)
 Main PID: 14441 (/usr/bin/spamd )
   CGroup: /system.slice/spamassassin.service
           ├─14441 /usr/bin/spamd --pidfile /var/run/spamd.pid -d -c -m5 -H
           ├─14452 spamd child
           └─14453 spamd child

```

### Other Notes:

BTW1: exim is now inside /etc/exim/ instead of /etc/exim4

BTW2: Sadly I'm unable to answer the logical question on the forum (maybe as a French Speaker it make no sense for me)

**Comment by anton-reutov** [comment]
On CentOS 6 and 7 spamassassin located in /etc/mail/spamassassin
