### ISSUE TITLE
Upgrade Vesta Roundcube

### ISSUE THREAD

**Issue by rainbowhat** [serghey-rodin/vesta#116]
Upgrade Vesta Roundcube , How do I? Is that possible? The current design and version is bad.

**Comment by Prosp3r** [comment]
@demlasjr please can you describe how to update the roundcube. I'm having issues with the version on vesta for ubuntu 14.x wasn't even creating the database. So I uninstalled and reinstalled roundcube. 
This didn't solve my problems cause I can't access roundcube from /webmail url anymore.  not even available on /roundcube.

Please show how you did your upgrade.

**Comment by skurudo** [comment]
@Prosp3r let's do this on forum, okey?

https://forum.vestacp.com/viewtopic.php?t=12228
https://forum.vestacp.com/viewtopic.php?t=10708
