### ISSUE TITLE
Lets Encrypt on auto renew directory home change from public_shtml to public_html

### ISSUE THREAD

**Issue by auban** [serghey-rodin/vesta#1173]
### Operating System (OS/VERSION):

Debian 8

### VestaCP Version:

0.9.8 release 17

### Other Notes:

If for a domain lets encrypt is enable on public_shtml directory on automatic renew the public_shtml directory change to public_html.

Best regards,

Auban le Grelle
Stag Agency

**Comment by bekerov** [comment]
Same behavior. Can anybody explain please.
