### ISSUE TITLE
Saving web with nginx template sometimes clips config template

### ISSUE THREAD

**Issue by pbajno** [serghey-rodin/vesta#1175]
` "location" directive is not allowed here in /home/admin/conf/web/nginx.conf`

It's the message i get or any other if I verify xnginx config with  **nginx -t && service nginx reload** after I make changed to the nginx template.

So I make some changes. Make sure config is in valid format, I upload it to this directory:: **/usr/local/vesta/data/templates/web/nginx/php-fpm** and when I reload website nginx template from vesta CP, i get my nginx.conf clipped. It leaves out certain portions of this code (last lines of nginx template):

```
    location /vstats/ {
        alias   %home%/%user%/web/%domain%/stats/;
        include %home%/%user%/web/%domain%/stats/auth.conf*;
    }

    include     /etc/nginx/conf.d/phpmyadmin.inc*;
    include     /etc/nginx/conf.d/phppgadmin.inc*;
    include     /etc/nginx/conf.d/webmail.inc*;

    include     %home%/%user%/conf/web/nginx.%domain%.conf*;
```
I am almost sure it's a parsing error.

**Comment by Skamasle** [comment]
Maybe you have something here ? include     %home%/%user%/conf/web/nginx.%domain%.conf*;

Can you paste complete template ?

But if you have custom template this not is a vesta issue, maybe you get something wrong in your vhost.
