### ISSUE TITLE
letsencrypt.pipe is missing

### ISSUE THREAD

**Issue by Niklan** [serghey-rodin/vesta#1176]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

Версия:0.9.8 (x86_64)	
Релиз:17

### Installed Software (what you got with the installer):

php-fpm, nginx, mysql

### Other Notes:

My client got emails with this content:

```
Error: SSL=yes is already exists
sed: can't read /usr/local/vesta/data/queue/letsencrypt.pipe: No such file or directory
sed: can't read /usr/local/vesta/data/queue/letsencrypt.pipe: No such file or directory
```

I looked at server and letsecnrypt.pipe is missing. Also I looked at others pipes and found that they just contains commands to execute or empty.

I created this file by command: `touch /usr/local/vesta/data/queue/letsencrypt.pipe` and leave it empy. Also set `chmod 750 letsencrypt.pipe` to match others.

1. This is correct way to fix the problem?
2. I have several domains by diffirent users who have LetsEncrypt SSL's. Do I need to add some commands to this pipe file or cron created by default is ok? `
sudo /usr/local/vesta/bin/v-update-letsencrypt-ssl`

I don't know how reproduce this problem, but all LetsEncrypt certificates works well for now, some of them needs update soon, so I don't know, do I need worry about this file or cron will make all the job?

**Comment by Niklan** [comment]
Today we recive new email, but it only contains:

> Error: SSL=yes is already exists

What does it means? Why it's come as error?

**Comment by sir-gon** [comment]
I'm having the same issue of @Niklan ... every day i'm getting an email with this (only) message, for only one domain in one user (a subdomain with their own website/config than the main site).

In addition, only this user is NOT completing the generation of their automatic daily backup.

**Comment by sir-gon** [comment]
I don't know why, but one of mysq /home/user/conf/snginx.conf was fully mess!!! Some lines were missing...

I repaired manually the file (using nginx.conf). Following, i restarted nginx and then I tried to running manually /usr/local/vesta/bin/v-backup-users. Now the process was completed with no errors.

**Comment by anton-reutov** [comment]
Write more, how we can reproduce this problem

**Comment by Niklan** [comment]
I don't know how reproduce it. I using NGINX web-server configuration without apache, and created SSL for several sites. Thats it. I think the problem in SSL certificate update. One site has expiration date 14.05.2017 but still not update, I think this is the issue, he's trying but can't, after that send this notification.

**Comment by Niklan** [comment]
Looks like I found the reason. SSL is not generated for one domain, if I try to generate it directly by `
sudo /usr/local/vesta/bin/v-update-letsencrypt-ssl`.

He said `Error: LE domain.com validation` — where I can find logs why it's happens. This domain has SSL generated with current nginx conf, and `.well-known` path return correct string.

**Comment by vgaiver** [comment]
Similar problem, when updating letsencrypt cert for domain the action is unsuccessful (error: SSL=yes is already exists). I guess the problem is around my nginx conf, there i have a redirect all connections to https, beside .well-known/acme-challenge/ link (witch is used while updating, to check the domain), but looks like it doesn`t works right, because of hsts header in snginx.conf (it always sayas to redirect all to https).
For now the solution to update the cert is temporarily disable all redirections to https and after update enable them back,
It would be fine to fix this up )

nginx.conf:

```
server {
    listen      my-ip:80;
    server_name my-domain.com www.my-domain.com;
    location / {
        return 301 https://my-domain.com$request_uri;
    }
    include /home/admin/conf/web/nginx.my-domain.com.conf*; # here we get letsencrypt conf
}
```

snginx.conf (partial):
```
server {
    listen      my-ip:443;
    resolver    77.88.8.8;
    server_name my-domain.com www.my-domain.com;
    ...

    ssl on;
    ssl_certificate /home/admin/conf/web/ssl.my-domain.com.pem;
    ssl_certificate_key /home/admin/conf/web/ssl.my-domain.com.key;
    ssl_session_timeout 24h;
    ssl_protocols ...;
    ssl_prefer_server_ciphers on;
    ssl_dhparam /home/admin/conf/web/dhparams.pem;
    add_header Strict-Transport-Security "max-age=31536000;"; # hsts that breaks down the domain 
    # check while updating cert
    ...
}
```

**Comment by kevit-development** [comment]
I have a similair issue.

Ubuntu 16.04.2 x64
Version: 0.9.8 (amd64), Release:17

**Comment by kevit-development** [comment]
I believe this was due to https://letsencrypt.status.io/pages/history/55957a99e800baa4470002da#58fbd62b93d7b5a030000005

**Comment by anton-reutov** [comment]
Write the more about this problem. When the problem is appears?

**Comment by vgaiver** [comment]
You should configure your domain to redirect all connections to https.
http://your-site.com/.well-known/acme-challenge/ -> https://your-site.com/.well-known/acme-challenge/
And after it try to update letsencrypt domain certificate by  /usr/local/vesta/bin/v-update-letsencrypt-ssl
Output of this action would be "error: SSL=yes is already exists"

**Comment by patrykmoura** [comment]
same problem here "error: SSL=yes is already exists".
i was getting .well-known not found problems, but i solved putting a txt record as followed by https://www.sslforfree.com/.

But now i'm getting this "error: SSL=yes is already exists"....

Anyone ?

Thanks in advance!

**Comment by anton-reutov** [comment]
Let me know if this problem exist in 0.9.8-18
