### ISSUE TITLE
Installation Error: mysql start failed

### ISSUE THREAD

**Issue by ky0nch3ng** [serghey-rodin/vesta#1187]
### Operating System (OS/VERSION):
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

### Other Notes:

--2017-04-29 21:10:39--  http://c.vestacp.com/ubuntu/16.04/mysql/my-small.cnf
Resolving c.vestacp.com (c.vestacp.com)... 104.236.66.100
Connecting to c.vestacp.com (c.vestacp.com)|104.236.66.100|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 731 [text/plain]
Saving to: ‘/etc/mysql/my.cnf’

/etc/mysql/my.cnf             100%[=================================================>]     731  --.-KB/s    in 0s

2017-04-29 21:10:39 (91.5 MB/s) - ‘/etc/mysql/my.cnf’ saved [731/731]

Job for mysql.service failed because the control process exited with error code. See "systemctl status mysql.service" and "journalctl -xe" for details.
Error: mysql start failed

**Comment by Skamasle** [comment]
can you run journalctl -xe ?

Maybe you run out of memory, this need more information
