### ISSUE TITLE
New letsencrypt certificates cannot be generated.

### ISSUE THREAD

**Issue by delta360** [serghey-rodin/vesta#1189]
### Operating System (OS/VERSION):

Applies to all OS versions. Tried on Ubuntu 12, Ubuntu 16 and Debian 8.

### VestaCP Version:

0.9.8-17

### Installed Software (what you got with the installer):

Not applicable.

### Steps to Reproduce:

Try to generate a new certificate via Vesta Letsencrypt. This will get returned:
Error: The key authorization file from the server did not match this challenge [xxx] != [xxz]

### Related Issues/Forum Threads:

https://community.letsencrypt.org/t/letsencrypt-vesta-client-error-the-key-authorization-file-from-the-server-did-not-match/32822

### Other Notes:

N/A

**Comment by delta360** [comment]
Nevermind, it was the DNS, its always the DNS.

**Comment by duard** [comment]
I have this issue too
