### ISSUE TITLE
Can send emails but can't receive emails

### ISSUE THREAD

**Issue by duard** [serghey-rodin/vesta#1197]
### Operating System (OS/VERSION):

Ubuntu 16.04

### VestaCP Version:

The last version

### Installed Software (what you got with the installer):

apache

### Steps to Reproduce:

fresh install 

**# the problem**
I create a new domain.com 
new contact@domain.com email account
I can send emails but I cant receive 

550 5.1.1 **The email account that you tried to reach does not exist**. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser b94si15609173itd.99 - gsmtp

**Comment by yokowasis** [comment]
check your mx record

**Comment by huloza** [comment]
this appears to be a dns configuration problem, is not a vesta bug.
