### ISSUE TITLE
Install Failed with Error "Error: invalid status format :: global"

### ISSUE THREAD

**Issue by LenKiMo** [serghey-rodin/vesta#1198]
### Operating System (OS/VERSION):

Ubuntu 16.04 64-Bit
Both problem in Linux kernel 4.4.0/4.9.28

### VestaCP Version:

0.9.8-17

### Installed Software (what you got with the installer):

Nginx, Apache, Remi, Iptables, MySql

### Steps to Reproduce:

Install Vesta by using command with:
`bash vst-install.sh --nginx yes --apache yes --phpfpm no --named no --remi yes --vsftpd yes --proftpd no --iptables yes --fail2ban no --quota no --exim no --dovecot no --spamassassin no --clamav no --mysql yes --postgresql no --hostname ABBB --email xxxx --password xxxxxxxxx`

No matter using vst-intall.sh from `vestacp.com` or `github.com`, the result is same.

### Related Issues/Forum Threads:

https://forum.vestacp.com/viewtopic.php?f=41&t=14598
I tried times and posted result in thread.

### Other Notes:

No matter choose Fail2ban or not, it still same.

All fail message:
```
2017-05-16 10:30:14 (168 MB/s) - ‘/etc/phpmyadmin/config.inc.php’ saved [5156/5156]
Error: invalid status format :: global
grep: /usr/local/vesta/data/ips/*: No such file or directory
grep: /usr/local/vesta/data/ips/*: No such file or directory
Error: no IP is available
Error: can't create [b]abc.com[/b] domain
```

**Comment by Skamasle** [comment]
No IP available,

You have dedicated server, VPS or where you install it ?

**Comment by LenKiMo** [comment]
A VPS which can success to Internet successfully before install Vesta. Usually after this failed I can't reinstall again due to can not connect server likes my VPS network is down.

**Comment by lzomedia** [comment]
i get this error still
