### ISSUE TITLE
Number of Backups one less than advertised

### ISSUE THREAD

**Issue by plutocrat** [serghey-rodin/vesta#1202]
### Operating System 
Ubuntu 16.04
### VestaCP Version:
Latest
### Installed Software (what you got with the installer):
standard reverse proxy, swapped mysql for mariadb
### Steps to Reproduce:
 - Set number of backups in package to eg 5. 
 - Wait a few days. 
 - See 5 backups listed in VestaCP web interface. 'ls -hal /backup/' => See only 4 actual backups held there for each user.
 - Try to download oldest backup => Fails

**Comment by joubertredrat** [comment]
For documentation.

Same issue: https://bugs.vestacp.com/issues/330

**Comment by anton-reutov** [comment]
Will be fixed in 0.9.8-18
