### ISSUE TITLE
Vesta Restore Backup System BUG

### ISSUE THREAD

**Issue by huloza** [serghey-rodin/vesta#1208]
### Operating System (OS/VERSION):

Debian 8

### VestaCP Version:

0.9.8 - 17

### Installed Software (what you got with the installer):

bash vst-install.sh –nginx yes –apache yes –phpfpm no –named yes –remi yes –vsftpd no –proftpd yes –iptables yes –fail2ban yes –quota yes –exim yes –dovecot yes –spamassassin yes –clamav yes –mysql yes –postgresql no

### Steps to Reproduce:

Restore a user in another server. "v-restore-user user user.DATE.tar

### Other Notes:

The following files inside /etc/domains/DOMAIN must be owned by Debian-exim user and mail group, otherwise errors will appear in exim4 logs:

aliases
dkim.pem
fwd_only
antivirus
antispam

when you use v-restore-user this files are owned by root NOT Debian-exim. so you will see this kind of errors in logs:
2017-06-05 00:01:30 1dHjCo-0000f4-Nl unable to open private key file for reading: /etc/exim4/domains/DOMAIN/dkim.pem

**Comment by dpeca** [comment]
Already fixed on github - https://github.com/serghey-rodin/vesta/commit/7815539e915ec8f779c7158891261bdfaff41ee7

**Comment by huloza** [comment]
this is not in the official repo, only in github ?

**Comment by dpeca** [comment]
Will be in next Vesta update.

**Comment by robindirksen1** [comment]
When will it be @dpeca ?

**Comment by dpeca** [comment]
Maybe @anton-reutov knows.

**Comment by anton-reutov** [comment]
Planned in September 2017
