### ISSUE TITLE
default template breaking some web apps

### ISSUE THREAD

**Issue by n1trux** [serghey-rodin/vesta#1219]
### Operating System (OS/VERSION):

Debian 8

### VestaCP Version:

0.9.8-17

### Installed Software (what you got with the installer):

php-fpm, nginx, mysql

### Steps to Reproduce:

Install basically any web app, get errors because index.php isn't found or expire headers are wrong. Last app I had this error with was [InvoicePlane](http://invoiceplane.com/).

### Other Notes:

Fixed by removing this in `/home/user/conf/web/nginx.conf`:

    location / {
        location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|css|js)$ {
            expires     max;
        }
    }

and adding this:

    try_files $uri $uri/ /index.php?$args;

**Comment by Skamasle** [comment]
For custom apps you need do custom templates, by default vesta with php-fpm support some apps,wordpress, prestashop, etc nut in many orders you need custom template or try user wp template, this one can run with order apps

This just fail just by rewrite, this not is a vesta bug, you need modify templates, as you add rewrite rules to .htaccess when run apache.

**Comment by n1trux** [comment]
>For custom apps you need do custom templates

But why not use a **default** template which works with many/most apps?

It's pretty counter-intuitive to make people set a "wordpress" template to run some app which is not wordpress.

We have way too few templates to cover all apps. Where would you suggest to put the custom templates which are not shipped with vesta?

Maybe we can get some template which doesn't have anything in it so you can put custom stuff in `/home/user/conf/web/nginx.example.org.conf`?

**Comment by Skamasle** [comment]
Yes, /home/user/conf/web/nginx.example.org.conf this one is for custom rules and addons in vhost.

**Comment by n1trux** [comment]
Yeah, would be nice if there was a template with no rules in it… I'll get to it asap.
