### ISSUE TITLE
Unable to add IP address as new domain

### ISSUE THREAD

**Issue by rinkuyadav999** [serghey-rodin/vesta#1223]
### Operating System (OS/VERSION):

Ubuntu 16.04

### VestaCP Version:

 0.9.8 (amd64)

### Installed Software (what you got with the installer):

apache2, nginx, bind9 , exim4, dovecot , clamav-daemon , spamassassin, mysql , vsftpd , cron ,iptables, fail2ban

### Steps to Reproduce:

Login to Vesta control panel
Click on Web
Add Web Domain
in Domain text box, Type server IP Address and add domain
 → Error: Web alias xx.xx.xx.xxx exists

### Related Issues/Forum Threads:

Found anything that might be related to this? It might help us find the cause.

### Other Notes:

I want to use IP address of server as well domain names like xx.xx.xx.xxx (IP) and example.com (name)

**Comment by Skamasle** [comment]
You want a IP as domain name ?

I think is not posible do it, what do you want to do with it ?

**Comment by rinkuyadav999** [comment]
@Skamasle i want to use IP same as domain name. I think, it is possible because when we install vesta first time, it adds IP as domain name.

**Comment by SCelik** [comment]
In VestaCP if you don't assign a domain to an ip (Control Panel -> Ip -> Assign Domain), firs created domain opens in browser if you type ip in address bar. If you assign a domain, it will be opend in browser.

**Comment by rinkuyadav999** [comment]
If there is not any domain added, i can add IP as domain. If there is any domain added, i will not able to add IP as domain :) Just tested with new VPS.

**Comment by SCelik** [comment]
Why do you want to add "Ip" as domain? If you want both ip and domain name resolve to same wwwroot there is a setting in panel called "Assigned Domain".

Do you want to serve web site witout any domain name? Just Ip address?
