### ISSUE TITLE
Login error "Invalid username or password."

### ISSUE THREAD

**Issue by LouisForaux** [serghey-rodin/vesta#1228]
### Operating System (OS/VERSION):

Debian 7

### VestaCP Version:

0.9.8

### Installed Software (what you got with the installer):

I dont remember, sory...

### Steps to Reproduce:

I have no idea...
### Problem ?
I have the error "Invalid username or password." when I try to log in with the admin account, a password change will no resolve the problem...

**Comment by dpeca** [comment]
Please use forum for this type of error.
Check logs first.
Maybe server filled dedicated quota for 'admin' user, try to delete log files, maybe you free space.
