### ISSUE TITLE
Nginx template caching for a https web site cause loop

### ISSUE THREAD

**Issue by lucav** [serghey-rodin/vesta#1233]
### Operating System (OS/VERSION):

Debian 8

### VestaCP Version:

0.9.8-17

### Installed Software (what you got with the installer):

bash vst-install.sh --nginx yes --apache yes --phpfpm no --named yes --remi yes --vsftpd no --proftpd yes --iptables yes --fail2ban yes --quota no --exim yes --dovecot yes --spamassassin yes --clamav yes --mysql yes --postgresql no

### Steps to Reproduce:

Choose nginx proxy template as "caching" for a web site with https (in my case a wordpress site with baseurl protocol https)

### Related Issues/Forum Threads:

Not found

### Other Notes:

If is selected nginx proxy template as "caching" for my web site, the web site loop forever (loop redirect to https).

I have resolved the issue changing the line number 10 of caching.stpl file:

`proxy_pass      http://%ip%:%web_port%;`

to this:

`proxy_pass      https://%ip%:%web_ssl_port%;`

Is it correct?

**Comment by anacondaqq** [comment]
Here how must looks caching.stpl template (already fixed loops)
```
server {
    listen      %ip%:%proxy_ssl_port%;
    server_name %domain_idn% %alias_idn%;
    ssl         on;
    ssl_certificate      %ssl_pem%;
    ssl_certificate_key  %ssl_key%;
    error_log  /var/log/%web_system%/domains/%domain%.error.log error;

    location / {
        proxy_pass      https://%ip%:%web_ssl_port%;

        proxy_cache cache;
        proxy_cache_valid 15m;
        proxy_cache_valid 404 1m;
        proxy_no_cache $no_cache;
        proxy_cache_bypass $no_cache;
        proxy_cache_bypass $cookie_session $http_x_update;

        location ~* ^.+\.(%proxy_extentions%)$ {
            proxy_cache    off;
            root           %docroot%;
            access_log     /var/log/%web_system%/domains/%domain%.log combined;
            access_log     /var/log/%web_system%/domains/%domain%.bytes bytes;
            expires        max;
            try_files      $uri @fallback;
        }
    }

    location /error/ {
        alias   %home%/%user%/web/%domain%/document_errors/;
    }

    location @fallback {
        proxy_pass      https://%ip%:%web_ssl_port%;
    }

    location ~ /\.ht    {return 404;}
    location ~ /\.svn/  {return 404;}
    location ~ /\.git/  {return 404;}
    location ~ /\.hg/   {return 404;}
    location ~ /\.bzr/  {return 404;}

    include %home%/%user%/conf/web/snginx.%domain%.conf*;
}
```

**Comment by francrodriguez** [comment]
Bug is still active. Vesta 0.9.8-23.

**Comment by anacondaqq** [comment]
yes, because template by me above - is incorrect. I stopped to use vesta long time ago, but forgot to write a solution, but i did change something in the template above, and everything start to work fine.

**Comment by ludo237** [comment]
@anacondaqq what did you change? 😕

**Comment by anton-reutov** [comment]
@francrodriguez, write more about steps to reproduce, if this problem still exists. I can't reproduce it
