### ISSUE TITLE
web/add/db/index.php double footer

### ISSUE THREAD

**Issue by szbnwer** [serghey-rodin/vesta#1240]
just delete the footer from the end of the file... :D i'm new with pull requests, the previous one i've made is still not merged, so what gh offered contains the other change as well...

btw should i make a fresh copy every time for a new change, or how this can be handled in the future?

**Comment by anton-reutov** [comment]
Add this issue in out tracker
https://bugs.vestacp.com

**Comment by dpeca** [comment]
Solved by @madeITBelgium commit.
