### ISSUE TITLE
[Need help] Include NGINX conf

### ISSUE THREAD

**Issue by Niklan** [serghey-rodin/vesta#1245]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

Latest

### Installed Software (what you got with the installer):

php-fpm, nginx, mysql

I have several custom nginx configs which repeat a lot of NGINX configurations and edit them is pain. I created special file `/etc/nginx/conf.d/MYCONF.inc` and pass all rules what i need. I added to all my configs `include     /etc/nginx/conf.d/MYCONF.inc*;`, but NGINX won't start with this.

Error log says: `no port in upstream "%backend_lsnr%" in /etc/nginx/conf.d/MYCONF.inc:165`, this line contains default variable `fastcgi_pass    %backend_lsnr%;`. How can I fix it? Maybe I create include file not correctly? Without include same config works fine.

The whole part with problem line (which is standart from vesta configs):

```
location ~ [^/]\.php(/|$) {
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        if (!-f $document_root$fastcgi_script_name) {
            return  404;
        }

        fastcgi_pass    %backend_lsnr%;
        fastcgi_index   index.php;
        fastcgi_param SCRIPT_FILENAME $request_filename;
        fastcgi_intercept_errors on;
        fastcgi_buffer_size 32k;
        fastcgi_buffers 4 32k;
        include         /etc/nginx/fastcgi_params;
    }
```

**Comment by dpeca** [comment]
VestaCP is parsing `%backend_lsnr%` in template file.
When you put in in included file, it can not be parsed.
Simply substitute `%backend_lsnr%` with port number... but I guess that you need separated port numbers for each account, so you can not do it with included file...

I'm closing this because this is not issue.
You can continue discussion here, just don't re-open issue.

**Comment by Niklan** [comment]
@dpeca thank you for answer.

I did this:

```
set $backend_lsnr %backend_lsnr%;
include     /etc/nginx/conf.d/MYCONF.inc*;
```
It's bad?

Am I understand correctly? The variables like `%something%` used by vesta as placeholder for replacement? This is not support by Nginx?

**Comment by dpeca** [comment]
Correct, it's not supported by nginx, it's just Vesta template replacement.

If it is working now - it is not bad.
