### ISSUE TITLE
Cron Job bug report

### ISSUE THREAD

**Issue by andybowser** [serghey-rodin/vesta#1250]
### Operating System (OS/VERSION):

Ubuntu 16.04.2

### VestaCP Version:

0.9.8 release 17

### Installed Software (what you got with the installer):

--nginx yes --apache yes --phpfpm no --named yes --remi yes --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota yes --exim yes --dovecot yes --spamassassin yes --clamav yes --mysql yes --postgresql yes

### Steps to Reproduce:

email error

### Other Notes:

Cron Job came up with the following. 

`Signal 11 (SEGV) caught by ps (procps-ng version 3.3.10).
ps:display.c:66: please report this bug`

when running
`sudo /usr/local/vesta/bin/v-update-sys-queue dns-cluster`

In the same batch of emails I did get `/bin/sh: execle: Cannot allocate memory`

**Comment by SebTM** [comment]
Could you check your system-ressources with "free -m" and "df -h" and posting th resulsts?

**Comment by andybowser** [comment]
free -m 
```
              total        used        free      shared  buff/cache   available
Mem:        1016020      827268       68592       49188      120160       23088
Swap:             0           0           0
```

df -h
```
Filesystem      Size  Used Avail Use% Mounted on
udev            477M     0  477M   0% /dev
tmpfs           100M   11M   89M  11% /run
/dev/vda1        25G  3.2G   21G  14% /
tmpfs           497M  4.0K  497M   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           497M     0  497M   0% /sys/fs/cgroup
tmpfs           100M     0  100M   0% /run/user/1000
```

**Comment by andybowser** [comment]
It seems to be clamd maxing out the memory.
![screen shot 2017-08-03 at 4 13 12 pm](https://user-images.githubusercontent.com/485249/28908477-424aad2a-7867-11e7-9681-e54b08b377be.png)

**Comment by anton-reutov** [comment]
it seems that problem with memory

**Comment by andybowser** [comment]
I recreated the VM and migrated the data. This seems to have solved the issue.
