### ISSUE TITLE
Typo in v-add-letsencrypt-user

### ISSUE THREAD

**Issue by jaredearle** [serghey-rodin/vesta#1253]
### Operating System (OS/VERSION):

All

### VestaCP Version:

0.9.8

### Issue:

Typo discovered - https://github.com/serghey-rodin/vesta/blob/master/bin/v-add-letsencrypt-user#L58

"perm" should be "pem"

**Comment by bikerdave** [comment]
+1

**Comment by noogen** [comment]
Confirm a bug in 0.9.8 v17 on Ubuntu 16.04.03 LTS

**Comment by 4t4r1** [comment]
+1

**Comment by narookak** [comment]
confirmed issue with "Ubuntu 14.04.5 LTS" too.
root@webapps01:~# v-add-letsencrypt-domain user domain.com
pkey: Invalid format "perm" for -inform
pkey: Use -help for summary.
Error: LetsEncrypt account registration 400

tried correcting the typo, but getting below error after that.

sed: can't read /usr/local/vesta/data/queue/letsencrypt.pipe: No such file or directory

**Comment by noogen** [comment]
manually create the file by doing: touch /usr/local/vesta/data/queue/letsencrypt.pipe
VestaCP has issue creating this file, sometime.

**Comment by anton-reutov** [comment]
@narookak 
DO
Ubuntu 14.04 x64
`v-add-letsencrypt-domain user domain.com`

I cant reproduce this problem. The certificate is added successfully

**Comment by narookak** [comment]
@anton-reutov, thanks, I will give it a try again.

**Comment by anton-reutov** [comment]
Try and let me know if problem still exits

**Comment by narookak** [comment]
This is working now, after applying fix suggested by @noogen

**Comment by szbnwer** [comment]
i think that missing pipe is because the installer, i think i didn't see it in the debian installer when the stucked development and forking topics came up

**Comment by sviriden** [comment]
How to reproduce on DO:

If I install Vesta on totally clean server — everything works fine.

But if I add PHP7.1 repo and update&upgrade system before install, I get this error:
`Error: LetsEncrypt account registration 400`

1. Create Droplet Ubuntu 16.04.3 x32
2. `ssh root@IP`
3.
```
add-apt-repository ppa:ondrej/php
apt-get update
apt-get upgrade -y
apt-get dist-upgrade
curl -O http://vestacp.com/pub/vst-install.sh
sudo groupdel admin 
bash vst-install.sh
```
4. Change DNS A record for used domain
5. Open Vesta CP and try to receive LE certificate => error
6. After fixing file `/usr/local/vesta/bin/v-add-letsencrypt-user` =>everything works

**Comment by noogen** [comment]
Do you really need to re-create?  This is reported as a typo:  https://github.com/serghey-rodin/vesta/blob/master/bin/v-add-letsencrypt-user#L58

exponent=$(openssl pkey -inform **perm** -in "$key" -noout -text_pub |\

It is specified here, valid values are: DER or PEM

https://wiki.openssl.org/index.php/Manual:Pkey(1)

 -inform DER|PEM
    This specifies the input format DER or PEM. 

In this case, the typo is **perm** and not **pem**

**Comment by dpeca** [comment]
Fix accepted.
