### ISSUE TITLE
Issue moving a user from one host to another

### ISSUE THREAD

**Issue by kezern** [serghey-rodin/vesta#1266]
I have moved one user from one host to a new one following this instructions.
[http://vestacp.com/docs/#how-to-migrate-user-to-another-server](http://vestacp.com/docs/#how-to-migrate-user-to-another-server)
That user has a wordpress installation. Everything seems to be moved correctly but wordpress shows a message about an error connecting to database. I have changed the password of the database to the one specified in wp-config.php and now it works fine.
It seems after moving the user, the password of the database in the new server is different from the older server.
Has it any sense?

**Comment by Skamasle** [comment]
Hi

Maybe you use ubuntu 16 ?

https://forum.vestacp.com/viewtopic.php?f=20&t=13239

In ubuntu 16 in 100% case if you not have a patch you get errors with users, in backups, in restores etc
