### ISSUE TITLE
There is wrong stpl template for laravel

### ISSUE THREAD

**Issue by tualik** [serghey-rodin/vesta#1269]
https://github.com/serghey-rodin/vesta/blob/ab17ffe7f8b0e48a5ed8e3d3762375622b720b3a/install/rhel/7/templates/web/nginx/php-fpm/laravel.stpl#L4
%docroot% -> %sdocroot%
https://github.com/serghey-rodin/vesta/blob/ab17ffe7f8b0e48a5ed8e3d3762375622b720b3a/install/rhel/7/templates/web/nginx/php-fpm/laravel.stpl#L2
%web_port% -> %web_ssl_port%

**Comment by anton-reutov** [comment]
Please add commit

**Comment by tualik** [comment]
Have you any contribution guide?

**Comment by anton-reutov** [comment]
`%web_port% -> %web_ssl_port%`
Already added in https://github.com/serghey-rodin/vesta/pull/1196

**Comment by anton-reutov** [comment]
@tualik https://stackoverflow.com/questions/27211578/how-to-commit-changes-to-github-with-github-desktop

**Comment by tualik** [comment]
I mean any formats for flow, branch, commit-messages...  project oriented, @anton-reutov  thanks for comment.

**Comment by anton-reutov** [comment]
@tualik 
Why would you want to change the docroot?
```
root %docroot%/public;
%docroot% -> %sdocroot%
```

**Comment by madeITBelgium** [comment]
The docroot in the **s**tpl file is wrong.
%docroot% = public_html
%sdocroot% = public_html or public_shtml depends on setting.

See default.**s**tpl here it is %sdocroot%
https://github.com/serghey-rodin/vesta/blob/master/install/rhel/7/templates/web/nginx/php-fpm/default.stpl#L4

Then check Laravel.tpl here it is %docroot%
https://github.com/serghey-rodin/vesta/tree/master/install/rhel/7/templates/web/nginx/php-fpm/laravel.tpl#L4

And Laravel.stpl here it is %docroot% needs to change to %sdocroot%
https://github.com/serghey-rodin/vesta/tree/master/install/rhel/7/templates/web/nginx/php-fpm/laravel.stpl#L4

**Comment by anton-reutov** [comment]
Yes, you a right.
I will create commit with this change

**Comment by madeITBelgium** [comment]
There are more files with this problem:

https://github.com/serghey-rodin/vesta/blob/master/install/rhel/7/templates/web/nginx/php-fpm/cms_made_simple.stpl#L4
https://github.com/serghey-rodin/vesta/blob/master/install/rhel/7/templates/web/nginx/php-fpm/codeigniter3.stpl
...

**Comment by luizjr** [comment]
> Have you any contribution guide?

https://github.com/luizjr/Tools-VestaCP have templates if you need.
