### ISSUE TITLE
[Suggestion] Read below

### ISSUE THREAD

**Issue by TheLegendaryMarc** [serghey-rodin/vesta#1271]
My Suggestions are:

- Debian 9 and Ubuntu 17 Support
- PHP 7.1 Support (by default)
- Different PHP Versions and PHP.ini files
- Changing the Document Root from the CP
- Lets Encrypt SSL for the CP itself
- Optional: Redesign of the CP
- easier creation of subdomains
- HTTP/2 Support
- Github Integration
- Multi Server Managment

**Comment by anton-reutov** [comment]
Please add your ideas and enhancements in out tracker. Before adding use the search
https://bugs.vestacp.com/

**Comment by Skamasle** [comment]
I think 99% of your sugestiong are alredy in bugs.vestacp.com

**Comment by anton-reutov** [comment]
- Support for Debian 9
https://bugs.vestacp.com/issues/566
- Support for Ubuntu 17
https://bugs.vestacp.com/issues/589
- PHP 7.1 Support (by default)
https://bugs.vestacp.com/issues/590
- Different PHP Versions and PHP.ini files
https://bugs.vestacp.com/issues/529
https://bugs.vestacp.com/issues/103
- Changing the Document Root from the CP
https://bugs.vestacp.com/issues/412
https://bugs.vestacp.com/issues/591
- HTTP/2 Support
https://bugs.vestacp.com/issues/104
- Multi Server Managment
https://bugs.vestacp.com/issues/572

- Lets Encrypt SSL for the CP itself
Already added, or something yet?
![ssl](https://user-images.githubusercontent.com/6527481/30513002-3c8e729e-9b04-11e7-89fe-16f6fdd5c9fd.png)
- Optional: Redesign of the CP
The redesign was not so long ago. We will do adaptive layout
- easier creation of subdomains
And so very easy
- Github Integration
Whats you mean?
