### ISSUE TITLE
how to change hostname in exim4

### ISSUE THREAD

**Issue by darkworks** [serghey-rodin/vesta#1285]
### Operating System (OS/VERSION):

OS : Debian 8.9

### VestaCP Version:

latest version build 17

### Installed Software (what you got with the installer):

php , maria , nginx , apache 

### Steps to Reproduce:

Problem : i can get mails but i cant send mails when i send mail from roundcube i get error 

> SMTP Error (550): Failed to set sender (Access denied - Invalid HELO name (See RFC2821 4.1.3)).

what i did 
i debug the issue and found that $sender_helo_name in exim4 vesta template have value of my server ip instead of domain. i checked exim4 logs and found that its still picking old hostname , although i have changed hostname from shell when i type hostname name in terminal i get my site domain address however when i check exim4 logs its still picking up old invalid hostname  reject log have 

> root@zworks.com <root@zworks> R=dnslookup T=remote_smtp defer (-53): retry time not reached for any host

so any idea how to set hostname or directly set value of $sender_helo_name to my site domain so that i can send mails 

old invalid hostname : zworks
new hostname : mywebsite address , display ok in terminal with hostname command 
thanks

**Comment by moucho** [comment]
Open /etc/roundcube/config.inc.php and search for thjs line:
$config['smtp_helo_host'] = '';

Insert between those single quotes your valid hostname, for example:

$config['smtp_helo_host'] = 'server.zworks.com';

That should fix your problem.

**Comment by darkworks** [comment]
thanks for quick reply ... however its giving me same error and debug results shows $sender_helo_name = server ip

**Comment by darkworks** [comment]
ok error changed to  

> root@useotools.com: Unrouteable address

**Comment by moucho** [comment]
That's a totally diferent issue.
Usually, that means that the mail account root@useotools.com isn't set properly to receive mail on you VPS

**Comment by darkworks** [comment]
but from gmail when i send mail to root@useotools.com ... i get it instantly  , problem is i cant send from server back to gmail

**Comment by dpeca** [comment]
```
# v-change-sys-hostname
Usage: v-change-sys-hostname HOSTNAME
```

After that restart exim.

I think this topic is for forum.

**Comment by darkworks** [comment]
did this restarted exim but $sender_helo_name value is still sever ip address , any idea for quick fix for it to overwrite it in template maybe

**Comment by dpeca** [comment]
I checked my exim templates, it  does not contains hostname of my server.
What you get when you type in console `hostname` ?
And what is in `/etc/hostname` ?

**Comment by darkworks** [comment]
here is my exim template : https://pastebin.com/PyxjwsMq           ,
 i added macro on top 
`MAIN_HARDCODE_PRIMARY_HOSTNAME = useotools.com` 
 but it not worked :(

/etc/hostname     have  useotools.com

also i have added 
```
kernel.hostname = useotools.com
kernel.domainname = useotools.com
```

to /etc/sysctl.conf

but still no luck same error
`2017-09-28 12:07:25 H=localhost.localdomain (198.50.220.183) [127.0.0.1] rejected MAIL <contactus@useotools.com>: Access denied - Invalid HELO name ( 198.50.220.183) (See RFC2821 4.1.3)`

**Comment by dpeca** [comment]
Crazy suggestion - try to reboot server?
Is it VPS?
Some virtual hypervisors has it's own administration panel when you must enter desired hostname, or it's will be restarted on each server reboot.

**Comment by darkworks** [comment]
ya you were right , just changed hostname from vps panel and rebooted , but still same access denied error , my exim main log dump : https://pastebin.com/sYemmgnq
