### ISSUE TITLE
[Feature Request] Using pigz for faster compression and only one backup command step

### ISSUE THREAD

**Issue by 001101** [serghey-rodin/vesta#1287]
Hello,

backups are taken really long on my systems (and we are only talking about 4GB compressed and 8GB uncompressed), have a KVM with four dedicated Xeon E5-2630, not the fastet, but it do the job and the harddisk is a SSD, so it is no lowend thing.

Just searching around and found that there is the pigz tool, parallel gzip compression:

https://bioinfoexpert.wordpress.com/2014/10/11/speeding-up-tar-gz-compression

It is also possible to give tar directly a app switch for specific compression (--use-compress-program= or -I), normally the backup script runs it in two steps, first tar, than gzip.

tar -I pigz -cf backup.tar.bz2 backup_dir

What you think?

greets

**Comment by Skamasle** [comment]
This sugestion is acctully in bug tracker for future versions

**Comment by 001101** [comment]
Cool, where can i found it, can you please refer?

**Comment by robindirksen1** [comment]
@001101 https://bugs.vestacp.com/issues/577

https://github.com/serghey-rodin/vesta/pull/1255/

**Comment by anton-reutov** [comment]
Ok, i will close this issue as duplicate

**Comment by 001101** [comment]
it is on russian, why?

**Comment by anton-reutov** [comment]
@001101, because our community speaking on English and Russian

**Comment by 001101** [comment]
Please read more carefully!

I am talking about PIGZ and also referenced it with links, not only GZ

**Comment by mslepko** [comment]
Can this be revisited again? I've switched to PIGZ on one of my servers and I see a massive performance and speed improvements. 

For example a backup of 100GB with GZIP takes about 6hrs, with PIGZ it takes around 2.5-3hrs.

GZIP
```
-- SUMMARY --
2020-11-25 14:07:57 Size: 93710 MB
2020-11-25 14:07:57 Runtime: 335 minutes
```

PIGZ
```
-- SUMMARY --
2020-12-03 11:59:59 Size: 93749 MB
2020-12-03 11:59:59 Runtime: 147 minutes
```

I can submit a PR in the next couple of days.

**Comment by Lupul** [comment]
How does pigz compare to `zstd -9 -T0`?

**Comment by mslepko** [comment]
@lapuh I’ll check it.

**Comment by mslepko** [comment]
| ZSTD | TIme | PIGZ | Time |
| ------ | -----| ---- | ---- |
| Size: 4627 MB | Runtime: 5 minutes | Size: 4320 MB | Runtime: 8 minutes |
| Size: 31599 MB | Runtime: 104 minutes | Size: 37938 MB | Runtime: 109 minutes |
| Size: 18036 MB | Runtime: 5 minutes | Size: 18387 MB | Runtime: 12 minutes |
| Size: 8073 MB | Runtime: 8 minutes | Size: 8092 MB | Runtime: 13 minutes |

ZSTD is quicker but not by much. I'm sticking with PIGZ :)

**Comment by ScIT-Raphael** [comment]
Have a look at hestiacp (https://github.com/hestiacp/hestiacp), we already have implemented and are using zstd as default for backups.

**Comment by mslepko** [comment]
@ScIT-Raphael I use Hestia on a couple of servers already. Vesta is on legacy servers with Centos.
