### ISSUE TITLE
Vesta Restore DB Access Denied

### ISSUE THREAD

**Issue by iamra** [serghey-rodin/vesta#1294]
### Operating System (OS/VERSION):

Ubuntu 16.04 

### VestaCP Version:

0.9.8

### Installed Software (what you got with the installer):

Default for 2GB vps

### Steps to Reproduce:

Backup a user account from one Vesta server, restore user account on new server.
DB access denied for installed wordpress application.
Go to DB, edit user password, update in wp-config.php, access success.

### Other Notes:

Error Example with WordPress Instance:
Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'sacweb_wp_mana_p'@'localhost' (using password: YES) in /home/exampleuser/web/exampledomain/public_html/wp-includes/wp-db.php on line 1548

**Comment by madeITBelgium** [comment]
Duplication of #1266
