### ISSUE TITLE
SSH "login" option bug

### ISSUE THREAD

**Issue by malefici** [serghey-rodin/vesta#1295]
### Operating System (OS/VERSION):

```bash
[root@vestacp1 /]# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
[root@vestacp1 /]# uname -a
Linux vestacp1 4.13.4-200.fc26.x86_64 #1 SMP Thu Sep 28 20:46:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### VestaCP Version:

0.9.8 x86_64, release 17

### Installed Software (what you got with the installer):

Only base software

```bash
bash vst-install.sh --nginx yes --phpfpm yes --apache no --named no --remi yes --vsftpd no --proftpd no --iptables yes --fail2ban yes --quota yes --exim yes --dovecot yes --spamassassin yes --clamav yes --mysql yes --postgresql no
```

### Steps to Reproduce:

1. Create new package with `login` option `nologin`
2. Create new user with `login` option `nologin`
3. Try to login via ssh. It works correctly, user not available.
4. Change package `login` option to `bash`.
5. Try to login via ssh. It works but with `sh`.
6. Change back `login` option to `nologin`.
7. Try to login via ssh. It works with `sh`. That is not correct.

**Comment by anton-reutov** [comment]
Yes, bug has been confirmed

**Comment by anton-reutov** [comment]
https://bugs.vestacp.com/issues/601

**Comment by anton-reutov** [comment]
0.9.8-23 centos 7,6 can't reproduce
