### ISSUE TITLE
vesta picks wrong ip?

### ISSUE THREAD

**Issue by ajmalkhanjamro** [serghey-rodin/vesta#1326]
hello i have install vesta on ubuntu 16.04 and i have use php code to get client ip but instead of getting getting client ip iam getting my own ip i have use this code 

<?php
echo $_SERVER['REMOTE_ADDR'];
?>
it gets back my own ip i have tried each and every fix available on web modding nginx config apache2 and stuff all did not worked and not fixed my issues if any one had solved this please can answer to this

**Comment by SCelik** [comment]
https://calvin.me/forward-ip-addresses-when-using-nginx-proxy/

**Comment by vvcares** [comment]
Haha. I had that same issue but i resolved it. Which is not VestaCP issue but nginx related issue. 

R u using cloudflare?

**Comment by ajmalkhanjamro** [comment]
i h ave found the issue and fixed  some apache module was causing it

**Comment by atassumer** [comment]
add this line to http.conf after <IfModule remoteip_module>
   RemoteIPInternalProxy xxx.xxx.xxx.xxx #real ip
