### ISSUE TITLE
PHPMyAdmin end-user password?

### ISSUE THREAD

**Issue by desfire** [serghey-rodin/vesta#1374]
### Operating System (OS/VERSION):

Centos7

### VestaCP Version:

0.9.8-17

### Installed Software (what you got with the installer):

nginx + apache

### Steps to Reproduce:

Create a new user > create database > open phpmyadmin > incorrect password

### Other Notes:

Should be password be the same as to login to Vesta right? not working

**Comment by dpeca** [comment]
Vesta account password and password for database is not the same.

**Comment by desfire** [comment]
So what is phpmyadmin password for each account on Vesta? How do I need which one it is?

**Comment by moucho** [comment]
The database user and password you created on the "create database" screen.

**Comment by moucho** [comment]
@desfire There is no way right now to do that

**Comment by alex-connor** [comment]
@desfire you can add request for this feature on our bug tracker: https://bugs.vestacp.com
