### ISSUE TITLE
nginx problem !!

### ISSUE THREAD

**Issue by ifeelingz** [serghey-rodin/vesta#1377]
Operating System (OS/VERSION):
CentOS 7

VestaCP Version:
LATEST VERSION (Nov 25): 0.9.8-17

Installed Software (what you got with the installer):
nginx, php-fpm

After installing nginx did not work before, I did not pass the problem, I try to test on the last 2 servers found the same problem.

> `nginx.service - nginx - high performance web server
>    Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Fri 2017-12-22 15:58:05 +07; 3min 38s ago
>      Docs: http://nginx.org/en/docs/
>   Process: 3760 ExecStop=/bin/kill -s TERM $MAINPID (code=exited, status=0/SUCCESS)
>   Process: 3763 ExecStartPre=/usr/sbin/nginx -t -c /etc/nginx/nginx.conf (code=exited, status=1/FAILURE)
>  Main PID: 13402 (code=exited, status=0/SUCCESS)
> 
> Dec 22 15:58:05 host.domain.com systemd[1]: Starting nginx - high performance web server...
> Dec 22 15:58:05 host.domain.com nginx[3763]: nginx: [emerg] unexpected "}" in /home/admin/conf/web/nginx.conf:44
> Dec 22 15:58:05 host.domain.com nginx[3763]: nginx: configuration file /etc/nginx/nginx.conf test failed
> Dec 22 15:58:05 host.domain.com systemd[1]: nginx.service: control process exited, code=exited status=1
> Dec 22 15:58:05 host.domain.com systemd[1]: Failed to start nginx - high performance web server.
> Dec 22 15:58:05 host.domain.com systemd[1]: Unit nginx.service entered failed state.
> Dec 22 15:58:05 host.domain.com systemd[1]: nginx.service failed.`

My installation steps
[https://i.imgur.com/d11ZfWv.png](url)

Thank you very much.

**Comment by alex-connor** [comment]
> Dec 22 15:58:05 host.domain.com nginx[3763]: nginx: [emerg] unexpected "}" in /home/admin/conf/web/nginx.conf:44
did you see this error? pls open your /home/admin/conf/web/nginx.conf and find line 44 and check this "unexpected "}""

**Comment by ifeelingz** [comment]
> `server {
>     listen      0.0.0.0:80;
>     server_name host.domain.com www.host.domain.com;
>     root        /home/admin/web/host.domain.com/public_html;
>     index       index.php index.html index.htm;
>     access_log  /var/log/nginx/domains/host.domain.com.log combined;
>     access_log  /var/log/nginx/domains/host.domain.com.bytes bytes;
>     error_log   /var/log/nginx/domains/host.domain.com.error.log error;
> 
>     location / {
> 
>         location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|css|js)$ {
>             expires     max;
>         }
> 
>         location ~ [^/]\.php(/|$) {
>             fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
>             if (!-f $document_root$fastcgi_script_name) {
>                 return  404;
>             }
> 
>             fastcgi_pass    127.0.0.1:9001;
>             fastcgi_index   index.php;
>             include         /etc/nginx/fastcgi_params;
>         }
>     }
> 
>     error_page  403 /error/404.html;
>     error_page  404 /error/404.html;
>     error_page  500 502 503 504 /error/50x.html;
> 
>     location /error/ {
>         alias   /home/admin/web/host.domain.com/document_errors/;
>     }
> 
>     location ~* "/\.(htaccess|htpasswd)$" {
>         deny    all;
>         return  404;
>     }
> 
>     location /vstats/ {
>         alias   /home/admin/web/host.domain.com/stats/;
>         include /home/admin/conf/web/host.domain.com.auth
>     }
> 
>     include     /etc/nginx/conf.d/phpmyadmin.inc*;
>     include     /etc/nginx/conf.d/phppgadmin.inc*;
>     include     /etc/nginx/conf.d/webmail.inc*;
> 
>     include     /home/admin/conf/web/nginx.host.domain.com.conf*;
> }
> `

After installing, I have not set or adjusted anything.

**Comment by alex-connor** [comment]
try use this: https://pastebin.com/rtiVRH4M

**Comment by ifeelingz** [comment]
Thank you very much for you help me.

I installed VestaCP very often, but never found this.

**Comment by alex-connor** [comment]
;)

**Comment by ifeelingz** [comment]
Is there a path change of vstats?

Old:
>     location /vstats/ {
>         alias   /home/admin/web/host.domain.in.th/stats/;
>         **include /home/admin/web/host.domain.in.th/stats/auth.conf*;**
>     }

nginx work

New:
>     location /vstats/ {
>         alias   /home/sygnus/web/host.domain.in.th/stats/;
>         **include /home/sygnus/conf/web/host.domain.in.th.auth**
>     }

nginx not work

**Comment by alex-connor** [comment]
There was no closing sign ";"
