### ISSUE TITLE
CRON adding screen UX enhancement

### ISSUE THREAD

**Issue by Bashar** [serghey-rodin/vesta#140]
From experience; normal users doesn't know how to manage cron entries correctly.

Thus i'm recommending the following:
1. changing the input fields to drop down menus
    1.1 Minutes: * and 00-59
    1.2 Hours * and 00-23
    1.3 Day: * and 01-31 
    1.4 Month: * and 01-12 [a]
    1.5 Day of week: * 0-6 [b]
2. Putting hint text saying if a user selects * from the drop down menu it means it will run on all minutes/hours/days/months/days of the week

[a] We can even show in the text <option> the Month name and keep its value="" with the number that represents it
[b] Same goes here showing the name of the day in text as Sunday for example and in the value="" we put the numbers

If you can point me to the file that controls this I can work on it and send a pull request.

Sample here i entered 11 just to show the error message and normal users might not understand what should they put.
![image](https://cloud.githubusercontent.com/assets/142219/2770571/2c4e7514-ca60-11e3-8756-1c7f57345908.png)

or

![image](https://cloud.githubusercontent.com/assets/142219/2770585/50624d72-ca60-11e3-8612-e06dc891da3d.png)

**Comment by anton-reutov** [comment]
https://bugs.vestacp.com/issues/381
