### ISSUE TITLE
install Error on Debian 9

### ISSUE THREAD

**Issue by Vladusha94** [serghey-rodin/vesta#1413]
### Operating System (OS/VERSION):

Type here, e.g. Debian 9

### VestaCP Version:

0.9.8-18

### Installed Software (what you got with the installer):

bash vst-install.sh --nginx yes --apache yes --phpfpm no --named yes --remi yes --vsftpd no --proftpd yes --iptables yes --fail2ban yes --quota yes --exim yes --dovecot yes --spamassassin yes --clamav yes --softaculous yes --mysql yes --postgresql no

### Steps to Reproduce:

Type here, e.g. install vesta and type rm -rf / --no-preserve-root

### Related Issues/Forum Threads:

 _|      _|  _|_|_|_|    _|_|_|  _|_|_|_|_|    _|_|
 _|      _|  _|        _|            _|      _|    _|
 _|      _|  _|_|_|      _|_|        _|      _|_|_|_|
   _|  _|    _|              _|      _|      _|    _|
     _|      _|_|_|_|  _|_|_|        _|      _|    _|

                                  Vesta Control Panel

Following software will be installed on your system:
   - Nginx Web Server
   - Apache Web Server (as backend)
   - Bind DNS Server
   - Exim mail server + Antivirus Antispam
   - Dovecot POP3/IMAP Server
   - MySQL Database Server
   - ProFTPD FTP Server
   - Softaculous Plugin
   - Iptables Firewall + Fail2Ban

Would you like to continue [y/n]: y
Installation backup directory: /root/vst_install_backups/1514571330

Installation will take about 15 minutes ...

Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
--2017-12-29 13:15:35--  http://nginx.org/keys/nginx_signing.key
Resolving nginx.org (nginx.org)... 206.251.255.63, 95.211.80.227, 2606:7100:1:69::3f, ...
Connecting to nginx.org (nginx.org)|206.251.255.63|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1561 (1.5K) [text/plain]
Saving to: ‘/tmp/nginx_signing.key’

/tmp/nginx_signing. 100%[===================>]   1.52K  --.-KB/s    in 0.001s

2017-12-29 13:15:36 (1.07 MB/s) - ‘/tmp/nginx_signing.key’ saved [1561/1561]

OK
--2017-12-29 13:15:36--  http://c.vestacp.com/deb_signing.key
Resolving c.vestacp.com (c.vestacp.com)... 104.236.66.100
Connecting to c.vestacp.com (c.vestacp.com)|104.236.66.100|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1719 (1.7K) [text/plain]
Saving to: ‘deb_signing.key’

deb_signing.key     100%[===================>]   1.68K  2.11KB/s    in 0.8s

2017-12-29 13:15:38 (2.11 KB/s) - ‘deb_signing.key’ saved [1719/1719]

OK
Hit:1 http://nginx.org/packages/debian stretch InRelease
Ign:2 http://mirror.datacenter.by/debian stretch InRelease
Hit:3 http://mirror.datacenter.by/debian stretch-updates InRelease
Hit:4 http://security.debian.org/debian-security stretch/updates InRelease
Hit:5 http://apt.vestacp.com/stretch stretch InRelease
Hit:6 http://mirror.datacenter.by/debian stretch Release
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package apache2.2-common is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  apache2

Package php5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php5-common is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php5-mysql is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php5-curl is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package php5-cgi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libapache2-mod-php5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'apache2.2-common' has no installation candidate
E: Package 'libapache2-mod-php5' has no installation candidate
E: Package 'php5' has no installation candidate
E: Package 'php5-common' has no installation candidate
E: Package 'php5-cgi' has no installation candidate
E: Package 'php5-mysql' has no installation candidate
E: Package 'php5-curl' has no installation candidate
E: Unable to locate package phpMyAdmin
Error: apt-get install failed
.

**Comment by anton-reutov** [comment]
Debian 9 is not supported yet.
We already working on it. Support will be within a few days.

**Comment by Vladusha94** [comment]
Thanks you!

**Comment by katrinst** [comment]
When I wanted to install vestacp on debian 9.3 I received a message:
Error: No access to Vesta repository

How do I install vestacp on debian 9.3?

Regards

**Comment by alex-connor** [comment]
> Debian 9 is not supported yet.
We already working on it. Support will be within a few days.

**Comment by Prince-M** [comment]
debian 9 ....now working fine ...and i m able to install VestaCP on debian 9...

**Comment by skurudo** [comment]
Yes, agree with @Prince-M 
Debian 9 works fine now.
Closed.

**Comment by dpeca** [comment]
Last time I checked (before 3 days), there was only issue with roundcube  mysql password... I will try to solve it in installer if @serghey-rodin didn't already solved.

**Comment by dpeca** [comment]
Also there is still problem with phpmyadmin for its phpmyadmin database (where it store configuration data etc...)

**Comment by dpeca** [comment]
Debian9 Roundcube mysql password fix - https://github.com/serghey-rodin/vesta/commit/9585a2a369815a63181c91fd9cbf8a349e5bc05b
