### ISSUE TITLE
Vesta fail2ban does not ban IP attacked on MySQL

### ISSUE THREAD

**Issue by rinkuyadav999** [serghey-rodin/vesta#1417]
### Operating System (OS/VERSION):

Ubuntu 16.04 - x86_64

### VestaCP Version:

0.9.8 (amd64) | Release: 18

### Installed Software (what you got with the installer):

apache2, nginx, bind9, exim4, dovecot, clamav-daemon, spamassassin, mysql, vsftpd, cron, iptables, fail2ban

### Steps to Reproduce:

I checked: /var/log/fail2ban.log, it does not ban MySQL attacked IP. it works only for exim and dovecot
Here /var/log/mysql/error.log i found many Access denied Like:
2018-01-01T09:48:38.259035Z 38884 [Note] Access denied for user 'root'@'221.229.204.101' (using password: YES)
Above IP tried to find password 60-70 times but fail2ban does not ban this IP.

### Related Issues/Forum Threads:

Found anything that might be related to this? It might help us find the cause.

### Other Notes:

I have edited codes in /etc/fail2ban/jail.local but still does not ban.

/etc/fail2ban/jail.local::

[ssh-iptables]
enabled  = true
filter   = sshd
action   = vesta[name=SSH]
logpath  = /var/log/auth.log
maxretry = 5

[vsftpd-iptables]
enabled  = true
filter   = vsftpd
action   = vesta[name=FTP]
logpath  = /var/log/vsftpd.log
maxretry = 5

[exim-iptables]
enabled = true
filter  = exim
action  = vesta[name=MAIL]
logpath = /var/log/exim4/mainlog
maxretry = 5

[dovecot-iptables]
enabled = true
filter  = dovecot
action  = vesta[name=MAIL]
logpath = /var/log/dovecot.log
maxretry = 5

[mysqld-iptables]
enabled  = true
filter   = mysqld-auth
action   = vesta[name=DB]
logpath  = /var/log/mysql/error.log
maxretry = 5

[vesta-iptables]
enabled = true
filter  = vesta
action  = vesta[name=VESTA]
logpath = /var/log/vesta/auth.log
maxretry = 5

Why
```
[mysqld-iptables]
enabled = true
filter = mysqld-auth
action = vesta[name=DB]
logpath = /var/log/mysql/error.log
maxretry = 5 
```
does not ban ?

**Comment by rinkuyadav999** [comment]
There was failregex issue,

**Comment by arditmorina** [comment]
@rinkuyadav999  what was the failregex issue ?  Because same issue is happening to me ?

**Comment by rinkuyadav999** [comment]
@arditmorina use https://github.com/fail2ban/fail2ban/blob/0.11/config/filter.d/mysqld-auth.conf
