### ISSUE TITLE
v-rebuild-user failed

### ISSUE THREAD

**Issue by ntfs1984** [serghey-rodin/vesta#1419]
```
root@fakka:/home/admin/conf/web# v-rebuild-user admin
Error: php-fpm restart failed
Error: php-fpm restart failed
Error: php-fpm restart failed
Error: php-fpm restart failed
Error: nginx restart failed
root@fakka:/home/admin/conf/web# systemctl status nginx.service
● nginx.service - nginx - high performance web server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-01-01 20:53:52 CET; 2s ago
     Docs: http://nginx.org/en/docs/
  Process: 32335 ExecStop=/bin/kill -s TERM $MAINPID (code=exited, status=0/SUCCESS)
  Process: 30951 ExecReload=/bin/kill -s HUP $MAINPID (code=exited, status=0/SUCCESS)
  Process: 3802 ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf (code=exited, status=1/FAILURE)
 Main PID: 13401 (code=exited, status=0/SUCCESS)

Jan 01 20:53:52 fakka.online systemd[1]: Starting nginx - high performance web server...
Jan 01 20:53:52 fakka.online nginx[3802]: nginx: [emerg] unexpected "}" in /home/admin/conf/web/fakka.online.nginx.conf:44
Jan 01 20:53:52 fakka.online systemd[1]: nginx.service: Control process exited, code=exited status=1
Jan 01 20:53:52 fakka.online systemd[1]: Failed to start nginx - high performance web server.
Jan 01 20:53:52 fakka.online systemd[1]: nginx.service: Unit entered failed state.
Jan 01 20:53:52 fakka.online systemd[1]: nginx.service: Failed with result 'exit-code'.
root@fakka:/home/admin/conf/web# 
```
BUT HOW ??? I used utility to rebuild configuration, nothing did manually. Did you tested before production at all ???

**Comment by ntfs1984** [comment]
After I inserted ";" what you missed, I've got this":

Jan 01 21:00:49 fakka.online nginx[7077]: nginx: [emerg] open() "/home/admin/conf/web/fakka.online.auth" failed (2: No such file or directory) in /home/admin/conf/web/fakka.online.nginx.conf

Guys, please advice how to fix this ASAP

**Comment by anton-reutov** [comment]
What OS on you server and Vestacp version ? It is necessary to specify

**Comment by ntfs1984** [comment]
Ubuntu 16.04

Seems I have root of issue: something with template. I ran v-update-web-templates and everything was fixed, BUT I want to mention that this bug came without active actions from my end. Previously everything worked fine, today I decided to add domain, saw error, tried to regenerate configs from scratch and got these errors.

**Comment by anton-reutov** [comment]
This issue also reproduced in 0.9.8-17, when you try to restart nginx via ssh
but in 0.9.8-18 this problem already fixed, i think templates on your system was not updated
