### ISSUE TITLE
Backup retention

### ISSUE THREAD

**Issue by harry195** [serghey-rodin/vesta#1421]
### Operating System (OS/VERSION):

Type here, e.g. CentOS 7

### VestaCP Version:

Type here, e.g. 0.9.8-18 (latest from vestacp.com)

### Installed Software (what you got with the installer):

Type here, e.g. exim, dovecot, iptables, proftpd, apache, mysql

### Steps to Reproduce:

Type here, e.g. install vesta and create backups
Backups are created successfully, but retention doesn't work. After the specified limit is reached, the backup is removed from the web interface, but actual file is never deletes thus filling server's space with backups

**Comment by Skamasle** [comment]
In may case rotation working fine

How many backups are you configure to save ?

Can you same more details, also let me see your cron configuration please

**Comment by harry195** [comment]
There are every single cron job that were created during the installation. I doesn't matter how many backups I configure, let's say if I configured 1 backup and I created it, everything works perfectly, If I (or cron) creates another, the old one is deleted from the web interface, but the file remains on the disk.

**Comment by robindirksen1** [comment]
Did you update from 0.9.8-17 to -18?

**Comment by Skamasle** [comment]
Yes, I can confirm it, but this issue is only in one backup, so, if you have this setup

1 backup -> vesta leave 2
2 backups -> vesta leave 3
3 backups -> vesta leave 4

Web site is updated but vesta leave in repositorie one backup more

The counter fail in local_backup() function

**Comment by robindirksen1** [comment]
So with the date+time in the filename it's running correct (so more then 1 backup each day is possible)?

**Comment by Skamasle** [comment]
@robindirksen1 yes you can create more than one backup a day

Just modify your cron, you can run a backup each hour if you whant.

**Comment by robindirksen1** [comment]
I thought that this could be the problem, but it isn't.

**Comment by robindirksen1** [comment]
So this function is failing: https://github.com/serghey-rodin/vesta/blob/dcf0ae96a8279f2a6802f3982c2df45df0b23d1e/bin/v-backup-user#L494
