### ISSUE TITLE
Question about the Password during the installation

### ISSUE THREAD

**Issue by jodumont** [serghey-rodin/vesta#1426]
Hi;

I installed via bash vst-install.sh and wondering the `--password` parameter is it just for the VestaCP WebUI Console on port 8083 ? or it's also used for mysql and postgres, ...

I'm consern because I figured after, I had a space in my cut and paste password and it result of a weak password.

**Comment by darkworks** [comment]
ya i think vesta password is mysql root account password too

**Comment by jodumont** [comment]
thanks for the tips ;)

**Comment by dpeca** [comment]
it's not mysql password too...
