### ISSUE TITLE
FTP 530 login incorrect on 'Upgraded' VestaCP v18

### ISSUE THREAD

**Issue by mehargags** [serghey-rodin/vesta#1437]
### Operating System (OS/VERSION):
Debian 8.x

### VestaCP Version:

Type here, e.g. v0.9.8 release 18

### Installed Software (what you got with the installer):

Type here, e.g. Apache + Nginx

### Steps to Reproduce:

on a VestaCP that is upgraded from v17 to v18, after creating an FTP user for a domain, you can't login and it will throw FTP 530 login incorrect.

### How I fixed:
I checked **/etc/passwd** and I saw that there is an additional _/usr_ in front of _/sbin/nologin_ which was causing it.
Removing the _**/usr**_ fixes the ftp login.

`vestausr_ftpusr:x:1009:1009::/home/vestausr/web/domain.com/public_html:/usr/sbin/nologin`
be changed to
`vestausr_ftpusr:x:1009:1009::/home/vestausr/web/domain.com/public_html:/sbin/nologin`

### No problem on Debian 9
**Note:** Works fine on **Debian 9**, both with upgraded or fresh VestaCP with **/usr/sbin/nologin** for the user in /etc/passwd. The bug is only problem on Debian 8

Can the Devs please take a look into this and confirm if this is a big indeed ?

**Comment by dpeca** [comment]
In SSH, as root, execute:
`echo "/usr/sbin/nologin" >> /etc/shells`
It should solve your problem.

**Comment by robinwo** [comment]
@dpeca This answer is wrong. Doing this, opens up FTP connections for any credentials, so it seems!

**Comment by dpeca** [comment]
"/usr/sbin/nologin" is added to /etc/shells in every VestaCP installation in last two years...
So...
Make conclusion yourself.

**Comment by dpeca** [comment]
https://github.com/serghey-rodin/vesta/blob/master/install/vst-install-debian.sh#L663

**Comment by robinwo** [comment]
Huh, but then how come that this single addition opens up FTP access for any credentials in my setup? Installed Vesta also ~2yrs ago, nothing changed in permissions / FTP services.

**Comment by dpeca** [comment]
Something other is wrong there.
Check /etc/shadow, maybe that account does not have password, or FTP daemon is somehow configured to allow anonymous login.

**Comment by ruturaaj** [comment]
Facing this same problem with VestaCP on CentOS 7.5 ... none of the above solutions working good for me. Any help for CentOS 7.x?

**Comment by alex-connor** [comment]
Try to follow this tip:
> In SSH, as root, execute:
> `echo "/usr/sbin/nologin" >> /etc/shells`
> It should solve your problem.

**Comment by ruturaaj** [comment]
`/usr/sbin/nologin` was already there; I checked the passwds and added `/sbin/nologin` to `/etc/shells` ... this solved my problem.

**Comment by lukapaunovic** [comment]
Yes, @ruturaaj adding` /sbin/nologin` solved the issue and `/usr/sbin/nologin` was already there. 
So @dpeca you should commit and add `/sbin/nologin` to `/etc/shells` too.
Because I just installed Vesta and updated with files from GitHub, on Centos 7 64 bit latest version. And I had this issue.

**Comment by HristoA** [comment]
In fresh installation of CentOS 7.5 and last VestaCP this: `echo "/usr/sbin/nologin" >> /etc/shells`  work like charm

**Comment by KashifHK123** [comment]
> guess not all images are the same. Both should be added.

it work for me, Thanks!

**Comment by KashifHK123** [comment]
`echo "/sbin/nologin" >> /etc/shells`
it work for me in Centos 7, **Thanks!**

**Comment by hieuhuynh93** [comment]
I'm using v24 on CentOS 7, this issue still not fixed. So I have to add 2 lines to /etc/shells by manually.
Thanks for the best way.

**Comment by lukapaunovic** [comment]
@hieuhuynh93 It's fixed on GitHub just release hasn't been made yet.  :/

**Comment by hidonet** [comment]
Changed this line 
pam_service_name=ftp
to 
pam_service_name=vsftpd
in /etc/vsftpd/vsftpd.conf and worked for me.
