### ISSUE TITLE
Error in nginx php5-fpm template files (vstats section)

### ISSUE THREAD

**Issue by n1trux** [serghey-rodin/vesta#1439]
Hi guys,

I noticed that there's an error since the newest update in nearly every template on my system (Debian 8, nginx, php5-fpm).

The vstats section looks like this:

    location /vstats/ {
        alias   %home%/%user%/web/%domain%/stats/;
        include %home%/%user%/conf/web/%domain%.auth
    }

There's a `.conf;` missing at the end of the include line. Why is that?

**Comment by mehargags** [comment]
I got that bug too on one of my servers

the previous sites from v17 have the line as 
include /home/<user>/web/<domain>/stats/auth.conf*;

But when I created a new site for user after v19 upgrade, it shows the line like
include /home/<user>/conf/web/<domain>auth

I had to put in *; in the end to be able to pass thru Nginx -t.

Definitely a bug left... can we get this fixed ASAP pls. It is breaking whole server

**Comment by cakama3a** [comment]
+1
