### ISSUE TITLE
Nginx HTTP2 template does not work

### ISSUE THREAD

**Issue by elnino79** [serghey-rodin/vesta#1462]
### Operating System (OS/VERSION):

Debian 9.3

### VestaCP Version:

0.9.8-18

### Installed Software (what you got with the installer):

vst-install.sh --nginx yes --apache yes --phpfpm no --named no --remi yes --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota no --exim no --dovecot no --spamassassin no --clamav no --softaculous yes --mysql yes --postgresql no --hostname xxx.xxx.xx --email xxx@xxx.xx --password xxx

### Steps to Reproduce:

After changing Nginx template to HTTP2, service Nginx does not restart. 

> systemd[1]: Starting nginx - high performance web server...  
> nginx[23034]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok  
> nginx: [emerg] open() "/var/log/httpd/domains/xxx.xxx.xx.error.log" failed (2: No such file or directory)  
> nginx: configuration file /etc/nginx/nginx.conf test failed  
> nginx.service: Control process exited, code=exited status=1

**Comment by anton-reutov** [comment]
Hi,
we will check it

**Comment by ZulqarnainKhaan** [comment]
Same issue i faced, when disabled http2 template, nginx restarted

Ubuntu 18.04
Nginx + Apache config

**Comment by anton-reutov** [comment]
@ZulqarnainKhaan use this templates
https://github.com/serghey-rodin/vesta/blob/master/install/ubuntu/18.04/templates/web/nginx/http2.tpl
https://github.com/serghey-rodin/vesta/commit/d6c79c7d7ee3b5cbc04b235798af9e6d1a7a62f5

@elnino79 already solved
