### ISSUE TITLE
GLIBC_2.14 unavailable on Debian 7.11

### ISSUE THREAD

**Issue by apmorton** [serghey-rodin/vesta#1465]
### Operating System (OS/VERSION):

Debian 7.11

### VestaCP Version:

0.9.8-19

### Steps to Reproduce:

```
# /etc/init.d/vesta start
[....] Starting vesta-nginx: vesta-nginx/usr/local/vesta/nginx/sbin/vesta-nginx: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/vesta/nginx/sbin/vesta-nginx)
```

### Other Notes:

System previously working, update to 0.9.8-19 appears to have broken support for Debian 7

**Comment by anton-reutov** [comment]
```
apt-get update
apt-get install vesta-nginx vesta-php --reinstall
```

**Comment by apmorton** [comment]
resolved.  just so I know - did you silently push a change to 0.9.8-19 at some point, or was this some other issue on my end?
