### ISSUE TITLE
Breaking install centos 7

### ISSUE THREAD

**Issue by hiepvq** [serghey-rodin/vesta#1471]
Note: Forwarding request to 'systemctl enable nginx.service'.
Created symlink /etc/systemd/system/multi-user.target.wants/nginx.service, pointing to /usr/lib/systemd/system/nginx.service.
Redirecting to /bin/systemctl start nginx.service
Failed to get D-Bus connection: Operation not permitted
Error: nginx start failed

i am using centos 7 on docker

**Comment by Skamasle** [comment]
I install this in centos 7 a lot off times and not get issues, so, maybe docker problem ?
