### ISSUE TITLE
NGINX conf site level reverts back to default.

### ISSUE THREAD

**Issue by ahmnabil** [serghey-rodin/vesta#1472]
### Operating System (OS/VERSION):
CentOS 7

### VestaCP Version:
0.9.8 | Release:19

### Installed Software (what you got with the installer):

nginx, php-fpm

### Steps to Reproduce:

edit nginx conf site level located at
/home/user/conf/web/example.com.nginx.conf

save and restart nginx, then i don't know when did it happen, but all the edits were gone.

**Comment by Skamasle** [comment]
When you rebuild or save something in vestacp you lost your edits

So you not need change that file, but you can create new template for that site and leave it in /usr/local/vesta/data/templates/nginx or use the include file.

**Comment by ahmnabil** [comment]
hello, i don't have that folder
/usr/local/vesta/data/templates/"nginx"
 i only have dns and web
should i create it?

but again, before the last update everything was working fine editing the site specific template nginx. and there are configs that i need to be applied to one site only.
