### ISSUE TITLE
Could have an option to uninstall or disable phpMyAdmin?

### ISSUE THREAD

**Issue by edirpedro** [serghey-rodin/vesta#1480]
I didn't find any option to disable or uninstall the phpMyAdmin. I don't know if I can uninstall this too.

I prefer to connect through SSH and I use local tools like Sequel. I had experienced a malware attack on the last server I've built, I forgot to change the URL to access the phpMyAdmin and in the first day that the server was active, it got a malware, then I changed manually the phpMyAdmin URL because I got many requests to this tool, then I cleaned the server, one week after and nothing happens until now. I don't know if phpMyAdmin was the reason but as I don't use this tool, I'd love an ease way to disable it, direct in the Vesta panel.

**Comment by edirpedro** [comment]
Thanks @Skamasle, that' a better solution to me.

Just a suggestion. There are options on the page `/edit/server/`, could be an option to disable it in that form.

**Comment by Skamasle** [comment]
Not, that not disable it, that only remove link from phpmyadmin

**Comment by weergave1** [comment]
why would difficult do just do this in ssh.
yum remove phpmyadmin

**Comment by NickCoolii** [comment]
> You can disable it. Just move out /etc/httpd/conf.d/phpmyadmin.conf
In my case that was `/etc/apache2/conf.d/phpmyadmin.conf` - symlink to `/etc/phpmyadmin/apache.conf`.
