### ISSUE TITLE
 Laravel setup Support out of box

### ISSUE THREAD

**Issue by dipit2007** [serghey-rodin/vesta#1487]
please provide  Laravel setup Support out of box. Its required for most of the user.

**Comment by robindirksen1** [comment]
So you want a template that supports laravel? This can be made by yourself, copy the default.(s)tpl in the /usr/local/vesta/data/template/httpd(nginx)/  folder and change the document root with /public behind.

**Comment by madeITBelgium** [comment]
There is already laravel template support. https://github.com/serghey-rodin/vesta/blob/master/install/rhel/7/templates/web/nginx/php-fpm/laravel.tpl

**Comment by dipit2007** [comment]
what if I want to setup nginx as front end & apache as back-end? I need this type setup out of box . Can you please help me? Thanks a lot.

**Comment by madeITBelgium** [comment]
Yes you can use that too. I have multiple laravel websites running on nginx+apache vesta cp instance. What exactly do you need?

**Comment by dipit2007** [comment]
What I do now .. I install Laravel in private folder of each domain. then move public folder content of Laravel to public_html and change laravel's index.php accordingly. 

All these I do manually . Then I need to provide permission as following

php_admin_value open_basedir /home/admin/web/example.com/public_html:/home/admin/web/example.com/private/bitbucket:/home/admin/tmp

So, can we do all these from Vesta without manual intervention. Please help me.

Thanks a lot.

**Comment by robindirksen1** [comment]
As @madeITBelgium said, you can use the template (edit domain -> nginx template - select "laravel") which will point the document_root to public, for example: /home/user/web/domain/public_html/public. All your site content will be placed in public_html (.env, /app, /config, etc).

If the nginx template doesn't  exists create it under: /usr/local/vesta/data/templates/web/nginx/ (correct me if i'm wrong @madeITBelgium )

**Comment by madeITBelgium** [comment]
The template will only exist if you have a nginx - php-fpm installation.
What I do on my nginx - apache installation.
Upload laravel code to public_html. Then create .htaccess file with:

```
<IfModule mod_rewrite.c>
	RewriteEngine on
	
	RewriteCond %{REQUEST_URI} !^public
	RewriteRule ^(.*)$ public/$1 [L]
</IfModule>
```
