### ISSUE TITLE
SPF and DKIM Mail Validation 

### ISSUE THREAD

**Issue by Exadra37** [serghey-rodin/vesta#149]
if our server supports IPv6, the DKIM and SPF validation will fail with the default DNS configuration provided by Vestacp, with your email going directly to spam box in Hotmail and Yahoo.

The solution is to change the txt record for the SPF i if your server supports IPv6 in the DNS from `v=spf1 a mx ip4:123.456.789.987 ?all` to `v=spf1 a mx ip4:123.456.789.987 ip6:1a00:2b00::3c00:4d00:5e00:6f00 -all`, changing the ip addresses to match the ones used by your server.

@serghey-rodin Can you add ipv6 support to the SPF template in DNS for the next VestaCp release?

Other tips to have a properly mail validation:

Apply this workaround https://github.com/serghey-rodin/vesta/issues/148 to solve  mail permissions issues.

You need also to setup ptr records. Ask to your VPS or Server provider to do that.

If you don't want to go to their spam list do not send emails to Yahoo or Hotmail without using a tool to validate your mail server.

The best tool to check the email validation for me his http://www.port25.com/support/authentication-center/email-verification/

Perform this tests from webmail, outlook and php.

If is validate for all, now Yahoo and Hotmail will accept your first email without complains, but if you already have sent some emails, that have been marked as spam you will need to wait a long time until you will be white listed again.

In that case you can ask for support in https://io.help.yahoo.com/contact/index?locale=en_US&y=PROD_MAIL&page=contact&actp=lorax and http://mail.live.com/mail/postmaster.aspx

P.S: Sorry if my English is not very good, but is not my natural language.
EDIT: Fix typo

**Comment by SysVoid** [comment]
Closing old issue.
