### ISSUE TITLE
v-restore-user screw up mysql accounts

### ISSUE THREAD

**Issue by kolomparrudi** [serghey-rodin/vesta#1523]
### Operating System (OS/VERSION):
Debian 8 jessie

### VestaCP Version:
latest

### Installed Software (what you got with the installer):
php-fpm, apache, mysql

### Steps to Reproduce:
v-restore-user username backupname
### Related Issues/Forum Threads:
I restored a some days old backup to an existing accout.
After restore the previously working mysql account won't work (user exists, but password is wrong).

### Other Notes:
Selective restore not working, I tried to restore only web and mysql by running v-restore-user with these arguments:
v-restore-user USER BACKUP yes no no yes no no no

**Comment by dpeca** [comment]
What distribution?
I have this issue on Debian9, but backup was generated on Debian8.

**Comment by kolomparrudi** [comment]
It's debian 8 (jessie)

**Comment by iLogge** [comment]
yep, i have a similar problem. my fix is to delete the database first, then run restore again.

**Comment by dpeca** [comment]
Issue is happening even I restore backup to new server, so database does not exists before resoring backup.

**Comment by iLogge** [comment]
ok thats strange. im also on debian 9 and restred backups from a previous debian 8 installation. i did them partially like you (kinda). what happend to me when i ran the command multiple times -> database counter increased while no new database was created (files were overwritten correctly) but my pw didnt work anymore and i couldnt fix it by setting a new pw. i had to delete the database and then restore it again. i was running the restore command with the real database name instead of "yes" and renamed the backup file to read the same as the new/old system user.

**Comment by dpeca** [comment]
This is happening even on the same machine, just checked.
- create db
- make backup
- remove db
- restore backup
= wrong mysql pass.

I will investigate this now.

**Comment by dpeca** [comment]
`v-restore-user` is not creating mysql user.....

now we will see why...

**Comment by dpeca** [comment]
function `rebuild_mysql_database()` in `func/rebuild.sh`
```
2018-04-05 19:32:18 admin_wp1
CREATE DATABASE `admin_wp1` CHARACTER SET UTF8
GRANT ALL ON `admin_wp1`.* TO `admin_wp1`@`%`
ERROR 1133 (28000) at line 1: Can't find any matching row in the user table
GRANT ALL ON `admin_wp1`.* TO `admin_wp1`@localhost
ERROR 1133 (28000) at line 1: Can't find any matching row in the user table
UPDATE mysql.user SET Password='*7AB1D8D5C04A0E7B5B6BE84B9DDB91921DE71500' WHERE User='admin_wp1'
FLUSH PRIVILEGES
```

**Comment by dpeca** [comment]
bug is here:
https://github.com/dpeca/vesta/blob/master/func/rebuild.sh#L538

**Comment by dpeca** [comment]
It see version `10` as `1`

**Comment by Skamasle** [comment]
Yes that fix mysql 5.7 compatibility so need add some fixes for mariadb 10.1 I investigate it from mariadb 10.x but no time to fix

Need aditional fixes for mariadb 10 and also future mysql 8

**Comment by dpeca** [comment]
Yup, `-f1` should be checked also...
OK, we got it.
I'll fix now.

**Comment by Skamasle** [comment]
I think better way for that is a function to check if is mariadb and if is mysql, is easy way to get compatibility for future realeses

**Comment by dpeca** [comment]
Any idea how we can check if it's Maria?

**Comment by Skamasle** [comment]
Not is that line the issue, the issue here is a user creation

rebuild_mysql_database() {
    mysql_connect $HOST
    mysql_query "CREATE DATABASE \`$DB\` CHARACTER SET $CHARSET" >/dev/null

    if [ "$(echo $mysql_ver |cut -d '.' -f2)" -ge 7 ]; then
        mysql_query "CREATE USER IF NOT EXISTS \`$DBUSER\`" >/dev/null
        mysql_query "CREATE USER IF NOT EXISTS \`$DBUSER\`@localhost" >/dev/null
        query="UPDATE mysql.user SET authentication_string='$MD5'"
        query="$query WHERE User='$DBUSER'"
    else
        query="UPDATE mysql.user SET Password='$MD5' WHERE User='$DBUSER'"
    fi
    mysql_query "CREATE USER '$DBUSER'@'%';"
    mysql_query "CREATE USER '$DBUSER'@'localhost';"
    mysql_query "GRANT ALL ON \`$DB\`.* TO \`$DBUSER\`@\`%\`" >/dev/null
    mysql_query "GRANT ALL ON \`$DB\`.* TO \`$DBUSER\`@localhost" >/dev/null
    mysql_query "$query" >/dev/null
    mysql_query "FLUSH PRIVILEGES" >/dev/null
}

Maybe this happen in some mysql version

**Comment by Skamasle** [comment]
You can see in your mysql, the user never be created in restore, so cant reset password with a UPDATE query

In 5.7 version I create user not know why exactly omit it in orther versions.

**Comment by dpeca** [comment]
Yes, I figured it out too... Maria is using Password field for some reason...
I found a way to check if it's Maria

**Comment by Skamasle** [comment]
I think is not need i not know 10.2 but it works in same way I this is valid for mysql also so just add that lines 

    mysql_query "CREATE USER '$DBUSER'@'%';"
     mysql_query "CREATE USER '$DBUSER'@'localhost';"

**Comment by Skamasle** [comment]
Maybe in this way is easyest

```
rebuild_mysql_database() {
    mysql_connect $HOST
    mysql_query "CREATE DATABASE \`$DB\` CHARACTER SET $CHARSET" >/dev/null
    mysql_query "CREATE USER IF NOT EXISTS \`$DBUSER\`" >/dev/null
    mysql_query "CREATE USER IF NOT EXISTS \`$DBUSER\`@localhost" >/dev/null
    if [ "$(echo $mysql_ver |cut -d '.' -f2)" -ge 7 ]; then
        query="UPDATE mysql.user SET authentication_string='$MD5'"
        query="$query WHERE User='$DBUSER'"
    else
        query="UPDATE mysql.user SET Password='$MD5' WHERE User='$DBUSER'"
    fi
    mysql_query "GRANT ALL ON \`$DB\`.* TO \`$DBUSER\`@\`%\`" >/dev/null
    mysql_query "GRANT ALL ON \`$DB\`.* TO \`$DBUSER\`@localhost" >/dev/null
    mysql_query "$query" >/dev/null
    mysql_query "FLUSH PRIVILEGES" >/dev/null
}
```

**Comment by Skamasle** [comment]
Ok that last slould work but I think will fail in mysql 5.1 not know exactly if mysql 5.1 can interpret "CREATE USER IF NOT EXISTS" but always this part "IF NOT EXISTS" can be removed and do compatibility

**Comment by dpeca** [comment]
I think this is it - https://github.com/serghey-rodin/vesta/commit/eb7e6d2fba27e5ebbf1284ec924941073094a985
I will please users to test this fix on CentOS.
Works fine on Debian.

**Comment by dpeca** [comment]
OK, i'm on it...

**Comment by moucho** [comment]
If it is of any help, on my installs with CentOS 7 and MariaDB 10.1 and MariaDB 10.2 the problem was that on this versions the statement "GRANT" doesn't create the user, because by default sql_mode is set with NO_AUTO_CREATE_USER
I added the line "sql_mode = NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO"
to keep the defaults but allow to create users with "GRANT" statement.

Right now everything works as expected, with VestaCP version 0.9.8-19 on CentOS 7 and MariaDB (10.1-10.2)

**Comment by dpeca** [comment]
I forgot `>/dev/null` in my fix, that's why errors shown...
And somehow restoring create user... even with that error...

If I understand @Skamasle - he is sugesting that we should use SQL from ELSE block (that is created for mysql < 5.7 ) and then to add `CREATE USER` again below.

That idea has two problems.
First, it sounds wrong to use SQL that is created for mysql 5.7 in completly new MariaDB fork.
Second, that way `CREATE USER` will be executed twice, firstly in IF (mysql_ver -gt 7 ) and secondly below.

I guess the only problem is `IF NOT EXISTS`...
And somehow user is created even with that error...
And the reason why we see error is because I forgot `>/dev/null` in my fix.

**Comment by dpeca** [comment]
```
        if [ "$mysql_fork" = "mariadb" ] && [ "$(echo $mysql_ver |cut -d '.' -f1)" -eq 5 ]; then
            mysql_query "CREATE USER \`$DBUSER\`" 
            mysql_query "CREATE USER \`$DBUSER\`@localhost" 
        else
            mysql_query "CREATE USER IF NOT EXISTS \`$DBUSER\`" 
            mysql_query "CREATE USER IF NOT EXISTS \`$DBUSER\`@localhost" 
        fi
```

What do you think?

**Comment by dpeca** [comment]
https://github.com/serghey-rodin/vesta/commit/b3d78bbfdb1d9642abb2e5efc5ff056b5fe2703b

**Comment by dpeca** [comment]
Refactoring is welcomed.
Code now looks like confusion, but it works fine now.
However, should be refactored, probably this way:
```
IF mysql
    IF < 5.7
    IF >= 5.7
IF mariadb
    IF = 5
    IF = 10
```

Or simple to use old SQL statements that works on all versions, like here https://github.com/serghey-rodin/vesta/blob/master/func/db.sh#L202-L208

**Comment by dpeca** [comment]
OK, I refactored it.

Here is exactly what I did - whole proccess from old code through patching issue and refactoring - http://mycity.tech/screenshots/refactoring-rebuild_mysql_database.png

Just to help to all of us to understand what is done and what code is for what mysql version.

**Comment by dpeca** [comment]
Tested on:
- mysql 5.5.59 (debian8)
- mariadb 5.5.56 (centos7)
- mariadb 10.1.26 (debian9)
