### ISSUE TITLE
Bug in Calculation @ v-update-user-counters

### ISSUE THREAD

**Issue by iLogge** [serghey-rodin/vesta#1526]
### Operating System (OS/VERSION):

Debian 9

### VestaCP Version:

Latest

### Installed Software (what you got with the installer):

Default

### Steps to Reproduce:

just run from shell ->   "v-update-user-counters"   , then check counters in panel and compare them to directory size calculation directly from console. you will see they are wrong.

### Related Issues/Forum Threads:

my own topic:
https://forum.vestacp.com/viewtopic.php?f=41&t=16493&p=68314#p68314

### Other Notes:

FIX: 

in "v-update-user-counters" add "DISK=0" after line 55.

    U_DISK=0
    DISK=0  ## FIX
    U_DISK_DIRS=$(get_user_value '$U_DISK_DIRS')

thats it :)

**Comment by skullwritter** [comment]
ok, i will put an pull request, but i cannot get the same results in ubuntu. in here, everything is equal to me.
