### ISSUE TITLE
[PR] Mail, SSL, domains: Automatically create PEM certificate bundle for dovecot after LetsEncrypt renews certificate

### ISSUE THREAD

**Issue by giacomodeglinnocenti** [serghey-rodin/vesta#1528]
### Operating System (OS/VERSION):

Debian 9 Stretch

### VestaCP Version:

latest stable?

### Installed Software (what you got with the installer):

apache, nginx, mysql, exim4, dovecot, ...

### Steps to Reproduce:

Install Vesta
Create and configure a domain
Issue a LetsEncrypt SSL Certificate
Manually create a bundle PEM to work with Dovecot
Make the certificate expire

### Related Issues/Forum Threads:

Pem bundle is not update

### Other Notes:

**Possible solutions:**

This thread is actually a discussion in order to open a PR. 
All begun with my dovecot SSL configuration, as in order to Dovecot to work, I needed to create a PEM bundle manually concatenating the original PEM and the CA files in a new file as in exaple:

```
cd /home/<user>/conf/web/
cat ssl.<domain>.com.pem ssl.<domain>.it.ca > ssl.<domain>.com.bundle.pem
#dont forget to give right permissions
chmod 644 /home/<user>/conf/web/ssl.<domain>.com.bundle.pem
chmod 644 /home/<user>/conf/web/ssl.<domain>.com.key
```
so once I have the bundled PEM, I actually can use it in the dovecot SSL conf to make it work, as follows:

```
in /etc/dovecot/conf.d/10-ssl.conf
----------------------------------

ssl = yes
ssl_cert = </usr/local/vesta/ssl/certificate.crt
ssl_key = </usr/local/vesta/ssl/certificate.key

local_name mail.<domain>.com {
  ssl_cert = </home/<user>/conf/web/ssl.<domain>.com.bundle.pem
  ssl_key = </home/<user>/conf/web/ssl.<domain>.com.key
}
```

so at this point I Just need to 

`systemctl restart dovecot`

and I can start use SSL mail service by clients.

NOW, the point is that after 3 months the certificate will expire and so the bundled PEM certificate will be no more valid. I think it would be quite simple and easy to keep Vesta LetsEncrypt renewal script to just do the additional concat and so preserve the validity of my file.

So I'm thinking to submit a PR, but I would like to actually discuss with you about this modification.

Any side effect? Do you think this could be useful to have?

I think the file to be edit is this one:

vesta/bin/v-update-letsencrypt-ssl

https://github.com/serghey-rodin/vesta/blob/master/bin/v-update-letsencrypt-ssl

Do you think is this correct?

Thanks,
 Giacomo

**Comment by dpeca** [comment]
Correct place will be under my latest commit - https://github.com/serghey-rodin/vesta/commit/b2e75d89b763cc82d12696bceceda20199b22716

So, it should be v-add-web-domain-ssl

Idea is OK to me.

**Comment by giacomodeglinnocenti** [comment]
We can close this as for real Dovecot does NOT need the .pem to wok, so all the discussion is worthless. Thanks anyway for the attention.

Cheers
