### ISSUE TITLE
You should really change "william.cage" into "example"

### ISSUE THREAD

**Issue by andreagobetti** [serghey-rodin/vesta#1530]
Today something went wrong while i was creating a new mail account, after clicking on **add** instead of showing me the username that I had typed, in the box on the right it showed me "william.cage@myservername".

![william](https://user-images.githubusercontent.com/16362674/38460727-fe567ae2-3abf-11e8-826d-0fe4dc4288c0.png)

I received an empty confirmation mail from Vesta, I tought this behavior was caused by a virus, maybe an attempt to create an account to send spam mails, and started analyzing all my logs and server files for hours, then I came to know that william.cage isn't a bad guy alias, but only a bad example username, you should really change **_william.cage_** into **_example_**! :smile: 

The template is web/templates/admin/add_mail_acc.html on line 161

**Comment by Neustradamus** [comment]
Ticket to close no?

**Comment by andreagobetti** [comment]
Problem solved, thanks!
