### ISSUE TITLE
High Outgoing Traffic

### ISSUE THREAD

**Issue by LandyLane** [serghey-rodin/vesta#1535]
### Operating System (OS/VERSION):

Ubuntu 16.04.4 LTS

### VestaCP Version:

0.9.8-18 (current download version)

### Installed Software (what you got with the installer):

install command:vst-install-ubuntu.sh --nginx yes 
				--apache yes --phpfpm no --named yes --remi yes
				--vsftpd no --proftpd no --iptables yes 
				--fail2ban yes --quota no --exim yes --dovecot yes 
				--spamassassin yes --clamav yes --softaculous no 
				--mysql yes --postgresql no

### Steps to Reproduce:

Unknown, check network usage (i used tcptrack)

### Other Notes:

I logged into a VPS I setup for a friend running VestaCP that I recently installed. Everything was setup as normal; however logs show since yesterday it began spiking network traffic. I thought this was just a unique case but I checked other VPS's where I had installed Vesta and they too had extremely high network usage. 

Here is when I was watching during an attack: https://i.gyazo.com/6bad454c12d10d9fa3f95a780ffaa2c4.png

After blocking the outgoing IP address via IP tables:
https://i.gyazo.com/3787f7e3c907f3ab3a156e95692b3a95.mp4

Soon after it began attacking a new IP address. 
https://i.gyazo.com/523ccc7c4a5728a6a040a79613bf21a0.mp4

I can't determine the source IP address as I had to shutdown the box to prevent reaching its network's outgoing cap for the month. Let me know if anyone else experience similar issues. (Note: the vps's are running on Microsofts Azure hosting -> 1 hour of network traffic https://i.gyazo.com/f5e294d425827a9dfeafa81384b9cbb8.png, 2 days of traffic: https://i.gyazo.com/3636c6c8dc2ef46428dc737a8c96c3a4.png)

**Comment by madeITBelgium** [comment]
https://forum.vestacp.com/viewtopic.php?f=10&t=16556
