### ISSUE TITLE
Problem updating packages

### ISSUE THREAD

**Issue by wavedocs** [serghey-rodin/vesta#1536]
### Operating System (OS/VERSION):

Debian 8.10

### VestaCP Version:

0.9.8

### Installed Software (what you got with the installer):

apache, nginx, mysql

### Steps to Reproduce:

v-update-sys-vesta

### Other Notes:

It's a bad idea to [check](https://github.com/serghey-rodin/vesta/blob/master/bin/v-update-sys-vesta#L36) the directory /etc/sysconfig  for the batch operating system manager

```
wavedocs@im: ~# sudo v-update-sys-vesta-all
/usr/local/vesta/bin/v-update-sys-vesta: line 38: yum: command not found
Error: vesta update failed
/usr/local/vesta/bin/v-update-sys-vesta: line 38: yum: command not found
Error: vesta-nginx update failed
/usr/local/vesta/bin/v-update-sys-vesta: line 38: yum: command not found
Error: vesta-php update failed
/usr/local/vesta/bin/v-update-sys-vesta: line 38: yum: command not found
Error: vesta-ioncube update failed
/usr/local/vesta/bin/v-update-sys-vesta: line 38: yum: command not found
```

**Comment by alex-connor** [comment]
This requirement for correct work of Softaculous

**Comment by darkworks** [comment]
Debian not use YUM ,it use standard apt  package manager ,

if you have cent OS  you can install YUM via rpm if its not installed 

install yum , looks like you do not have yum , you can install yum via rpm 

```
wget http://mirror.centos.org/centos/6/os/i386/Packages/yum-3.2.29-40.el6.centos.noarch.rpm
rpm -Uvh yum-3.2.29-40.el6.centos.noarch.rpm
```

**Comment by SjamonDaal** [comment]
Not working because Debian is apt-get, so yum: command not found.

**Comment by KeiroD** [comment]
So replace the commands with `apt`.

**Comment by baoang** [comment]
@alex-connor but if users don't select softabulous module, for instance, just with nginx, php-fpm, mysql an remi, ioncube is somewhat not necessary.

**Comment by noogen** [comment]
@baoang ioncube lib(.so/binary) come with just for use on Vesta (/usr/local/vesta/ioncub) as it is required for Scriptaculous.  It is not required to install on your system.  Vesta run on it's on isolated nginx with php5.6-fpm configured with php ini here: /usr/local/vesta/php/lib/php.ini

**Comment by baoang** [comment]
Thank you, @noogen for your information. The reason I mentioned ioncube is that when installing Vesta on CentOS (6 & 7), I found the following warning message. I don't know if there's something wrong with my distro. It reported *no such file or dir*. 
```
  Installing : vesta-0.9.8-20.x86_64                                                        232/242
  Installing : vesta-ioncube-0.9.8-20.x86_64                                                233/242
/usr/local/vesta/ioncube/ioncube.sh: line 19: /etc/init.d/vesta: No such file or directory
warning: %post(vesta-ioncube-0.9.8-20.x86_64) scriptlet failed, exit status 127
Non-fatal POSTIN scriptlet failure in rpm package vesta-ioncube-0.9.8-20.x86_64
  Installing : mailx-12.5-16.el7.x86_64                                                     234/242
```

I ran the scripts like this
```
bash vst-install.sh --nginx yes --phpfpm yes --apache no --named no --remi yes --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota no --exim no --dovecot no --spamassassin no --clamav no --softaculous no --mysql yes --postgresql no
```

**Comment by anton-reutov** [comment]
Debian 8, can't reproduce this problem
