### ISSUE TITLE
Softalocus not working after update to 0.9.8-20

### ISSUE THREAD

**Issue by robindirksen1** [serghey-rodin/vesta#1539]
### Operating System (OS/VERSION):

Centos 7.4

### VestaCP Version:

0.9.8-20 (updated yesterday)

### Installed Software (what you got with the installer):

Default installer

### Steps to Reproduce:

Update VestaCP to 0.9.8-20 with GUI web updater

### Related Issues/Forum Threads:

-

### Other Notes:

Response from softalocus: 
```Site error: the ionCube PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking. Please visit get-loader.ioncube.com for install assistance.```

![image](https://user-images.githubusercontent.com/22446895/38549297-fe84ce88-3cb3-11e8-9156-f43e303b96bc.png)

**Comment by SjamonDaal** [comment]
Check if the installed ionCube Loader is compatible with your current PHP version.

**Comment by alex-connor** [comment]
For fix this issue run script /usr/local/vesta/ioncube/ioncube.sh

**Comment by robindirksen1** [comment]
@alex-connor fixed by running the command you provided: `/usr/local/vesta/ioncube/ioncube.sh`
