### ISSUE TITLE
SSL config error in nginx

### ISSUE THREAD

**Issue by xchwarze** [serghey-rodin/vesta#1550]
### Operating System (OS/VERSION):
Ubuntu 16LTS

### VestaCP Version:
0.9.8 r20

### Installed Software (what you got with the installer):
php-fpm, apache, nginx, mysql

### Steps to Reproduce:
Activate SSL on hosts block nginx.

root@agendaonline:/var/log/nginx# less error.log
2018/04/18 00:08:58 [emerg] 8345#8345: unexpected "}" in /home/admin/conf/web/xxxxxxxxxxxx.com.nginx.ssl.conf:60

XXXXXXXXXXX.nginx.ssl.conf:60
    location /vstats/ {
        alias   /home/admin/web/xxxxxxxxxxxxxxxxx.com/stats/;
        include /home/admin/conf/web/xxxxxxxxxxxxxxxxx.com.auth
    }

after edit....
2018/04/18 00:12:31 [emerg] 9026#9026: open() "/home/admin/conf/web/.com.auth"xxxxxxxxxxxxxxxxx failed (2: No such file or directory) in /home/admin/conf/web/xxxxxxxxxxxxxxxxx.com.nginx.ssl.conf:59

### Other Notes:
This fail after update to 0.9.8 r19

**Comment by asfihani** [comment]
Please check your template files for example /usr/local/vesta/data/templates/web/nginx/php-fpm/wordpress.tpl section **location /vstats/**, if you found line:

`include %home%/%user%/conf/web/%domain%.auth`

you should modify to:

`include %home%/%user%/conf/web/%domain%.auth*;`

a simple **replace** command can do the trick:

`replace 'include %home%/%user%/conf/web/%domain%.auth' 'include %home%/%user%/conf/web/%domain%.auth*;' -- /usr/local/vesta/data/templates/web/nginx/php-fpm/*`

don't forget to backup the templates or and rebuild the user

**Comment by xchwarze** [comment]
thanks!
fixed after reinstall all templates
