### ISSUE TITLE
Creating subdomains by non-owners.

### ISSUE THREAD

**Issue by BukinPK** [serghey-rodin/vesta#1555]
### Operating System (OS/VERSION):

Ubuntu 14.04

### VestaCP Version:

0.9.8 20

### Installed Software (what you got with the installer):

apache, nginx, mysql, bind

### Steps to Reproduce:

Users can create and use subdomains for domains of other clients whose domain zone is hosted on our server. 
This is unacceptable.

**Comment by ifaist0s** [comment]
I was able to reproduce this issue. **Ubuntu 16.04** with **VESTA 0.9.8 r20**
I was also able to obtain a **Let's Encrypt SSL certificate for the subdomain!**

This situation could lead to serious problems.

**Comment by Hoto-Cocoa** [comment]
This makes not admin user can create a sub-domain in main domain.

**Comment by ifaist0s** [comment]
I'm really disappointed to see that such a security issue was closed by the maintainer. Dismissing such an issue so easily, unfortunately marks VESPA CP as a LAB/Testing Software, not suitable for hosting/production use.

Alas if anyone could get _**support**.vestacp.com,_ or _**billing**.vestacp.com,_  by only hosting it on the same server as _vestacp.com_.

**Comment by kittyhackcom** [comment]
I have lot of servers running on vestacp with lot of custimisations and scripts made just for it.

Time to do a fork just to repair this (or at least be able to disable it).
