### ISSUE TITLE
is web/list/rrd/image.php simply trash?

### ISSUE THREAD

**Issue by szbnwer** [serghey-rodin/vesta#1556]
trash, or it had a purpose that havent been achieved, or i didnt get the point of it? :D

**Comment by noogen** [comment]
Huh?  What do you mean trash?  It is use to display those statistic images on the GRAPH menu.

**Comment by szbnwer** [comment]
ahhh sorry, i fooled myself by asking before learning a bit :D i just didnt understand that it sends headers only but no content... now i know its just nginx magic :)

sorry for the noize, and thx for your replay! :)
