### ISSUE TITLE
License is visible on demo

### ISSUE THREAD

**Issue by noogen** [serghey-rodin/vesta#1557]
### Operating System (OS/VERSION):

Ubuntu 16.04 / Any or All OS

### VestaCP Version:

0.9.20 / Any or All

### Installed Software (what you got with the installer):

Apache -> Nginx / does it matter?

### Steps to Reproduce:

1.  Login to Panel as admin - https://demo.vestacp.com/
2.  https://demo.vestacp.com:8083/edit/server/  - Server menu -> Configuring Server -> see your licenses

### Related Issues/Forum Threads:

NA

### Other Notes:

I suggest obfuscate these license?  To not display them or just display the first or last 3 characters?  ****f90 or ****cbc

I know it's an honor system and I have actually purchased my own license to support VestaCP, but I'm  reporting this in case it is not intended or being overlooked.

**Comment by anton-reutov** [comment]
This license only for demo server and this key will not working on another ips
