### ISSUE TITLE
Exim4 fails after Let's Encrypt certificate renewal as the permission are reset

### ISSUE THREAD

**Issue by giacomodeglinnocenti** [serghey-rodin/vesta#1572]
### Operating System (OS/VERSION):

Debian 9

### VestaCP Version:

Latest

### Installed Software (what you got with the installer):

php-fpm, apache, nginx, mysql

### Steps to Reproduce:

Configure Exim4 SSL certificates in `/etc/exim4/exim4.conf.template` to enable it to read the SSL certificate from the `/home/<user>/conf/web/` folder, and gives the .crt and .key files the right permissions (at least 644).

Wait for Let's Encrypt SSL certificate automatic renewal.

See Exim4 fails as after the renewal the certificates permission will be reset to the original 640.

### Related Issues/Forum Threads:

https://forum.vestacp.com/viewtopic.php?t=14557

https://forum.vestacp.com/viewtopic.php?t=15577

### Other Notes:

It would be nice to get the certificates with the right permission or at least, do someone know an easy way to use unix ACL to make the certificates being created with the right permissions?

Would a symlink solve this problem (I don't think so).

**Comment by dpeca** [comment]
This can not be considered as issue, since you are trying to do something that is not foreseen by Vesta.

What do you try to do, maybe I can help you?
To use Exim in the way that Exim uses different SSL for different domain?
Or just to use certified hostname SSL (for example letsencrypt) in Exim? (the same SSL for all domains)

**Comment by giacomodeglinnocenti** [comment]
Actually what I'm doing is just to configure Vesta System to support mail with SSL with multi domain support.

I have already successfully configured the system as I'm going to show but the problem is when vesta let's encrypt automatically re-issue the certificates, the certificate itself comes with unix permission with insufficent permission to allow exim4 process to read it, and so exim4 fails to provide the right SSL certificate for incoming emails and some mail providers (i.e. google) refuse to deliver the email.

My configuration follows:

### in /etc/exim4/exim4.conf.template

```
tls_privatekey = ${if exists{/home/<user>/conf/web/${tls_sni}.key}{/home/admin/conf/web/${tls_sni}.key}{/home/<user>/conf/web/ssl.<generic-gdomain.tld>.key}}
tls_certificate = ${if exists{/home/<user>/conf/web/${tls_sni}.crt}{/home/<user>/conf/web/${tls_sni}.crt}{/home/admin/conf/web/ssl.<generic-domain.tld>.crt}}
```

and to match the exim4 ${tls_sni} variable with the mail domain I've done the following:

```
ln -s /home/admin/conf/web/ssl.<domain1.tld>.crt /home/admin/conf/web/mail.<domain1.tld>.crt
ln -s /home/admin/conf/web/ssl.<domain1.tld>.key /home/admin/conf/web/mail.<domain1.tld>.key
ln -s /home/admin/conf/web/ssl.<domain2.tld>.crt /home/admin/conf/web/mail.<domain2.tld>.crt
ln -s /home/admin/conf/web/ssl.<domain2.tld>.key /home/admin/conf/web/mail.<domain2.tld>.key
```

where domain1 and domain2 are my domains.

And in final (and here's the key of this issue) 

```
chmod 644 /home/admin/conf/web/ssl.<domain1.tld>.crt
chmod 644 /home/admin/conf/web/ssl.<domain1.tld>.key
chmod 644 /home/admin/conf/web/ssl.<domain2.tld>.crt
chmod 644 /home/admin/conf/web/ssl.<domain2.tld>.key
```

to allow exim to read the .crt and .key files.

This configuration supports multi domain SSL for mail managed by exim4.

The point now is that when Let's Encrypt re-issue the certificate it re-generates it with 640 permission instead of 644, so exim4 process fails to read it and gives the following error:

`TLS error on connection from <mail.external-domain.tld> [<IP>] (cert/key setup: cert=/home/<user>/conf/web/mail.<domain.tld>.crt key=/home/<user>/conf/web/ssl.<domain.tld>.key): Error while reading file`

If i want to re-enable exim4 to provide correctly the certificate I have to log in ssh and do manually:

```
chmod 644 /home/admin/conf/web/ssl.<domain1.tld>.crt
chmod 644 /home/admin/conf/web/ssl.<domain1.tld>.key
```

Is there any other way to do this that would be not to manually re-set the right permission, as asked in my first post?

Thanks

**Comment by jmagbanuaph** [comment]
A cron job to chmod the certs perhaps?

**Comment by dpeca** [comment]
Add chmod that you need here - https://github.com/serghey-rodin/vesta/blob/master/bin/v-add-web-domain-ssl#L129
That code is also executed on SSL renewing.

**Comment by fsoyer** [comment]
Hi guys,
I just have this problem. Following dpeca's tip, I've added this :
> # Needed if exim/dovecot must access the certificates
> chmod 644 $HOMEDIR/$user/conf/web/ssl.$domain.*
at line 87 in /usr/local/vesta/bin/v-add-web-domain-ssl (after the last "cp"). I'll tell you on next renewal if it works !

**Comment by giacomodeglinnocenti** [comment]
Hi,
 I have followed another way, as I didn't know how the Vesta software update would handle scripts customization, I preferred to add a chronjob.

`sudo chmod 644 /home/admin/conf/web/ssl.<hostname>.key; sudo chmod 644 /home/admin/conf/web/ssl.<hostname>.crt; sudo chmod 644 /home/admin/conf/web/ssl.<hostname2>.crt; sudo chmod 644 /home/admin/conf/web/ssl.vps1.<hostname2>t.key; sudo chmod 644 /home/admin/conf/web/ssl.<hostname3>t.key; sudo chmod 644 /home/admin/conf/web/ssl.<hostname3>.crt;

 Of course I have to update / add commands to that job every time I add o edit any Mail instance, but it worked great till now and I didn't need to update any part of code.

Only tip: In this way you would have to give the User group which the instance belong to (in my case `admin`), permission to run chmod, by editing permission with `visudo `(i'm on debian): (edits in bold)

```
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
**Defaults:admin  !requiretty**

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root    ALL=(ALL:ALL) ALL

# Members of the admin group may gain root privileges
**%admin  ALL=(ALL) ALL**

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d

**admin ALL = NOPASSWD: /bin/chmod**
```

Any comment / critic would be appreciated.

Cheers
