### ISSUE TITLE
Заменить Roundcube на Rainloop

### ISSUE THREAD

**Issue by ghost** [serghey-rodin/vesta#159]
Прошу обратить внимание на почтовый веб-клиент RainLoop http://rainloop.net/ Он гораздо лучше старичка Roundcube, которому пора отдыхать. К сожалению, про RainLoop мало кто знает, но это не мешает ему быть легким, красивым и очень функциональным. Уделите ему 10 минут и попробуйте установить у себя — вам понравится! Собственно, предлагаю заменить веб-клиент для почты на RainLoop.

**Comment by skurudo** [comment]
AfterLogic / Rainloop support
https://bugs.vestacp.com/issues/373

Roundcube плагины 
https://bugs.vestacp.com/issues/374
