### ISSUE TITLE
SSL certificates errors on Ubuntu 16.04.

### ISSUE THREAD

**Issue by gabriel3l** [serghey-rodin/vesta#1622]
As found here: https://forum.vestacp.com/viewtopic.php?t=17031 and here: https://forum.vestacp.com/viewtopic.php?t=15925

My VestaCP domains (Let's Encrypt SSL enabled) are expiring and not getting renewed.
Moreover, when I try to reissue a new certificate by disabling the SSL Support, I get an error 3 and if I try to enable the Let's Encrypt SSL back again it says: "Field "ssl certificate, ssl key" can not be blank."
No error logs on domains. When trying to reach domains, it shows Invalid SSL certificate.
I used no external scripts for let's encrypt SSL support.

It's been like that for 3 days, any ideas? On production.

VestaCP 0.9.8 release 21

**Comment by franciscopaniskaseker** [comment]
Same problem here.

**Comment by franciscopaniskaseker** [comment]
Using /usr/local/vesta/bin/v-add-letsencrypt-domain I can enable again.
Using web interface not.

**Comment by Soto-Seia** [comment]
I am currently installed VestaCP 16.04.4 and there is no problem with SSL certifications, try fresh-install if you can. Fresh-installing the Ubuntu is the best way I recommand. If you are not allowed to fresh-install, try re-installing VestaCP as forced(requires backing up). I hope you solve!

**Comment by vikasprogrammer** [comment]
```
# v-add-letsencrypt-domain admin domain.com
Error: php-fpm pool doesn't exist
```

**Comment by anton-reutov** [comment]
Can't reproduce on Ubuntu 16
