### ISSUE TITLE
Do not install VestaCP on Debian 8 and 9

### ISSUE THREAD

**Issue by Acidter** [serghey-rodin/vesta#1624]
### Operating System (OS/VERSION):

Debian 8,9

### VestaCP Version:

0.9.8-21

### Installed Software (what you got with the installer):

nginx, apache, phpfpm, named, remi, vsftpd, proftpd, iptables, fail2ban, quota, exim, dovecot, spamassassin, clamav, softaculous, mysql, postgresql

### Steps to Reproduce:

Скрипт установки не верно определяет ОС, скачивается vst-install-ubuntu.sh, вместо vst-install-ubuntu.sh

Скрипт добавляет строку в /etc/apt/sources.list.d/nginx.list:

deb http://nginx.org/packages/mainline/ubuntu/ jessie nginx

Этот путь не соответвует дистрибутиву Debian 8, выполянется обращение к 

Failed to fetch http://nginx.org/packages/mainline/ubuntu/dists/jessie/nginx/binary-amd64/Packages

получаем ошибку 404

Лог установки по ссылке https://txtbin.timeweb.tk/?984a3aa2b50d7d50#b8/MdKzme+jO+y71vyvvsbnLD+BD4vphoJ3nQDVNh+s=

Для Debian 9 установка проходит, но также подставляется некорректный дистрибутив в /etc/apt/sources.list.d/nginx.list при установке и панель Vesta не работает.
Лог установки по ссылке https://txtbin.timeweb.tk/?34b14e7ec8245da4#2DLQfFIA3ky9hAbEs9/2//xJf65vVvgTND9liG6cLmE=

**Comment by serghey-rodin** [comment]
Спасибо, исправили
