### ISSUE TITLE
Error grep: Invalid range end on apt-get update

### ISSUE THREAD

**Issue by macklus** [serghey-rodin/vesta#1627]
### Operating System (OS/VERSION):

Ubuntu 16.04

### VestaCP Version:

0.9.8-22

### Installed Software (what you got with the installer):

php-fpm, nginx, mariadb

### Steps to Reproduce:

When i execute **apt-get update** and **apt-get upgrade** i got:
```
Setting up file (1:5.25-2ubuntu1.1) ...
Setting up vesta (0.9.8-22) ...
grep: Invalid range end
Processing triggers for libc-bin (2.23-0ubuntu10) ...

```

**Comment by anton-reutov** [comment]
Can't reproduce on our test servers
