### ISSUE TITLE
502 - Bad gateway on Vesta CP admin

### ISSUE THREAD

**Issue by petarkozic** [serghey-rodin/vesta#1635]
### Operating System (OS/VERSION):
Ubuntu 16.04

I tried, all from https://github.com/serghey-rodin/vesta/issues/1625
but problem persist.

Update server, reboot server, update vesta sys-all update vesta, chaneg php-fpm PM (dynamic, ondeman)

Nothing helps.

**Comment by anton-reutov** [comment]
Can you provide access to your server? info@vestacp.com

**Comment by petarkozic** [comment]
@anton-reutov 
Sorry, but I can't because that is client instance. Thank you on understand.

**Comment by anton-reutov** [comment]
On our test servers the problem in not reproduce after this commands
```
apt-get update
apt-get upgrade
rm -f /var/run/vesta-php.sock
service vesta restart
```
we can't help you, because we don't have servers where this problem still exists
