### ISSUE TITLE
Firewall blocks services after first reboot on a clean installation

### ISSUE THREAD

**Issue by pablobae** [serghey-rodin/vesta#1639]
### Operating System (OS/VERSION):

Centos 7 64

### VestaCP Version:
0.9.8 (x86_64) Release: 22

### Installed Software (what you got with the installer):

Centos: minimal installation
VestaCP:   

- web: ngin+apache
- ftp: no
- mail: exim
- dns: named
-firewall: iptables + fail2ban
-softwaculous: no
-additional repo: remi
-Quota: no
-DB: MySQL
                   
### Steps to Reproduce:

1)  Fresh install of centos 7
2)  VestaCP installation: 
`bash vst-install.sh --nginx yes --apache yes --phpfpm no --named yes --remi yes --vsftpd no --proftpd no --iptables yes --fail2ban yes --quota no --exim yes --dovecot no --spamassassin no --clamav no --softaculous no --mysql yes --postgresql no --hostname host --email email@host --password xxxxx`
3) Restart
4) SSH, web and others services are blocked by iptables 

### Related Issues/Forum Threads:

When server is restarted firewall block all type connections with this rule:
[Chain INPUT (policy ACCEPT 0 packets, 0 bytes)]
0 0 REJECT all -- * * 0.0.0.0/0 0.0.0.0/0 reject-with icmp-host-prohibited

**Comment by ainonovo** [comment]
Сергей здравствуйте. Здравствуйте дорогие гитхабовцы)
У меня схожая проблема. Цент ос 7 х64. Стандартная установка - абсолютно всё работает, единственное что сменил порт самой панели - всё работает. Но после перезагрузки не работает ни чего кроме 22 порта (слав те Хоспади).

В логах ничего нет - либо я не разобрался.
Спасает лишь v-restart-service iptables - но лишь до очередного ребута.

[root@vps ~]# v-restart-service iptables
Note: Forwarding request to 'systemctl disable iptables.service'.
Removed symlink /etc/systemd/system/basic.target.wants/iptables.service.
Note: Forwarding request to 'systemctl enable iptables.service'.
Created symlink from /etc/systemd/system/basic.target.wants/iptables.service to /usr/lib/systemd/system/iptables.service.

**Comment by dpeca** [comment]
Try:
`systemctl disable firewalld`
and then reboot server again.

**Comment by dpeca** [comment]
Vesta has its own firewall.
`firewalld` is centos firewall, and should not be installed at all, because it  is conflicting with Vesta firewall.

Some mini-centos-images obviously comes with firewalld enabled by default.
@serghey-rodin we should prevent this in installer script.

**Comment by pablobae** [comment]
It's not an issue with the firewall, it's about the installer. There is an issue open on VestaCP Bug Tracker. 

And by other hand, if you don't know that issue, and you are installing vesta in a vps or dedicated, after first reboot, you can't access server, so you can't exec:
`systemctl disable firewalld`

**Comment by ainonovo** [comment]
22 ssh port work always. not work http, ftp, imap etc.

**Comment by pablobae** [comment]
hehe yes, but I use to change that port number so.. First time, when I discovered this issue I could not login with ssh :(

**Comment by dpeca** [comment]
As I said, it should be disabled in installer.
Will see if I can do that.

**Comment by dpeca** [comment]
@serghey-rodin solved it.
https://github.com/serghey-rodin/vesta/commit/07a7c90cf6634c130b6df4005c6c339b02e6333d

**Comment by pablobae** [comment]
good job!
