### ISSUE TITLE
PHPMyAdmin Access denied Error On Debian 9

### ISSUE THREAD

**Issue by iamra** [serghey-rodin/vesta#1646]
### Operating System (OS/VERSION):
Debian 9

### VestaCP Version:
Version:0.9.8 (amd64) | Release:22

### Installed Software (what you got with the installer):
Standard Packages on Large instance

### Steps to Reproduce:
Install Vesta on clean Debian 9 image, try to log into root user in PHPMyAdmin with Vesta generated password, error occurs.

### Other Notes:
Here is the full error output:

#1698 - Access denied for user 'root'@'localhost'
 mysqli_real_connect(): (HY000/1045): Access denied for user 'phpmyadmin'@'localhost' (using password: YES)
 Connection for controluser as defined in your configuration failed.
 mysqli_real_connect(): (HY000/1698): Access denied for user 'root'@'localhost'

**Comment by dpeca** [comment]
try https://forum.vestacp.com/viewtopic.php?f=14&t=10307&start=60#p71828

**Comment by iamra** [comment]
Thank you dpeca, that resolved the login issue, not I am attempting to figure out why the root use can not log in to phpmyadmin. I will do some testing on my part. Hopefully this is fixed for future releases.

Thank you for your help and time.

**Comment by iamra** [comment]
I am not sure that this is Vesta, MariaDB or Debian 9 related,
But even after reconfiguring the phpmyadmin, the root user is not able to login neither through phpmyadmin nor through a remote connection.
I ran mysql_secure_installation to check if there a root password set and I keep getting:
`#1698` - Access denied for user 'root'@'localhost'
`mysqli_real_connect():` (HY000/1698): Access denied for user 'root'@'localhost'

Non root users can login, in Debian 8, root user could log in and was assigned the same password as admin after the Vesta CP Install script.

**Comment by ram108** [comment]
`I am attempting to figure out why the root use can not log in to phpmyadmin`
Root logins are pohibited in security reasons. Read this tread:
https://askubuntu.com/questions/763336/cannot-enter-phpmyadmin-as-root-mysql-5-7

**Comment by iamra** [comment]
@ram108 ,

I ran the security configuration script and enabled root login in the settings, I am having problems logging in as root even when the settings are set to enable it. This used to be possible in Debian 8 Vesta install, but the error thrown in Debian 9 may be the cause of it unless settings have been changed and the security configuration is disabled somewhere else.

**Comment by linuskom** [comment]
This issue is happening with "root" user in PhPMYAdmin with new VestaCP install on Ubuntu 16.04 LTS.
I have double checked the passwords : nano /usr/local/vesta/conf/mysql.conf
+
nano /root/.my.cnf

The error message is: #1698 - Access denied for user 'root'@'localhost'

It seems 'sufficient levels of quality checks' has not been implemented prior to version release.

**Comment by Skamasle** [comment]
This is the solution for this issue:

https://askubuntu.com/a/1059308

By defult

```
ariaDB [(none)]> select user, host, plugin from mysql.user;
+---------------+-----------+-------------+
| user          | host      | plugin      |
+---------------+-----------+-------------+
| root          | localhost | unix_socket |
| roundcube     | localhost |             |
| admin_default | %         |             |
| admin_default | localhost |             |
| phpmyadmin    | localhost |             |
+---------------+-----------+-------------+

```
This is setup in this way for security, so you may want create new root user for your use for maintain secure but you can change unix_socket for mysql_native_password as describe link before.

Works for debian with mariadb

**Comment by Skamasle** [comment]
I think we can consider this as not a bug, because vesta by default not leave root access to phpmyadmin, and this is disabled by security in mysql in new versions.

What do you think @dpeca  ?

The solution is there, and the best way to do it is create new root user ( for security is betther )

**Comment by bubblecatcher** [comment]
Hi, i had these issues after install and eventually found this cleared them:


run
mysql_secure_installation

ensure all files are using correct password
/root/.my.cnf
/usr/local/vesta/conf/mysql.conf

remove mysql root password (dpkg-reconfigure -plow phpmyadmin fails with root pw error)
mysql -uroot -p
SET PASSWORD FOR root@localhost=PASSWORD(''); 
quit

reconfigure phpmyadmin
dpkg-reconfigure -plow phpmyadmin

rerun
mysql_secure_installation

log into phpmyadmin with no errors

:)

**Comment by linuskom** [comment]
Greeting to all fellow VestsCP users.

This thing is disturbing and is a security concern. Have a look at the link: https://forum.vestacp.com/viewtopic.php?f=10&p=73886&sid=170b7d683dba0bdf593fa6a5cb3c64c6#p73886


The implication is; servername and password are send via GET request to some kind of script under vestacp.com. And its highly likely that VestaCP staff have access to all root credentials and log access it seems.

We need clarification!

This can easily become a vector for security attack !!!!

No one like giving their credit card passcode! 

I wonder if VestaCP developers can throw some light on this ????

**Comment by elpedriyo** [comment]
BUMP
