### ISSUE TITLE
Security: MySQL listens on ALL interfaces after vestacp install!

### ISSUE THREAD

**Issue by COLABORATI** [serghey-rodin/vesta#1657]
After installing vestacp on a fresh debian system I see that MySQL is listening **on all interfaces**.

Please do not do that. This is so annyoing. Learn to configure systems in a secure way. Horrible.

**Comment by madeITBelgium** [comment]
MySQL is by default listening on port 3306 and publicly available for the public. You can manage this in your firewall.
