### ISSUE TITLE
Add command / option and docs for changing default ssh port

### ISSUE THREAD

**Issue by COLABORATI** [serghey-rodin/vesta#1658]
Yes, this is something many admins do, because it still at least helps to keep the logs clean:
please support users of your vestap software to change the default ssh port. 

I can of course just change the port in /etc/ssh/sshd_config, but because there is no good documentation for vestacp it is not clear what side effects that might have, if this setting will be changed on upgrade if fails2ban is somehow automatically configured or if anything else in vestacp will just not work anymore because of this manual change in a user file.

What I have learned today is, that a login is not possible after just changing the port in the sshd_config file - there seems to be some firewall setup with vestacp. Please write **more documentation**, thanks!

**Comment by madeITBelgium** [comment]
For support you can better look and search at the forum: https://forum.vestacp.com/viewtopic.php?t=6235#p17835
