### ISSUE TITLE
Change insecure dangerous-by-design php->sudo architecture

### ISSUE THREAD

**Issue by COLABORATI** [serghey-rodin/vesta#1661]
OK, from what I understand this project is made directly from the _"How to Construct Insecure Web Software Cookbook"_. The web interface offers a nice shuttle service directly to a passwordless sudo. This is very, very bad design. This catastrophic architecture has to change completely. 

You need to put something between the web gui and the sudo execution, there are several ways to do it, the most simple way would be: 
* the web gui only writes a file with command statements.
* a cron job by the admin user checks for that file, validates if the commands exist and are allowed, and executes them.  

Seriously, some people with experience in building secure software should take a closer look and redesign this. Until that happens I strongly recommend to disable public access to the web gui - if you somehow want to do one last thing please make the vesta nginx listen to 127.0.0.1 by default and write some warnings on the website of this project.

**Comment by madeITBelgium** [comment]
The way you suggest is not possible, everytime a page is loading and needs data the user needs to wait until the cron is finished?
The sudo mechanism is definitely not the best method but I do not see many alternatives.
