### ISSUE TITLE
Question: What exactly is this for ?

### ISSUE THREAD

**Issue by poppabear8883** [serghey-rodin/vesta#1673]
https://github.com/serghey-rodin/vesta/blob/6a34f064c410815d974bc983393ea5232d57c8e8/install/vst-install-ubuntu.sh#L970-L974

As the title asks, what is this code for, apparently it works fine with out this added ?

**Comment by madeITBelgium** [comment]
https://mysqlserverteam.com/initialize-your-mysql-5-7-instances-with-ease/
