### ISSUE TITLE
Can't access control panel after installation

### ISSUE THREAD

**Issue by ulfklose** [serghey-rodin/vesta#1674]
### Operating System (OS/VERSION):

Ubuntu 18.04.1

### VestaCP Version:

0.9.8-22

### Installed Software (what you got with the installer):

--nginx yes --phpfpm yes --apache no --named yes --remi no --vsftpd no --proftpd no --iptables yes --fail2ban yes --quota no --exim no --dovecot no --spamassassin no --clamav no --softaculous no --mysql yes --postgresql no

### Steps to Reproduce:

bash vst-install.sh --nginx yes --phpfpm yes --apache no --named yes --remi no --vsftpd no --proftpd no --iptables yes --fail2ban yes --quota no --exim no --dovecot no --spamassassin no --clamav no --softaculous no --mysql yes --postgresql no

### Related Issues/Forum Threads:

No.

### Other Notes:

I did a clean install on a Hetzner Cloud server, so freshly installed Ubuntu 18.04 with all updates installed. I used the installation command above. 

There's a process running on 0.0.0.0 and port 8083 but I can't connect to it. Chrome tells me that there's a problem with HSTS. I never visited that site before and didn't change anything after installing.

**Comment by madeITBelgium** [comment]
The domain name you are using is probably configured with HSTS. Try to clear the HSTS cache: chrome://net-internals/#hsts

**Comment by ulfklose** [comment]
I don't know why this happened, because I'm sure that I never opened that URL in both browser before, but clearing their caches let me at least load the site. Thank you.
