### ISSUE TITLE
Backup exclusions not working (WEB+fix)

### ISSUE THREAD

**Issue by BoxOfSnoo** [serghey-rodin/vesta#1677]
I am on Debian 9 with the latest source (0.9.8 release 22).  I was wondering why my backups were so huge - despite the fact that I excluded certain web directories.

I believe the line is here:

https://github.com/serghey-rodin/vesta/blob/6825caa764c58117ff79c39f3f944338cbe75c0a/bin/v-backup-user#L236

I fixed it locally by moving the `*` **after** the ${fargs[0]}.  e.g.

`tar -cpf- ${fargs[@]} * |gzip -$BACKUP_GZIP - > $tmpdir/web/$domain/domain_data.tar.gz`

I tried the tar command manually to verify this was the issue, and that the change corrected it.  My backup went from over 6GB to 75MB.

None of the other tar commands seem to use this pattern so I think this one change will fix the whole backup.

I have tar v1.29

**Comment by madeITBelgium** [comment]
#1666
