### ISSUE TITLE
Ubuntu 18.04 - Email issue on first Vesta install

### ISSUE THREAD

**Issue by ioannidesalex** [serghey-rodin/vesta#1678]
### Operating System (OS/VERSION):

Ubuntu 18.04

### VestaCP Version:

0.9.8-22

### Installed Software (what you got with the installer):

Nginx, PHP-FPM, MySQL, Exim4, Dovecot, Roundcube

### Steps to Reproduce:

During Vesta installation, the following issues occur:

1) Dovecot issue:
Adding user Debian-exim to group mail
Adding user dovecot to group mail
Job for dovecot.socket failed.
See "systemctl status dovecot.socket" and "journalctl -xe" for details.

2) Roundcube error
DATABASE ERROR: CONNECTION FAILED!
Unable to connect to the database!
Please contact your server-administrator.

This is caused because of this error during installation:
ERROR 1007 (HY000) at line 1: Can't create database 'roundcube'; database exists
ERROR 1050 (42S01) at line 8: Table 'session' already exists

### Related Issues/Forum Threads:

https://forum.vestacp.com/viewtopic.php?f=41&t=16849&start=10

**Comment by ioannidesalex** [comment]
I really don't know what else to do to get the attention of the team and fix these serious issues @serghey-rodin @dpeca

**Comment by dpeca** [comment]
Sorry, I maintain only Debian stuff :/
I'm not very well familiar with Ubuntu :/

**Comment by luizjrdeveloper** [comment]
> I really don't know what else to do to get the attention of the team and fix these serious issues @serghey-rodin @dpeca

I was able to solve this problem a while ago.
Just open the DOVECOT configuration file according to your system.
https://vestacp.com/docs/#config-log-location-debian-ubuntu

**

> Clique Here to see code to fix Dovecot Connection #1669.

**

**Comment by dpeca** [comment]
fixed with https://github.com/serghey-rodin/vesta/pull/1669
