### ISSUE TITLE
Error: apt-get install failed

### ISSUE THREAD

**Issue by KarelWintersky** [serghey-rodin/vesta#1681]
### Operating System (OS/VERSION):

ubuntu 16.04 clean install (server)

### VestaCP Version:

latest? 

### Installed Software (what you got with the installer):

none, clean installation

### Steps to Reproduce:

```
curl -O http://vestacp.com/pub/vst-install.sh
bash vst-install.sh --nginx yes --phpfpm yes --apache no --named yes --remi yes --vsftpd no --proftpd no --iptables yes --fail2ban yes --quota no --exim yes --dovecot yes --spamassassin yes --clamav yes --softaculous yes --mysql yes --postgresql no
```

Result:
```
Installation backup directory: /root/vst_install_backups/1533850309




Installation will take about 15 minutes ...

Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
--2018-08-09 21:31:54--  http://nginx.org/keys/nginx_signing.key
Resolving nginx.org (nginx.org)... 95.211.80.227, 62.210.92.35, 2001:1af8:4060:a004:21::e3, ...
Connecting to nginx.org (nginx.org)|95.211.80.227|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1561 (1.5K) [text/plain]
Saving to: ‘/tmp/nginx_signing.key’

/tmp/nginx_signing.key                100%[======================================================================>]   1.52K  --.-KB/s    in 0s

2018-08-09 21:31:54 (97.4 MB/s) - ‘/tmp/nginx_signing.key’ saved [1561/1561]

OK
--2018-08-09 21:31:54--  http://c.vestacp.com/deb_signing.key
Resolving c.vestacp.com (c.vestacp.com)... 104.236.66.100
Connecting to c.vestacp.com (c.vestacp.com)|104.236.66.100|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1719 (1.7K) [text/plain]
Saving to: ‘deb_signing.key’

deb_signing.key                       100%[======================================================================>]   1.68K  --.-KB/s    in 0s

2018-08-09 21:31:55 (93.0 MB/s) - ‘deb_signing.key’ saved [1719/1719]

OK
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Get:4 http://nginx.org/packages/mainline/ubuntu bionic InRelease [2,112 B]
Get:5 http://nginx.org/packages/mainline/ubuntu bionic/nginx amd64 Packages [10.0 kB]
Get:6 http://apt.vestacp.com/bionic bionic InRelease [2,187 B]
Get:7 http://apt.vestacp.com/bionic bionic/vesta amd64 Packages [1,004 B]
Fetched 15.3 kB in 11s (1,441 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package mc is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package rssh is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package expect
E: Unable to locate package fail2ban
E: Unable to locate package idn
E: Package 'mc' has no installation candidate
E: Unable to locate package ntpdate
E: Unable to locate package php-fpm
E: Unable to locate package phpmyadmin
E: Unable to locate package roundcube-core
E: Unable to locate package roundcube-mysql
E: Unable to locate package roundcube-plugins
E: Package 'rssh' has no installation candidate
E: Unable to locate package webalizer
Error: apt-get install failed


```

**Comment by dpeca** [comment]
Are you running Ubuntu under Windows10?

**Comment by KarelWintersky** [comment]
Of course, **NO**!

**Comment by Skamasle** [comment]
In your first message you mark as you use ubuntu 16, but your repos say you try use ubuntu 18, your ubuntu isnt fully supported yet

**Comment by Skamasle** [comment]
Ok my bad, main site say is supported, I try check it

You use default repost, is a clean install ?

**Comment by KarelWintersky** [comment]
@Skamasle , sorry, ubuntu 18 of course. Yeah, clean install from `ubuntu-18.04.1-live-server-amd64.iso `

**Comment by anton-reutov** [comment]
Can't reproduce on our test servers. Please, try again, and let me know if problem still exists

**Comment by skullwritter** [comment]
@KarelWintersky try an apt-get update,maybe it will fix the issue
also try to add the multiverse repos, might help.
last thing, try to install the standard server package if you didn't (this is for 16.04 coudn't find the 18.04, might work):
`apt-get install manpages dnsutils bsdmainutils psmisc python3-gdbm ufw dosfstools ed telnet powermgmt-base ntfs-3g ubuntu-release-upgrader-core iputils-tracepath python3-update-manager groff-base python3-distupgrade bind9-host mtr-tiny bash-completion mlocate tcpdump geoip-database install-info irqbalance language-selector-common friendly-recovery command-not-found info hdparm man-db lshw update-manager-core apt-transport-https accountsservice command-not-found-data python3-commandnotfound time ltrace parted popularity-contest strace ftp ubuntu-standard lsof`

**Comment by Skamasle** [comment]
By default you have only main repos, ensure you have main restricted universe multiverse thats the problem

```
deb http://archive.ubuntu.com/ubuntu bionic main 
deb http://archive.ubuntu.com/ubuntu bionic-security main 
deb http://archive.ubuntu.com/ubuntu bionic-updates main
```
Your repo need look like this:

```
deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu bionic-security main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse
```

**Comment by jamiel-sharief** [comment]
Just ran into the same problem. I think you should mention to users re this on the install instructions.

**Comment by pramod7770** [comment]
i have same problem with my site https://printerdrivers.com
please follow when u install before running bash vst-install.sh
run the below command
```
 apt-get update
apt-get install gnupg
```
this fixed my problem

**Comment by Sagargit-tech** [comment]
> apt-get install gnupg

no not working dude

**Comment by Govind-Deshmukh** [comment]
leave every thing just 

go to etc/apt/source.list

delete every thing

paste following lines

deb http://archive.ubuntu.com/ubuntu bionic main 
deb http://archive.ubuntu.com/ubuntu bionic-security main 
deb http://archive.ubuntu.com/ubuntu bionic-updates main

save file

run instillation file again

that worked for me
