### ISSUE TITLE
Need help for update php 7.0 to php 7.2 for laravel 5.6 support

### ISSUE THREAD

**Issue by shahzad-sarwar** [serghey-rodin/vesta#1682]
Digital Ocean Ubuntu based droplet

Need desperate and urgent help for updating php on vestacp.

My installation procedure is follow.

curl -O https://assets.digitalocean.com/vesta/install-vesta-do.sh

chmod +x install-vesta-do.sh

bash install-vesta-do.sh --force --nginx yes --phpfpm yes --apache no --named yes --remi yes --vsftpd no --proftpd no --iptables yes --fail2ban yes --quota no --exim yes --dovecot yes --spamassassin yes --clamav yes --softaculous no --mysql yes --postgresql no

Any help would really be appreciated.

Thanks

**Comment by skullwritter** [comment]
# Commands as Root (will install php7.2 with modules):
`apt-get update`
`apt-get install python-software-properties`
`LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php`
`apt-get update`
`apt-get install php7.2 php7.2-cgi php7.2-cli php7.2-common php7.2-curl php7.2-gd php7.2-imap php7.2-intl php7.2-json php7.2-ldap php7.2-mbstring php7.2-mysql php7.2-opcache php7.2-pspell php7.2-readline php7.2-soap php7.2-xml`

# Set Default php to 7.2 using upgrade alternatives:
`update-alternatives --config php`

# Restart nginx and php-fpm:
`service php-fpm restart`
`service nginx restart`

## hope this helps you bro.

**Comment by shahzad-sarwar** [comment]
Thank you so much for your response.

I'm still seeing this in php-fpm settings.

/etc/php/7.0/fpm/php.ini

**Comment by skullwritter** [comment]
1. did you set the default php version with update-alternatives?
1. Also chech this link from the forum:
https://forum.vestacp.com/viewtopic.php?t=15860
