### ISSUE TITLE
How to make UFT8mb4 available for MySQL ?

### ISSUE THREAD

**Issue by jodumont** [serghey-rodin/vesta#1698]
### Operating System (OS/VERSION):
Ubuntu 18.04LTS
but probably all of them

### VestaCP Version:
VestaCP  0.9.8 (amd64) release 22
but probably any release

### Installed Software (what you got with the installer):
php-fpm, nginx
but probably independent of these

### Steps to Reproduce:
I add my remote percona server sucessfully with `v-add-database-host mysql new-server.com root password` and able to interact with it via VestaCP

Now the percona-server is configured as nextcloud recommend; and more and more applications too;
with **utf8mb4** by default

to be sure of these additional config in `/etc/mysql/percona-server.conf.d/mysqld.cnf`
**REMARK: this is not the issue it's just to put in context**
> \# http://bugs.mysql.com/bug.php?id=68514
> performance_schema=OFF
> max_connections=50
> \# on ec2, without this we get a sporadic connection drop when doing the initial migration
> max_allowed_packet=32M
> 
> \# https://mathiasbynens.be/notes/mysql-utf8mb4
> character-set-server = utf8mb4
> collation-server = utf8mb4_unicode_ci
> 
> [mysqldump]
> quick
> quote-names
> max_allowed_packet  = 16M
> default-character-set = utf8mb4
> 
> [mysql]
> default-character-set = utf8mb4
> 
> [client]
> default-character-set = utf8mb4

### Related Issues/Forum Threads:
https://forum.vestacp.com/viewtopic.php?t=17208

### ISSUE:
Now on the vesta host in /usr/local/vesta/conf/mysql.conf
I added utf8mb4 in the `CHARSETS='UTF8MB4,UTF8,...'`
then restart, reboot, ...
I still unable to select utf8mb4

I also add `default-character-set='utf8mb4'` inside `/usr/local/vesta/conf/.mysql.IP.Se.rv.er` without success

### EXPECTED:
Being able to, at least, select utf8mb4
hoping utf8mb4 being by default

### Anything else?
Their is a way to add on the vesta side ?
> [client]
> default-character-set = utf8mb4

**Comment by skullwritter** [comment]
....
https://dev.mysql.com/doc/refman/8.0/en/adding-character-set.html

**Comment by jodumont** [comment]
@skullwritter ; maybe I miss understood but
as I tried to say everything is fine on my mysql service, it's only vestacp not showing the option
such as an example if I use adminer and/or create a database via cli
the database will use the default-character-set I define which is utf8mb4
I would like the same behavior when I create a database via vestacp .

**Comment by jodumont** [comment]
I saw it was merged and fixed
thanks to @skullwritter for your care and contribution

**Comment by skullwritter** [comment]
@jodumont u're welcome
