### ISSUE TITLE
Reverse MX A records (PTR)

### ISSUE THREAD

**Issue by sarzali07** [serghey-rodin/vesta#1719]
### Operating System (OS/VERSION):

CentOS Linux release 7.5.1804 (Core)

### VestaCP Version:

 0.9.8  22   x86_64  yes   2018-10-09

### Installed Software (what you got with the installer):

Fresh installation of vestacp package

### Other Notes:

After installing vestacp on virtual machine it do not send email like creating account on vestacp it do not send email to users for its credentials.
After checking 
ERROR: No reverse DNS (PTR) entries. The problem MX records are: 
134.151.161.108.in-addr.arpa -> no reverse (PTR) detected
You should contact your ISP and ask him to add a PTR record for your ips

can anyone help me out this.

Reply

**Comment by gytisrepecka** [comment]
As the error says - ISP which is assigning your server an IP address should make PTR record in their side. You can't do much regarding this from your side.
