### ISSUE TITLE
Letsencrypt tries to renew certs on suspended websites

### ISSUE THREAD

**Issue by webworker01** [serghey-rodin/vesta#1731]
Ubuntu - Vesta 0.9.8

**Comment by skullwritter** [comment]
bro give more details, logs, system version (14.04 - 18.04) etc....

**Comment by webworker01** [comment]
I've seen this on 16.04 and 18.04. Suspend a website that had letsencrypt ssl cert added, when it comes time to attempt cert renewal get a message like this:

`webworker.sh =Error: web webworker.sh is suspended`

**Comment by webworker01** [comment]
This is the script throwing the error https://github.com/serghey-rodin/vesta/blob/master/bin/v-update-letsencrypt-ssl  Probably just a check to see if suspended before attempting to renew

**Comment by skullwritter** [comment]
i'm doing that bro, just an minute (figurative speaking)

**Comment by webworker01** [comment]
Thanks, not a rush my friend, just has been a minor annoyance getting emailed every few days. I don't think it affected anything else negatively. 👍

**Comment by skullwritter** [comment]
the fix has ben made.
