### ISSUE TITLE
Force renew certificate

### ISSUE THREAD

**Issue by pdapnz** [serghey-rodin/vesta#1732]
Is it possible add `force` option into `v-update-letsencrypt-ssl` to renew all certificates independent of they expire date?

The problem is -  I add new alias to domain I must renew certificate. And today it is only possible by disable/enable SSL at domain page of panel. During this procedure site go offline while new certifacate will be issued. In my case alias count is over 80 and renew process takes 5-10 minutes. During this time site offline.

https://github.com/serghey-rodin/vesta/blob/master/bin/v-update-letsencrypt-ssl#L44

**Comment by pdapnz** [comment]
Did the following test. I comment expiration check. The certificate has been re-issued, but there are no new aliases in it, they have not been added. So the `fource` option will not solve the problem.

Is any ideas how solve such problem?

**Comment by madeITBelgium** [comment]
The v-update-letsencrypt-ssl command uses the aliases from the certificate.

Run this command: v-add-letsencrypt-domain

**Comment by pdapnz** [comment]
So I simply can run the following command:

`v-add-letsencrypt-domain username site.com newsubdomain.site.com`

or I must pass all aliases?

**Comment by madeITBelgium** [comment]
I think all aliases. Comma separated.
ex: 
```
v-add-letsencrypt-domain username site.com newsubdomain.site.com,www.site.com,www1.site.com,sub1.site.com
```

Example code: https://github.com/serghey-rodin/vesta/blob/master/web/edit/web/index.php#L369-L370

**Comment by pdapnz** [comment]
Thank you! 
`v-add-letsencrypt-domain` solved my problem!

**Comment by Kuplevatsky** [comment]
solved my problem too!

**Comment by Kuplevatsky** [comment]
Thank you!
