### ISSUE TITLE
Upgrade Roundcube to version 1.3.8

### ISSUE THREAD

**Issue by Mehran** [serghey-rodin/vesta#1746]
### Operating System (OS/VERSION):

Ubuntu  16.04

### VestaCP Version:

Last Version

### Installed Software (what you got with the installer):

Roundcube

after installation complete Rouncube, version it uses is 1.2 Beta, the Last version on Roundcube site is 1.3.8 How can I upgrade to the last Version? 

I try to copy files from a site but seems config file is missing.

**Comment by plutocrat** [comment]
I wouldn't say this is a bug of Vesta's as vesta just uses the default roundcube version supplied in the distribution's repositories. For Ubuntu 16, this is roundcube 1.2beta. I don't know why they use a beta version. 
There are some suggestions here in case you haven't found them:
https://forum.vestacp.com/viewtopic.php?t=16660
