### ISSUE TITLE
Regression: Can't add www as alias bug is back. 

### ISSUE THREAD

**Issue by plutocrat** [serghey-rodin/vesta#1748]
This bug seems to have been re-introduced on current version of Vesta. 
https://github.com/serghey-rodin/vesta/pull/1490/files

It prevents the www alias from being added to the domain after creation.

**Comment by adilsonb** [comment]
It´s true... 

I follow @plutocrat  hint to solve this problem.

The fix is to edit func/main.sh, line 936 and change:

aliases=$(echo "$aliases" |grep -v www.$domain |sed -e "/^$/d")
to
aliases=$(echo "$aliases" |sed -e "/^$/d")
