### ISSUE TITLE
PHPMYADMIN Not work

### ISSUE THREAD

**Issue by pablosavigne** [serghey-rodin/vesta#1787]
### Operating System (OS/VERSION):

Ubuntu 18.04 LTS

### VestaCP Version:

LATEST VERSION (Jun 27): 0.9.8-23

### Installed Software (what you got with the installer):

php-fpm, nginx, mysql, bind9, exim, dovecot, vsftp

### Steps to Reproduce:

After completed first vesta instalation, webmail and phpmyadmin dont work. IMG ATTACHED

![screenshot_182](https://user-images.githubusercontent.com/34542318/49699334-b21b5700-fbc7-11e8-9bb5-07a28d771613.png)
![screenshot_181](https://user-images.githubusercontent.com/34542318/49699335-b21b5700-fbc7-11e8-8c09-4fb591307290.png)

**Comment by coolwebs** [comment]
I don't think you can login with root - and it would be a terrible idea to have that on a remote server.
Instead, try and use the credentials that you setup when you created your database within Vesta cp. You can see existing credentials if you edit your database.

**Comment by cantalupo555** [comment]
@anton-reutov This is not a bug, only mysql root is disabled for remote access, if by chance the user wanted to access it will have to do this through the linux terminal.
