### ISSUE TITLE
ssh authorization without password by key

### ISSUE THREAD

**Issue by babenkoma** [serghey-rodin/vesta#1801]
Tell me please, how i can authorization without password by key?

My steps:
1. I created folder .ssh in my home dir
2. I created file .ssh/authorized_keys and copy to them my ssh public key

But, I cannot auth without password!

**Comment by Pleskan** [comment]
Hi it is offtopic question because it's not related to Vesta issues in any form.
So please, look at https://www.digitalocean.com/community/tutorials/ssh-ubuntu-18-04-ru for reference.
You also may have some distribution-specific features that prevents pubkey auth to work as expected (like SELinux in CentOS 7).

**Comment by babenkoma** [comment]
Yes, I understand. Thank you for link. I read such instructions on many resources, but all of them did not help me. I think, that Vesta has some settings, that will not allow to auth without password

**Comment by babenkoma** [comment]
I wanted to register on Vesta forum, but I cannot do it, because after send form in console appear error of validation and registeration does not end

**Comment by anton-reutov** [comment]
Здравствуйте Марина. Напишите подробнее о проблеме регистрации на форуме. Мы поможем Вам.

**Comment by babenkoma** [comment]
Здравствуйте. При регистрации заполняю все поля, отвечаю на вопрос. В результате сообщение
`You have incorrectly sorted the items to the correct list of the confirmation question.`
Также есть ошибка в консоле [http://joxi.ru/nAyxlBWFgj7V92](http://joxi.ru/nAyxlBWFgj7V92)

**Comment by anton-reutov** [comment]
Напишите на info@vestacp.com желаемый логин и email на форуме.

**Comment by babenkoma** [comment]
Написала

**Comment by anton-reutov** [comment]
Должно прийти письмо на вашу почту с ссылкой для подтверждения регистрации.

**Comment by babenkoma** [comment]
Спасибо за помощь с регистрацией! Может на форуме мне помогут с моей проблемой
