### ISSUE TITLE
logrotate mysql bug

### ISSUE THREAD

**Issue by solvegenadmin** [serghey-rodin/vesta#1808]
### Operating System (OS/VERSION):

Debian GNU/Linux 9.5 (stretch)

### VestaCP Version:

0.9.8-23

### Installed Software (what you got with the installer):

all excluded softaculus and named.

### Steps to Reproduce:
1.) Enable mysql-slow.log:
slow_query_log = 1
long_query_time = 5
slow_query_log_file = /var/log/mysql/mysql-slow.log
2.) Check log after 24h
Current result: log is rotated by logrotate and no longer written.
Expectable result: log is rotated by logrotate and start to write again without restart of MySQL server.
### Related Issues/Forum Threads:
Logrotate config: /etc/logrotate.d/mysql-server 
### Other Notes:
MB OS related issue.

**Comment by Skamasle** [comment]
Hi

This happens in all mysql logs or only in slow log ?

I asume you use default mariadb version in debian 9, mariadb 10.1.

Can you paste here the mysql-server file located logrotate.d ?

**Comment by solvegenadmin** [comment]
HI! 
Maria version: Server version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1
This happens for all MySQL logs.
Here is contains of /etc/logrotate.d/mysql-server:
`/var/log/mysql/mysql.log /var/log/mysql/error.log  /var/log/mysql/mysql-slow.log {
        daily
        rotate 7
        missingok
        create 640 mysql adm
        compress
        sharedscripts
        postrotate
          test -x /usr/bin/mysqladmin || exit 0
          if [ -f `my_print_defaults --mysqld | grep -m 1 -oP "pid-file=\K.+$"` ]; then
            # If this fails, check debian.conf!
            mysqladmin --defaults-file=/etc/mysql/debian.cnf --local flush-error-log \
              flush-engine-log flush-general-log flush-slow-log
          fi
        endscript
}
`

**Comment by anton-reutov** [comment]
Will be checked, need a few days for that.

**Comment by Skamasle** [comment]
You can connect to mysql with root ?

If you change password this can happen also

Just for confirm you can root this manually without errors ?

```
mysqladmin --defaults-file=/etc/mysql/debian.cnf --local flush-error-log \
              flush-engine-log flush-general-log flush-slow-log
```

**Comment by anton-reutov** [comment]
We can't reproduce this problem on our test servers
