### ISSUE TITLE
[feature request] Free space for backup

### ISSUE THREAD

**Issue by pdapnz** [serghey-rodin/vesta#1823]
I'm using Vesta backup functionality for making backup to remote FTP. The problem with this feature is that it is required free disk space necessary for backup. It is 2 * size_of_backup.

This is because:
1) Vesta make local archive before pushing it to remote FTP.
2) Before making full user archive it make archive for each domain, and then combine them to one archive.

So is any plans to optimize this process? Ideal flow is do not make any local files during remote backup. This is real problem then you backup size is over dozens gigabytes. For example my size backup is 30Gb, so free space necessary 2*30 = 60 Gb.  And I must have 60Gb of free space only for backup purposes. And it is sad.

**Comment by anton-reutov** [comment]
We will think what we can do. We have plans to optimize backup system

**Comment by Skamasle** [comment]
I do some incrementalbackups jobs for vesta

But if you want a tar.gz file with all files in a pack is impossible not spend disk space during backup, transfer and then compress is very slow, al gziped backups in all systems has this problem.

You can rsync.

I work in this some time a go https://github.com/Skamasle/Incremental-Vesta-Backup/blob/master/sk-rsync-vesta-backup.sh need improvements and restore functions but thats the idea.
