### ISSUE TITLE
VestaCP Logout in few seconds

### ISSUE THREAD

**Issue by vihatsoft** [serghey-rodin/vesta#1849]
### Operating System (OS/VERSION):

CentOS 7.6.1810

### VestaCP Version:

Version:0.9.8 (x86_64) Release:23

### Installed Software (what you got with the installer):

php-fpm, nginx,mariadb

### Related Issues/Forum Threads:

VestCP always logout in few second. 
- login success and logout within few second when click on any option after successfully login. 
- some time type username and password and hit enter and back to login page and ask again for login without any error, that means login success but auto logout.
- this is not problem with only one Vestacp panel or server. i have many different server with vestacp and all have same issue since more than 6 to 10 month.
- i know this issue already mentioned on github but i don't know why not solve this major bug by vestaCP..
 https://github.com/serghey-rodin/vesta/issues/1380

### Other Notes:

Please solve this major bug, thank you,

**Comment by vihatsoft** [comment]
solved,

**Comment by andyg2** [comment]
> solved,

How?

**Comment by anton-reutov** [comment]
Try to clear cache and cookies of your browser

**Comment by babulgogoi** [comment]
this problem still exists in my installation

is there a fix?

**Comment by taufardh** [comment]
> solved,

if u solve this... better to post the solution.. it can help other.. thanks

**Comment by anton-reutov** [comment]
maybe the problem with sessions

**Comment by vihatsoft** [comment]
reinstalled vesta and fix.
