### ISSUE TITLE
SMTP Realy Gateway on Exim4

### ISSUE THREAD

**Issue by luizjr** [serghey-rodin/vesta#1856]
### Operating System (OS/VERSION):

Ubuntu 18.04

### VestaCP Version:

0.9.8-23

### Installed Software (what you got with the installer):

Exim4

### Steps to Reproduce:

Need add relay Exim4 to sendo emails from other server authorized.
https://ajuda.locaweb.com.br/wiki/gateway-para-envio-de-e-mails/

### Related Issues/Forum Threads:

Found anything that might be related to this? It might help us find the cause.

### Other Notes:

I tried to do it quickly, but other people have tried?
What do I have to do to work??

**Comment by ScIT-Raphael** [comment]
I'm glad you found it!
