### ISSUE TITLE
[Feature Request] Services to show all system services

### ISSUE THREAD

**Issue by dustindauncey** [serghey-rodin/vesta#186]
I'd love the ability for Vesta to show not only the services used by Vesta but all services in the server. 

Perhaps by default there could be a checkbox to hide all non-Vesta-used services, but then if checking the box it shows all services instead of the non-Vesta-used ones. 

Hope that makes sense. Would love to see this. If a simple change, I don't mind tackling the code myself but most likely is over my head.

**Comment by anton-reutov** [comment]
Already completed
