### ISSUE TITLE
404 with 0.9.8-24

### ISSUE THREAD

**Issue by Eliottiosdevs** [serghey-rodin/vesta#1861]
Hey there,

After running `sudo apt update` or `sudo apt upgrade` I get this error: 

`E: Failed to fetch http://apt.vestacp.com/bionic/pool/vesta/v/vesta/vesta_0.9.8-24_amd64.deb  404  Not Found [IP: 104.236.66.100 80]
E: Failed to fetch http://apt.vestacp.com/bionic/pool/vesta/v/vesta-nginx/vesta-nginx_0.9.8-24_amd64.deb  404  Not Found [IP: 104.236.66.100 80]
`

### Operating System (OS/VERSION):

Ubuntu 18.04 LTS

### VestaCP Version:

0.9.8-24

### Installed Software (what you got with the installer):

php-fpm, apache, nginx, mysql

### Steps to Reproduce:

`sudo apt update` or `sudo apt upgrade`

**Comment by anton-reutov** [comment]
Hi,
We are already working on it. Please waiting.

**Comment by anton-reutov** [comment]
Try to install again

**Comment by Zagur** [comment]
I don't know if it has to do, but vesta-softaculous is not in the repository.

Reading state information... Done
E: Unable to locate package vesta-softaculous
Error: apt-get install failed

# apt-cache search vesta
vesta - Vesta
vesta-ioncube - ionCube Loader for Vesta
vesta-nginx - Vesta Nginx
vesta-php - Vesta php-fpm

**Comment by anton-reutov** [comment]
Now we are rebuilding the packages.
