### ISSUE TITLE
SSL for IDN domains seems to be broken on release 24

### ISSUE THREAD

**Issue by moucho** [serghey-rodin/vesta#1866]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

0.9.8-24

### Installed Software (what you got with the installer):

apache, nginx

### Steps to Reproduce:

Try to add Let's Encrypt certificate to an IDN domain, the response received from their validation server:

```
Expires: Sun, 21 Apr 2019 14:07:15 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache

HTTP/1.1 400 Bad Request
Server: nginx
Content-Type: application/problem+json
Content-Length: 142
Boulder-Requester: 55619610
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: I5z-sDhIphDg_Z7QKUnQdifGGoWQ_UjnFUlxEIFrsrE
Expires: Sun, 21 Apr 2019 14:07:15 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sun, 21 Apr 2019 14:07:15 GMT
Connection: close

{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Error creating new order :: Invalid character in DNS name",
  "status": 400
}

```

**Comment by anton-reutov** [comment]
Can you provide access to the server via Forum PM ? We will check it tomorrow

**Comment by moucho** [comment]
I've sent a PM with the required information.
I also have made a quick PR #1867 that fixes the problem for now
