### ISSUE TITLE
Default configuration appears incorrect in /etc/httpd/conf.d/[IPaddress].conf

### ISSUE THREAD

**Issue by dustindauncey** [serghey-rodin/vesta#189]
Hi there,

I was receiving messages on boot time about "NameVirtualhost:8443 has no Virtual Hosts" which seemed odd. I found this resource which shows common mistakes in Apache configurations: https://wiki.apache.org/httpd/CommonMisconfigurations#Using_the_same_Listen_and.2For_NameVirtualHost_multiple_times.

In my file, which is default as I did not touch it before, is as follows: 

NameVirtualHost [IPaddress]:8080
Listen [IPaddress]:8080
NameVirtualHost [IPaddress]:8443
Listen [IPaddress]:8443

Where [IPaddress] is equal to my servers IP address. I then changed it to below and it no more errors were present about improper "NameVirtualHost:8443 has no Virtual Hosts".

NameVirtualHost [IPaddress]:8080
Listen [IPaddress]:8080
# NameVirtualHost [IPaddress]:8443
# Listen [IPaddress]:8443

I edited the /etc/httpd/conf.d/[IPaddress].conf file and commented out the line about 8443 and restarted and all is good now, at least from what I can tell. Is this a poor default configuration or is this intentional? If it is just a poor configuration, then perhaps it can be improved in the source. I'd love to do that myself if I can receive confirmation on whether this is proper or not.

**Comment by SysVoid** [comment]
Closing old issue.
