### ISSUE TITLE
apache2 fails to restart after reboot server or restart vestacp

### ISSUE THREAD

**Issue by progcode** [serghey-rodin/vesta#1893]
### Operating System (OS/VERSION):

Ubuntu 16.04.6 LTS

### VestaCP Version:

0.9.8 Release 24

### Installed Software (what you got with the installer):

Default vesta install

### Steps to Reproduce:

Reboot server or just restart vestacp. After that vesta-nginx started, apache2 not, because the port 80 is already allocated by nginx (wtf?)

Running the command systemctl status apache2.service returns:

https://cl.ly/0e0z3w2f2z1Y

### Related Issues/Forum Threads:

I dont find anything.

### Other Notes:

Kill all nginx process solve this issue.

**Comment by noogen** [comment]
Maybe something is wrong with your config?  Apache should be binding to 8080 and 8443 in a nginx->apache2 setup.  There should be a file in your `/etc/apache2/conf.d/` folder `your-ip-addy.conf` with:
```
Listen 127.0.0.1:8080
Listen 127.0.0.1:8443
```

This way, apache2 is hidden from external and can only access through nginx.

**Comment by Skamasle** [comment]
Oh yes, if you install apache only without nginx to prevent this uninstall nginx or turn it off

systemctl disable nginx

**Comment by progcode** [comment]
> But your post say you use vesta default install, you are sure about that ?

YES. I installed from here: http://vestacp.com/install/ with configurator, apache options

**Comment by Skamasle** [comment]
So if you not use nginx turn it off and reboo ( disable from startup ) this will solve your issue
