### ISSUE TITLE
Этот сайт не может обеспечить безопасное соединение

### ISSUE THREAD

**Issue by psp-anon** [serghey-rodin/vesta#1894]
### Operating System (OS/VERSION):

ubuntu 16.04

### VestaCP Version:

24

### Installed Software (what you got with the installer):

apache, nginx, mysql

на новый домен хотел поставить сертификат выдало 400 ошибку. после выполнение инструкции https://forum.vestacp.com/viewtopic.php?p=77189#p77189 слетели сертификаты со всех доменов. ну как слетели все на мепсте и обновляются сертификаты и ставяться на старых без проблем. но САЙТЫ НЕ ОТКРЫВАЮТСЯ !!! 
ОШИБКУ ВЫДАЕТ НА ХРОМЕ 

> Этот сайт не может обеспечить безопасное соединение Сайт ***.ru отправил недействительный ответ.
> ERR_SSL_PROTOCOL_ERROR

и новый домен удалял. и сетификаты обновлял. ничего не помогает!!!
отключение принудительного https тоже не помогает. уже хочу принудительно http сделать. одна беда

**Comment by Beaudinn** [comment]
I think it is related to https://forum.vestacp.com/viewtopic.php?f=11&t=18597&sid=186702e70514b870e75ab0dbabf1683e&start=10#

**Comment by psp-anon** [comment]
I tried all of that post (besides reinstall). Doesn't help

**Comment by psp-anon** [comment]
reinstall и последние 2 фикса не помогают!

**Comment by psp-anon** [comment]
РЕШИЛ. ПРОБЛЕМА БЫЛА В СТАРЫХ КАСТОМНЫХ ШАБЛОНАХ.
/usr/local/vesta/data/templates/web/nginx/CUSTOM.stpl
/usr/local/vesta/data/templates/web/nginx/CUSTOM.tpl

от того и не восставливался с бекапа.

НАДО ПОМЕНЯТЬ :
listen 11.22.33.44:443;
ssl on;
НА :
listen 11.22.33.44:443 ssl;
listen 443 ssl;

СУКА 3 ДНЯ ПОД ЖОПУ

**Comment by psp-anon** [comment]
РЕШИЛ. ПРОБЛЕМА БЫЛА В СТАРЫХ КАСТОМНЫХ ШАБЛОНАХ.
/usr/local/vesta/data/templates/web/nginx/CUSTOM.stpl
/usr/local/vesta/data/templates/web/nginx/CUSTOM.tpl

от того и не восставливался с бекапа.

НАДО ПОМЕНЯТЬ :
listen 11.22.33.44:443;
ssl on;
НА :
listen 11.22.33.44:443 ssl;
listen 443 ssl;

СУКА 3 ДНЯ ПОД ЖОПУ
