### ISSUE TITLE
FileManager show *.pe dir as images

### ISSUE THREAD

**Issue by neyder** [serghey-rodin/vesta#1897]
### Operating System (OS/VERSION):

Ubuntu 18.04

### VestaCP Version:

 0.9.8 (amd64) 24

### Installed Software (what you got with the installer):

php-fpm, apache, nginx, mysql

### Steps to Reproduce:

activate file manager.
try to access through file manager to ".pe" directories

I tested so and again .pe is national domain, and vesta filemanager acts like every *.pe directories are images, so it loads an spotlight and my clients can't access that dirs with click, i can access writing dirname in URL like:

`{vestacp domain}:8083/list/directory/?dir_a=/home/user/web/some.domain.pe/&dir_b=/home/user`

### Related Issues/Forum Threads:

https://bugs.vestacp.com/issues/602

### Other Notes:
.pe is a TLD for Perú so many clients use it and can't use without a workaround like typing directory in browser's address bar.

**Comment by Skamasle** [comment]
Yes, remember this bug, I thinks was fixed.

Is a javascript problem, I cant checkit :/

**Comment by anton-reutov** [comment]
Already fixed in the new version of FM. New release will be soon.
