### ISSUE TITLE
Recover database

### ISSUE THREAD

**Issue by yamenarahman** [serghey-rodin/vesta#1915]
I've installed vesta on a preconfigured server and it wiped existing databases, so how can I recover those databases?

**Comment by ScIT-Raphael** [comment]
Usualy backup, you should have been informed, that vesta needs a clean installation: https://github.com/serghey-rodin/vesta/blob/9de1d46bb6657281bf7cfd88ef28b0e744e77619/install/vst-install-ubuntu.sh#L260-L267

You should find the backup in /root/vst_install_backups: https://github.com/serghey-rodin/vesta/blob/9de1d46bb6657281bf7cfd88ef28b0e744e77619/install/vst-install-ubuntu.sh#L526-L536

**Comment by yamenarahman** [comment]
@ScIT-Raphael First thanks for your reply, I know I've done a stupid thing, is there any way I can recover these databases? I can't find the directory you're referring to.

**Comment by ScIT-Raphael** [comment]
If it is not there, you will have to take your backup. If you dont have a backup, you could try to aquire a sysadmin to check if there is something left but probaly the db's are lost.

**Comment by Skamasle** [comment]
Yes in /root/* you may find mysql dir, not is a mysqldump backup but a sysadmin can recover it
