### ISSUE TITLE
[SECURITY] Injection of code for let's encrypt challenge

### ISSUE THREAD

**Issue by shakaran** [serghey-rodin/vesta#1936]
Hi, I am doing a PCI compliance test for a website, and the auditors are saying that I am getting some XSS and SQL Injections in this part of code:

https://github.com/serghey-rodin/vesta/blob/84ef0a118fd73351126fb0e0da3392fe282eb789/bin/v-add-letsencrypt-domain#L164

For example:

**Vulnerable url:** 
`https://midomain.com/.well-known/acme-challenge/AccountSections.php/%22%3E%3Cscript%3Ealert(/openvas-xss-test/);%3C/script%3E
`

**Vulnerable url:** 

`https://midomain.com/.well-known/acme-challenge/library/PHPExcel/PHPExcel/Shared/JAMA/docs/download.php/%27%3E%3Cscript%3Ealert(/openvas-xss-test/);%3C/script%3E`

This is because (.*) allows inject whatever path file or route and reply with a 200, so PCI scanners are doing false positives for that. But we are allowing inject strings that it shouldn't inject

**Comment by noogen** [comment]
The only thing that locate or handling `^/\.well-known/acme-challenge/(.*)$` is a nginx 200 `text/plain` response with a Lets Encrypt string so there's no way that it would perform that script.

I hate those stupid false positive scans.  I hate more are those idiots who claim to be security expert and do not know how to verify those false positive.  It is responding with `text/plain` so it wouldn't be executing on the client-side browser.

**Comment by truongan** [comment]
> But we are allowing inject strings that it shouldn't inject

Well, we are allowing injecting of string but we don't execut it, we don't return anything for it so this cant not be count as a security issue. It's no issue at all.
