### ISSUE TITLE
"Deprecation Notice" message on login page of phpMyAdmin on

### ISSUE THREAD

**Issue by muratkoca** [serghey-rodin/vesta#1954]
### Operating System (OS/VERSION):

Type here, e.g. CentOS 7

### VestaCP Version:

 0.9.8-24

### Installed Software (what you got with the installer):

 apache, nginx, mysql

### Other Notes:

I reinstalled my VPS. I use Centos 7 as the operating system. I installed VestaCP with the following codes and encountered a problem.

> Connect to your server as root via SSH
`ssh root@your.server`

> Download installation script
`curl -O http://vestacp.com/pub/vst-install.sh`

> Run it
`bash vst-install.sh --nginx yes --apache yes --phpfpm no --named yes --remi yes --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota no --exim yes --dovecot yes --spamassassin no --clamav yes --softaculous yes --mysql yes --postgresql no --hostname ***.***.***.*** --email ******@****** --password **********`

The problem I encountered on the phpMyAdmin login screen is as follows:

> Deprecation Notice in ./libraries/classes/Url.php#253
> Array and string offset access syntax with curly braces is deprecated
> 
> Backtrace
> 
> functions.php#74: include_once()
> Autoload.php#210: Fedora\Autoloader\includeFile(string '/usr/share/phpMyAdmin/libraries/classes/Url.php')
> Fedora\Autoloader\Autoload::loadClass(string 'PhpMyAdmin\\Url')
> ./libraries/classes/Header.php#234: spl_autoload_call(string 'PhpMyAdmin\\Url')
> ./libraries/classes/Header.php#286: PhpMyAdmin\Header->getJsParams()
> ./libraries/classes/Header.php#217: PhpMyAdmin\Header->getJsParamsCode()
> ./libraries/classes/Header.php#144: PhpMyAdmin\Header->_addDefaultScripts()
> ./libraries/classes/Response.php#178: PhpMyAdmin\Header->__construct()
> ./libraries/classes/Response.php#212: PhpMyAdmin\Response->__construct()
> ./libraries/classes/Plugins/Auth/AuthenticationCookie.php#89: PhpMyAdmin\Response::getInstance()
> ./libraries/classes/Plugins/AuthenticationPlugin.php#265: PhpMyAdmin\Plugins\Auth\AuthenticationCookie->showLoginForm()
> ./libraries/common.inc.php#366: PhpMyAdmin\Plugins\AuthenticationPlugin->authenticate()
> ./index.php#23: require_once(./libraries/common.inc.php)
> 
> Deprecation Notice in ./libraries/classes/Server/Privileges.php#4023
> Array and string offset access syntax with curly braces is deprecated
> 
> Backtrace
> 
> functions.php#74: include_once()
> Autoload.php#210: Fedora\Autoloader\includeFile(string '/usr/share/phpMyAdmin/libraries/classes/Server/Privileges.php')
> Fedora\Autoloader\Autoload::loadClass(string 'PhpMyAdmin\\Server\\Privileges')
> ./libraries/classes/Twig/ServerPrivilegesExtension.php#34: spl_autoload_call(string 'PhpMyAdmin\\Server\\Privileges')
> ExtensionSet.php#438: PhpMyAdmin\Twig\ServerPrivilegesExtension->getFunctions()
> ExtensionSet.php#423: Twig\ExtensionSet->initExtension()
> ExtensionSet.php#397: Twig\ExtensionSet->initExtensions()
> Environment.php#966: Twig\ExtensionSet->getUnaryOperators()
> Lexer.php#459: Twig\Environment->getUnaryOperators()
> Lexer.php#110: Twig\Lexer->getOperatorRegex()
> Environment.php#539: Twig\Lexer->__construct()
> Environment.php#595: Twig\Environment->tokenize()
> Environment.php#408: Twig\Environment->compileSource()
> Environment.php#381: Twig\Environment->loadClass(
> string '__TwigTemplate_b94fcc3f26f66bb9f5554b68d3bd086ac3f9d446c135f4d025f547a85a4f2926',
> string 'login/header.twig',
> NULL,
> )
> Environment.php#359: Twig\Environment->loadTemplate(string 'login/header.twig')
> ./libraries/classes/Template.php#106: Twig\Environment->load(string 'login/header.twig')
> ./libraries/classes/Template.php#140: PhpMyAdmin\Template->load(string 'login/header')
> ./libraries/classes/Plugins/Auth/AuthenticationCookie.php#144: PhpMyAdmin\Template->render(
> string 'login/header',
> array,
> )
> ./libraries/classes/Plugins/AuthenticationPlugin.php#265: PhpMyAdmin\Plugins\Auth\AuthenticationCookie->showLoginForm()
> ./libraries/common.inc.php#366: PhpMyAdmin\Plugins\AuthenticationPlugin->authenticate()
> ./index.php#23: require_once(./libraries/common.inc.php)
> 
> 
> Deprecation Notice in ./libraries/classes/Server/Privileges.php#4278
> Array and string offset access syntax with curly braces is deprecated
> 
> Backtrace
> 
> functions.php#74: include_once()
> Autoload.php#210: Fedora\Autoloader\includeFile(string '/usr/share/phpMyAdmin/libraries/classes/Server/Privileges.php')
> Fedora\Autoloader\Autoload::loadClass(string 'PhpMyAdmin\\Server\\Privileges')
> ./libraries/classes/Twig/ServerPrivilegesExtension.php#34: spl_autoload_call(string 'PhpMyAdmin\\Server\\Privileges')
> ExtensionSet.php#438: PhpMyAdmin\Twig\ServerPrivilegesExtension->getFunctions()
> ExtensionSet.php#423: Twig\ExtensionSet->initExtension()
> ExtensionSet.php#397: Twig\ExtensionSet->initExtensions()
> Environment.php#966: Twig\ExtensionSet->getUnaryOperators()
> Lexer.php#459: Twig\Environment->getUnaryOperators()
> Lexer.php#110: Twig\Lexer->getOperatorRegex()
> Environment.php#539: Twig\Lexer->__construct()
> Environment.php#595: Twig\Environment->tokenize()
> Environment.php#408: Twig\Environment->compileSource()
> Environment.php#381: Twig\Environment->loadClass(
> string '__TwigTemplate_b94fcc3f26f66bb9f5554b68d3bd086ac3f9d446c135f4d025f547a85a4f2926',
> string 'login/header.twig',
> NULL,
> )
> Environment.php#359: Twig\Environment->loadTemplate(string 'login/header.twig')
> ./libraries/classes/Template.php#106: Twig\Environment->load(string 'login/header.twig')
> ./libraries/classes/Template.php#140: PhpMyAdmin\Template->load(string 'login/header')
> ./libraries/classes/Plugins/Auth/AuthenticationCookie.php#144: PhpMyAdmin\Template->render(
> string 'login/header',
> array,
> )
> ./libraries/classes/Plugins/AuthenticationPlugin.php#265: PhpMyAdmin\Plugins\Auth\AuthenticationCookie->showLoginForm()
> ./libraries/common.inc.php#366: PhpMyAdmin\Plugins\AuthenticationPlugin->authenticate()
> ./index.php#23: require_once(./libraries/common.inc.php)

What does this mean?

How to solve this problem?

Thank you.

![1](https://user-images.githubusercontent.com/25561562/68027214-d8a41e00-fcc2-11e9-9147-6fba33cc6774.PNG)
![2](https://user-images.githubusercontent.com/25561562/68027216-d93cb480-fcc2-11e9-877d-497467e123c3.PNG)
![3](https://user-images.githubusercontent.com/25561562/68027217-d93cb480-fcc2-11e9-98fa-d6d7b36f6717.PNG)
![4](https://user-images.githubusercontent.com/25561562/68027219-d93cb480-fcc2-11e9-99bc-df814c6ba50e.PNG)
![5](https://user-images.githubusercontent.com/25561562/68027220-d9d54b00-fcc2-11e9-8543-a55ac7580e56.PNG)

**Comment by anton-reutov** [comment]
Try this fix
https://github.com/phpmyadmin/phpmyadmin/pull/15404/commits/b989e825e14229ab558eeea312d9eaf8a483a2d9

**Comment by anton-reutov** [comment]
After changes you should relogin in the phpmyadmin
