### ISSUE TITLE
Vesta not create database user on remote database

### ISSUE THREAD

**Issue by Bittyby** [serghey-rodin/vesta#1958]
### Operating System (OS/VERSION):
Ubuntu 18.04

### VestaCP Version:

latest

### Installed Software (what you got with the installer):

--vsftpd no --proftpd yes --nginx yes --phpfpm yes --apache no

### Steps to Reproduce:

Install Mariadb from ubuntu repositories.
In vesta add the remote DB.
Create a database in vestacp.

### Other Notes:
I am using mariadb on ubuntu 18.04. I will transfer DB phpmyadmin to it.
In vestacp, when creating a database, only databases are created, but the user is not created.
There is nothing in the logs.

Any ideas?

**Comment by Bittyby** [comment]
Decent support :)

**Comment by Lupul** [comment]
do you have grant perms configured on the remote mysql server?

**Comment by Bittyby** [comment]
@Lupul 

```
nano /usr/local/vesta/conf/mysql.conf
HOST='192.168.1.227'
PASSWORD='PASSWORD'

cd /usr/local/vesta/bin/
./v-add-database-host mysql 192.168.1.226 user 'PASSWORD'
```

```
CREATE USER 'user'@'192.168.1.227' IDENTIFIED BY 'PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO 'user'@'192.168.1.227';
```

cat /etc/mysql/mariadb.conf.d/50-server.cnf

```
bind-address = 192.168.1.227
```

**Comment by Lupul** [comment]
you ned to add grant priv also:
`GRANT ALL PRIVILEGES ON ...... WITH GRANT OPTION;`

**Comment by Bittyby** [comment]
Does not work.

```
GRANT ALL PRIVILEGES ON *.* TO 'user'@'192.168.1.227' WITH GRANT OPTION;
flush privileges;
```

192.168.1.226 mariadb
192.168.1.227 vestacp

**Comment by Lupul** [comment]
Can you tried connecting from '.227' to mariadb server '.226' using mysql command and creating a test user? this would confirm your permissions are configured properly.

**Comment by Bittyby** [comment]
Yes, remote connection works

**Comment by Lupul** [comment]
Thats good.
The code that creates database and user is here, and uses the 'GRANT ALL' syntax, maybe it will help you track down the issue.
https://github.com/serghey-rodin/vesta/blob/931fb5beebca60c72176596e088a06393741987c/func/db.sh#L205-L214

**Comment by Bittyby** [comment]
Can you show the line in which the MySQL user is created?
I do not see her...

**Comment by Lupul** [comment]
Line 208 and 212.
you can drop the redirection to /dev/null and dump the output to a log file.

**Comment by Lupul** [comment]
have you found the problem?

**Comment by Bittyby** [comment]
I made a conclusion to the file and it is not

```
    query="GRANT ALL ON \`$database\`.* TO \`$dbuser\`@\`%\`
        IDENTIFIED BY '$dbpass'"
    #mysql_query "$query" > /dev/null
     mysql_query "$query" > /root/all.txt

    query="GRANT ALL ON \`$database\`.* TO \`$dbuser\`@localhost
        IDENTIFIED BY '$dbpass'"
    #mysql_query "$query" > /dev/null
     mysql_query "$query" > /root/localhost.txt

     echo "$query" > /root/query.txt

```

**Comment by Bittyby** [comment]
This option also does not work.

```
# MySQL
mysql_connect() {
    echo test > /root/test.txt
```

**Comment by Bittyby** [comment]
`chmod +x /usr/local/vesta/func/*.sh`
