### ISSUE TITLE
So this is an abandoned project?

### ISSUE THREAD

**Issue by progcode** [serghey-rodin/vesta#1971]
Two years ago there was a ticket for this, and since then the situation has not changed so much. So this is an abandoned project?

#1330

**Comment by skullwritter** [comment]
No it isn't, but it has a slow development.

**Comment by progcode** [comment]
A very slow development.

**Comment by 4183r** [comment]
it's been one of the best control panel but Sadly I feel like it's a dead project now! 
there is a new CP based on vestacp and they are very active for the development.

https://github.com/hestiacp/hestiacp/
