### ISSUE TITLE
Ubuntu 19.10: repository eoan doesnt have a Release file

### ISSUE THREAD

**Issue by noraj** [serghey-rodin/vesta#1980]
### Operating System (OS/VERSION):

Ubuntu Server 19.10 fresly installed

### VestaCP Version:

must be 0.9.8-25 

### Steps to Reproduce:

`curl http://vestacp.com/pub/vst-install.sh | bash`

![image](https://user-images.githubusercontent.com/16578570/75896759-d6e89380-5e37-11ea-821f-5efaafb25269.png)

**Comment by Lupul** [comment]
18.10 is the most recent Ubuntu release supported 
https://github.com/serghey-rodin/vesta/tree/master/install/ubuntu

**Comment by noraj** [comment]
I can confirm that it worked on 18.04

**Comment by jkarlos000** [comment]
Hello @noraj please use this repositories:

`deb http://old-releases.ubuntu.com/ubuntu disco-security universe main multiverse
deb http://old-releases.ubuntu.com/ubuntu disco universe main multiverse
deb http://old-releases.ubuntu.com/ubuntu disco-updates main multiverse`

Ubuntu 20 is here!

**Comment by noraj** [comment]
Sure
