### ISSUE TITLE
[Bug] Services list shows incorrect uptime for services other than server itself

### ISSUE THREAD

**Issue by dustindauncey** [serghey-rodin/vesta#199]
Hi there,

I originally believed that all my services were restarting on their own but I could never find a good reason why, and after some investigation over the past week, I am starting to think the services uptime in Vesta are just not accurate.

Example service: httpd

In Vesta as of this moment, it shows uptime of only 41 minutes for the httpd service. Yet, when I run the following command, I get the output as below:

[root@vps1 ~]# ps -eo pid,comm,lstart,etime,time,args | grep httpd
 1512 httpd           Thu Aug  7 00:24:46 2014    19:27:03 00:00:02 /usr/sbin/httpd
 3969 grep            Thu Aug  7 19:51:49 2014       00:00 00:00:00 grep httpd
14712 httpd           Thu Aug  7 14:09:37 2014    05:42:12 00:01:46 /usr/sbin/httpd
14713 httpd           Thu Aug  7 14:09:38 2014    05:42:11 00:01:46 /usr/sbin/httpd
14714 httpd           Thu Aug  7 14:09:38 2014    05:42:11 00:01:47 /usr/sbin/httpd
17613 httpd           Thu Aug  7 15:09:58 2014    04:41:51 00:01:20 /usr/sbin/httpd
26651 httpd           Thu Aug  7 08:05:34 2014    11:46:15 00:03:55 /usr/sbin/httpd

Nowhere do I see where 41 minutes is coming from, and the service has basically been running since after midnight to this moment and yet instead of showing 19 hours of uptime, it shows 41 minutes. Mind you there are multiple services for it which makes me think it might be getting confused somehow, but even if that was true I still don't see 41 minutes as an uptime listed for any of them. Why is this? I believe that the calculator of this in Vesta is incorrect. But if anyone can prove me wrong and point me back at my services actually restarting, I'm all ears. :-)

**Comment by xeux** [comment]
This is still occurring right? using Version: 0.9.8 (x86_64)
