### ISSUE TITLE
Execute another script when LE Certificate Updated

### ISSUE THREAD

**Issue by sebasira** [serghey-rodin/vesta#1996]
### Operating System (OS/VERSION):

Ubuntu 14.04

### VestaCP Version:

0.9.8

### Other Notes:

I'd like to know if there's a way to execute another custom script after the SSL Certificate from Let'sEncrypt has been updated.

I have the LE SSL Certificate that auto-renew every 2 months. Sadly as my hostname is not the same as the domain name (rookie error when installing Vesta for the first time several years ago), the SLL is not automatically applied to Exim and Dovecot even though I have **UPDATE_HOSTNAME_SSL='yes'**

So I decided to create a CRON job that run every day to execute 

> v-update-host-certificate [user] [domain]

If I could just call this script only after the certificate has been updated it would be great. 

But that's not the only reason. I also have a Java app running on the server that depends on that SSL certificate, so after it's updated I need to shutdown my app and load the new certificate. I could also do it with a cron job every (let's say 25th day of the month, because the cert is updated on 22th), but again I would like to know if there's a way to be *notified* when the certificate has been updated and only then do my actions.

Right now I have just think I could check on the certificate and see if the expiracy date is the same 
or have change, and then execute my scripts. Any ideas on how can I check the certificate expiracy with a bash script?

**Comment by dpeca** [comment]
https://github.com/serghey-rodin/vesta/commit/d15e1037041a59b9f2edebf8744f7ee7fc1721cd
