### ISSUE TITLE
bug, maybe a security issue

### ISSUE THREAD

**Issue by bberg1984** [serghey-rodin/vesta#2007]
hi, i believe i found a bug that could be a security issue.
is there an email i can send it to?
i can't find any contact info on the website or on github.

**Comment by Lupul** [comment]
Hello @bberg1984, please give HestiaCP (Vesta fork) team a heads up too. (contact details are on the "Security Policy" page on our github repo)

**Comment by bberg1984** [comment]
sure, done already.

**Comment by madeITBelgium** [comment]
dev@vestacp.com

**Comment by dpeca** [comment]
Fixed - https://github.com/serghey-rodin/vesta/commit/b6cadcd9923c5337380efd59da5cbb689293300c
