### ISSUE TITLE
[Bug] Mail "do not store forwarded mail" setting ignored after change to aliases

### ISSUE THREAD

**Issue by dustindauncey** [serghey-rodin/vesta#201]
It appears that when an email address is created, and the "do not store forwarded mail" setting is checked after a forwarding address is in the text box and then saved, it works as expected. However, if a change is made after-the-fact by adding an alias to that same account, for example, and the "do not store forwarded mail" is still checked, then saved, it still saves forwarded mail regardless of that setting. So making a change to an email account that is currently set to forward-only, it loses that setting when a change is made even though it should not affect it at all. I hope this makes sense. Let me know if I can elaborate any further.

**Comment by tommyvallier** [comment]
Confirming this issue on my server - file is being overwritten.
