### ISSUE TITLE
support for postfix

### ISSUE THREAD

**Issue by mkkeck** [serghey-rodin/vesta#202]
Would be a support for postfix mailserver with amavisd, mysql user storage, spamd, dovecot available?

**Comment by smat88** [comment]
+1 postfix/dovecot

**Comment by marcelloinfoweb** [comment]
+1 para postfix/dovecot

**Comment by KeiroD** [comment]
You can easily install `postfix` yourself... at least, in Ubuntu with a simple `apt-get install postfix` and it'll automatically take care of the dependencies for you.

You'd have to install the other stuff you want yourself, though.

**Comment by smat88** [comment]
Of course, but would postfix be correctly configured by vesta ?

**Comment by KeiroD** [comment]
@smat88 For the most part, yes. You may or may not need to force it to use one IPv4 or IPv6 IP. I have mine running postfix, no problems so far after checking over its configuration.

There are many guides online on how to configure postfix.

**Comment by smat88** [comment]
@KeiroD Thanks for your info. For example, can I create an e-mail-alias in VestaCP, and postfix will recognise it?

**Comment by KeiroD** [comment]
@smat88 Not sure. I believe so?

Just in case, try this as well: http://www.serverwatch.com/tutorials/article.php/3912056/Adding-Users-and-Aliases-for-Postfix.htm

**Comment by AbbyNormal** [comment]
Btw postfix is far superior then exim, it has significantly better performance than exim, it is modular in design, has cleaner config files and is newer. You should really upgrade this panel to use better email tech :+1:

**Comment by marcelloinfoweb** [comment]
+1 postfix/dovecot
Em 19/11/2015 10:28, "AbbyNormal" <notifications@github.com> escreveu:

**Comment by maop** [comment]
+1 postfix  
i really dislike the monstruosity of exim's configs and tracking its logs is very hard... 
postfix is so beautiful <3

**Comment by rmalenko** [comment]
+1 Postfix / Dovecot / AmavisNew = store in MySQL (this allows to transfer easy in case needs)

**Comment by skurudo** [comment]
Guys, who can help on forum and here with postfix configuration, if in future postfix will be optional?

**Comment by rmalenko** [comment]
I can try to help

**Comment by drequivalent** [comment]
>skurudo

Так чего, в Весте постфиксу быть?

**Comment by mehargags** [comment]
I want to configure SOGO groupware too... Anyone in for this ?

**Comment by andyzasl** [comment]
+1

**Comment by anton-reutov** [comment]
https://bugs.vestacp.com/issues/380

**Comment by ms1ra** [comment]
+1 postfix.
