### ISSUE TITLE
New subdomains are redirected to a another subdomain on the same server

### ISSUE THREAD

**Issue by ibrahimhajjaj** [serghey-rodin/vesta#2020]
I have two subdomains created in the example.net account and when I attempt to go to any of them you're redirected to one of my clients domain and the here is the CURL Result

![image](https://user-images.githubusercontent.com/23178074/86490695-f1446680-bd70-11ea-8503-783ceb422525.png)

**Comment by dpeca** [comment]
Install SSL on subdomains, or do not call them via https
