### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by carlos-andres** [serghey-rodin/vesta#2024]
### Operating System (OS/VERSION):

macOS Catalina

### VestaCP Version:

0.9.8-24

### Installed Software (what you got with the installer):

apache2 + mariadb + php73

### Steps to Reproduce:

n/a

### Related Issues/Forum Threads:

n/a

### Other Notes:

I like to know if i can run vesta on macos .. if is supported... thanks

**Comment by jaapmarcus** [comment]
MacOS is not supported..

**Comment by skullwritter** [comment]
Unfortunately not every developer has a macos and emulating one it's very hard.

To provide the system/manager to macos, would be like taking a bullet in a foot without anything to test actively against it
