### ISSUE TITLE
Webdomain / Maildomain migration to another user

### ISSUE THREAD

**Issue by serejch** [serghey-rodin/vesta#203]
Hi, we are using VESTA CP, but we need to migrate some previously created web / mail domains and databases (including data) from one user to another. Is there any way to do that? Thank you a lot for response.

Best regards,
Vaclav Serejch

**Comment by ibrahimuslu** [comment]
I have moved one of my customer domain to the new user of them. MANUALLY. 
I have backup files and mysql data and DELETE the old one and add domain to the new user and move the files and mysql data manually. No automation yet.

**Comment by serghey-rodin** [comment]
Please take a look here http://vestacp.com/docs/#how-to-migrate-user-to-another-server
Is that what you are looking for?

**Comment by ibrahimuslu** [comment]
domain transfer is different from server migration.
I totally appreacite you about server migration. It works perfect but. Moving a domain to another user is sth different. it may be done automatically but if there is no mysql databases in my opinion. 
Thanks in advance
