### ISSUE TITLE
Issue with Cron sudo /usr/local/vesta/bin/v-update-sys-rrd 

### ISSUE THREAD

**Issue by zvkfhapjg** [serghey-rodin/vesta#2032]
### Operating System (OS/VERSION):

Ubuntu 18.04

### VestaCP Version:

0.9.8-26

I'm having an issue whereby every few days I get multiple emails with the following cron issue.
sudo /usr/local/vesta/bin/v-update-sys-rrd 
sudo unable to resolve host 'www.domain.com': resource temporarily unavailable

When this happens it seems to stop emails coming through. 
Does anyone have any suggestions on how I can rectify this? 

Thanks everyone :)

**Comment by dpeca** [comment]
Your datacenter has DNS issue or even network connectivity issues.

You can 'fix' this type of error by adding:
`111.111.111.111 www.domain.com`
to the bottom of file **/etc/hosts**
(of course, put IP of your server IP instead 111.111.111.111)

And of course, this will not solve all other issues related to DNS issue in your datacenter or network connectivity issue.
This will just help your server to know its  own IP even DNS in datacenter has issues.

**Comment by zvkfhapjg** [comment]
> 
> 
> Your datacenter has DNS issue or even network connectivity issues.
> 
> You can 'fix' this type of error by adding:
> `111.111.111.111 www.domain.com`
> to the bottom of file **/etc/hosts**
> (of course, put IP of your server IP instead 111.111.111.111)
> 
> And of course, this will not solve all other issues related to DNS issue in your datacenter or network connectivity issue.
> This will just help your server to know its own IP even DNS in datacenter has issues.

That's great thank you!
