### ISSUE TITLE
 Can send emails but can't receive emails

### ISSUE THREAD

**Issue by anjutares** [serghey-rodin/vesta#2033]
### Operating System (OS/VERSION):

CentOS Linux release 7.8.2003 (Core)

### VestaCP Version:

 0.9.8 (x86_64) 

### Installed Software (what you got with the installer):
nginx, apache, named, remi, vsftpd, iptables, fail2ban, quota, exim, dovecot, spamassassin, clamav, softaculous, mysql, postgresql 

### Steps to Reproduce:
Install:
`curl -O http://vestacp.com/pub/vst-install.sh`
`sudo bash vst-install.sh --nginx yes --apache yes --phpfpm no --named yes --remi yes --vsftpd yes --proftpd no --iptables yes --fail2ban yes --quota yes --exim yes --dovecot yes --spamassassin yes --clamav yes --softaculous yes --mysql yes --postgresql yes --hostname myhostname.net --email mymail@myhostname.net --password mypass`
Fixing Exim bug, using old vs.:
`wget https://ca1.dynanode.net/exim-4.93-3.el7.x86_64.rpm`
`rpm -Uvh --oldpackage exim-4.93-3.el7.x86_64.rpm`
SSL:
`source /etc/profile`
`PATH=$PATH:/usr/local/vesta/bin && export PATH`
`v-add-letsencrypt-domain 'admin' $HOSTNAME '' 'yes'`
`v-update-host-certificate admin $HOSTNAME`
`echo "UPDATE_HOSTNAME_SSL='yes'" >> /usr/local/vesta/conf/vesta.conf`

### Related Issues/Forum Threads:

Similar error, but doesnt works for me:
https://github.com/serghey-rodin/vesta/issues/1197

### Other Notes:
*** The Server Works but one day to another it stop working (to receive emails)
I tried to review MX record, but doesnt work.
Vesta Installatión doesnt have ReverseDNS, but its wors two weeks ago.
Server is on a DMZ at my home (All ports open)

**Comment by dpeca** [comment]
Sorry, this can't be a 'bug ticket'
You didn't provide any evidence that something is wrong with Vesta code.
Maybe you have issue with new versin of Exim - see forum thread https://forum.vestacp.com/viewtopic.php?f=12&t=19994

**Comment by dpeca** [comment]
To be honest, ticket should be opened generally for Exim conf file on CentOS.
