### ISSUE TITLE
Changes in LE ACMEv2 API

### ISSUE THREAD

**Issue by moucho** [serghey-rodin/vesta#2038]
### Operating System (OS/VERSION):

All systems/versions

### VestaCP Version:

0.9.8-26

### Installed Software (what you got with the installer):

apache, nginx, mysql

### Steps to Reproduce:

On November 1st, 2020 Let's Encrypt will remove support for unauthenticated GETs from the production V2 API. Since that moment, updating or creating a new certificate in VestaCP will fail because "GET" is used to download the ".pem" file (v-add-letsencrypt-domain, line 235)

### Related Issues/Forum Threads:

https://community.letsencrypt.org/t/acme-v2-scheduled-deprecation-of-unauthenticated-resource-gets/74380

**Comment by Dgriffin1988** [comment]
Payments
