### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [serghey-rodin/vesta#2058]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by dpeca** [comment]
Hello,
I'm one of the Vesta developers.
Feel free to send issue to dev@vestacp.com

**Comment by ScIT-Raphael** [comment]
Hi @zidingz 

We provide under https://github.com/hestiacp/hestiacp a fork of vestacp. In case your issue is related to it aswell, please inform us over the security policy function in the project or over e-mail (info@hestiacp.com). Thanks you!

**Comment by aaPanel-russian** [comment]
**zidingz**, send your report to info@vestacp.com, or dev@vestacp.com

**Comment by anton-reutov** [comment]
**zidingz**, you can send your report to info@vestacp.com or dev@vestacp.com

**Comment by dpeca** [comment]
@anton-reutov 
Better dev@vestacp.com because on that mail I will receive issue and fix it ASAP (as I always did), so we will avoid waiting and fix will be ready just to run build.

**Comment by anton-reutov** [comment]
**dpeca,**  Ok
