### ISSUE TITLE
Adding *.domain.tld breaks domain

### ISSUE THREAD

**Issue by TheLastProject** [serghey-rodin/vesta#206]
Adding *.domain.tld works to allow all subdomains to redirect to the domain in question, however, it makes it impossible to make any further changes to the domain, as you can no longer save changes. See attached screenshot.

There are two issues here:
1. The domains are checked on the OLD data, not the new data
2. \* should be considered valid as a subdomain

![snapshot12](https://cloud.githubusercontent.com/assets/1885159/4091472/cc48e0b2-2f88-11e4-9a18-6f8ed778abd3.png)

**Comment by SysVoid** [comment]
@serghey-rodin
