### ISSUE TITLE
VestaCP.com expired

### ISSUE THREAD

**Issue by jaapmarcus** [serghey-rodin/vesta#2060]
<img width="732" alt="Screenshot 2021-07-26 at 17 55 33" src="https://user-images.githubusercontent.com/9754650/127020321-a0071694-d971-4904-81af-19f2c06c3874.png">

Registry Domain ID: 1608266903_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.publicdomainregistry.com
Registrar URL: www.publicdomainregistry.com
Updated Date: 2021-07-26T14:33:31Z
Creation Date: 2010-07-26T14:13:27Z
Registrar Registration Expiration Date: 2021-07-26T14:13:27Z
Registrar: PDR Ltd. d/b/a PublicDomainRegistry.com

**Comment by ScIT-Raphael** [comment]
... time if flying, again a year over: https://github.com/serghey-rodin/vesta/issues/2025
