### ISSUE TITLE
v-update-sys-vesta-all syntax error

### ISSUE THREAD

**Issue by fsoyer** [serghey-rodin/vesta#2075]
### Operating System (OS/VERSION):
CentOS Linux release 7.9.2009 (Core)

### VestaCP Version:
vesta        1.0.0  1    x86_64  yes   2021-10-30
vesta-php    0.9.8  26   x86_64  yes   2019-09-30
vesta-nginx  0.9.8  26   x86_64  yes   2019-09-30

### Installed Software (what you got with the installer):
php-fpm, apache, nginx, mysql

### Steps to Reproduce:
update Vesta to 1.0.0-1 via yum
At night, the v-update-sys-vesta-all cron says : 
`/usr/local/vesta/bin/v-update-sys-vesta: ligne41: Erreur de syntaxe près du symbole inattendu « fi »
/usr/local/vesta/bin/v-update-sys-vesta: ligne41: `fi [ "$package" = "vesta-ioncube" ]; then '`

At line 41, a "fi" is effectively in place of "if". 

### Other Notes:
Not so hard to debug and repair with the right message by mail ;) Just think to fix it in version 1.0.0-2.

**Comment by mix5003** [comment]
i just open pull request for fix this #2074

**Comment by 53RG1U5** [comment]
> i just open pull request for fix this #2074

Hi!
Do you know whats wrong with letsencrypt in new update?

**Comment by fsoyer** [comment]
> i just open pull request for fix this #2074

Oh sorry, I didn't see it.
