### ISSUE TITLE
i18n in Firewall edit error

### ISSUE THREAD

**Issue by mysterynet** [serghey-rodin/vesta#2079]
### Operating System (OS/VERSION):

Centos 7

### VestaCP Version:

1.0.0(x86_64) 

### Related Issues/Forum Threads:

When use language cn(chinese) and other not en(english), the firewall edit page will make error request like this:

======post request======
------WebKitFormBoundary
Content-Disposition: form-data; name="ok"
add
------WebKitFormBoundary
Content-Disposition: form-data; name="token"
===hidden===
------WebKitFormBoundary
Content-Disposition: form-data; name="v_action"
阻止
------WebKitFormBoundary
Content-Disposition: form-data; name="v_protocol"
TCP
------WebKitFormBoundary
Content-Disposition: form-data; name="v_port"
11
------WebKitFormBoundary
Content-Disposition: form-data; name="v_ip"
0.0.0.0/0
------WebKitFormBoundary
Content-Disposition: form-data; name="v_comment"
------WebKitFormBoundary--
======end======
In v_action section the 阻止 is DROP,this problem also broken in jp(and other).
jp:拒否
ar:حذف
.....

I think maybe the value in the request need to change to 'DROP' Not the word in user's language

**Comment by mysterynet** [comment]
the api response this:
{"ok_msg":null,"error_msg":"Error: invalid action format :: \u963b\u6b62"}

**Comment by jaapmarcus** [comment]
v_action should not be translated..

**Comment by anton-reutov** [comment]
I can't reproduce this. Can you send me some screenshots, or video?
Or steps how to reproduce this

**Comment by jaapmarcus** [comment]
Use a non alphanumeric language like Chinese ...

**Comment by mysterynet** [comment]
> I can't reproduce this. Can you send some screenshots, or video? Or steps how to reproduce this

ok, plz wait

**Comment by mysterynet** [comment]
In file src/react/src/components/Firewall/Add/AddFirewall.jsx
==line:23
const [state, setState] = useState({
    loading: false,
    actions: [
      i18n['DROP'],  <-here translate the action to user'language
      i18n['ACCEPT']  <-here translate the action to user'language
    ],
    protocols: [
      i18n['TCP'],
      i18n['UDP'],
      i18n['ICMP']
    ],
    okMessage: '',
    errorMessage: ''
  });

==line:96
<SelectInput
            options={state.actions}   <- here just use the translated action  
            name="v_action"
            id="action"
            title={i18n['Action']} />


Follow is the step to reproduce
======
1. change vestacp to non English(here I will use cn,jp to show)
![1](https://user-images.githubusercontent.com/93434755/139563281-75a83fa8-5587-4dec-87dd-ae569d081a96.JPG)
![2](https://user-images.githubusercontent.com/93434755/139563284-60c49697-0a5c-42fc-ac9e-51503a04d823.JPG)

2. select the firewall here
![3](https://user-images.githubusercontent.com/93434755/139563294-08f12ec0-6c85-45ac-a96c-5e256822ec07.JPG)

3. add a firewall record(edit is also fine)
![4](https://user-images.githubusercontent.com/93434755/139563304-b80c8463-2b50-48d6-b936-289f3eba4bc2.JPG)

4. choose the action like "放行" mean "accept" and add other information
![5](https://user-images.githubusercontent.com/93434755/139563337-2f265528-cac4-450b-bda6-a4870dd902f5.JPG)

5.click button add(or edit)
![6](https://user-images.githubusercontent.com/93434755/139563366-e491e7f9-527b-40b8-a0ab-251a2791d452.JPG)
will see this report, it mean this is a invalid action about "放行"(the '放行' is translate in chinese not english "ACCEPT")

the option value is translate to user's language at this
![image](https://user-images.githubusercontent.com/93434755/139563523-ad7b1660-2c8b-44f7-b97f-9e3460b9fbc8.png)
