### ISSUE TITLE
(Feature Request) Limit Username Length

### ISSUE THREAD

**Issue by ghost** [serghey-rodin/vesta#208]
Hey Guys,
A few of my website customers are having trouble with creating databases.

Database usernames/names are limited to 16 characters, when the username/name is longer VestaCP won't let you make the database.

This is a problem if someone makes a username in VestaCP that's longer than 15 charecters, it makes creating a database impossible!

I'd like to see a length limit on account usernames imposed by the system to keep this from happening, something like 10 or 12 characters max.

**Comment by nicdnepr** [comment]
Any progress? 6 years and still limit 16
Why 16? Why not 255?

**Comment by Skamasle** [comment]
Is a MySQL limit, mariadb not have this issue, but limit exist for
compatibility in migrations
