### ISSUE TITLE
Vesta Installation on centos 6

### ISSUE THREAD

**Issue by obipeter8Ho** [serghey-rodin/vesta#2081]
### Operating System (OS/VERSION):

Centos 6

### VestaCP Version:

VestaCP Release 1.0.0-1

### Installed Software (what you got with the installer):

Vesta

### Related Issues/Forum Threads:

--> Finished Dependency Resolution
Error: Package: vesta-1.0.0-1.x86_64 (vesta)
           Requires: /usr/local/vesta/php/bin/php
Error: Package: vesta-ioncube-1.0.0-1.x86_64 (vesta)
           Requires: vesta-php
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

### Other Notes:

Anything else?

**Comment by obipeter8Ho** [comment]
please if you need more clarifications, let me know.

**Comment by obipeter8Ho** [comment]
can it be fixed today?

**Comment by anton-reutov** [comment]
try to install again

**Comment by obipeter8Ho** [comment]
alright.. a moment..

**Comment by obipeter8Ho** [comment]
It works now.. Thank you 

Also i noticed on the Vesta panel itself, when you want to add a Web domain, DNS Support and Mail Support cant be unticked. if that can be looked into, that will be great too..
