### ISSUE TITLE
Still not solved

### ISSUE THREAD

**Issue by Penguinehis** [serghey-rodin/vesta#2087]
### Operating System (OS/VERSION):

Ubuntu 18.04

![image](https://user-images.githubusercontent.com/54519344/139542916-9d29bb82-49db-415a-b5ca-e77263c476a7.png)

### VestaCP Version:

Release 1.0.0.2

### Installed Software (what you got with the installer):

Default

### Steps to Reproduce:

 v-add-letsencrypt-domain user domain
 Not save the correct SSL and not allow to acess the website

Not working change the proxy template
Not working the Lests encrypt buttom
the command  v-add-letsencrypt-domain broke the domain and not allow to change the SSL

![image](https://user-images.githubusercontent.com/54519344/139565637-104cb329-e6a6-4037-a609-974b86abc754.png)

![image](https://user-images.githubusercontent.com/54519344/139565651-6452bacb-b9ea-4453-a718-0635c7b3b5cb.png)

![image](https://user-images.githubusercontent.com/54519344/139565655-aafa3575-1734-48bd-8b72-c86b5f3ee61c.png)

Updated to 1.0.0.2 and still broken

**Comment by Penguinehis** [comment]
![image](https://user-images.githubusercontent.com/54519344/139565814-e9a3c1ce-cbe3-4420-9af8-f6dc6b374ac7.png)

**Comment by Coxii** [comment]
Hey, whats up, because I needed quick fix, I have fixed this lets encrypt problem by myself, check my commit.
https://github.com/serghey-rodin/vesta/commit/aebc4575f8a7f3ff7241f6c638d9587219cd23d5

**Comment by andyg2** [comment]
I have the same problem. It just started today after what appears to be an update (theme has changed from orange to blue)

**Comment by Coxii** [comment]
> I have the same problem. It just started today after what appears to be an update (theme has changed from orange to blue)

If you need quick fix, check my commit :-)

**Comment by jonnydo** [comment]
> > I have the same problem. It just started today after what appears to be an update (theme has changed from orange to blue)
> 
> If you need quick fix, check my commit :-)

Yes, this solves the problem with SSL, now we get error 400 after save.
Aliases and proxies are not saved anyway

**Comment by Coxii** [comment]
yep seems its completly fucked up :-D Going to check that..

**Comment by Coxii** [comment]
> > > I have the same problem. It just started today after what appears to be an update (theme has changed from orange to blue)
> > 
> > 
> > If you need quick fix, check my commit :-)
> 
> Yes, this solves the problem with SSL, now we get error 400 after save. Aliases and proxies are not saved anyway ![image](https://user-images.githubusercontent.com/40856635/139576351-0d26634b-8347-443b-bb18-aeabe35e7ae2.png)

To me its working fine, and yes its true that aliases are not shown in Edit textarea after change (but seems they are created).

**Comment by mix5003** [comment]
for solve letsencrypt issue can you try this
1. run `v-change-web-domain-proxy-tpl user domain default`. eg ` v-change-web-domain-proxy-tpl admin example.com default`
2. run `v-add-letsencrypt-domain user domain`. eg `v-add-letsencrypt-domain admin example.com`

**Comment by jonnydo** [comment]
https://github.com/serghey-rodin/vesta/commit/43a6fc23ef792ad51ed759c58531be5041f51970

Solve my problem.

Lets Encrypt issued a certificate
![image](https://user-images.githubusercontent.com/40856635/139576780-8f4f3929-f526-4936-9b0b-d4c4b3fa2e43.png)

**Comment by anton-reutov** [comment]
Fixed, but not released yet. we need to fix all important bugs

**Comment by jonnydo** [comment]
Websites don't work .. somehow bring them back to life in this way
