### ISSUE TITLE
yum update issue - (httpd-manual-2.4.6-97.el7.centos.1.noarch)

### ISSUE THREAD

**Issue by rooteto** [serghey-rodin/vesta#2088]
### Other Notes:

I just installed the server and I'm getting this error.

![Screenshot_1](https://user-images.githubusercontent.com/3899331/139573839-2537b477-4d61-4a12-bcce-ec4a034e695c.png)

**Comment by anton-reutov** [comment]
Are your problem is solved ?

**Comment by rooteto** [comment]
Now it seems to be fixed again.

**Comment by anton-reutov** [comment]
Can we close this ticket ?

**Comment by rooteto** [comment]
okkey :)
