### ISSUE TITLE
Installatron support

### ISSUE THREAD

**Issue by fossxplorer** [serghey-rodin/vesta#209]
Hi,
does VestaCP support Installatron or is there any plans to support it in the near future?
This is quite important for a web hosting provider. It's the only feature that's holding me back from using VestaCP for a web hosting company.
Thanks.
@serghey-rodin

**Comment by skurudo** [comment]
We'll present new script soon - integration with Softaculous and you can easily Wordpress and other scripts.
or you can use 3rd-party module - https://forum.vestacp.com/viewtopic.php?f=19&t=8523 (project closed now, but it still work)

**Comment by xjlin0** [comment]
Looking forward to the integration with Softaculous  -- any updates?  You folks are great!  Thanks a ton!
