### ISSUE TITLE
User and Admin web templates are not editable

### ISSUE THREAD

**Issue by hollanddata** [serghey-rodin/vesta#2092]
### Operating System (OS/VERSION):

Centos 7

### VestaCP Version:

Core Package Version: 1.0.0 (X86_64) Release: 2

### Installed Software (what you got with the installer):

apache, mysql

**Comment by hollanddata** [comment]
Nothing changes when editing the web templates /usr/local/vesta/web/templates

**Comment by mysterynet** [comment]
Hi,The Vestacp is change to react font-end. 
So the templates file had deprecated.
If you need to change templates,you can change the react javascript in src/react/

**Comment by hollanddata** [comment]
Thanks!

**Comment by hollanddata** [comment]
Where are the php files?

**Comment by mysterynet** [comment]
noop, the fore-end had change to HTML+JS(react), No PHP template file more ever.
Look like the API is same as before(some change but not all)

**Comment by wojsmol** [comment]
@mysteryneIf I understand correctly @hollanddata is asking for server configuration templates and not html and css front-end templates.

**Comment by hollanddata** [comment]
I was asking for /usr/local/vesta/web/templates
So when users or admin logs in those templates.
https://drive.google.com/file/d/1La_h2OXTt3Gzj339CfUTKPGUl0tId8Jo/view?usp=sharing

**Comment by Ozea** [comment]
> I was asking for /usr/local/vesta/web/templates So when users or admin logs in those templates. https://drive.google.com/file/d/1La_h2OXTt3Gzj339CfUTKPGUl0tId8Jo/view?usp=sharing

@mysterynet and @wojsmol are right.
Vesta CPanel has been moved to React. Therefore, old web templates you could find in /web/templates/ are deprecated. Even though you edit them nothing will happen. React source files you can find in /src/react/
