### ISSUE TITLE
Webmail no have button on Tab "Mail"

### ISSUE THREAD

**Issue by skorpions2000** [serghey-rodin/vesta#2094]
### Operating System (OS/VERSION):

Debian 9.13

### VestaCP Version:

Version: 1.0.0 (Amd64) Release: 2

### Installed Software (what you got with the installer):

vesta(Core Package)
vesta-php(Php Interpreter)
vesta-nginx(Internal Web Server)
vesta-ioncube(Php Encoder)
vesta-softaculous(App Installer)

### Bug?/Problem:

After click MAIL, no have button "open webmail"...
![01](https://user-images.githubusercontent.com/11683786/139584729-df2d7ef1-3ce2-456a-9050-efa354954bee.jpg)

**Comment by anton-reutov** [comment]
Try to update on 1.0.0.4
Let me know if this problem still exists

**Comment by anton-reutov** [comment]
Can we close this ticket ?
