### ISSUE TITLE
When vestacp connect on DNS cluster, no work API...

### ISSUE THREAD

**Issue by skorpions2000** [serghey-rodin/vesta#2096]
Operating System (OS/VERSION):
Debian 9.13

VestaCP Version:
Version: 1.0.0 (Amd64) Release: 2

Installed Software (what you got with the installer):
vesta(Core Package)
vesta-php(Php Interpreter)
vesta-nginx(Internal Web Server)
vesta-ioncube(Php Encoder)
vesta-softaculous(App Installer)

Bug?/Problem:
When vestacp connect on DNS cluster, no work tab Server -> Configure...
Only open white page... No work API...
![04](https://user-images.githubusercontent.com/11683786/139585755-b95dd7f0-c9ae-46a6-a0d9-6c44275609d5.jpg)

**Comment by skorpions2000** [comment]
When connect to api:
https://domain:8083/api/v1/ 
Does it work as before?

**Comment by skorpions2000** [comment]
And when server on no DNS cluster, on Server -> Configure is normal open page with setting and write previous version on label:
![09](https://user-images.githubusercontent.com/11683786/139591175-bc41c3c5-98a1-4fff-bf49-ff47f840eab2.jpg)

**Comment by anton-reutov** [comment]
Fixed, please waiting release
