### ISSUE TITLE
No save setting on domain... No generate SSL certificate...

### ISSUE THREAD

**Issue by skorpions2000** [serghey-rodin/vesta#2098]
### Operating System (OS/VERSION):

Debian 9.13

### VestaCP Version:

Version: 1.0.0 (Amd64) Release: 2

### Installed Software (what you got with the installer):

vesta(Core Package)
vesta-php(Php Interpreter)
vesta-nginx(Internal Web Server)
vesta-ioncube(Php Encoder)
vesta-softaculous(App Installer)

### Bug?/Problem:

No saving new configure on domain after adding new domain on user... write "Changes have been saved." but nothing happened, no change version php (Web Template apache2) and no change "Proxy Template nginx"... 
Work only Additional FTP...?
When click on SSL Support -> Generate CSR...  No generate SSL certificate on domin.... open white page with header...
![05](https://user-images.githubusercontent.com/11683786/139587337-2963e2c0-148c-4f1a-a1c0-7d5ea2b8042f.jpg)

**Comment by anton-reutov** [comment]
confirmed, will be fixed

**Comment by anton-reutov** [comment]
proxy, ssl already fixed, but no released yet.
Generate CSR - in progress

**Comment by meerajsharif** [comment]
### SSL Support + Lets Encrypt Support Not saving or No change
https://prnt.sc/1xyqaba
https://prnt.sc/1xyq6ts
https://prnt.sc/1xyqeya
https://prnt.sc/1xyqj3r
