### ISSUE TITLE
Problem with mobile version... Nothing no clickable... 

### ISSUE THREAD

**Issue by skorpions2000** [serghey-rodin/vesta#2100]
### Operating System (OS/VERSION):

Debian 9.13

### VestaCP Version:

Version: 1.0.0 (Amd64) Release: 2

### Installed Software (what you got with the installer):

vesta(Core Package)
vesta-php(Php Interpreter)
vesta-nginx(Internal Web Server)
vesta-ioncube(Php Encoder)
vesta-softaculous(App Installer)

### Bug?/Problem:

Problem with mobile version... Nothing no clickable... 
![07](https://user-images.githubusercontent.com/11683786/139587727-dd5e56b4-474c-431a-a55c-c122cb5487fa.jpg)

**Comment by ezequielbenito** [comment]
same here, waiting for fix

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Responsive](https://trello.com/c/SVJlENOR/68-responsive)
