### ISSUE TITLE
Rollback vestacp from backup after last update =)

### ISSUE THREAD

**Issue by skorpions2000** [serghey-rodin/vesta#2101]
### Operating System (OS/VERSION):

Debian 9.13

### VestaCP Version:

Version: 1.0.0 (Amd64) Release: 2

### Installed Software (what you got with the installer):

vesta(Core Package)
vesta-php(Php Interpreter)
vesta-nginx(Internal Web Server)
vesta-ioncube(Php Encoder)
vesta-softaculous(App Installer)

### Bug solved with rollback?/Problem solved rollback?:
We have problem with DNS cluster, it no work on latest version vestacp, after last update. We have backup our servers and we do rollback because have problem with this function... 
If you have like this problem, you can do this at one's own risk.

1. Get your backup folder before update /usr/local/vesta/
2. Do command: service vesta stop
3. Delete in /usr/local/vesta/ all but except -/usr/local/vesta/conf and -/usr/local/vesta/data
4. Copy from backup all folder but except -/usr/local/vesta/conf and -/usr/local/vesta/data
5. And start service: service vesta start.
6. Turn off auto update =)

It's ok for rollback?

**Comment by skorpions2000** [comment]
And after rollback files we have new packages installed...
![10](https://user-images.githubusercontent.com/11683786/139593386-d31a592d-4b89-4d5e-98ce-851097be7ad0.jpg)

If you have old packages, you can rollback them...
You can do this at one's own risk!
dpkg -i /var/cache/apt/archives/vesta_0.9.8-26_amd64.deb
dpkg -i /var/cache/apt/archives/vesta-php_0.9.8-26_amd64.deb 
dpkg -i /var/cache/apt/archives/vesta-nginx_0.9.8-26_amd64.deb 
dpkg -i /var/cache/apt/archives/vesta-ioncube_0.9.8-26_amd64.deb 
dpkg -i /var/cache/apt/archives/vesta-softaculous_0.9.8-26_amd64.deb
After this we have:
![11](https://user-images.githubusercontent.com/11683786/139593412-0065d22e-c99a-4e08-97dc-fef7bef59e72.jpg)

**Comment by msaad2110** [comment]
Seems like everything is broken.

@skorpions2000 not working for me.

**Comment by skorpions2000** [comment]
We have old packages, and what we doing...?

1. Backup!
2. do command:
   - dpkg -i /var/cache/apt/archives/vesta_0.9.8-26_amd64.deb
   - dpkg -i /var/cache/apt/archives/vesta-php_0.9.8-26_amd64.deb
   - dpkg -i /var/cache/apt/archives/vesta-nginx_0.9.8-26_amd64.deb
   - dpkg -i /var/cache/apt/archives/vesta-ioncube_0.9.8-26_amd64.deb
   - dpkg -i /var/cache/apt/archives/vesta-softaculous_0.9.8-26_amd64.deb
3. service vesta restart
And after we have previous version.
For many our servers it works. On all our servers...
If you have like this problem, you can do this at one's own risk!

**Comment by ScIT-Raphael** [comment]
> We have old packages, and what we doing...?
> 
> 1. Backup!
> 2. do command:
>    
>    * dpkg -i /var/cache/apt/archives/vesta_0.9.8-26_amd64.deb
>    * dpkg -i /var/cache/apt/archives/vesta-php_0.9.8-26_amd64.deb
>    * dpkg -i /var/cache/apt/archives/vesta-nginx_0.9.8-26_amd64.deb
>    * dpkg -i /var/cache/apt/archives/vesta-ioncube_0.9.8-26_amd64.deb
>    * dpkg -i /var/cache/apt/archives/vesta-softaculous_0.9.8-26_amd64.deb
> 3. service vesta restart
>    And after we have previous version.
>    For many our servers it works. On all our servers...
>    If you have like this problem, you can do this at one's own risk!

Don't forget to disable the auto update...

**Comment by msaad2110** [comment]
I don't have old packages on my server help would be appreciated if someone can share them here

**Comment by grvweb** [comment]
> I don't have old packages on my server help would be appreciated if someone can share them here

After a lot of research I found old packages here 
http://mirror.nullivex.com/vestacp/stretch/pool/vesta/v/
I don't know how safe it was.
If anyone succeeds, please reply.

**Comment by Volodya1234** [comment]
> > I don't have old packages on my server help would be appreciated if someone can share them here
> 
> After a lot of research I found old packages here http://mirror.nullivex.com/vestacp/stretch/pool/vesta/v/ I don't know how safe it was. If anyone succeeds, please reply.

On one of the servers, I had a bunch of previous versions of Vesta for Debian.

http://vm.abcd.tools/vesta/
