### ISSUE TITLE
Cannot add database to domain. Prefix admin_ For All domain. I wish you had tested it first there are bugs everywhere and my system is updated!!!

### ISSUE THREAD

**Issue by AyhanDelican** [serghey-rodin/vesta#2104]
### Operating System (OS/VERSION):

Type here, e.g. Debian

### VestaCP Version:

Type here, e.g. 3.14159

### Installed Software (what you got with the installer):

Type here, e.g. php-fpm, apache, nginx, mysql

### Steps to Reproduce:

Type here, e.g. install vesta and type rm -rf / --no-preserve-root

### Related Issues/Forum Threads:

Found anything that might be related to this? It might help us find the cause.

### Other Notes:

Anything else?

**Comment by anton-reutov** [comment]
Bug is registered

**Comment by byjameson** [comment]
Ayhan test ettik ama yine de buglar olabilir normal bir durum

**Comment by AyhanDelican** [comment]
> 
> 
> Ayhan test ettik ama yine de buglar olabilir normal bir durum

Şu ortamda tanıdık bir lisan görmek mutlu etti.
Üstadım yorumum biraz sert kaçmış olabilir kusuruma bakma lütfen ama inan nasıl ve neyi test ettiğinizi anlamadım.

e-posta eklenemiyor
ssl (let's encrypt) çalışmıyor. Aynı anda; Aliases alanını boşaltıyor.
Herhangi bir etki alanına veritabanı eklemek istediğimde, ön ad olarak; admin_ i default getiriyor (kullanıcı adını getirmiyor)

Bu arada kolay gelsin tekrar.

**Comment by ScIT-Raphael** [comment]
@AyhanDelican @byjameson maybe you want to stick on english, this makes it easier to follow the communication. But yes, personaly I also think that there was not much testing for that release.

**Comment by anton-reutov** [comment]
Fixed. waiting release
