### ISSUE TITLE
DNS Cluster no give answer if in zona has SUSPENDED record on slave server...

### ISSUE THREAD

**Issue by skorpions2000** [serghey-rodin/vesta#2105]
### Operating System (OS/VERSION):

Debian 9.13

### VestaCP Version:

Version: 0.9.8 (amd64) | Release:26

### Installed Software (what you got with the installer):

vesta(Core Package)
vesta-php(Php Interpreter)
vesta-nginx(Internal Web Server)
vesta-ioncube(Php Encoder)
vesta-softaculous(App Installer)

### Bug?/Problem:

DNS Cluster no give answer if in zona has SUSPENDED record on slave server...
If there is at least one entry in the zone that is paused, then the entire zone will not respond. 
I don't know if this is fixed in version 1

**Comment by anton-reutov** [comment]
We will check and fix it. Thank you

**Comment by anton-reutov** [comment]
What OS on your servers slave-master

**Comment by skorpions2000** [comment]
> What OS on your servers slave-master

Debian 9.13 on all servers

**Comment by anton-reutov** [comment]
Thank you

**Comment by Lucksmith369** [comment]
is an error in remote.sh there is the old api
guys last realeased killed all vestacp users  ^^
please revert it and set this version to beta state.
next problem with dns cluster is the react script there is an map and if you only have one more server that crash the react app.
