### ISSUE TITLE
HTTPS issue. Redirrect different website.

### ISSUE THREAD

**Issue by byjameson** [serghey-rodin/vesta#2106]
### Operating System (OS/VERSION):

CENTOS 7

### VestaCP Version:

NEW VERRSIION UPDATED IT ATUOMATICALLY
### Installed Software (what you got with the installer):
php-fpm, apache, nginx, mysql

My problem is i have 2 different websites as you can see
http://www.tahminimce.net
https://www.thebettipster.com
if you write tahminimce with https
https://www.tahminimce.net redirect to https://www.thebettipster.com

This bug exists in the old version, now it is in the new version too

**Comment by byjameson** [comment]
I made ssl in thebettipster with letsencrypte on vesta panel.

**Comment by anthonyrossbach** [comment]
Both sites should use HTTPS but if you don't want to do that you can make a default config file for Nginx that responds to failed queries locked to the IP.

For example a config in the dir `/etc/nginx/conf.d/example.conf`

```

server {
  listen IPHERE:80 default_server;
  listen IPHERE:443 ssl default_server;
  server_name _;
  ssl_certificate /usr/local/vesta/ssl/certificate.crt;
  ssl_certificate_key /usr/local/vesta/ssl/certificate.key;
  ssl_session_tickets off;
  return 200 "<!DOCTYPE html><html lang='en'><head><title>Working on it</title><meta charset='utf-8'><meta name='viewport' content='width=device-width'><style>html,body{ background:#ffffff;font-weight: 600; } .brand{ background: rgb(var(--subColor));color: rgb(var(--logoColor));position: fixed;bottom: 10px;left: 10px;font-weight: 600;font-size: 14px;border-radius: 9px;padding: 20px;padding-top: 10px;padding-bottom: 10px; } .floatbox{ background: rgb(var(--subColor));color: rgb(85,85,85);margin:0px auto;text-align:center;max-width:580px;padding:10px;margin-top:20vh;border-radius:9px; } .floatbox.sub{ margin-top:20px;margin-bottom:40px; } h1{ color:rgb(var(--logoColor)); }</style></head><body><div class='floatbox'><h1>Still working on it</h1><p>Sorry we don't have a website to show you just yet. We are still setting it up. If the website owner is seeing this you might need to enable TLS for the domain.</p></div></body>";
  add_header Content-Type text/html;
  default_type text/html;
}
```

**Comment by anthonyrossbach** [comment]
It will need to have a certificate provided though, as it must return a valid certificate of some kind. Even if for a different site aka why a random site loads, it loads the next site with a 443 port ready to go.

**Comment by byjameson** [comment]
okey i understand as you said that this is not a bug. this is work type.

**Comment by anthonyrossbach** [comment]
It's kinda a bug as the default rule should be made, but this rule would not work if the root site does not have a cert also, and a default install would not have that.

Problem is you can't return a site over 443 without a valid certificate (can be self signed). So it needs to send the browser something, the best option is to make a cert for the domain in question.

Second option is too use Cloudflare for it and have it do the redirect on the Cloudflare edge before it even hits the server.
