### ISSUE TITLE
Why Apache

### ISSUE THREAD

**Issue by sinanisler** [serghey-rodin/vesta#211]
Helloo,

Why vesta installing apache to ? isnt nginx is enough for dealing all hosts and dns requests ?

Is there a way to install only nginx for hosting websites ?

** I 'm fearing for balancing issues I have big website daily 25k I'm thinking to install vesta :/
4gb - 2 core + ssd.

**Comment by skurudo** [comment]
Advanced Install Settings solved this problem.
You can have nginx+apache or nginx+php-fpm configuration when you instal CP.

**Comment by jodumont** [comment]
if I may;

most of software are developed based on **.htaccess** rules which are well interpreted by apache.
by using nginx, you may have to translate them into your nginx config file
this is why vestacp propose [different templates](https://github.com/serghey-rodin/vesta/tree/master/install/debian/9/templates/web/nginx/php-fpm) when you install nginx+php-fpm
