### ISSUE TITLE
Graphs /list/rrd/ - no image VestaCP Version: 1.0.0-2

### ISSUE THREAD

**Issue by dddmmm5** [serghey-rodin/vesta#2110]
### Operating System (OS/VERSION):

Type here, e.g. Ubuntu 16.04      (X86_64)

VestaCP Version: 1.0.0-2

![image](https://user-images.githubusercontent.com/40426709/139602994-25047c1b-ccfc-45e9-9211-e695a91ba8e2.png)

**Comment by gregoriopellegrino** [comment]
For me it is ok on 1.0.0-4

**Comment by anton-reutov** [comment]
**ddmmm5**, Have you solved this problem?
