### ISSUE TITLE
Updated to 1.0.0-2 although auto-update has been disabled.

### ISSUE THREAD

**Issue by dddmmm5** [serghey-rodin/vesta#2113]
### Operating System (OS/VERSION):

Type here, e.g. Ubuntu 16.04(x86_64)

### VestaCP Version:

Type here, e.g. 1.0.0-2

Tell me how to disable auto-updates?

![image](https://user-images.githubusercontent.com/40426709/139603744-6050bfa8-d991-4e79-9cb9-3e7f6b7e571a.png)

**Comment by PecceG2** [comment]
Same case here. I woke up with this news in my hosting panel ...

**Comment by serghey-rodin** [comment]
It seems like updates were installed by apt itself. This option is defined  in /etc/apt/apt.conf.d/20auto-upgrades
For more information please check https://help.ubuntu.com/community/AutomaticSecurityUpdates
@PecceG2 @dddmmm5  we've fixed a couple of serious bugs in 1.0.0-4 and preparing a new release next Monday
