### ISSUE TITLE
upgraded un ubuntu manually to 1.0.0-3 to fix SSL lets encrypt but www alias still not working

### ISSUE THREAD

**Issue by tccadam** [serghey-rodin/vesta#2114]
### Operating System (OS/VERSION):

Ubuntu 16.04

### VestaCP Version:

1.0.0-3

------------------------------------

I see there are lots of people affected by the auto update to version 1.0.0, and I see you are activly working of fixing the issues, so I ran apt-get update  and then apt-get upgrade and let everything upgrade, then I ran /etc/init.d/vesta restart

Ran: /usr/local/vesta/bin/v-list-sys-vesta-updates
Which now shows me:
PKG                VER    REL  ARCH   UPDT  DATE
---                ---    ---  ----   ----  ----
vesta              1.0.0  3    amd64  yes   2021-10-31
vesta-php          1.0.0  1    amd64  yes   2021-10-31
vesta-nginx        1.0.0  1    amd64  yes   2021-10-31
vesta-ioncube      1.0.0  1    amd64  yes   2021-10-31
vesta-softaculous  1.0.0  1    amd64  yes   2021-10-31

in the GUI I was then able to turn on SSL for a domain and it did work, it got the certificate from lets encrypt and the website loaded and the proxy template says force-https so those 2 things are fixed, THANKS!

but for some reason the www alias disappears, and when I try to manually type it in I get this message, see screenshot:
also, the date is off by a day but my server has the correct date and time.

![image](https://user-images.githubusercontent.com/64762525/139604954-5e0eaa7f-58e8-4b8c-b1b0-a5dc118a9365.png)

**Comment by OptionExplicit** [comment]
Thanks man. This fixed the issue on my end as well. Will Vesta 1.0.0-3 also automatically be set to all other servers as they did with the broken Vesta 1.0.0 ?

**Comment by anton-reutov** [comment]
No, you can update your servers in the update section (choose all packages and run update in the select
or via cli command
`v-update-sys-vesta-all`

**Comment by anton-reutov** [comment]
Can we close this ticket ?

**Comment by tccadam** [comment]
I think you fixed the alias issue in 1.0.0-4 so sure, i'm closing it. thanks.
