### ISSUE TITLE
list/server css style error - show inactive service as active

### ISSUE THREAD

**Issue by medsaif95** [serghey-rodin/vesta#2116]
### Operating System (OS/VERSION):

Ubuntu 18.04      (x86_64)

### VestaCP Version:

1.0.0.3

### Installed Software (what you got with the installer):

php7,apache, nginx, mysql,scf 

in list/server/ page the page show the running  service & inactive services with same CSS style 
no more gray  color in the disabled / stooped services

**Comment by ezequielbenito** [comment]
same here

**Comment by anton-reutov** [comment]
Will be fixed in the next hot fix release
