### ISSUE TITLE
Vesta 1.0.0 after updated File manager is not working 

### ISSUE THREAD

**Issue by nayanivijay26** [serghey-rodin/vesta#2117]
### Operating System (OS/VERSION):

CentOS 7(64 Bit)

### VestaCP Version:

1.0.0

### Installed Software (what you got with the installer):

php-fpm, apache, nginx, mysql, FTP

### Related Issues/Forum Threads:

Vesta after updated File manager is not working, UPLOADING, DOWNLOADING and Not able extract archived file.

### Other Notes:

Give me solution on this.

**Comment by anton-reutov** [comment]
Hi,
try to update vesta
`v-update-sys-vesta-all`

**Comment by ezequielbenito** [comment]
Same here, file manager not working. on Version: 1.0.0 (amd64) Release: 2

**Comment by anton-reutov** [comment]
> 
> 
> Same here, file manager upload/download, not working. on Version: 1.0.0 (amd64) Release: 2

try to update vestacp
v-update-sys-vesta-all
