### ISSUE TITLE
Blank main configuration page

### ISSUE THREAD

**Issue by tcjn** [serghey-rodin/vesta#2118]
### Operating System (OS/VERSION):

CentOS Linux release 7.8.2003 (Core)

### VestaCP Version:

[root@s0 bin]# /usr/local/vesta/bin/v-list-sys-vesta-updates
PKG          VER    REL  ARCH    UPDT  DATE
---          ---    ---  ----    ----  ----
vesta        1.0.0  1    x86_64  yes   2021-10-30
vesta-php    1.0.0  1    x86_64  yes   2021-11-01
vesta-nginx  1.0.0  1    x86_64  yes   2021-11-01

### Installed Software (what you got with the installer):

php-fpm, apache, nginx, mysql

### Steps to Reproduce:

AutoUpgrade to recent version

### Other Notes:

After update I am no longer able to edit main configuration of my VestaCP interface. All I can see is a blank page and nginx-error.log show such log:
2021/11/01 10:24:26 [error] 9833#0: *11 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/local/vesta/web/api/v1/login/index.php on line 129
PHP message: PHP Notice:  Undefined variable: error in /usr/local/vesta/web/api/v1/login/index.php on line 167" while reading response header from upstream, client: xx, server: _, request: "GET /api/v1/login/index.php?token=a64a56f947428a309a592f024f522dcc HTTP/1.1", upstream: "fastcgi://unix:/var/run/vesta-php.sock:", host: "myvesta.org:8083", referrer: "https://myvesta.org:8083/edit/server/"

I was trying to clean up session folder - no success. Any hint to solve this?

**Comment by anton-reutov** [comment]
Try to update your vestacp
`v-update-sys-vesta-all`

**Comment by tcjn** [comment]
> Try to update your vestacp `v-update-sys-vesta-all`

I can confirm that after update to REL 3 issue is resolved:
[root@s0 var]# /usr/local/vesta/bin/v-list-sys-vesta-updates
PKG          VER    REL  ARCH    UPDT  DATE
---          ---    ---  ----    ----  ----
vesta        1.0.0  3    x86_64  yes   2021-11-01
vesta-php    1.0.0  1    x86_64  yes   2021-11-01
vesta-nginx  1.0.0  1    x86_64  yes   2021-11-01
[root@s0 var]#

Looks like whole story was related to this issue - https://github.com/serghey-rodin/vesta/commit/1738423829323db4d382278027a5aa7d2361c72a ;-) 
Thanks.
