### ISSUE TITLE
Cannot save FTP accounts

### ISSUE THREAD

**Issue by gregoriopellegrino** [serghey-rodin/vesta#2119]
### Operating System (OS/VERSION):

Centos 7

### VestaCP Version:

1.0.0-1

### Installed Software (what you got with the installer):

php-fpm, nginx, mariadb

### Steps to Reproduce:

- Go to Web tab > edit a domain > click on Add one more FTP Account
- Fill in user and password
- Click Save

The page reloads with no FTP user added. Trying to login it via FTP it doesn't work.

**Comment by anton-reutov** [comment]
Try to update vestacp
`v-update-sys-vesta-all`

**Comment by gregoriopellegrino** [comment]
I get

```
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
```

**Comment by anton-reutov** [comment]
Correct v-update-sys-vesta
https://raw.githubusercontent.com/serghey-rodin/vesta/master/bin/v-update-sys-vesta

**Comment by gregoriopellegrino** [comment]
Done and updated, but now I get `ERR_CONNECTION_REFUSED` when trying to access port 8083

**Comment by anton-reutov** [comment]
send me acceess to yiur server. we will check whats problem
info@vestacp.com

**Comment by gregoriopellegrino** [comment]
Vesta service was stopped. Restarted using: `service vesta start`. Now I'm in.

But still cannot save new FTP user.

**Comment by anton-reutov** [comment]
What errors are you get ?

**Comment by gregoriopellegrino** [comment]
No errors, but the FTP account is not saved.

https://user-images.githubusercontent.com/5065125/139693536-827338e6-1681-4242-b61a-a3f5b76e9d87.mov

**Comment by anton-reutov** [comment]
video is not working

**Comment by gregoriopellegrino** [comment]
Here you have as gif

![no-ftp-account](https://user-images.githubusercontent.com/5065125/139694438-dc2fb711-73ad-4dfe-81b2-dac1ade4dfd3.gif)

**Comment by anton-reutov** [comment]
Thank you. This bug already registered. We are working under fix

**Comment by centrus** [comment]
My VestaCP production sever was automaticly updated to version 1.0 and the option for FTP backup disappeared.
I was digging trough the source code and found variable backup_adv whitch is returning null from ajax request even if i found that $v_backup_adv is set to "yes" everywhere....

**Comment by anton-reutov** [comment]
> 
> 
> My VestaCP production sever was automaticly updated to version 1.0 and the option for FTP backup disappeared. I was digging trough the source code and found variable backup_adv whitch is returning null from ajax request even if i found that $v_backup_adv is set to "yes" everywhere....

I will check it

**Comment by anton-reutov** [comment]
What vesta core version on your server?

**Comment by centrus** [comment]
my bad it is backup_remote_adv  i saw that response backup_remote_adv is set to $v_backup_remote_adv, and i thint that $v_backup_remote_adv should be initialized when user first open settings menu.

**Comment by centrus** [comment]
> my bad it is backup_remote_adv i saw that response backup_remote_adv is set to $v_backup_remote_adv, and i thint that $v_backup_remote_adv should be initialized when user first open settings menu.

I added $v_backup_remote_adv to="yes"; to web/api/v1/edit/server/index.php in // List backup settings  and it worked

**Comment by centrus** [comment]
> What vesta core version on your server?


vesta
Core Package
Version:
1.0.0 (Amd64)
Release:
3

UPDATED
vesta-php
Php Interpreter
Version:
1.0.0 (Amd64)
Release:
1

UPDATED
vesta-nginx
Internal Web Server
Version:
1.0.0 (Amd64)
Release:
1

**Comment by anton-reutov** [comment]
Thank you. Will be fixed

**Comment by ezequielbenito** [comment]
same here, we need urgent fix!

**Comment by anton-reutov** [comment]
try to update vestacp to 1.0.0.4

**Comment by gregoriopellegrino** [comment]
thanks, it works, this issue can be closed

**Comment by anton-reutov** [comment]
As per your request, we are closing this ticket

**Comment by wojsmol** [comment]
@anton-reutov  Remote backups are still broken on Vestacp 1.0.0-4.

**Comment by anton-reutov** [comment]
> 
> 
> @anton-reutov Remote backups are still broken on Vestacp 1.0.0-4.

How we can reproduce this? I'm tryed set up ftp backups on a fresh server and it 's working

**Comment by wojsmol** [comment]
On autro-updated server in `port/edit/server/` in backup section I see only local backup settings and no remote backup settings. Additionally on refined remote backup server I don't have backups from November.

**Comment by anton-reutov** [comment]
wojsmol, will be fixed in the next hot fix release, most of bugs already fixed and waiting release

**Comment by wojsmol** [comment]
@anton-reutov When next hotfix will be released?

**Comment by anton-reutov** [comment]
After few days
