### ISSUE TITLE
utf8mb4 charset not found

### ISSUE THREAD

**Issue by domikuss** [serghey-rodin/vesta#2120]
### Operating System (OS/VERSION):

Ubuntu 18.04

### VestaCP Version:

1.0.0-3

### Installed Software (what you got with the installer):

PHP, apache, nginx, mysql

### Steps to Reproduce:

1. Go to Web tab > DB > click on Add database
2. Choose Charset
3. utf8mb4 not found
### Other Notes:

https://github.com/serghey-rodin/vesta/pull/1702
Now it is not listed in the React UI. Only in PHP

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [utf8mb4 charset not found #2120](https://trello.com/c/QMLUT76o/169-utf8mb4-charset-not-found-2120)

**Comment by domikuss** [comment]
🤔
