### ISSUE TITLE
обновление VestaCP 1.0.0 (X86_64) Релиз: 3

### ISSUE THREAD

**Issue by Dmitrykzw** [serghey-rodin/vesta#2121]
Чекбокс Поддержка Lets Encrypt на действующем сайте не активен
![4W6eMAH](https://user-images.githubusercontent.com/93530303/139681929-b69964f5-8158-4a5b-90c9-6cf88061724b.png)

**Comment by Dmitrykzw** [comment]
также в логах показывается только одна строка

**Comment by anton-reutov** [comment]
Уже работаем над фиксами

**Comment by ykpon** [comment]
> Уже работаем над фиксами

Вы можете просто откатить билд обратно в мастере с новой версией, чтобы мы могли обновиться до прежней нормально работающей версии, а новые обновления выкатывать в дев ветку? Я не против сам потестить, но не на рабочем сервере.

**Comment by ezequielbenito** [comment]
Это уже исправлено?

**Comment by anton-reutov** [comment]
да
