### ISSUE TITLE
Обновление

### ISSUE THREAD

**Issue by phatrudinov** [serghey-rodin/vesta#2122]
CentOS 7.8.2003
vesta core package Version: 1.0.0 (x86_64)
Release: 1

Пытаюсь обновиться до версии релиза 3 
v-update-sys-vesta-all

[root@localhost ~]# v-update-sys-vesta-all
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
[root@localhost ~]#

**Comment by anton-reutov** [comment]
https://github.com/serghey-rodin/vesta/issues/2119#issuecomment-956253904

**Comment by l0stmagic** [comment]
Так же

**Comment by anton-reutov** [comment]
Обноовите файл v-update-sys-vesta
по ссылке

**Comment by phatrudinov** [comment]
Спасибо. Решилось!
