### ISSUE TITLE
nginx restart failed

### ISSUE THREAD

**Issue by Repazol** [serghey-rodin/vesta#2124]
### Operating System (OS/VERSION):
Linux version 3.13.0-132-generic (buildd@lcy01-02) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #181-Ubuntu SMP Wed Sep 13 13:25:39 UTC 2017

### VestaCP Version:
1.0.0 (i386)

sudo ./v-add-letsencrypt-domain admin leads.it-scs.net

Error: nginx restart failed
Error: Let's Encrypt validation status 400

**Comment by anton-reutov** [comment]
Try to update vestacp
v-update-sys-vesta-all

and check that the proxy support for all domains is enabled

**Comment by Repazol** [comment]
![изображение](https://user-images.githubusercontent.com/11893021/139728018-03d405ec-7462-406d-83b2-2f640e5379b1.png)

hmm... but ssl working

![изображение](https://user-images.githubusercontent.com/11893021/139728180-2559883b-469b-4b33-a0d0-35daae5475eb.png)

**Comment by anton-reutov** [comment]
run this command and send me output
`systemctl status nginx.service`

**Comment by Repazol** [comment]
![изображение](https://user-images.githubusercontent.com/11893021/139735403-1d005958-b4a1-4732-9763-0d7aef8762fe.png)

**Comment by Repazol** [comment]
Failed to issue method call: No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/systemd1/unit/nginx_2eservice
a

**Comment by anton-reutov** [comment]
Can you provide access to your server? We will check what happened.
Send to info@vestacp.com

**Comment by Repazol** [comment]
send on mail
