### ISSUE TITLE
A bike inside vesta package

### ISSUE THREAD

**Issue by AntonKirilov** [serghey-rodin/vesta#2131]
### Operating System (OS/VERSION):

Debian 9

### VestaCP Version:

Vesta 1.0.4

### Issue:

11 megabytes of an bike

![image](https://user-images.githubusercontent.com/65451492/139840506-99f2abfe-30c1-42e1-bb5e-1c8dca7ba041.png)

![image](https://user-images.githubusercontent.com/65451492/139840741-52ac9569-49b5-41ee-865d-2deb611dcb27.png)

**Comment by anton-reutov** [comment]
I ask to our developers about this :))

**Comment by Pleskan** [comment]
> ### Operating System (OS/VERSION):
> 
> Debian 9
> ### VestaCP Version:
> 
> Vesta 1.0.4
> ### Issue:
> 
> 11 megabytes of an bike
> 
> ![image](https://user-images.githubusercontent.com/65451492/139840506-99f2abfe-30c1-42e1-bb5e-1c8dca7ba041.png)
> 
> ![image](https://user-images.githubusercontent.com/65451492/139840741-52ac9569-49b5-41ee-865d-2deb611dcb27.png)

Hmm... the wheels are round not square that's innovation, indeed :-)

**Comment by anton-reutov** [comment]
Will be deleted :))
