### ISSUE TITLE
Add new FTP User (Error)

### ISSUE THREAD

**Issue by detroism** [serghey-rodin/vesta#2133]
### Operating System (OS/VERSION):

Ubuntu 18.04

### VestaCP Version:

Версия:
1.0.0 (Amd64)

### Other Notes:

https://prnt.sc/1y67bl6 - при попытке сохранить дополнительного юзера для фтп отображается такая ошибка (см скрин) и юзер соответственно не сохраняется

**Comment by anton-reutov** [comment]
Не отображается скрин.
Но я примерно понимаю о какой ошибке идет речь.
Попробуйте обновить панель до 1.0.0.4

**Comment by detroism** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/90238237/139870942-2ed8fafc-be59-4ab0-960f-9e71bd3d88b6.png)

А можете, пожалуйста, скинуть инструкцию как сделать обновление?

**Comment by detroism** [comment]
https://youtu.be/2kf0B4n3PwQ

При попытке обновить через веб интерфейс ничего не происходит (см. видео)

**Comment by anton-reutov** [comment]
core будет 3 или 4 ?

**Comment by detroism** [comment]
Страницу обновлял, но после этого ничего не происходит. Про Core, сорри не совсем понял вопрос. Попробую всё таки через консоль обновится, хоть и не силён в этом

**Comment by anton-reutov** [comment]
Vesta Core package в разделе Updates
3 или 4

**Comment by detroism** [comment]
![image](https://user-images.githubusercontent.com/90238237/139929891-78d03a47-2830-4aa9-bab1-6d12739d2e88.png)

**Comment by anton-reutov** [comment]
Обновите через ssh
v-update-sys-vesta-all
или предоставьте доступ к серверу на info@vestacp.com обновим

**Comment by detroism** [comment]
скинул на почту

**Comment by detroism** [comment]
Так мне поможет кто-то?

**Comment by anton-reutov** [comment]
Извините, сейчас посмотрю. Большая нагрузка на суппорт
