### ISSUE TITLE
Problem whit Search in mail Menu not show result

### ISSUE THREAD

**Issue by danterob** [serghey-rodin/vesta#2134]
### Operating System (OS/VERSION):

Debian 9.13

### VestaCP Version:

vesta        1.0.0  4    amd64  yes   2021-11-01
vesta-php    1.0.0  1    amd64  yes   2021-10-31
vesta-nginx  1.0.0  1    amd64  yes   2021-10-31

### Installed Software:

MySQL 5.5.9999+default
PHP 7.3.28
php7.3-fpm 7.3.31-2
nginx 1.18.0-2

### Steps to Reproduce:

When I try to search in menu Mail or over List Accounts not show result, then active dev tools in browser and showing the next error when push button for search:

`Uncaught TypeError: e.changeSearchTerm is not a function
  handleSearchTerm Mails.jsx:408
  s SearchInput.jsx:11
  onSubmit SearchInput.jsx:27
  React 12
  unstable_runWithPriority scheduler.production.min.js:18
  React 10
  unstable_runWithPriority scheduler.production.min.js:18
  React 5`
![imagen](https://user-images.githubusercontent.com/5551411/139905332-d3f6d261-b597-4120-9068-5a9871760aa7.png)

But if search in other menu that not Mail, the search button not present problem and showing my search.

**Comment by anton-reutov** [comment]
Will be fixed. Thank you Roberto
