### ISSUE TITLE
Where is the external SSH backup option?

### ISSUE THREAD

**Issue by hollanddata** [serghey-rodin/vesta#2136]
### Operating System (OS/VERSION):

Type here, e.g. CentOS 7

### VestaCP Version:

Core Package Version: 1.0.0 (X86_64)

**Comment by anton-reutov** [comment]
v-add-backup-host
ftp/sftp

**Comment by hollanddata** [comment]
and at the controlpanel? It was Server / Configure / Backup / Exernal backup / FTP/SSH

**Comment by anton-reutov** [comment]
We will check that

**Comment by anton-reutov** [comment]
Fix will be in the next hot fix release
