### ISSUE TITLE
What is the current vestacp version ?

### ISSUE THREAD

**Issue by 512bit-zz** [serghey-rodin/vesta#2138]
What is the current vestacp version ?

Is it safe to update ? 

Is dns cluster working in the latest versions ?

What is still not working ?

I have heard people saying the latest vesta is not compatible with centos 6 ?

**Comment by youradds** [comment]
Our emails have buggered up with the latest update. I wish we'd had auto-updates turned off :( Now our catchalls are not working , and we can't send or receive  anything :/

**Comment by TechLS** [comment]
How about an about page? or some sort of System Status page that tells this in the control panel?

**Comment by youradds** [comment]
> 
> 
> How about an about page? or some sort of System Status page that tells this in the control panel?

To see your current version? You can see that in the CP as **admin > Updates**, and then you see something like:

![Uploading Screenshot 2021-11-03 at 15-03-18 Vesta - UPDATES.png…]()

**Comment by TechLS** [comment]
Going to sound weird. I haven't any problems with your updates. Keep up the good work.

**Comment by 512bit-zz** [comment]
I don't need to know what my version is.. i want to know what the current latest version is because there is no update changelog to show what is the current version...

Because of the first update my servers dont auto update because its broken. Before i fix the vesta update file i want to know what else is still broken :s

**Comment by youradds** [comment]
> 
> 
> I don't need to know what my version is.. i want to know what the current latest version is because there is no update changelog to show what is the current version...
> 
> Because of the first update my servers dont auto update because its broken. Before i fix the vesta update file i want to know what else is still broken :s


1.0.0.4 is the latest version. Our server got auto updated. Bit annoying, as its broken our emails :(  Otherwise, it seems to be working ok (we are using pretty limited features though on Ubuntu 18.04)

**Comment by lianglee** [comment]
How to find latest version github still showing 0.9.28.x

**Comment by youradds** [comment]
Or sure.i also can't see v1 on the repos. Only 0.9.28

**Comment by duddy2007** [comment]
i also want to know what the current latest version
i know only 1 method apt update then apt list --upgradable 
and search in the list of Vesta updates
but this is very inconvenient, you have to go into the console
if auto-update is disabled, why is there no information in the panel itself about which version is currently the latest

**Comment by anton-reutov** [comment]
last version 1.0.0.4

**Comment by duddy2007** [comment]
> last version 1.0.0.4
Антон, вопрос то звучит по другому, где можно посмотреть текущую актуальную версию Весты, а то что сейчас релиз 1.0.0.4 это и так понятно из обсуждений тут и на форуме. Вопрос где в панели это видно или на каком сайте это видно, информации нет вообще никакой, просто идут обновления одно за одним и все.

**Comment by neto737** [comment]
VestaCP version control is a really, really weird. There's no info about version on their website or even a release on GitHub, only tags without any further info (also sometimes tags are simply ignored).

**Comment by 512bit-zz** [comment]
I have not upgraded to 1.0.0.4 out of fear that critical things like DNS cluster is not working. Can anyone confirm if DNS cluster master/slave is working in 1.0.0.4 ?

@neto737 i believe the vestacp project was abandoned a while back and there are forks of it out there that are active.

**Comment by youradds** [comment]
> 
> 
> I have not upgraded to 1.0.0.4 out of fear that critical things like DNS cluster is not working. Can anyone confirm if DNS cluster master/slave is working in 1.0.0.4 ?
> 
> @neto737 i believe the vestacp project was abandoned a while back and there are forks of it out there that are active.

It's not been abandoned, as they just brought out 1.0.0.4 ;) But yes, there are quite a few bugs still in the new version (with DNS clusters being one of them)
