### ISSUE TITLE
Ubuntu 14.04: "-bash: ll: command not found" after installation

### ISSUE THREAD

**Issue by fengkaijia** [serghey-rodin/vesta#214]
Hello,

I'm using Ubuntu 14.04 and is logging in with root via SSH. After installed Vesta, the ```ll``` command missed (it worked before the installation), but ```ls -l``` still works. Might this be a problem with the installation?

**Comment by ravi22691** [comment]
Need Permanant Solution for it, as it was working while Ubuntu was installed.

**Comment by rapto** [comment]
.bashrc should do it. You may have to copy /etc/skel/* to your profile manually.
