### ISSUE TITLE
Logs are not shown

### ISSUE THREAD

**Issue by artscripts** [serghey-rodin/vesta#2141]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

Version:
1.0.0 (X86_64)
Release:4

### Installed Software (what you got with the installer):

php-fpm, nginx, mysql

### Other Notes:

Не показываются логи полностью при просмотре у домена через панель. Только одна ближайшая операция и все.
https://yadi.sk/i/Xdy-Z5284v9MUQ

**Comment by anton-reutov** [comment]
Исправлено. Фикс в ближайшем хот фикс релизе

**Comment by medsaif95** [comment]
The problem still exist in version 1.0.0.4
Ubuntu 18.04      (x86_64)

**Comment by anton-reutov** [comment]
Fix will be in 1.0.0.5 - 8 Nov

**Comment by phatrudinov** [comment]
> 
> 
> Fix will be in 1.0.0.5 - 8 Nov

Уже 9 ) Когда можно ждать фикс?

**Comment by ocsnetworks** [comment]
Issue still resides in CentOS 7 with VestaCP 1.0.0-5.
Even the template view is squashed.
[https://www.ocs-networks.com/apps/VestaCP/VestaCP-LogIssue.png](Image Example)
