### ISSUE TITLE
Vestacp Won't update 

### ISSUE THREAD

**Issue by medsaif95** [serghey-rodin/vesta#2142]
### Operating System (OS/VERSION):
CentOS 7

### VestaCP Version:

1.0.0.1

### Installed Software (what you got with the installer):
php, apache, nginx, mysql

when try to update my vesta by cron server send mail for me  , if by manual nothing happen 

Cron <admin@ns1> sudo /usr/local/vesta/bin/v-update-sys-vesta-all

/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '

**Comment by phatrudinov** [comment]
https://github.com/serghey-rodin/vesta/issues/2119#issuecomment-956253904
