### ISSUE TITLE
SSL Support doesn't work since v1.0 update

### ISSUE THREAD

**Issue by kristijansoldo** [serghey-rodin/vesta#2143]
### Operating System (OS/VERSION):

Debian 9.8      (X86_64)

### VestaCP Version:
v1.0

### Steps to Reproduce:

Cannot generate SSL when creating or editing web.

**Comment by anton-reutov** [comment]
try update vesta to 1.0.0.4

**Comment by kristijansoldo** [comment]
How? I can't update through vestacp admin interface.

**Comment by anton-reutov** [comment]
via ssh
`v-update-sys-vesta-all`

**Comment by youradds** [comment]
Works fine on 1.0.0.4 for me.

**Comment by kristijansoldo** [comment]
![image](https://user-images.githubusercontent.com/15091958/140706251-34dfe6ee-fba3-4692-827d-bcb9eea59456.png)

Cannot update.

**Comment by youradds** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/15091958/140706251-34dfe6ee-fba3-4692-827d-bcb9eea59456.png)
> 
> Cannot update.

You need to update `v-update-sys-vesta`:

https://github.com/serghey-rodin/vesta/issues/2119

New code can be found here:

https://raw.githubusercontent.com/serghey-rodin/vesta/master/bin/v-update-sys-vesta

Hope that helps :)

**Comment by kristijansoldo** [comment]
![image](https://user-images.githubusercontent.com/15091958/140720655-4792457d-8efe-4033-8950-2f5eb3c445fd.png)
I've updated and triggered the script and nothing happened. 

1. Update
![image](https://user-images.githubusercontent.com/15091958/140720728-f1eb551b-3b0d-4d16-8a41-f791addfc094.png)

2. Same verson
![image](https://user-images.githubusercontent.com/15091958/140720833-99ec8da9-0f5e-467c-9deb-df2bac9c5cc9.png)

**Comment by youradds** [comment]
You are on 1.0.0.4 now , which is the latest :)

**Comment by kristijansoldo** [comment]
Works now, thx.
