### ISSUE TITLE
Error with domains where SSL is already enabled.

### ISSUE THREAD

**Issue by Magnanimousthefirst** [serghey-rodin/vesta#2149]
### Operating System (OS/VERSION):
Ubuntu 18.04.6 LTS

### VestaCP Version:
Vesta Core 1.0.0 R4
Vesta PHP 1.0.0 R1
Vesta-Nginx 1.0.0 R1

Clicking on Web Domain Edit results in a full blank screen, but only for domains that already have SSL enabled.

Nginx-error.log show error:
2021/11/08 09:05:44 [error] 26208#0: *6 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/local/vesta/web/api/v1/login/index.php on line 129
PHP message: PHP Notice:  Undefined variable: error in /usr/local/vesta/web/api/v1/login/index.php on line 167" while reading response header from upstream, client: myip, server: _, request: "GET /api/v1/login/index.php?token=cd40b204dbb257ac5e19bcff229fc104 HTTP/1.1", upstream: "fastcgi://unix:/var/run/vesta-php.sock:", host: "myserver:8083", referrer: "https://myserver:8083/edit/web/"

If I manually edit web.conf and set the SSL tag to 'No' , the edit page displays correctly, however as soon as I tick the enable SSL box again, the page immediately goes blank again.  No need to even click on save.

Enabling and disabling proxy manually has no effect.

This error is new and only came up when the new version popped up.

Looking forward to some assistance.
Thanks,
James

**Comment by ezequielbenito** [comment]
Checked this and for me, it's working on Ubuntu 16.04 with Firefox.

**Comment by anton-reutov** [comment]
Are you sure that your version is 1.0.0.4 ?
send me result of this command
v-list-sys-vesta-updates

**Comment by Magnanimousthefirst** [comment]
Hi,

Thanks for coming back to me.

PKG          VER    REL  ARCH   UPDT  DATE
---          ---    ---  ----   ----  ----
vesta        1.0.0  4    amd64  yes   2021-11-04
vesta-php    1.0.0  1    amd64  yes   2021-10-31
vesta-nginx  1.0.0  1    amd64  yes   2021-10-31

Regards,
James

**Comment by anton-reutov** [comment]
can't reproduce this

**Comment by Magnanimousthefirst** [comment]
I get the following error message in the browser under dev tools.  Does this perhaps help narrow down the issue?

react-dom.production.min.js:193 TypeError: Cannot read properties of null (reading 'length')
    at Ba (main.0b1695fb.chunk.js:1)
    at Zo (2.01285f6b.chunk.js:2)
    at js (2.01285f6b.chunk.js:2)
    at tl (2.01285f6b.chunk.js:2)
    at Zs (2.01285f6b.chunk.js:2)
    at Hs (2.01285f6b.chunk.js:2)
    at 2.01285f6b.chunk.js:2
    at t.unstable_runWithPriority (2.01285f6b.chunk.js:2)
    at Ii (2.01285f6b.chunk.js:2)
    at zi (2.01285f6b.chunk.js:2)
Ya @ react-dom.production.min.js:193
EditWeb.jsx:76 TypeError: Cannot read properties of null (reading 'length')
    at Ba (main.0b1695fb.chunk.js:1)
    at Zo (2.01285f6b.chunk.js:2)
    at js (2.01285f6b.chunk.js:2)
    at tl (2.01285f6b.chunk.js:2)
    at Zs (2.01285f6b.chunk.js:2)
    at Hs (2.01285f6b.chunk.js:2)
    at 2.01285f6b.chunk.js:2
    at t.unstable_runWithPriority (2.01285f6b.chunk.js:2)
    at Ii (2.01285f6b.chunk.js:2)
    at zi (2.01285f6b.chunk.js:2)
(anonymous) @ EditWeb.jsx:76
manifest.json:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by Magnanimousthefirst** [comment]
If I delete the web domain and manually remove any configs related to the domain and re-create the domain the problem is then resolved.  Going to close this issue with that work around.

Thx.
