### ISSUE TITLE
Ubuntu 14.04: Have to manually restart MySQL to make it work

### ISSUE THREAD

**Issue by fengkaijia** [serghey-rodin/vesta#215]
MySQL, installed by Vesta, started but with the following error in `/var/log/mysql/error.log`after the system was booted:

```
140914 15:57:13  InnoDB: Unable to open the first data file
InnoDB: Error in opening ./ibdata1
140914 15:57:13  InnoDB: Operating system error number 11 in a file operation.
InnoDB: Error number 11 means 'Resource temporarily unavailable'.
InnoDB: Some operating system error numbers are described at
InnoDB: http://dev.mysql.com/doc/refman/5.5/en/operating-system-error-codes.html
140914 15:57:13 InnoDB: Could not open or create data files.
140914 15:57:13 InnoDB: If you tried to add new data files, and it failed here,
140914 15:57:13 InnoDB: you should now edit innodb_data_file_path in my.cnf back
140914 15:57:13 InnoDB: to what it was, and remove the new ibdata files InnoDB created
140914 15:57:13 InnoDB: in this failed attempt. InnoDB only wrote those files full of
140914 15:57:13 InnoDB: zeros, but did not yet use them in any way. But be careful: do not
140914 15:57:13 InnoDB: remove old data files which contain your precious data!
140914 15:57:13 [ERROR] Plugin 'InnoDB' init function returned error.
140914 15:57:13 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
140914 15:57:13 [ERROR] Unknown/unsupported storage engine: InnoDB
140914 15:57:13 [ERROR] Aborting

140914 15:57:13 [Note] /usr/sbin/mysqld: Shutdown complete

140914 15:57:13 mysqld_safe Number of processes running now: 0
140914 15:57:13 mysqld_safe mysqld restarted
140914 15:57:13 [Note] Plugin 'FEDERATED' is disabled.
140914 15:57:13 InnoDB: The InnoDB memory heap is disabled
140914 15:57:13 InnoDB: Mutexes and rw_locks use GCC atomic builtins
140914 15:57:13 InnoDB: Compressed tables use zlib 1.2.8
140914 15:57:13 InnoDB: Using Linux native AIO
140914 15:57:13 InnoDB: Initializing buffer pool, size = 128.0M
140914 15:57:13 InnoDB: Completed initialization of buffer pool
InnoDB: Unable to lock ./ibdata1, error: 11
InnoDB: Check that you do not already have another mysqld process
InnoDB: using the same InnoDB data or log files.
140914 15:57:13  InnoDB: Retrying to lock the first data file
InnoDB: Unable to lock ./ibdata1, error: 11
InnoDB: Check that you do not already have another mysqld process
InnoDB: using the same InnoDB data or log files.
140914 15:58:53  InnoDB: Unable to open the first data file
InnoDB: Error in opening ./ibdata1
```

And the `Unable to lock ./ibdata1, error: 11` kept occuring until:

```
140914 15:58:53  InnoDB: Operating system error number 11 in a file operation.
InnoDB: Error number 11 means 'Resource temporarily unavailable'.
InnoDB: Some operating system error numbers are described at
InnoDB: http://dev.mysql.com/doc/refman/5.5/en/operating-system-error-codes.html
140914 15:58:53 InnoDB: Could not open or create data files.
140914 15:58:53 InnoDB: If you tried to add new data files, and it failed here,
140914 15:58:53 InnoDB: you should now edit innodb_data_file_path in my.cnf back
140914 15:58:53 InnoDB: to what it was, and remove the new ibdata files InnoDB created
140914 15:58:53 InnoDB: in this failed attempt. InnoDB only wrote those files full of
140914 15:58:53 InnoDB: zeros, but did not yet use them in any way. But be careful: do not
140914 15:58:53 InnoDB: remove old data files which contain your precious data!
140914 15:58:53 [ERROR] Plugin 'InnoDB' init function returned error.
140914 15:58:53 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
140914 15:58:53 [ERROR] Unknown/unsupported storage engine: InnoDB
140914 15:58:53 [ERROR] Aborting

140914 15:58:53 [Note] /usr/sbin/mysqld: Shutdown complete

140914 15:58:53 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
```

I can see `mysqld` running in `top`, but still, I cannot connect to MySQL. When using `mysql -p`, an error message is shown:

`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

Also in `/var/run/mysqld/`, there's no `mysqld.sock` or `mysqld.pid`. I would need to manually restart MySQL by `service mysql restart` to make it work.

**Comment by Decadence** [comment]
The same issue for me.
Manually restart MySQL service from web interface is temporary solution.

**Comment by KeiroD** [comment]
Look in `/etc/init/mysql.conf` and edit the following:

Near the topc of mysql.conf, comment the following line:
`start on runlevel [2345]`

Add the following line directly after that commented code:

`#start on runlevel [2345]
start on (net-device-up IFACE=eth0 and local-filesystems and runlevel [2345])`


After commenting the following line, it should look like this:
`#start on runlevel [2345]`
`start on (net-device-up IFACE=eth0 and local-filesystems and runlevel [2345])`
`stop on starting rc RUNLEVEL=[016]`

Or `IFACE=lo` but that may present issues. Successfully tested on 14.04 with multiple restarts after running into this issue.

**Comment by Drewkan** [comment]
Exactly same problem here, your fix didn't work on second server i tried KeiroD. Weird that in the first one i had no problems anymore

**Comment by AaronGaim** [comment]
I think i found solution using this advice [stackoverflow](https://stackoverflow.com/questions/11657829/error-2002-hy000-cant-connect-to-local-mysql-server-through-socket-var-run/15039113#15039113).
I just deleted the my.cnf file, in the console I wrote:
`rm /etc/mysql/my.cnf`
I am really nooby and I am not sure that it's a good solution, but it resolve the problem.
The question is how `my.cnf` delete impact on the server and should I create it (`my.cnf`) in a different place?

**Comment by KeiroD** [comment]
@Drewkan Odd. Well, glad to hear it works for you, at least to a degree.

@AaronGaim If it doesn't find it there, it'll look for `/etc/my.cnf` there. If not there, then probably a few more other places.

**Comment by leandrobtu** [comment]
I solve using this script:

#!/bin/sh
##################################
# Script for monitor and restart process			      #
##################################
# process name for filter
PROCESSO=mysql
# check interval  (in seconds)
INTERVALO=10
while true; do
      # count process itens runing
      OCORRENCIAS=`ps ax | grep $PROCESSO | grep -v grep| wc -l`
      if [ $OCORRENCIAS -eq 0 ]; then
                 /etc/init.d/$PROCESSO start
                 tail -n 20 /var/log/log_do_processo.log |mail -s "Alert! The process $PROCESSO restarted" youremail@email.com
       fi
       # wait interval
        sleep $INTERVALO
done
# end Script

for rum in background use 

nohup ./scriptname.sh &

Big Hugs!
