### ISSUE TITLE
Changing password for FTP user has no effect

### ISSUE THREAD

**Issue by gregoriopellegrino** [serghey-rodin/vesta#2151]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

1.0.0-4

### Installed Software (what you got with the installer):

php-fpm, nginx, mariadb

### Steps to Reproduce:

go to t

- he web tab
- click the **Edit** button of a host
- go to **Additional FTP** section (my host has four FTP accounts)
- for an account click on **Generate** (next to password)
- click on **Save** button

The save is successful, but the user's password has not changed.

**Comment by anton-reutov** [comment]
try to run this commands
```
echo "/sbin/nologin" >> /etc/shells
echo "/usr/sbin/nologin" >> /etc/shells
```

**Comment by gregoriopellegrino** [comment]
They are already there:

```
cat /etc/shells

/bin/sh
/bin/bash
/usr/bin/sh
/usr/bin/bash
/sbin/nologin
/usr/sbin/nologin
```

**Comment by anton-reutov** [comment]
What error are you get ?

**Comment by gregoriopellegrino** [comment]
No errors. After saving the host conf I get Changes have been saved.

But the FTP password is not changed.

**Comment by anton-reutov** [comment]
I meant errors in the ftp client

**Comment by gregoriopellegrino** [comment]
With new credentials I get

```
530 Login incorrect.
```

With old credentials (old password) I can login :)

**Comment by anton-reutov** [comment]
Ok, thank you. I will check it.

**Comment by gregoriopellegrino** [comment]
Is it fixed in 1.0.0-5?

Thanks

**Comment by anton-reutov** [comment]
Yes, fix release will be tommorow

**Comment by gregoriopellegrino** [comment]
Is the new version released?

**Comment by wojsmol** [comment]
@anton-reutov IMHO if RWD fix will delay release too match then it can be moved to `1.0.0-6`.

**Comment by anton-reutov** [comment]
Users are waiting fix for "responsive", we should doing this in 1.0.0.5
