### ISSUE TITLE
Unable to uncheck MAIL or DNS Support while adding new domain

### ISSUE THREAD

**Issue by hassaan-dev** [serghey-rodin/vesta#2152]
### Operating System (OS/VERSION):

CentOS 7.9.2009

### VestaCP Version:

0.9.8
Core Package Version: 1.0.0 (X86_64)

### Installed Software (what you got with the installer):

apache, nginx, mariadb

### Steps to Reproduce:

I have server running CentOS 7 since a year ago, I do not install mail services. Since latest UI update, I am unable to add domain because I am unable to uncheck **MAIL** option for domain and If I add domain without unchecking **MAIL** option then I got this error "**Error: MAIL_SYSTEM is not enabled**"

### Screenshot
https://filehush.com/gBYavZoIJlhVTcm

**Comment by anton-reutov** [comment]
Try to update vestacp to 1.0.0.4

**Comment by hassaan-dev** [comment]
how to update via terminal? I am also unable to update panel

**Comment by anton-reutov** [comment]
`v-update-sys-vesta-all`

**Comment by hassaan-dev** [comment]
I tried the same command on 3 of my servers and found the same error on terminal on all servers

```
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
```

**Comment by anton-reutov** [comment]
v-update-sys-vesta
line 41
change fi on if

```
if [ "$package" = "vesta-ioncube" ]; then 
    valid=1
fi
```
and try again

**Comment by hassaan-dev** [comment]
Thank you, you such a life saver 💯
