### ISSUE TITLE
php -q in cron not work after update 1.0.0 r4 on debian x64

### ISSUE THREAD

**Issue by mrdenisters** [serghey-rodin/vesta#2153]
### Operating System (OS/VERSION):

Debian 10

### VestaCP Version:

1.0.0 r4

### Installed Software (what you got with the installer):

apache, nginx fcgi

### Steps to Reproduce:

Сron stopped working after update 1.0.0 r4 7/11/2021
There are no errors in the logs, but the scripts stopped running on schedule

Exemple comand in user vestacp:
/usr/bin/php /home/user/web/anysite.com/public_html/seo_package_cli.php not work
php -q /home/user/web/anysite.com/public_html/seo_package_cli.php not work after update vestacp
curl -k https://anysite.com/seo_package_cli.php work, but this is not problem resolve.
in syslog
![изображение](https://user-images.githubusercontent.com/37337807/141137979-93ab6ea6-4872-4779-819b-e3d4ac3cf56f.png)

**Comment by anton-reutov** [comment]
Are you sure that your Debian version is 10 ? Installer for Debian 10/11 is not ready yet

**Comment by mrdenisters** [comment]
Yes, but in phpinfo deb8
![изображение](https://user-images.githubusercontent.com/37337807/141165990-9af210e3-183d-443f-a2d9-ba474a088f45.png)
![изображение](https://user-images.githubusercontent.com/37337807/141166308-94a6daaf-7ca9-4233-abec-c1054482adb7.png)

**Comment by anton-reutov** [comment]
Ok, i will check this issue. Please, waiting

**Comment by anton-reutov** [comment]
Team:
https://forum.vestacp.com/viewtopic.php?f=35&t=18257&p=85160#p85124

**Comment by mrdenisters** [comment]
I apologize that I misled everyone. I installed several versions of PHP with this script https://github.com/rikcage/vst-php-selector and after installing the default for the system PHP8 was selected with which did not work properly. I switched via Update Alternatives PHP to 7.4 by default and CRON earned as it should be, php -q work now. Vesta update nothing to match the time.

**Comment by anton-reutov** [comment]
If you problem already solved, can we close this ticket ?

**Comment by mrdenisters** [comment]
Yes, problem solved.
