### ISSUE TITLE
Aliases not saved in new domains

### ISSUE THREAD

**Issue by ezequielbenito** [serghey-rodin/vesta#2154]
### Operating System (OS/VERSION):

Ubuntu 16.04      

### VestaCP Version:

Version: 1.0.0 (amd64)
Release: 4

### Installed Software (what you got with the installer):

Tapache, nginx, mysql, vsftpd

### Steps to Reproduce:

1) Add new domain
2) Add SSL support with LetsEncrypt
3) Set Alias like www.domain.com
4) The page reloads but fields stays empty, not saved

### Related Issues/Forum Threads:

Probably related to SSL issues

**Comment by anton-reutov** [comment]
Fixed. Fix release will be tommorow

**Comment by ezequielbenito** [comment]
Здравствуйте, Антон, вы знаете, когда выйдет новое исправление?

**Comment by anton-reutov** [comment]
15 ноября. нужно ещё responsive исправить

**Comment by phatrudinov** [comment]
Антон, обновление уже вышло? Выполнял  v-update-sys-vesta-all но версия всеравно остается Release: 4 // CentOS 7.8.2003

**Comment by anton-reutov** [comment]
Нужно закончить задачу по мобильной версии интерфейса
https://github.com/serghey-rodin/vesta/milestone/7
номер 2100
