### ISSUE TITLE
File Manager : Rename dir, Create dir, download file are broken

### ISSUE THREAD

**Issue by benyaminl** [serghey-rodin/vesta#2155]
On V 1.0.0.4

Hello, I seen couple of bug here and there, and some are in progress. does https://github.com/serghey-rodin/vesta/blob/cfb55d2dbcb8c45d8660d94d3b806b53f1062569/web/download/file/index.php change is intended, I mean, disabling the API?

Also some Hook is wrong, cause when pressing d character can't create dir or rename dir. 

In short the JS doesn't check if it's focus on input or not.

**Comment by benyaminl** [comment]
Related to https://github.com/serghey-rodin/vesta/blob/master/web/js/file_manager.js#L2301-L2664 

Seems pop up check for pop up create, and update not called or such.

**Comment by benyaminl** [comment]
I can only said that any file manager shortcut is by passed and cause renaming file with hotkey character become imposible. If the dev can share the react code completely not only map, I would glad to help.

**Comment by Ozea** [comment]
Hello, @benyaminl !
You can find React source code in the following directory `/src/react/`.

We've been working on the FM hotkeys issues. Next releases will fix it, but you can always contribute and create your PR.

**Comment by anton-reutov** [comment]
Will fixed in 1.0.0.6

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [File Manager : Rename dir, Create dir, download file are broken](https://trello.com/c/ABBALUAu/174-file-manager-rename-dir-create-dir-download-file-are-broken)

**Comment by ezequielbenito** [comment]
is 1.0.0.5 already out?

**Comment by anton-reutov** [comment]
Not yet. we are working under #2100
release will be in 20 Nov

**Comment by anton-reutov** [comment]
#bugs with hotkeys
