### ISSUE TITLE
Error: nginx restart failed<br>

### ISSUE THREAD

**Issue by mihon4ik** [serghey-rodin/vesta#2156]
### Operating System (OS/VERSION):

CentOS release 6.5 (Final)

### VestaCP Version:

1.0.0

A notification with this subject comes to the mail after adding a certificate to the domain. 

The message says:

nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Stopping nginx: [ OK ]
Starting nginx: [ OK ]

And the second checkbox is unchecked (screenshot):

![sdsdsdsd](https://user-images.githubusercontent.com/18525804/141331752-5fd3bb34-be17-4f4f-833e-e65af130ed77.jpg)

**Comment by anton-reutov** [comment]
Что покажет команда
`systemctl status nginx.service`
И команда
`v-list-sys-vesta-updates`

**Comment by mihon4ik** [comment]
# sudo systemctl status nginx.service
sudo: systemctl: command not found
# sudo v-list-sys-vesta-updates
PKG          VER    REL  ARCH    UPDT  DATE
---          ---    ---  ----    ----  ----
vesta        1.0.0  4    x86_64  yes   2021-11-11
vesta-php    1.0.0  1    x86_64  yes   2021-11-11
vesta-nginx  1.0.0  1    x86_64  yes   2021-11-11

Заранее прошу прощения, если сделал что-то неправильно. Я совсем начинающий любитель.

**Comment by anton-reutov** [comment]
скиньте результат `service nginx restart`

**Comment by mihon4ik** [comment]
```
# sudo service nginx restart
Stopping nginx:                                            [  OK  ]
Starting nginx:                                            [  OK  ]
```

**Comment by anton-reutov** [comment]
Похоже что проблем со стартом nginx нет
`service nginx status`

**Comment by anton-reutov** [comment]
У вас в заголовке тикета указан тег <br>  - так панель выводит?

**Comment by mihon4ik** [comment]
Да, этот тег был в панели и в заголовке письма на почту.

**Comment by anton-reutov** [comment]
Скиньте ещё
`service nginx status`

**Comment by mihon4ik** [comment]
# sudo service nginx status
nginx (pid  24145) is running...

**Comment by anton-reutov** [comment]
nginx запущен

**Comment by anton-reutov** [comment]
По unchecked lets encrypt проблема должна была решится в 1.0.0.4

**Comment by mihon4ik** [comment]
Полный текст ошибки выглядит так

` Error: nginx restart failed<br>Error: nginx restart failed<br>Error: nginx restart failed`

**Comment by anton-reutov** [comment]
Доступ к серверу сможете предоставить? info@vestacp.com
В заголовке укажите номер тикета

**Comment by mihon4ik** [comment]
Да, конечно.

Еще была такая ошибка, но я ее поправил сам.

```
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
/usr/local/vesta/bin/v-update-sys-vesta: line 41: syntax error near unexpected token `fi'
/usr/local/vesta/bin/v-update-sys-vesta: line 41: `fi [ "$package" = "vesta-ioncube" ]; then '
```

**Comment by anton-reutov** [comment]
Хорошо, отправьте доступ, в первой половине дня посмотрим в чем проблема

**Comment by mihon4ik** [comment]
Отправил вам письмо. Хорошего вечера!
