### ISSUE TITLE
Disabled functions in Packages still showing up when logged in as USER

### ISSUE THREAD

**Issue by hollanddata** [serghey-rodin/vesta#2157]
CentOS 7

Core Package Version: 1.0.0 (X86_64) Release: 4

When disabling DNS, MAIL or something else at Packages, the function is still enabled for USERS.

![2021-11-11 21_43_55-Window](https://user-images.githubusercontent.com/54579231/141367205-945197fe-f031-4dd1-8669-315549d2857a.png)
![2021-11-11 21_46_05-Window](https://user-images.githubusercontent.com/54579231/141367206-ada66e7a-549d-4f2d-9801-9c711c0d9367.png)

**Comment by anton-reutov** [comment]
Thank you. Will be fixed

**Comment by anton-reutov** [comment]
Will fixed in 1.0.0.6

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Disabled functions in Packages still showing up when logged in as USER #2157](https://trello.com/c/inFalKrV/166-disabled-functions-in-packages-still-showing-up-when-logged-in-as-user-2157)
