### ISSUE TITLE
99, msg=Cannot assign requested address

### ISSUE THREAD

**Issue by mannt77** [serghey-rodin/vesta#2158]
Ubuntu 18
После недавних обновлений посыпались ошибки "99, msg=Cannot assign requested address", в частности при поиске sphinxSearch.  До этого все работало как часы.
В чем может быть проблема, какие конфиги были изменены обновлением и где искать проблему?

**Comment by anton-reutov** [comment]
Напишите подробнее где появляется проблема и как её повторить

**Comment by mannt77** [comment]
> Напишите подробнее где появляется проблема и как её повторить
Проблема начала появляться с начала месяца, в тот момент когда обновилась панель. Ошибка появляется при частых запросах к движку sphinxsearch.  На сервере прописаны несколько IP адресов (в панели vestaCP и /etc/netplan/01-netcfg.yaml).
До обновлений панели все работало как часы и ошибок не возникало. Не знаю в какую сторону копать, поэтому и спрашиваю.
