### ISSUE TITLE
Проблема с безопастностью | Файрвол

### ISSUE THREAD

**Issue by mannt77** [serghey-rodin/vesta#2159]
Ubuntu 18. VestaCP релиз 4
На вкладке файрвол было настроено правило доступа к серверу по SSH только для моего домашнего IP. (смотрите картинку https://ibb.co/hfBnbdg)
После обновления VestaCP это правило перестало учитываться (хотя оно по прежнему прописано) и доступ к серверу по SSH открывался для любого IP-адреса. Тут же посыпались баны в "показать fail2ban".
Удалил правило, вновь создал такое же и файрвол заработал должным образом. Примечательно, что на другом моем сервере такой проблемы не наблюдаю.
Прошу проверить эту "уязвимость".

**Comment by anton-reutov** [comment]
Перестает работать при каждом обновлении панели? 3, 4....
Как мы точно можем воспроивести данную проблему?

**Comment by mannt77** [comment]
> Перестает работать при каждом обновлении панели? 3, 4...
Не могу знать.
Порт SSH, как я писал выше был закрыт во вкладке "Файрвол" - разрешил только моему IP.  Cписок fail2ban был пуст. Пол года все работало нормально. В начале месяца VestaCP наконец-то начала обновляться. 2-3 дня назад заметил, что список fail2ban начал заполняться забаненными IP по правилу SSH.
Попробовал зайти на сервер по SSH с IP отличного от того, что прописал в правиле firewall - зайти получилось. Жаль не додумался проверить # iptables -S.
Я из панели весты удалил правило для SSH, и тут же создал такое же (c ACCEPT мой_IP). Правило заработало. Списки fail2ban теперь не пополняются. Доступ к SHH теперь только с моего IP как положено.
Я думаю, что при обновлении панели vestaCP подтянула свои дефолтные правила с открытыми для всех IP адресами, игнорировав правила, настроены admin-ом панели. При этом правила admin-f отображались во вкладке "Файрвол", но не работали. Прошу проверить скрипты последних обновлений панели.
