### ISSUE TITLE
Can't login to VestaCP 0.9.8-10

### ISSUE THREAD

**Issue by enricodeleo** [serghey-rodin/vesta#216]
Hi everybody,

I recently discovered that I can't login to my various VestaCP control panels after the upgrade to the latest release.
I tried to install it on a vanilla virtual machine based on CentOS 6.5 x64 with Vagrant and I can't even login for the first time.

I checked all the services (Vesta, MySQL etc) and everything seems to work. I also tried to change manually the password via cli (v-user-change-password) but even if the command is accepted nothing happens. Tried also different browsers of course (actually the first thing I thought was that something wasn't working with certificates and/or redirecting but nothing).

Despite this big issue, if I create domains, users and so on via cli the webserver do his job but still, a control panel is pretty much comfortable, isn't it? :)

Anyone had the same trouble?

Thank you in advance

**Comment by rmalenko** [comment]
I confirmed. I have tried restore password, however I still can not login.

**Comment by serghey-rodin** [comment]
Please try this workaround
```bash
mkdir -p /etc/sudoers.d
/usr/local/vesta/upd/add_sudo.sh
```

**Comment by SysVoid** [comment]
Closing at this is an old issue and appears to be resolved.
