### ISSUE TITLE
Проблема с обновлением кеша

### ISSUE THREAD

**Issue by mihon4ik** [serghey-rodin/vesta#2161]
### Operating System (OS/VERSION):

CentOS release 6.5 (Final)

### VestaCP Version:

1.0.0

Недавно заметил, что изображения (размещенные на моем сервере) на веб-страницах, всегда подгружаются из кеша диска. Когда их содержания обновляется, то для того, чтобы увидеть обновление на веб-странице приходится нажимать Ctrl + F5. Метатеги не помогают. 

Такие заголовки ответов (из инструмента для веб-разработчиков браузера)

![dfsdfdsfdsf](https://user-images.githubusercontent.com/18525804/141645305-49625c6d-2171-41a8-b8ca-611ef96d1402.jpg)
:

**Comment by anton-reutov** [comment]
У вас в cache-control хранение кешируемых файлов 1 год. Они хранятся локально.
Как только данный лимит времени пройдет, файлы с сервера обновятся снова.

**Comment by mihon4ik** [comment]
Спасибо!
