### ISSUE TITLE
Со страницы "Server -> show: CPU / MEM / NET / DISK -> WEB" пропали таблицы

### ISSUE THREAD

**Issue by Petyay** [serghey-rodin/vesta#2163]
### Operating System (OS/VERSION):
CentOS 7.7
### VestaCP Version:
Core Package Version: 1.0.0 (X86_64) Release: 1
### Installed Software (what you got with the installer):
vesta-php Version: 0.9.8 (X86_64) Release: 26
vesta-nginx Version: 0.9.8 (X86_64) Release: 26
### Steps to Reproduce:

Со страницы "Server -> show: CPU / MEM / NET / DISK -> WEB" пропали
таблицы. А именно - внизу была таблица со всеми соединениями по
http адресам. Но теперь, если посмотреть в HTML код, есть теги < td > < tr >
< th >, но пропал тег < table >...

**Comment by anton-reutov** [comment]
По остальным вкладкам данного раздела нормально?

**Comment by Petyay** [comment]
По всем вкладкам раздела "show: CPU / MEM / NET / DISK" (это CPU MEMORY DISK NETWORK WEB DNS MAIL DB) наблюдается та же проблема.
Эти URL не только нельзя вводить в адресную панель браузера, но и обновлять страницу.
Появляется ошибка 404.

**Comment by anton-reutov** [comment]
Вы точно про этот тикет?

**Comment by Petyay** [comment]
> Вы точно про этот тикет?
Извините) 

> По остальным вкладкам данного раздела нормально?
На остальных проблем не заметил

Спасибо за незаменимый продукт.

**Comment by anton-reutov** [comment]
Спасибо, будет исправлено

**Comment by anton-reutov** [comment]
Попадет в 1.0.0.6

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Со страницы "Server -> show: CPU / MEM / NET / DISK -> WEB" пропали таблицы #2163](https://trello.com/c/GLm076li/168-%D1%81%D0%BE-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B-server-show-cpu-mem-net-disk-web-%D0%BF%D1%80%D0%BE%D0%BF%D0%B0%D0%BB%D0%B8-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D1%8B-2163)
