### ISSUE TITLE
Manual Database URL option is missing

### ISSUE THREAD

**Issue by hollanddata** [serghey-rodin/vesta#2164]
Type here, e.g. CentOS 7

Core Package Version: 1.0.0 (X86_64) Release: 4

Manual Database URL option is missing like manual email option. 

![2021-11-15 13_02_57-Vesta - SERVER](https://user-images.githubusercontent.com/54579231/141779286-f41fac7b-ae32-4d23-9cb9-a425cf3d45ec.png)

**Comment by anton-reutov** [comment]
Will be fixed in 1.0.0.5

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Configure DB -  пропал input назначения ссылки phpmyadmin](https://trello.com/c/B8tWU68P/163-configure-db-%D0%BF%D1%80%D0%BE%D0%BF%D0%B0%D0%BB-input-%D0%BD%D0%B0%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D0%B8-phpmyadmin)

**Comment by anton-reutov** [comment]
Fix will be in 1.0.0.5
