### ISSUE TITLE
Dovecot error log

### ISSUE THREAD

**Issue by rmalenko** [serghey-rodin/vesta#217]
Hi,
I have in dovecot.log a lot of like this records.
auth: Error: passwd-file(qfrtrt,93.191.40.42,<dfrtrtrtty>): stat(/etc/exim4/domains//passwd) failed: No such file or directory

Many users are working without any problem, however some users complain that cannot get their email via POP3. As luck would have it are important customers.

**Comment by SysVoid** [comment]
Hi. Has this been fixed?

**Comment by SysVoid** [comment]
Closed due to inactivity.

**Comment by MahbbRah** [comment]
Having same issue, it keeps generating like that random user that I didn't created it's a personal setup but still seems a lots of random user generating and getting like that issue also, I have problem with IMAP server it's not resolving with port 143. I don't know why...
