### ISSUE TITLE
Error: Let's Encrypt nonce request status

### ISSUE THREAD

**Issue by stephensaid** [serghey-rodin/vesta#2180]
### Steps to Reproduce:
v-add_letsencrypt-domain user domain

All of my domains are failing to update ssl certificates and will soon expire.

This post suggests that this could be due to DST Root CA X3 Expiration (September 30, 2021) 
https://forum.vestacp.com/viewtopic.php?f=10&t=19158&p=85275#p84837

This is more or less when I started having this problem.

If I run curl -l "https://acme-v02.api.letsencrypt.org/directory" I get:
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by anton-reutov** [comment]
[Let's Encrypt nonce request status](https://gist.github.com/httpsx/516c2592d5ffb257f2fc80472b1fc38b)

**Comment by stephensaid** [comment]
Does this apply to Ubunut 14.04 too?
