### ISSUE TITLE
Don't press the server button

### ISSUE THREAD

**Issue by artscripts** [serghey-rodin/vesta#2188]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

Version:
1.0.0 (X86_64)
Release:
5

### Installed Software (what you got with the installer):

ngingx. php-fpm, mysql

### Steps to Reproduce:

When you click on the server button, the notification button opens

<a href="https://ibb.co/qpKLFT4"><img src="https://i.ibb.co/6FzcJjp/2021-11-23-12-26-00.png" alt="2021-11-23-12-26-00" border="0"></a>

### Other Notes:

Anything else?

**Comment by anton-reutov** [comment]
Can you write more? for mobile devices or desktop ?
What is the screen resolution? and your browser

**Comment by artscripts** [comment]
MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)
13.3-inch (2560 × 1600)
safari browser

on mobile iphone 7+ this error is not present

**Comment by jaapmarcus** [comment]
Can confirm the issue...

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Don't press the server button](https://trello.com/c/sFo1EUJc/177-dont-press-the-server-button)
