### ISSUE TITLE
CPU / Mem / Disk unreadable 

### ISSUE THREAD

**Issue by jaapmarcus** [serghey-rodin/vesta#2189]
### Operating System (OS/VERSION):

Type here, e.g. Ubuntu 18.04

### VestaCP Version:

1.0.0-5

### Installed Software (what you got with the installer):

Type here, e.g. php-fpm, apache, nginx, mysql

### Steps to Reproduce:

Go to
https://xxxxxx:8083/list/server/cpu

### Related Issues/Forum Threads:

<img width="1774" alt="Screenshot 2021-11-23 at 13 16 20" src="https://user-images.githubusercontent.com/9754650/143022671-3a30e482-e7a4-45ec-b0ad-512f067be5ad.png">

### Other Notes:

Anything else?

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CPU / Mem / Disk unreadable](https://trello.com/c/D7blPORI/175-cpu-mem-disk-unreadable)
