### ISSUE TITLE
Stop service fails 

### ISSUE THREAD

**Issue by jaapmarcus** [serghey-rodin/vesta#2190]
### Operating System (OS/VERSION):

Type here, e.g. Ubuntu 18.04

### VestaCP Version:

1.0.0-5

### Installed Software (what you got with the installer):

Type here, e.g. php-fpm, apache, nginx, mysql

### Steps to Reproduce:

Go to
https://xxxxxx:8083/list/server/ and stop any service:

### Related Issues/Forum Threads:

<img width="1439" alt="Screenshot 2021-11-23 at 13 18 55" src="https://user-images.githubusercontent.com/9754650/143022942-bfd41330-7a38-4a7a-b957-883c1dc3932c.png">

### Other Notes:

Anything else?

**Comment by anton-reutov** [comment]
Ubuntu 18, can't reproduce
try to stop/start via cli

```
v-stop-service apache2
v-start-service apache2
```

**Comment by jaapmarcus** [comment]
CLI or even via Select "all" works fine.  Except when clicking on a "stop" link  fails:

After clicking the service stops as intended ...
<img width="1101" alt="Screenshot 2021-11-23 at 14 42 22" src="https://user-images.githubusercontent.com/9754650/143034982-f444e6d0-6aa6-452d-a2a6-b073885c38a5.png">

**Comment by anton-reutov** [comment]
Can you provide access to your server, or server where we can reproduce this problem

**Comment by jaapmarcus** [comment]
Did a new install and no issue
