### ISSUE TITLE
Unable to alter /webmail/ alias

### ISSUE THREAD

**Issue by jaapmarcus** [serghey-rodin/vesta#2191]
### Operating System (OS/VERSION):

Ubuntu 18.04

### VestaCP Version:

Lastest

### Installed Software (what you got with the installer):

Doesn't matter

### Steps to Reproduce:

List Server -> Configure
<img width="1103" alt="Screenshot 2021-11-23 at 13 23 28" src="https://user-images.githubusercontent.com/9754650/143023563-f0ce532c-2545-4b78-8c8e-95af44573a9e.png">

Then press save

<img width="990" alt="Screenshot 2021-11-23 at 13 23 35" src="https://user-images.githubusercontent.com/9754650/143023596-62e757ca-ae3d-4f2a-8bb9-a94f2da6584b.png">

### Related Issues/Forum Threads:

Found anything that might be related to this? It might help us find the cause.

https://github.com/serghey-rodin/vesta/blob/cae9a1550d77e4b2f6d4637ee47efc57183f40ee/web/api/v1/edit/server/index.php#L639-L640

### Other Notes:

Anything else?

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unable to alter /webmail/ alias](https://trello.com/c/elIRhKSC/176-unable-to-alter-webmail-alias)

**Comment by sickcodes** [comment]
Confirmed, breaks the intended use of phpmyadmin

![Screenshot_2021-11-29_17-57-58](https://user-images.githubusercontent.com/65906298/143919299-da5ff5e2-5686-456b-a258-4d8b5a6a0414.png)
