### ISSUE TITLE
Doesn't show access logs and error logs

### ISSUE THREAD

**Issue by artscripts** [serghey-rodin/vesta#2192]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

1.0.0 release 5

### Installed Software (what you got with the installer):

php-fpm, nginx, mysql

### Steps to Reproduce:

Doesn't show access logs and error logs

<a href="https://ibb.co/R3bSc7G"><img src="https://i.ibb.co/N9C3K7g/2021-11-23-15-34-19.png" alt="2021-11-23-15-34-19" border="0"></a>

### Other Notes:

Anything else?

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Doesn't show access logs and error logs](https://trello.com/c/LEog6k2b/178-doesnt-show-access-logs-and-error-logs)

**Comment by aslik4rahan** [comment]
Hello, when fix logs problem?

**Comment by phatrudinov** [comment]
Такая же проблема.

**Comment by angelok1979** [comment]
В логах есть одна строчка, скачивается же полный лог.
Внешне хедер закрывает эту единственную строчку и ее почти не видно, но она одна есть.
