### ISSUE TITLE
Скрывается строка при переходе в показатели CPU, память

### ISSUE THREAD

**Issue by namyv** [serghey-rodin/vesta#2194]
CENTOS 7.9.2009
VESTA 1.0.0.5
При переходе во вкладку Сервер - показатели: Процессор, память, интерфейс Vesta скрывается под поисковой строкой браузера.  Проблема замечена в Chrome и Edge последних версий.
Проблема на двух серверах.
<a href="https://ibb.co/PG4LWWW"><img src="https://i.ibb.co/RTPF666/image.png" alt="image" border="0"></a>

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Doesn't show access logs and error logs](https://trello.com/c/LEog6k2b/178-doesnt-show-access-logs-and-error-logs)

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CPU / Mem / Disk unreadable](https://trello.com/c/D7blPORI/175-cpu-mem-disk-unreadable)
