### ISSUE TITLE
Web page(/list/web) blank when upgrade to version 5 In Chrome old version below 85

### ISSUE THREAD

**Issue by mysterynet** [serghey-rodin/vesta#2196]
### Operating System (OS/VERSION):

CentOS 6-7

### VestaCP Version:

1.0.0-5

### Installed Software (what you got with the installer):

php-fpm, apache, nginx, mysql

### Steps to Reproduce:

This is a JS-Browser not compatible error, below chrome 85, the replaceAll will cause "not a function error".

Update vesta to version 5 will break the control panel - web page (link is /list/web/), the page will just blank nothing on it,and back button on browser will not working too

yum upgrade vesta -y   
yum downgrade vesta -y  

And if I downgrade to version 4 the page will back.

### Related Issues/Forum Threads:
This is what I found on devtool:
======console======
TypeError: n.ALIAS.replaceAll is not a function
    at nc (WebDomain.jsx:75)
    at Zo (react-dom.production.min.js:153)
    at js (react-dom.production.min.js:257)
    at tl (react-dom.production.min.js:228)
    at Zs (react-dom.production.min.js:227)
    at Hs (react-dom.production.min.js:220)
    at react-dom.production.min.js:120
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Ii (react-dom.production.min.js:119)
    at zi (react-dom.production.min.js:120)
Ya @ react-dom.production.min.js:193

======WebDomain.jsx======
line75:{data.ALIAS.replaceAll(',', ', ')} <- here cause the error
error message: Uncaught (in promise) TypeError: n.ALIAS.replaceAll is not a function

**Comment by mysterynet** [comment]
File:src/react/src/components/WebDomain/WebDomain.jsx
Line:75
Change at commit:FM progress bar while uploading. Minor CPanel improvements as well as… (5b2c180d86a722dd75a32ccf3f747677e69f65ce)
Link:https://github.com/serghey-rodin/vesta/commit/5b2c180d86a722dd75a32ccf3f747677e69f65ce#diff-857d8e7353610e99c08d1e47e281a49f552f256aaec6a7e88e32f96a7e26c27f

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Web page(/list/web) blank when upgrade to version 5 In Chrome old version below 85](https://trello.com/c/zPdSaC6g/180-web-page-list-web-blank-when-upgrade-to-version-5-in-chrome-old-version-below-85)

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Нельзя зайти на некоторые страницы просто введя адрес в строку URL в браузере.](https://trello.com/c/ufxAwvbp/186-%D0%BD%D0%B5%D0%BB%D1%8C%D0%B7%D1%8F-%D0%B7%D0%B0%D0%B9%D1%82%D0%B8-%D0%BD%D0%B0-%D0%BD%D0%B5%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B5-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B-%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE-%D0%B2%D0%B2%D0%B5%D0%B4%D1%8F-%D0%B0%D0%B4%D1%80%D0%B5%D1%81-%D0%B2-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D1%83-url-%D0%B2-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B5)

**Comment by anton-reutov** [comment]
Fixed. You will be able to check it in 1.0.0.6
