### ISSUE TITLE
Crazy summary data

### ISSUE THREAD

**Issue by jonathanf** [serghey-rodin/vesta#2197]
### Operating System (OS/VERSION):

3 servers with Centos 7.9 

### VestaCP Version:

1.0.0.5

### Installed Software (what you got with the installer):

php-fpm, nginx, mysql

### Steps to Reproduce:

Go to any account and look summary data:

![Captura de pantalla de 2021-11-24 11-50-24](https://user-images.githubusercontent.com/926635/143281889-a5db6fcc-4623-4092-ae55-0ab4b227a23f.png)

### Related Issues/Forum Threads:

nop

### Other Notes:

This 1.0 version are really buggy.

**Comment by anton-reutov** [comment]
Try tp run this commands
```
sudo /usr/local/vesta/bin/v-update-sys-queue disk
sudo /usr/local/vesta/bin/v-update-sys-queue traffic
```

**Comment by jonathanf** [comment]
> Try to run this commands
> 
> ```
> sudo /usr/local/vesta/bin/v-update-sys-queue disk
> sudo /usr/local/vesta/bin/v-update-sys-queue traffic
> ```

Doesn't work, still wrong information is displayed.

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Crazy summary data](https://trello.com/c/XW8ZG2V3/181-crazy-summary-data)

**Comment by antonT39** [comment]
![image](https://user-images.githubusercontent.com/36173113/143463188-536e80b6-db70-4f9a-85e3-8f93353c10e7.png)
1.0.0.5
