### ISSUE TITLE
Заблокирован ввод в textarea id="ssl-certificate" при добавлении домена

### ISSUE THREAD

**Issue by antonT39** [serghey-rodin/vesta#2198]
### VestaCP Version:

1.0.0.5

### Other Notes:
![image](https://user-images.githubusercontent.com/36173113/143465672-95ff3152-9046-4764-96dd-c59e5030b9b6.png)
Заблокирован ввод в поле "SSL сертификат
" <textarea class="form-control" id="ssl-certificate" rows="3" name="v_ssl_crt"></textarea> при добавлении домена. Приходится создавать без SSL, а потом нажимать редактировать домен и вводить в эти поля. При редактировании вводится в id="ssl-certificate", а при добавлении нет.

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Заблокирован ввод в textarea id="ssl-certificate" при добавлении домена](https://trello.com/c/woQ9DzRS/183-%D0%B7%D0%B0%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD-%D0%B2%D0%B2%D0%BE%D0%B4-%D0%B2-textarea-idssl-certificate-%D0%BF%D1%80%D0%B8-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B8-%D0%B4%D0%BE%D0%BC%D0%B5%D0%BD%D0%B0)
