### ISSUE TITLE
Название сайта в разделе WEB

### ISSUE THREAD

**Issue by mannt77** [serghey-rodin/vesta#2199]
На вкладке "WEB" прижмите название сайта "к верху", так как алиасов для сайта можно задать очень много и в этом случае название самого сайта болтается неизвестно где - по серединке - очень неудобно.

Также хорошо бы gif ожидания (синяя полоска, которая появляется внизу страницы при внесении изменений) перенести куда-нибудь в центр страницы поверх всего. Чтобы лучше было видно его.

**Comment by anton-reutov** [comment]
Можете скрин залить по алиасам

**Comment by mannt77** [comment]
> Можете скрин залить по алиасам
![image](https://user-images.githubusercontent.com/94204926/143762980-de744159-73cb-43d4-b4dc-dec5bfeff774.png)

**Comment by anton-reutov** [comment]
Спасибо, будет исправлено

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Название сайта в разделе WEB](https://trello.com/c/W5G5fnpN/184-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81%D0%B0%D0%B9%D1%82%D0%B0-%D0%B2-%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%D0%B5-web)

**Comment by mannt77** [comment]
> Спасибо, будет исправлено

также можно уменьшить/убрать межстрочный интервал в алиасах? на той же картинке видно как все растягивается по вертикали.

**Comment by anton-reutov** [comment]
уберем
