### ISSUE TITLE
Не сохраняются изменения при открытии нескольких вкладов в браузере

### ISSUE THREAD

**Issue by mannt77** [serghey-rodin/vesta#2202]
С переходом панели на "AJAX" начались жуткие неудобства с сохранением изменений.
Например (Браузер Opera):
Захожу во вкладку WEB, тыкаю "редактировать" для каждого сайта колесиком мыши, чтобы в новых вкладках открыть редактирование сайтов.  Для каждого сайта изменяю, к примеру, алиасы. Жму на каждой вкладке сохранить. Изменения сохраняются только в последней открытой (колесиком мыши) вкладе. В остальных - не сохраняются. Приходится для каждой вкладки делать F5 и только уже потом производить изменения.
Это жутко выбешивает!!!
Можно это как-то пофиксить?

**Comment by anton-reutov** [comment]
Хорошо, проверим и пофиксим

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Не сохраняются изменения при открытии нескольких вкладов в браузере](https://trello.com/c/9ipdpzhI/185-%D0%BD%D0%B5-%D1%81%D0%BE%D1%85%D1%80%D0%B0%D0%BD%D1%8F%D1%8E%D1%82%D1%81%D1%8F-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BF%D1%80%D0%B8-%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B8-%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%B8%D1%85-%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%BE%D0%B2-%D0%B2-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B5)
