### ISSUE TITLE
Не работает переадресация с http на https для файлов сайта

### ISSUE THREAD

**Issue by mihon4ik** [serghey-rodin/vesta#2204]
### Operating System (OS/VERSION):

CentOS release 6.5 (Final)

### VestaCP Version:

1.0.0

Не работает переадресация с http на https для файлов сайта, то есть для ссылок вида http://www.domain.info/file.jpg
С чем это может быть связано?

В файле .htaccess есть такие строки:

RewriteEngine On
RewriteCond %{SERVER_PORT} ^80$ [OR]
RewriteCond %{HTTP} =on
RewriteRule ^(.*)$ https://www.domain.info/$1 [R=301,L]

**Comment by anton-reutov** [comment]
А так ?
`RewriteRule ^(.*).(jpg|jpeg|png|gif)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,NC,L]`

У вас движок или html страница?
Используется apache+nginx ?

**Comment by mihon4ik** [comment]
> А так ?
> `RewriteRule ^(.*).(jpg|jpeg|png|gif)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,NC,L]`

Попробовал. Без изменений. 

> У вас движок или html страница?

У меня html-страницы. 

> Используется apache+nginx ?

Да, верно.

**Comment by mihon4ik** [comment]
Хочу в файле nginx.conf прописать следующие строки, но панель не дает. 

```
server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}
```

**Comment by anton-reutov** [comment]
Попробуйте подключить  и применить шаблон 
http://vestacp.com/docs/#how-to-force-https

**Comment by mihon4ik** [comment]
> Попробуйте подключить и применить шаблон
> http://vestacp.com/docs/#how-to-force-https

Сделал. Не помогло.

**Comment by mihon4ik** [comment]
Заработало. Нужно было еще в настройках домена установить шаблон Proxy: force-https.

Большое спасибо!
