### ISSUE TITLE
Error code: 15 when trying to enable Lets Encrypt for existing domains with Cloudflare

### ISSUE THREAD

**Issue by ezequielbenito** [serghey-rodin/vesta#2208]
### Operating System (OS/VERSION):

Ubuntu 16.04

### VestaCP Version:

Version: 1.0.0 (amd64)
Release: 5

### Installed Software (what you got with the installer):

apache, nginx, mysql, vsftpd

### Steps to Reproduce:

1. Edit an existing domain
2. Remove check from SSL support
3. Save form
4. Go to Cloudflare and set SSL/TLS options to "Flexible" for that domain
5. Back in Vesta edit domain and check SSL support
6. Then check Lets Encrypt Support
7. Save form
8. It will load for a couple seconds and show error
9. If I sent Cloudflare to Full Strict the site will not load (will show Cloudflare error: Invalid SSL certificate)

### Related Issues/Forum Threads:

https://github.com/serghey-rodin/vesta/issues/2149

### Other Notes:

Before the November update I used to set Cloudflare SSL/TLS to flexible then create the SSL let's encrypt and then moved the Cloudflare to Full Strict mode. This is currently working on a Vesta Panel which didn't update.

**Comment by jaapmarcus** [comment]
Disable proxy -> Request SSL and then enable again

**Comment by ezequielbenito** [comment]
Doesn't work. Can you provide a more detailed steps? 

This is what was working flawlessly and currently this works on our other Vesta installation 0.9.8 release 26:

**Removing SSL from a given domain**
1. Edit an existing domain
2. Remove check from SSL support
3. Save form

**Removing Cloudflare SSL/TLS**
1. Go to Cloudflare and set SSL/TLS options to "Flexible" for that domain

**Now the actual steps in Vesta**
1. Edit domain the domain in question and check SSL support
2. Check Lets Encrypt Support
3. Save form

**Finally in Cloudflare**
1. Set SSL/TLS to Full (Strict)

**Comment by ezequielbenito** [comment]
After going over this again I detected that the domain the proxy was unchecked for this domain. My bad, but this updates are driving my crazy.

Consider this issue closed, anyway I will run additional checks.

In any case, a more descriptive error other than "15" could have helped ;-)
