### ISSUE TITLE
Roundcube: DATABASE ERROR: CONNECTION FAILED!

### ISSUE THREAD

**Issue by joubertredrat** [serghey-rodin/vesta#221]
Hi guys,

My friend install vesta without problem, but in all my instalations have this problem on install roundcube.

I checked install script and is normally, but in installation, is tried to install and configure roundcube before install mysql server and installation scripts report error on mysqlsocket.

Look my test installation as example in https://gist.github.com/joubertredrat/a6a18daa75bf0430a675

He try to include phpmyadmin and roundcube data on mysql on line 1480 and 1495, but mysql is configured on since line 1708.

Anyone have this problem or is only with me?

Thanks for this nice project.

**Comment by sdavides** [comment]
Roundcube: DATABASE ERROR: CONNECTION FAILED! on VPS Centos 6.x:

Change row setting configuration mysql roundcube 
config.inc.php line 14: 
from
$config['password_db_dsn'] = 'mysqli://user:pass@localhost/maildb';
to
$config['password_db_dsn'] = 'mysql://user:pass@localhost/maildb';

**Comment by robindirksen1** [comment]
And why would you change it to mysql instead of mysqli?

**Comment by sdavides** [comment]
otherwise in some versions of linux it does not work


Hi

2017-08-17 15:53 GMT+02:00 Robin Dirksen <notifications@github.com>:
