### ISSUE TITLE
is this line correct?

### ISSUE THREAD

**Issue by mix5003** [serghey-rodin/vesta#2210]
i am not sure. but i think this should not corect
https://github.com/serghey-rodin/vesta/blob/22f3dd11e2b89ff45f1209164ed98b1678828da3/web/api/v1/edit/server/index.php#L639

**Comment by anton-reutov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [is this line correct?](https://trello.com/c/nCjiiXuj/187-is-this-line-correct)
