### ISSUE TITLE
Некорректно сохраняются настройки доменов

### ISSUE THREAD

**Issue by DuoSoftOrg** [serghey-rodin/vesta#2212]
### Operating System (OS/VERSION):

Centos 7

### VestaCP Version:

1.0.0

### Steps to Reproduce:

После обновления интерфейса VestaCP появилась проблема сразу на двух VPS с Centos 7 (пробую из разных браузеров). Редактируя настройки любого домена, при нажатии на кнопку "сохранить", настройки сохраняются некорректно. Большая часть настроек (текстовые поля Обработка Proxy, Алиасы и тд) сохраняются в виде пустых полей или сбрасываются к дефолтным. Корректно сохраняются поля IP и Шаблон Web. Никаких ошибок не выводится, появляется уведомление " Изменения сохранены". Временно решить проблему помогает только удаление домена и добавление его заново сразу с нужными настройками. При редактировании добавленного домена в дальнейшем он также сохраняется некорректно. 

Также при добавлении нового домена чекбоксы "Поддержка DNS" и "Поддержка почты" не реагируют на клики и всегда находятся в чекнутом состоянии.

**Comment by anton-reutov** [comment]
Обновите панель до 1.0.0.5

**Comment by DuoSoftOrg** [comment]
Обновил с помощью команды v-update-sys-vesta-all
Теперь сама панель в браузере вообще не открывается (ERR_CONNECTION_REFUSED)
В логе такое:

2021-12-20 14:44:38 v-update-sys-vesta  'vesta' [Error 19]
2021-12-20 14:44:39 v-update-sys-vesta  'vesta-nginx' [Error 19]
2021-12-20 14:44:39 v-update-sys-vesta  'vesta-php' [Error 19]
2021-12-20 14:44:40 v-update-sys-vesta  'vesta-ioncube' [Error 19]
2021-12-20 14:44:41 v-update-sys-vesta  'vesta-softaculous' [Error 19]

**Comment by anton-reutov** [comment]
Доступ к серверу можете предоставить?

**Comment by DuoSoftOrg** [comment]
С проблемой выше разобрался

**Comment by DuoSoftOrg** [comment]
Разобрался с обновлением, проблемы устранились

**Comment by frkmusic** [comment]
> 

How did you fix the issue ? Kindly guide me, i have the same issue. @DuoSoftOrg

**Comment by frkmusic** [comment]
I figured out how to fix it. Thanks.
