### ISSUE TITLE
View Logs Web Interface Not Working

### ISSUE THREAD

**Issue by strikingwebsolutions** [serghey-rodin/vesta#2223]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

1.0.0.0

### Installed Software (what you got with the installer):

php-fpm, nginx, mariadb

### Steps to Reproduce:

View the web log (/list/web-log/?domain=xxx) 

Web -> [Mouse Over Domain] -> View Logs

### Related Issues/Forum Threads:

https://forum.vestacp.com/viewtopic.php?f=16&t=20738

### Other Notes:

Anything else?

![image](https://user-images.githubusercontent.com/37544202/148534406-471cda34-62de-4600-ada8-27a27d1e6772.png)

**Comment by gregoriopellegrino** [comment]
Same for me

**Comment by aslik4rahan** [comment]
same for me,
when will it be fixed? a big problem

**Comment by wojsmol** [comment]
@gregoriopellegrino @aslik4rahan Please post exact VestaCP version.

**Comment by gregoriopellegrino** [comment]
Version: 1.0.0 (X86_64)
Release: 5

**Comment by aslik4rahan** [comment]
Release: 5
i am using this version

**Comment by anton-reutov** [comment]
update to 1.0.0.6

**Comment by aslik4rahan** [comment]
thank you, now working logs. 👍
