### ISSUE TITLE
Topmenu not showing correctly show: CPU / MEM / NET / DISK

### ISSUE THREAD

**Issue by hollanddata** [serghey-rodin/vesta#2225]
Centos 7 - Core Package Version: 1.0.0 (X86_64) Release: 5 - NEW installation

show: CPU / MEM / NET / DISK

![2022-01-09 00_46_05-Vesta - SERVER](https://user-images.githubusercontent.com/54579231/148663750-eadfce97-0747-47a3-a6f3-ca39499e48a1.png)

Menu not showing correctly

![2022-01-09 00_49_44-Vesta - SERVER](https://user-images.githubusercontent.com/54579231/148663792-86930388-5590-41f4-90f8-8e572e9ec6d0.png)

**Comment by jaapmarcus** [comment]
Just wait for new release 

https://github.com/serghey-rodin/vesta/issues/2206

**Comment by anton-reutov** [comment]
1.0.0.6

**Comment by anton-reutov** [comment]
update to 1.0.0.6
