### ISSUE TITLE
Unable to save changes

### ISSUE THREAD

**Issue by almorak** [serghey-rodin/vesta#2227]
### Operating System (OS/VERSION):

CentOS 7.8, CentOS 6.9

### VestaCP Version:
vesta 1.0.0(X86_64) release 1
vesta-php 0.9.8(X86_64) release 26
vesta-nginx 0.9.8(X86_64) release 26
vesta-ioncube  0.9.8(X86_64) release 26
vesta-softaculous 0.9.8(X86_64) release 26

### Installed Software (what you got with the installer):

httpd, nginx, named, exim, dovecot, clamd, spamassassin, mariadb, vsftpd, crond, iptables, fail2ban

### additional library installed
sk-php-selector

### Steps to Reproduce:

I got 3 centos server with vestacp installed. Everything work like a charm in the past few years.
lately, when I wanna update the domains' SSL manually, it prompted restart Nginx failed.
Then i refreshed the page and every config under that domain disappeared.
Aliases gone, web & proxy template reset to default, proxy extensions go blank .. etc
I tried to add an alias, it prompted save success. but everything remains the same.
[after editing domain, proxy gone](https://drive.google.com/file/d/106q-h5x7YWz6iefLQ2FIvj1WJBoFKXQ0/view?usp=sharing)

I checked the /etc/nginx/conf.d/vesta.conf
those include line after the editing in vestacp gone.
include /home/admin/conf/web/mydomain.com.nginx.conf; <---- gone

then I checked the conf under /home/admin/conf/web/
the mydomain.com.nginx.conf files are gone too.
i cp another .nginx.conf & modified it, added the include line to vesta.conf
but still the same.

There is no log  in /var/log/nginx/error.log
But got some in /var/log/vesta/error.log
2022-01-07 08:36:39 v-list-dns-domain  'admin' 'mydomain.com' [Error 3]
2022-01-07 08:36:40 v-restart-proxy  [Error 20]
2022-01-07 09:53:37 v-list-dns-domain  'admin' 'mydomain.com' [Error 3]
2022-01-07 09:53:38 v-restart-proxy  [Error 20]
2022-01-07 10:10:51 v-list-dns-domain  'admin' 'mydomain.com' [Error 3]
2022-01-07 10:10:52 v-restart-proxy  [Error 20]
2022-01-07 10:30:44 v-restart-proxy  [Error 20]
2022-01-07 10:34:56 v-delete-dns-record  'admin' 'mydomain.com' '10' 'no' [Error 5]
2022-01-07 10:34:56 v-restart-proxy  [Error 20]
2022-01-07 10:47:56 v-list-dns-domain  'admin' 'mydomain.com' [Error 3]
2022-01-07 10:47:57 v-restart-proxy  [Error 20]
2022-01-08 03:41:10 v-add-dns-domain  'admin' 'domain.com' '172.31.24.43' '' '' '' '' '' '' 'admin0' 'admin1' 'admin2' [Error 4]
2022-01-08 03:41:11 v-restart-proxy  [Error 20]

"nginx -t" result
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

Some log in vestacp Log tab:
disabled ssl support for mydomain.com
disabled proxy support for mydomain.com

**Comment by almorak** [comment]
i did some search, it may related to https://forum.vestacp.com/viewtopic.php?f=11&t=20703
should I update all or just need to update the vesta core?

**Comment by jaapmarcus** [comment]
apt-update && apt upgrade

**Comment by frkmusic** [comment]
i also face the same issue, when i try to add new domain under WEB tab, everything is removed like, ssl details, lets encrypt doesn't work anymore, everything was working perfectly until this vestacp ui update arrived. 
I guess there is a bug in new update.
Even when i modified previous domains , when i save changes, everything previously saved is removed, ssl cert details are also gone. and domain stops working with 'https'
Additional FTP settings doesn't work as well. Alias is not saved. When we click save button, it shows message 'saved' but it removes everything that was previously added before 'vestacp ui update release'
If anyone knows fix kindly let me know.

**Comment by wojsmol** [comment]
@frkmusic Witch VestaCP version you are using? Latest version is 1.0.0 release 5.
