### ISSUE TITLE
Domain edit Aliases textarea value bug. 

### ISSUE THREAD

**Issue by lizard2010** [serghey-rodin/vesta#2231]
### Operating System (OS/VERSION):
CentOS Linux release 7.9.2009 (Core)

### VestaCP Version:
vesta-1.0.0-1.x86_64

### Steps to Reproduce:

Edit any existed domain with aliases via web interface. 
'Aliases' field should contain predefined aliases, instead it is empty.
And, obviously, if domain with empty alias field save, information about aliases lost. 

### Other Notes:

Looks like bug with textarea value settings, changes from screenshot fixed bug for me. 

![telegram-cloud-photo-size-4-6005728108474382092-y](https://user-images.githubusercontent.com/503863/150510406-2ccc37b3-2831-404d-bc7c-71091cf7e3d1.jpg)

Sorry for informing in this way, I prefer PR, but I have no idea, where original of code web/static/js/main.96e25cf6.chunk.js is.

**Comment by wojsmol** [comment]
Latest VestaCP version is1.0.0-5. Please apply [this](https://github.com/serghey-rodin/vesta/pull/2074/files) fix and then run update.

**Comment by lizard2010** [comment]
> Latest VestaCP version is1.0.0-5. Please apply [this](https://github.com/serghey-rodin/vesta/pull/2074/files) fix and then run update.

Thank you. It looks like it helped.
