### ISSUE TITLE
Окно с логами отображается некорректно (и уже очень давно)

### ISSUE THREAD

**Issue by mihon4ik** [serghey-rodin/vesta#2233]
### Operating System (OS/VERSION):

CentOS release 6.5 (Final)

### VestaCP Version:

1.0.0
Release: 5

![Снимок](https://user-images.githubusercontent.com/18525804/153759898-c651fb8d-2512-4402-88fe-7806b6e596ef.PNG)

**Comment by anton-reutov** [comment]
update to 1.0.0.6
