### ISSUE TITLE
SSL update does not change Vesta certificate

### ISSUE THREAD

**Issue by TheLastProject** [serghey-rodin/vesta#225]
I recently bought a new SSL certificate and installed it for my main domain using the Vesta "edit" option for the domain. This went well. However, Vesta still uses the old certificate. I have also replaced the certificate in /usr/local/vesta/ssl, but this made no difference either.

For some reason I literally can't find out after hours and hours of searching, Vesta (port 8083) still uses the old certificate.

**Comment by SysVoid** [comment]
You likely forgot to restart the web server. Closing this as it's an old issue.
