### ISSUE TITLE
vesta-php.sock

### ISSUE THREAD

**Issue by bobimicroweber** [serghey-rodin/vesta#2255]
### Operating System (OS/VERSION):
Ubuntu 18

### VestaCP Version:
latest

### Installed Software (what you got with the installer):
php-fpm,nginx

Hello guys, i looking this days where is compiled vesta-php and vesta-nginx

i search the whole repository files and can't find package vesta-php and vesta-nginx

I want to know how can i build custom version of vesta-php or vesta-nginx

**Comment by jaapmarcus** [comment]
VestaCP doesn't have published their build scripts for the packages.

You might be able to reverse engineer it with the Hestia build script

https://github.com/hestiacp/hestiacp/tree/main/src

**Comment by bobimicroweber** [comment]
> VestaCP doesn't have published their build scripts for the packages.
> 
> You might be able to reverse engineer it with the Hestia build script
> 
> https://github.com/hestiacp/hestiacp/tree/main/src

is that your panel bro? Looks very nice

**Comment by jaapmarcus** [comment]
Yes,

Vesta should not being used any more!

See:
https://github.com/serghey-rodin/vesta/issues/2254
https://github.com/serghey-rodin/vesta/issues/2252
https://github.com/serghey-rodin/vesta/issues/2246
https://github.com/serghey-rodin/vesta/issues/2006

**Comment by bobimicroweber** [comment]
I want to change the web panel with laravel panel.. can we connect each other?

**Comment by jaapmarcus** [comment]
Join our Discord server
https://discord.gg/7SDeq8vg

Just ping me in the any public panel.
