### ISSUE TITLE
VestaCP server unreacable

### ISSUE THREAD

**Issue by mistergeeker** [serghey-rodin/vesta#2259]
### Operating System (OS/VERSION):

Ubuntu 18.04.6 LTS

### VestaCP Version:

1.0.0-6

### Installed Software (what you got with the installer):

vesta              1.0.0  6    amd64  yes   2022-02-27
vesta-php          1.0.0  1    amd64  yes   2021-10-31
vesta-nginx        1.0.0  1    amd64  yes   2021-10-31
vesta-ioncube      1.0.0  1    amd64  yes   2021-10-31
vesta-softaculous  1.0.0  1    amd64  yes   2021-10-31

### Steps to Reproduce:

> sudo apt-get update

And then, I received the following error message:
> E: Failed to fetch http://apt.vestacp.com/bionic/dists/bionic/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
> E: The repository 'http://apt.vestacp.com/bionic bionic InRelease' is no longer signed.

It turned out that the domain name "vestacp.com" is expired. 
I am just wondering, is VestaCP this project permanently dead?

![Screenshot 2022-07-26 at 16 58 21](https://user-images.githubusercontent.com/59912129/181055551-62f60820-49b5-4b60-9da5-2022300727bf.png)

**Comment by anton-reutov** [comment]
Please, waiting some time.

**Comment by LandyLane** [comment]
I hope it gets renewed soon. Needed to install it and hestia isn't as simple to setup

**Comment by anthonyrossbach** [comment]
> I hope it gets renewed soon. Needed to install it and hestia isn't as simple to setup

Should really not be using VestaCP anymore, long outdated, the OS versions and PHP versions it's running are now out of date in 2 months and no longer getting updates against security problems.

As I have been now using Hestia its setup is exactly the same.

**Comment by divinity76** [comment]
please see https://github.com/serghey-rodin/vesta/issues/2254
