### ISSUE TITLE
Blank web edit page

### ISSUE THREAD

**Issue by ozturkgurbuz** [serghey-rodin/vesta#2274]
### Operating System (OS/VERSION):

 Ubuntu 18.04.6 LTS

### VestaCP Version:

```
PKG                VER    REL  ARCH   UPDT  DATE
---                ---    ---  ----   ----  ----
vesta              1.0.0  6    amd64  yes   2022-02-28
vesta-php          1.0.0  1    amd64  yes   2021-10-31
vesta-nginx        1.0.0  1    amd64  yes   2021-10-31
vesta-ioncube      1.0.0  1    amd64  yes   2021-10-31
vesta-softaculous  1.0.0  1    amd64  yes   2021-10-31
```

### Installed Software (what you got with the installer):
apache2 - nginx - bind9 - exim4 - dovecot - clamav - daemon - spamassassin - mysql - vsftpd - cron - fail2ban

### Related Issues/Forum Threads:
https://forum.vestacp.com/viewtopic.php?f=11&t=20872

### Issue:
Vestacp working good.
![image](https://user-images.githubusercontent.com/63477571/210057073-a840c3e4-0340-4977-9e78-93bdd8d7cc39.png)

**Whenever I want to enter the webedit page, a white blank screen comes up as in the picture below. This only happens for the main domain and subdomains with wildcard SSL added.**
![image](https://user-images.githubusercontent.com/63477571/210057634-94f241e4-4f77-46df-9140-ed8604586f13.png)

### Console Error
**When clicked edit button in web tab,I am getting this error from console.**
![image](https://user-images.githubusercontent.com/63477571/212036449-14e18760-adb6-4c89-9bd5-2bd81c949d61.png)

**Comment by ozturkgurbuz** [comment]
It's been 3 weeks, no answer yet, still neither here nor on the forum, I guess it's true vesta is dead 😔

**Comment by lookslikekoss** [comment]
@ozturkgurbuz got same problem, seems like issue is in SSL files. In my case was extra TAB in domainname.key file, at the end of it. When it has extra TAB symbol parser located at `vestadomain:8083/api/v1/edit/web/index.php` crashes once getting NULL values.

So try to check all your SSL files located here: /usr/local/vesta/data/users/%your_username%/ssl for extra invisible symbols.

**Comment by ozturkgurbuz** [comment]
@lookslikekoss 
Thank you very much for the reply
I opened ssl files for all main domains and subdomains and checked all .key .ca .pem .crt files. I checked one by one line by line and couldn't find any spaces or tabs.
I just fixed a subdomain .key file with a tab space. Then I restarted the server.
The result has not changed.

**Comment by lookslikekoss** [comment]
@ozturkgurbuz I spent 4 hours until I found those parasite TAB :) Just pay a bit more attention, 99.99% you have same issue as mine

**Comment by ozturkgurbuz** [comment]
@lookslikekoss 

Thank you very much dude.
You were absolutely right and as you said, the problem was from there, I fixed it now.
I am writing my thanks now because I live in one of the cities that experienced the earthquake in Turkey, now I had the opportunity.
Thank you very much for your interest and reply.
👍🙏

**Comment by lookslikekoss** [comment]
@ozturkgurbuz you're welcome! Glad to know that was helpful!
