### ISSUE TITLE
vesta not installing on centos 6

### ISSUE THREAD

**Issue by obipeter8Ho** [serghey-rodin/vesta#2277]
### Operating System (OS/VERSION):

CentOS 6 64 bit and 32bit

### Steps to Reproduce:

When i try installing vesta on centos6, this is what i got. 

vst-install.sh: line 1: `<!DOCTYPE html><html lang="en"  data-adblockkey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANnylWw2vLY4hUn9w06zQKbhKBfvjFUCsdFlb6TdQhxb9RXWXuI4t31c+o8fYOv/s8q1LGPga3DE1L/tHU4LENMCAwEAAQ==_d7312m+UBn1imDl/v3Td/7je09RF0ULfHqTNsCrsbSmeehsfbYSyprf56EXA4yQGNdefpN5ZBf3Pk062DiasHQ==><head><meta charset="utf-8"><title>vestacp.com&nbsp;-&nbsp;vestacp Resources and Information.</title><meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0"><meta name="description" content="vestacp.com is your first and best source for all of the information you’re looking for. From general topics to more of what you would expect to find here, vestacp.com has it all. We hope you find what you are searching for!"><link'

Also have tried opening the website (vestacp.com) and its unreachable.

Kindly assist to take a look and resolve. thank you

**Comment by jaapmarcus** [comment]
Server is down I am afraid you need to look it to alternatives with MyVesta or Hestia

**Comment by obipeter8Ho** [comment]
any timeframe when server might be up?

**Comment by jaapmarcus** [comment]
I have no connections with any VestaCP developer sadly so I have no idea.  
![image](https://user-images.githubusercontent.com/9754650/223420023-b9919d09-623d-4d8b-ba5e-3218b2b316c5.png)

Is the issues with their DNS.

**Comment by jaapmarcus** [comment]
Server is online again ...
