### ISSUE TITLE
Как обновлять панель?

### ISSUE THREAD

**Issue by blackyangell** [serghey-rodin/vesta#228]
На github постоянно видны новые изменения и дополнения - то 2, то 4 дня назад и пр. А в разделе "Обновления" в панели модули почему-то не обновляются, ни автоматически, ни вручную.

Подскажите, что нужно делать, чтобы получать все самые свежие обновления? Спасибо.

**Comment by skurudo** [comment]
Релизы для панели собираются далеко не сразу.
Считайте, что на гитхабе эдаки бета-тест, а стейбл релиз уже виден в панели.
