### ISSUE TITLE
VestaCP not working on centos 6

### ISSUE THREAD

**Issue by obipeter8Ho** [serghey-rodin/vesta#2291]
### Operating System (OS/VERSION):

centos6 64 bit

### VestaCP Version:

Vesta CP installation not working on centos 6. Getting the following error

curl: (6) Couldn't resolve host 'vestacp.com'
bash: vst-install.sh: No such file or directory

Also checked the website and its down

Any help will be appreciated. thank you

**Comment by obipeter8Ho** [comment]
This is the 3rd time this year.. First in March, second in May and now today.. Is there anyway to install vesta smoothly even if the website goes offline?

**Comment by hmv47** [comment]
Vesta is dead, so is CentOS.

**Comment by thomasgatt** [comment]
Switch to HestiaCP, it is a fork of Vesta

**Comment by obipeter8Ho** [comment]
some of us still use and prefer vestacp. Anyone close to Serghey can help and make contact with him..

**Comment by anthonyrossbach** [comment]
Hate to say it but it’s not being update with security patches and is not safe to use anymore, not if you value security and updates. HestiaCP works exactly the same but has new security features and gets updates and patches, like for the recent http2 bug that allows a single computer to easily hit a web server with requests that can take it offline.

**Comment by anthonyrossbach** [comment]
This project has had no updates in a year, and no real updates or fixes in several years.

**Comment by obipeter8Ho** [comment]
Vesta works smooth on my centos6 and Hestia dont support centos6. So for now, i have to stick with vesta. I wish there were alternative ways to install vesta even when the website is unavailable.

**Comment by anthonyrossbach** [comment]
Centos6 is long EOL for 3 years now and should not be used as it is NOT secure and at all since 2020. If you are using it you need to move off of it as soon as possible, not keep using it.

**Comment by obipeter8Ho** [comment]
yes you are right but its also a thing of choice bro.. i still prefer it for some of the things i run.

**Comment by anthonyrossbach** [comment]
That’s not a preference, that’s a huge security risk.

**Comment by obipeter8Ho** [comment]
thank you for your point. we will consider that. Please anyone reach Serghey yet?

**Comment by Skamasle** [comment]
Vestacp is up again

**Comment by anton-reutov** [comment]
Sergey is not interested in this project anymore. Sorry for this situation.
