### ISSUE TITLE
vesta not installing on centos 6

### ISSUE THREAD

**Issue by obipeter8Ho** [serghey-rodin/vesta#2294]
### Operating System (OS/VERSION):

centos 6

I get this error below when installing

File contains no section headers.
file: file:///etc/yum.repos.d/CentOS-Base.repo, line: 1
'<!doctype html>\n'

can anybody help? thank you

**Comment by Skamasle** [comment]
If you need CentOS 6, please use vault repos

CentOS 6 is obsolete more than 4 years.
