### ISSUE TITLE
[Bug] Core 0.9.8-10, Vesta-PHP 0.9.7-3: Changing system IP makes editing web domains return "Parsing Error" on save.

### ISSUE THREAD

**Issue by Term1nal** [serghey-rodin/vesta#230]
I used the page to change the system IP address, which seemed to work, but caused me to be unable to edit web domain settings until I returned the system IP back to what it was originally. This also occurs using the commandline interface to accomplish the same task. The only way around it, is to delete the web domain and re-add it (while under the new system IP).

**Comment by LostNerdUK** [comment]
I've also been facing this issue. @Term1nal is correct in saying that the only current workaround is by changing the main IP back which is a hassle.

**Comment by wyamout** [comment]
Same here, after stopping instance and starting again in amazon AWS a new ip address is assigned, I can still see old ip address showing under Web and cant save any edits in domains.

**Comment by rocky123xo** [comment]
Same issue.

**Comment by diego-vieira** [comment]
+1 using 0.9.8 release 12
