### ISSUE TITLE
[Feature Request] Nginx PHP-FPM

### ISSUE THREAD

**Issue by rmalenko** [serghey-rodin/vesta#234]
Hello,

Thanks for possibilities write own template. However sometime I and someone want to configure PHP-FPM for each website. I mean FPM pool. There is lack of to possibility create template for PHP-FPM and Nginx that each of website has own FPM pool or possibilities select predefined pool. 

Br,
Rostyslav

**Comment by Ham3D** [comment]
hey @serghey-rodin give me your twitter or email, i have something to share with you.
and what happened about this patch ? you said it will be ready in one week or so ...

**Comment by anton-reutov** [comment]
Already implemented
