### ISSUE TITLE
httpd failed when I try to suspend/unsuspend a domain.

### ISSUE THREAD

**Issue by crackdepirate** [serghey-rodin/vesta#253]
I receive "httpd service failed" message in control panel. 

check log, see :
"[root@0000000000 public_html]# service httpd restart
Stopping httpd:                                            [FAILED]
Starting httpd: httpd: Syntax error on line 89 of /etc/httpd/conf/httpd.conf: Syntax error on line 2 of /etc/httpd/conf.d/vesta.conf: Syntax error on line 407 of /home/admin/conf/web/httpd.conf: </VirtualHost><VirtualHost> directive missing closing '>'
                                                           [FAILED]
"

In file: '/home/admin/conf/web/httpd.conf:', 

find this: "</ VirtualHost >< VirtualHost 192.99.xxx.xxx:8080 >"

need to be [on different line] like :
"
</ VirtualHost>

< VirtualHost 192.99.xxx.xxx:8080>
"

restart httpd, it works.
if you can correct that, that will be nice.

**Comment by SysVoid** [comment]
Glad you got it fixed. Closing.
