### ISSUE TITLE
[Optimize][v-list-web-domains] Inefficient domain key in array

### ISSUE THREAD

**Issue by EminezArtus** [serghey-rodin/vesta#262]
Please don't make the output array main key the domain:

        `Array ( 
            [0] => Array
            ( 
                [DOMAIN] => 'example1.tld'
                [ETC] => '...'
            )
            [1] => Array 
            ( 
                [DOMAIN] => 'example2.tld'
                [ETC] => '...'
            )
        )`

Not

        `Array ( 
            ['example1.tld'] => Array ( 
                [ETC] => '...'
            )
            ['example2.tld'] => Array ( 
                [ETC] => '...'
            )
        )`

Otherwise we have to do extra steps to be able to pull the main domain.

        `$domains = array_keys($response);
       
        $return = '';
        foreach($response as $key=>$value)
        {
            $return[] = $response[$key];
        }
        
        foreach($return as $key=>$value)
        {
            $return[$key]['DOMAIN'] = $domains[$key];
        }`

**Comment by SysVoid** [comment]
Hello!

I am closing the issue due to inactivity.

Thank you for raising this issue, and please feel free to open it up again if this is still an active problem.
