### ISSUE TITLE
WHMCS Error: Limit reached / Upgrade package 

### ISSUE THREAD

**Issue by MdNor** [serghey-rodin/vesta#264]
I'm not sure whether WHMCS module should be discussed here, but I'll just try my luck.
I'm having problem creating new account using WHMCS module.

**Symptom**
Account actually created inside VestaCP, but WHMCS return "Error: Limit reached / Upgrade package" with pending status. Previously, there's only 1 account inside VestaCP which is _admin_

![whmcs-vestacp-error](http://i.imgur.com/EvqpEzF.png)

**Quota already enabled**
df -h

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        20G  1.9G   17G  10% /
tmpfs           246M     0  246M   0% /dev/shm
```

quota -u admin

```
Disk quotas for user admin (uid 501): 
     Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
      /dev/vda1     416  10000000 10050000              69       0       0  
```

I don't even know where to begin troubleshooting, as WHMCS debug log doesn't record anything. I manage to replicate this issue on 2 different servers.

I'm having [similar issue as reported by Asuka in forum](https://forum.vestacp.com/viewtopic.php?f=10&t=4804), but there is no solution yet.

**Comment by altomarketing** [comment]
Any upgrade about this bug ?

**Comment by MdNor** [comment]
@altomarketing 
I think this hasn't been logged as bug at all. I already destroy my Vesta server so I'm unable to try the suggested solution. 

If you have similar problem, try replying to @serghey-rodin suggestion on disabling FS quota.

**Comment by rmlhhd** [comment]
@serghey-rodin Seems this is still an on going issue, I can't use VestaCP with WHMCS because of this.

Running that quota command give me this - 

 v-delete-sys-quota
sed: -e expression #1, char 1: missing command
quotaoff: Mountpoint (or device) / not found or has no quota enabled.

**Comment by neuropass** [comment]
Can someone confirm this?

**Comment by zeahouse** [comment]
Планируются обновления под WHMCS 8.* ?
