### ISSUE TITLE
v-add-sys-quota issues

### ISSUE THREAD

**Issue by TheLastProject** [serghey-rodin/vesta#269]
When enabling v-add-sys-quota on Debian 7, the following message will be mailed daily:

```
/etc/cron.daily/quotacheck:
run-parts: failed to exec /etc/cron.daily/quotacheck: Exec format error
run-parts: /etc/cron.daily/quotacheck exited with return code 1
```

Running the command in /etc/cron.daily/quotacheck manually gives the following error:

```
# quotacheck -um /
quotacheck: Quota for users is enabled on mountpoint / so quotacheck might damage the file.
Please turn quotas off or use -f to force checking.
```

**Comment by ChristianGrech** [comment]
+1 on ubuntu

**Comment by Scorcher** [comment]
+1 Ubuntu 14.04, VestaCP 0.9.8-15
https://bugs.vestacp.com/responses/etc-crondaily-quotacheck-exec-format-error
https://forum.vestacp.com/viewtopic.php?t=9910#p35608

Where we should report a bugs preferable? bugs.vesta/github/forum?

**Comment by didyouexpectthat** [comment]
I have this on Debian 8.

``/etc/cron.daily/quotacheck`` is just ``quotacheck -um /``, so first you should edit /etc/cron.daily/quotacheck and add ``#! /bin/sh`` to the top. Secondly, make sure your /etc/fstab has mount options ``usrquota,grpquota``.
