### ISSUE TITLE
Can't change vestacp password from terminal

### ISSUE THREAD

**Issue by marii89** [serghey-rodin/vesta#274]
Hello,

I use Ubuntu from nowhere i can't login in my vestacp with my old password,
I try to change password from terminal with:

v-change-user-password admin newpassword

and not work, what is next solution for change vestacp admin password from terminal ?

Thanks.

**Comment by slrslr** [comment]
Vesta logs should be located in /usr/local/vesta/log/

**Comment by infoir** [comment]
I am trying to install vestacp on ubuntu12.04 from last week but the installation process gets terminated when 'webalizer' starts installing. So I removed the webalizer package from the installation script. Then the whole vestacp installs successfully. I also got the password. But now I am unable to login with that login details. Everytime it shows invalid username and password. I even tried to change the password using "/usr/local/vesta/bin/v-change-user-password admin mynewpass" but I am still getting the same error.

**Comment by isneezy** [comment]
I recently had similar problem and i solved by using the UNIX command `passwd`
```bash
root@ip-xxx-xx-xx-xx:/# passwd admin
Enter new UNIX password: 
Retype new UNIX password: 
passwd: password updated successfully
root@ip-xxx-xx-xx-xx:/#
```
Replace the word admin with your vestaCP username

**Comment by slrslr** [comment]
I also have this problem. This may be related: https://forum.vestacp.com/viewtopic.php?f=40&t=17644
