### ISSUE TITLE
Cron Daemon sending emails continuously to admin email.

### ISSUE THREAD

**Issue by performadigital** [serghey-rodin/vesta#275]
This is not so much an issue but a bit of a nuisance for me.

By default the admin user's cron tasks are all set to not be silent so send emails (some as often as every 5 minutes).

Could the cron tasks for admin not use > /dev/null 2>&1 by default to prevent this?

This caused my server emails to then be flagged as spam by Gmail as it had sent 1,000's of emails by the time I noticed it.

**Comment by TheLastProject** [comment]
Are these error messages or not? I'm just another user, but for me, they are error messages sent daily:
```
/etc/cron.daily/logrotate:
error: skipping "/var/log/roundcube/errors" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/roundcube/sendmail" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/roundcube/session" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
error: skipping "/var/log/roundcube/userlogins" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
/etc/cron.daily/quotacheck:
run-parts: failed to exec /etc/cron.daily/quotacheck: Exec format error
run-parts: /etc/cron.daily/quotacheck exited with return code 1
```

Clicking ```[ turn off notifications ]``` in the cron tab doesn't seem to change anything for me. Not trying to hijack this issue, but trying to figure out if this is the same issue I'm having.

Debian 7 here

**Comment by performadigital** [comment]
I resolved the issue simply by adding the >dev/null etc to cron commands but your issue appears to be due to /var/log/roundcube/ on your server being writable. I'd suggest looking at the permissions and possible setting it as something like 755 or less permissive.

Hadn't noticed a 'turn off notifications' in cron tab, that might have been exactly what I was meaning, voiding my issue!

**Comment by performadigital** [comment]
Closing this issue as it can easily be resolved by clicking the 'Turn off notifications' in Cron. Had just missed this! My bad/
