### ISSUE TITLE
New or updated IP; give error 504, 408

### ISSUE THREAD

**Issue by EminezArtus** [serghey-rodin/vesta#276]
I had to get a new IP and when I updated my IP everything went smooth, but when i tried to connect to any of the domains on my node I would get 504 or 408 http error.

It turns out that the firewall never updated, so I had to go into the panel and reapply all the firewall rules.
Now its working. I'm on Cent 6.5.

**Comment by serghey-rodin** [comment]
Thanks for report @EminezArtus. It's a shame we didn't think about it earlier. I will take care about it!
