### ISSUE TITLE
cron daemon sends message "MAIL_SYSTEM is not enabled"

### ISSUE THREAD

**Issue by zapalm** [serghey-rodin/vesta#277]
hello

how to disable or fix an issue with cron daemon that sends message "MAIL_SYSTEM is not enabled"?

indeed, I have turned off exim in the configuration due to uselessness (i using only sendmail).
it looks like a bug, because check should be made in the script - if a mail system is disabled in the configuration then cron do not need to notify the administrator by email.
but another thing when cron should notify the administrator - for example, if included in the configuration a mail system but it is not running...

a topic in the forum about this problem: https://forum.vestacp.com/viewtopic.php?f=31&t=6674&p=19762#p19762

**Comment by serghey-rodin** [comment]
Hello @zapalm 
Good point. We will fix that. As for now you disable cron email reporting using
```
v-delete-cron-reports admin
```

**Comment by KuJoe** [comment]
@serghey-rodin The command provided does not fix this. Additionally this message is being e-mailed to the wrong e-mail address for me (is it using the /etc/passwd- file by chance? I can't find any other mention of my old e-mail address anywhere else).

**Comment by serghey-rodin** [comment]
Account emails are stored in /usr/local/vesta/data/users/admin/user.conf You can modify this file using text editor or via web interface in control panel. 
Just make sure that there is no MAILTO in your crontab for admin user
crontab -l -u admin

**Comment by KuJoe** [comment]
The user.conf files has the correct e-mail and there's no MAILTO in the crontab (I manually changed it to MAILTO="" but that got cleared for some reason). We'll see if I get an e-mail tomorrow after rebooting the server. Thanks for the help. :)
