### ISSUE TITLE
trying to delete a domain, get "Error code: 20"

### ISSUE THREAD

**Issue by crackdepirate** [serghey-rodin/vesta#278]
hello, 

trying to delete a domain name as "testcolis.com" and get "error code: 20" 

what can I do to give you more details on that issue?

thank you

**Comment by EminezArtus** [comment]
Why are you deleting, How are you deleting, Have you modified any configuration files? What version # of vesta are you using, what linux distribution are you using?

**Comment by crackdepirate** [comment]
Why: made a mistake in the name.
How: click on the 'x delete' button under WEB menu
Modif. config files: yes, create a new template for nginx and httpd
I saw the error under the UI.

vesta version:
vesta:0.9.8, R12
vesta-php:0.9.7 R3
vesta-nginx:0.9.8 R3

OS: Centos 5.6, 64b

=======
log file:
/var/log/vesta/error.log
2015-01-08 20:41:36 v-delete-web-domain admin testcolis.com no       [Error 12]
2015-01-09 05:10:02 v-backup-user admin         [Error 12]
2015-01-09 05:10:02 v-backup-user admin         [Error 12]
2015-01-09 20:05:19 v-list-user root json        [Error 3]

laravel templates:
https://gist.github.com/crackdepirate/c83288610a9d6e86b5c6


if you need more info, please don't hesitate.

**Comment by EminezArtus** [comment]
This sounds dumb but change the template back to hosting or default and try to delete if that works it may be permissions on the template files you created.

**Comment by crackdepirate** [comment]
I already did that. 

So when I click 'edit', change httpd & nginx template to 'default', I get pop-up 'error code 12'.
Where I can find the meaning of theses codes?

see /var/log/vesta/error.log
2015-01-11 00:38:52 v-change-web-domain-tpl admin testcolis.com default no      [Error 12]
2015-01-11 00:39:59 v-delete-web-domain admin testcolis.com no       [Error 12]

**Comment by EminezArtus** [comment]
Try:
v-rebuild-user admin see if it updates any messed up files.

**Comment by crackdepirate** [comment]
sounds weird. this is my error:

[zz@zzzzzzzzzzzz bin]# v-rebuild-user admin
chmod: cannot access `/etc/exim/domains/default.domain': No such file or directory

in fact, the default.domain was disabled under 'mail' menu. So, I enable it. re-run the command line. no error. I've tried to delete my domain and get fail again. Error code 20.

==
permissions on templates are correct. admin:admin  -rwxr-xr-x

**Comment by EminezArtus** [comment]
# Error codes
OK=0
E_ARGS=1
E_INVALID=2
E_NOTEXIST=3
E_EXISTS=4
E_SUSPENDED=5
E_UNSUSPENDED=6
E_INUSE=7
E_LIMIT=8
E_PASSWORD=9
E_FORBIDEN=10
E_DISABLED=11
E_PARSING=12
E_DISK=13
E_LA=14
E_CONNECT=15
E_FTP=16
E_DB=17
E_RRD=18
E_UPDATE=19
E_RESTART=20 <- must be a issue restarting a service.

/usr/local/vesta/log/system.log
/usr/local/vesta/log/log/error.log

Check and see if all your services are running if one isn't restart the service in the console to see what the error is. Maybe this way you can fix the problem.

**Comment by crackdepirate** [comment]
Oh, that's interesting. Yes, I've turned off 2 services manually which are 'iptables' and 'fail2ban'. 
I am using CSF/LFD instead. 

but I tought that E_RESTART is related to httpd and nginx.

/usr/local/vesta/bin/v-delete-web-domain :

```
# Restart web server
if [ "$restart" != 'no' ]; then
    $BIN/v-restart-web
    if [ $? -ne 0 ]; then
        exit $E_RESTART
    fi
    $BIN/v-restart-proxy
    if [ $? -ne 0 ]; then
        exit $E_RESTART
    fi
fi
```


services httpd, nginx, exim, dovecot, mysqld,vsftpd, are up and running.

So, I will made some test since the UI returns me "error code 20" and the 'error.log' file, returns 'error code 12'

I copied default.tpl over laravel.tpl ,and get same result. Where is the parsing error?

thx for your help EminezArtus.

**Comment by serghey-rodin** [comment]
Sorry for late reply. Can you please send me /tmp/debug.log ? You can produce debug log using following commands
```
user=$(v-search-domain-owner testcolis.com)
bash -x v-delete-web-domain $user testcolis.com >/tmp/debug.log 2>&1
``
Thanks

**Comment by crackdepirate** [comment]
no problem. 

you can retrieve the debug.log under
https://gist.github.com/crackdepirate/1be49af3e642b457e548

sorry to miss that detail, but the domain is a fake domain, no ns, no a records are binded to that domain. I had created that domain to test my tpl files.

thank you,
