### ISSUE TITLE
v-sync-dns-cluster not syncing Serial #

### ISSUE THREAD

**Issue by EminezArtus** [serghey-rodin/vesta#283]
## v-sync-dns-cluster:

Isn't syncing serial numbers on slaves. This causes serial number mismatch.
http://mxtoolbox.com/problem/dns/DNS-SOA-Serial-Numbers-Match/

**Comment by serghey-rodin** [comment]
That's true, serials aren't synchronized. However it should only affect you if time on servers within a cluster is not synced by ntp. Can you please check if it is the case?

**Comment by EminezArtus** [comment]
By default it's not NTP is not installed do I need to install and use NTP? or what can I do to verify if its syncing with NTP?

**Comment by serghey-rodin** [comment]
NTP server isn't really necessary, all you need is NTP client. Vesta should install it by default. Just make sure the time is the same on all dns servers. If it's not you can easily fix it using following command
```
ntpdate -s pool.ntp.org
```

And in case there was no ntp cron job you can create it
```
/usr/sbin/ntpdate -s pool.ntp.org > /etc/cron.daily/ntpdate
chmod a+x /etc/cron.daily/ntpdate
```

**Comment by EminezArtus** [comment]
Ok I was wrong NTP is installed. I synced both server and did verify there was a cron job. I started clock on both servers `watch -n 0 date +%r` and everything looked good but serials still don't match. So I also deleted all the DNS records on the secondary server and also rebooted same issue with serials. I'm using UTC on both servers. What else can I do?

**Comment by serghey-rodin** [comment]
Yeah that's a tricky part. Can you please create new dns record on the master and check if it helps. Thank you

**Comment by EminezArtus** [comment]
Do I also need to setup AXFR (Zone Transfer) to update zones. DNS is not my area of expertise :D

**Comment by serghey-rodin** [comment]
No AXFR is not used in dns cluster implementation

**Comment by EminezArtus** [comment]
I added a new test record and it was pushed by its self to secondary NS but there is still a mismatch.

**Comment by EminezArtus** [comment]
Should I build a script to sync each domains serial with the parent? What do you suggest?

**Comment by EminezArtus** [comment]
I found out the issue, the issue is lag. I was doing this from one server in US  to another in UK. Maybe we can design something more precises?

**Comment by 7thkey** [comment]
I'm having the same problem but servers located on the same country and both working with ntpdate.
Why are serials not synchronized? Is there a way to patch this?
