### ISSUE TITLE
Q: Can we update vesta installed with the last version of master branch?

### ISSUE THREAD

**Issue by crackdepirate** [serghey-rodin/vesta#289]
Q: Can we update vesta installed with the last version of master branch?

if so, how ? 

thank you,

**Comment by EminezArtus** [comment]
I believe it is as follows:
>git remote add upstream https://github.com/serghey-rodin/vesta.git
git fetch upstream
git checkout master
git merge upstream/master

Syncing a fork: https://help.github.com/articles/syncing-a-fork/

**Comment by serghey-rodin** [comment]
As for the instance update you can use following commands
```
cd $(mktemp -d)
git clone git://github.com/serghey-rodin/vesta.git
/bin/cp -rf vesta/* /usr/local/vesta/
```
