### ISSUE TITLE
[Request] Vestacp.com Repo

### ISSUE THREAD

**Issue by EminezArtus** [serghey-rodin/vesta#290]
Please make the Vestacp.com website available so we can contribute different languages, fix typos, How to's, etc.

I think it should be available for the community to contribute to it.
An example: https://github.com/sentora

Also you should really think about making the new version Vestacp public, so we can beta test and submit pull requests, I don't understand why there is so much secrecy, if you want to make money on certain features, make a third party plugin system and make features available for purchase through a license, or subscription.

**Comment by crackdepirate** [comment]
great idea!

**Comment by GeertJohan** [comment]
:+1:

**Comment by serghey-rodin** [comment]
Thank you for you support Stuart.  I can assure you that Vesta will remain public open source project. We don't plan to fork it and develop two different versions at the same time. Just like you said the new version is just a version with ability to purchase and install additional modules. Not all of them will be free, like for example [FileManager](http://i.imgur.com/rnt0Q62.png). In new version Service tab will be renamed to System. It will work just like before with one exceptions. It will allow you to [configure](http://i.imgur.com/zPYGd26.png) server and its services.

The lack of information and updates isn't related to secrecy. We just don't have enough resources to make everything that was planned in time.

We are looking positive to translate website to other languages as well. Please give us a little bit more time to finish our current tasks :)

**Comment by EminezArtus** [comment]
Sounds good to me :) , thanks for the reply.
So if we do pull requests etc, how will you incorporate them into the new version? Should we stop doing pull requests, or just keep doing what we do?

**Comment by serghey-rodin** [comment]
Yes please continue to send pull requests. We will definitely review all of them before the new release. Thanks :)

**Comment by skurudo** [comment]
Hello, on screenshot with file manager I don's see buttons for chown / chmod. These features will be in paid version?

**Comment by joubertredrat** [comment]
:+1: :)

**Comment by skurudo** [comment]
Old thread.. closed.
