### ISSUE TITLE
Не добавляются сайты в конфиги

### ISSUE THREAD

**Issue by vickrasov** [serghey-rodin/vesta#299]
Когда в панели создаю новый сайт - там пишет, что все ок. Но в конфиги nginx и apache ничего не записывается. Соответственно, сайт не показывается. Как это можно исправить?

**Comment by skurudo** [comment]
А где вы конфиги смотрите? Конфигурационные файлы пользователей лежать /home/vashuser/conf

**Comment by vickrasov** [comment]
да, я там и смотрел. вот сейчас написало что сайт создан - http://joxi.ru/82QqQPpC3EXV2d, а в конфигах пусто. Из-за этого сайт не открывается
