### ISSUE TITLE
New lines at the end of vesta.conf prevent user login web interface

### ISSUE THREAD

**Issue by howanghk** [serghey-rodin/vesta#301]
Recently I enabled fail2ban on one of my server with vestacp installed. I added `FIREWALL_EXTENSION='fail2ban'` to the end of my `vesta.conf` file, and accidentally leaving **2 blank lines** at the end of file, like this:

```
WEB_SYSTEM='apache2'
WEB_RGROUPS='www-data'
WEB_PORT='8080'
WEB_SSL='mod_ssl'
WEB_SSL_PORT='8443'
PROXY_SYSTEM='nginx'
PROXY_PORT='80'
PROXY_SSL_PORT='443'
FTP_SYSTEM='vsftpd'
MAIL_SYSTEM='exim4'
IMAP_SYSTEM='dovecot'
ANTIVIRUS_SYSTEM=''
ANTISPAM_SYSTEM=''
DB_SYSTEM='mysql'
DNS_SYSTEM='bind9'
STATS_SYSTEM='webalizer,awstats'
BACKUP_SYSTEM='local'
CRON_SYSTEM='cron'
DISK_QUOTA='no'
REPOSITORY='cmmnt'
VERSION='0.9.8'
LANGUAGE='en'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'


```

This will cause `v-list-sys-config json` to output invalid JSON (notice the extra comma at the end)

```
{
    "config": {
        "WEB_SYSTEM": "apache2",
        "WEB_RGROUPS": "www-data",
        "WEB_PORT": "8080",
        "WEB_SSL": "mod_ssl",
        "WEB_SSL_PORT": "8443",
        "PROXY_SYSTEM": "nginx",
        "PROXY_PORT": "80",
        "PROXY_SSL_PORT": "443",
        "FTP_SYSTEM": "vsftpd",
        "MAIL_SYSTEM": "exim4",
        "IMAP_SYSTEM": "dovecot",
        "ANTIVIRUS_SYSTEM": "",
        "ANTISPAM_SYSTEM": "",
        "DB_SYSTEM": "mysql",
        "DNS_SYSTEM": "bind9",
        "STATS_SYSTEM": "webalizer,awstats",
        "BACKUP_SYSTEM": "local",
        "CRON_SYSTEM": "cron",
        "DISK_QUOTA": "no",
        "REPOSITORY": "cmmnt",
        "VERSION": "0.9.8",
        "LANGUAGE": "en",
        "FIREWALL_SYSTEM": "iptables",
        "FIREWALL_EXTENSION": "fail2ban",
    }
}
```

The invalid json will cause `json_decode()` in `web/login/index.php` line 31 return NULL, and hence the variables in `vesta.conf` are not populated into `$_SESSION` on line 33-35.

After successful login, the checking in `web/inc/main.php` line 4 will fail as `$_SESSION['VERSION']` is not set, and redirect user back to login page.

**Comment by howanghk** [comment]
Of course the simplest way to fix this is to remove the extra blank line at the end of `vesta.conf` file (that's what I did), but a fix in `v-list-sys-config` is appreciated.

**Comment by crackdepirate** [comment]
wah ! great one.
