### ISSUE TITLE
After adding new IP Vesta needs to restart iptables to prevent 500 error

### ISSUE THREAD

**Issue by performadigital** [serghey-rodin/vesta#304]
Recently routed an additional IP to a server and added this in Vesta with a domain assigned specifically to the domain.

Continually got 500 errors when trying to load the domain in browser. After looking thought nginx and apache config there were no issues, permissions and ownership were absolutely fine too.

After reading a couple of pointers on the Vesta forums I restarted the iptables service and this resolved the issue.

Surely this should be done automatically when adding a new IP though? Is there any reason for this not being the case?

**Comment by EminezArtus** [comment]
Already Solved https://github.com/serghey-rodin/vesta/issues/276

**Comment by performadigital** [comment]
Agreed, duplicate issue.
