### ISSUE TITLE
Error code: 12 при попытке заморозить (suspend) сайт

### ISSUE THREAD

**Issue by ss-abramchuk** [serghey-rodin/vesta#305]
Добрый день! При попытке заморозить сайт, в настройках которого включен nginx и ssl, вылетает ошибка с кодом 12. По всей видимости дело этом участке кода файла v-suspend-web-domain:

    # Checking proxy SSL
    if [ ! -z "$PROXY" ] && [ "$SSL" = 'yes' ]; then
        tpl_file="$WEBTPL/$PROXY_SSL/$PROXY.stpl"
        conf="$HOMEDIR/$user/conf/web/s$PROXY_SYSTEM.conf"
        del_web_config
        add_web_config
    fi

Вместо `$PROXY_SSL` должно быть `$PROXY_SYSTEM`, тогда все работает корректно. Поправьте, пожалуйста.

**Comment by serghey-rodin** [comment]
Спасибо за помощь. Баг исправлен.
