### ISSUE TITLE
Fresh Install on Ubuntu 14.04: Bug when adding database: mysql Crash

### ISSUE THREAD

**Issue by vincentcox** [serghey-rodin/vesta#306]
<p>Details:</p>
- Fresh install on DigitalOcean (VPS provider): ubuntu 14.04 32bit
- Added one website
- added an ftp user account
- trying to make database user ==> error:  Error: Connection failed
<p>RoundCube etc don't work after that point (before that point it worked well).
only fix is to reboot, but when trying to make database user==> problem happens again</p>
<p>Very weird because this happened on a clean install.</p>
<p>Will delete my VPS-server and start over I guess</p>
<p>edit: might be related to this thread, but not sure about that: https://github.com/serghey-rodin/vesta/issues/221</p>
<p>edit 2: seems like "update-rc.d mysql disable" keeps the rest up after the error. But the error remains</p>

**Comment by serghey-rodin** [comment]
Can you please email me login credentials to skid@vestacp.com I would like to test it on DO. Thanks

**Comment by oregapam** [comment]
I have same problem! (Don't have SWAP partition, if it helps!)

**Comment by EminezArtus** [comment]
May be related to issue #300

**Comment by oregapam** [comment]
Maybe, but my Hosting partner disabled swap creation, so this solution can't work for me.
The funny part: on debian wheezy the mysql don't crash, but the roundcube and most of things are outdated.

**Comment by vincentcox** [comment]
@oregapam : can you send your set-up login to the owner of the project (serghey-rodin). If it makes 2 of us, it means more people will face this issue.
I have setup my site manually in the meantime. It was bussiness critical so I had to remove my VPS.

vincent

**Comment by oregapam** [comment]
@vincentcox : Sorry, but i removed that ubuntu install and installed 12.04 with vestaCP, but at this time have problems with mail server, so I think if you want to make business now, you should search another control panel solution! (I doing this too...)

Mark

**Comment by vincentcox** [comment]
@oregapam What you say is hard for the developer. He did the effort to support us.
But you are kind of right: there is not much documentation available online. Also I really prefer Nginx in combination with php5-fpm. The speed is unbeatable. That's why I am using ispconfig at the moment. I really miss the simplicity vestacp had, but it fits more my needs (php5-fpm). 
The moment nginx and fpm is available in vestaCP, and more documentation is online I really go back to vestaCP. The one - click install is just awesome.

**Comment by superservidor** [comment]
I had the same problem after first reboot of the vps server with a fresh install of vestacp under Ubuntu 14.04 64 bits minimal. I solved the error following the steps indicated below.

To repair that error you must run as root at console the following command:

update-rc.d mysql disable

then reboot the server and the problem will be solved.

**Comment by superservidor** [comment]
Hi guys,

If some of you are having troubles with RoundCube Database after a fresh install of VestaCP in Ubuntu 14.04 64 bits only do the following thinsg:

1. execute this command as root:

update-rc.d mysql disable

2. Reboot the server and load again the webmail interface to send a test mail.

Don't do anything else, only run the previous command, restart the server  and the problem will be solved.

Long Live to VESTACP !!! It is the best control panel I have ever used.

Serghey, you are a great guy and a very smart human being !!! I send my Congratulations for VestaCP.
