### ISSUE TITLE
Error on install in Ubuntu

### ISSUE THREAD

**Issue by joubertredrat** [serghey-rodin/vesta#308]
Hi guys,

I saw here that install script was changed recently in https://github.com/serghey-rodin/vesta/commit/242ac15d5d3f5fc407db745ce3b7ab42d77a3722, but this don't work on Ubuntu.

When you run this script on Ubuntu, script always use rhel because not all Ubuntu installations have /etc/issue, me as example have 6 severs, only 4 have this file and is all Ubuntu 14.04

Because this issue, if don't have /etc/issue file, script assume that OS is rhel, then on install ...
```
root@rina:~# bash vst-install.sh
--2015-02-06 16:22:40--  http://vestacp.com/pub/vst-install-rhel.sh
Resolving vestacp.com (vestacp.com)... 104.236.66.100
Connecting to vestacp.com (vestacp.com)|104.236.66.100|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28984 (28K) [text/plain]
Saving to: 'vst-install-rhel.sh'

100%[===========================================================================================================>] 28,984      --.-K/s   in 0.1s    

2015-02-06 16:22:40 (287 KB/s) - 'vst-install-rhel.sh' saved [28984/28984]

Error: sorry, we currently support RHEL and CentOS only
root@rina:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
```

I remember another open source project that use script to detect OS, is Librenms.
This is their script, https://github.com/librenms/librenms/blob/master/scripts/distro

I will try to portable to vesta install script and test to be if works and I will post here again.
I hope to be helped.

Thanks

**Comment by EminezArtus** [comment]
This will be fixed in the mean time you can use:
wget http://vestacp.com/pub/vst-install-ubuntu.sh
bash vst-install-ubuntu.sh

**Comment by joubertredrat** [comment]
Thanks @EminezArtus,

I know this file and works fine, I tested a few seconds ago :)

**Comment by EminezArtus** [comment]
What does $(head -n1 /etc/issue | cut -f 1 -d ' ') give you in the console?

**Comment by joubertredrat** [comment]
@EminezArtus this is my output in my Ubuntu servers

```
root@rina:~# echo $(head -n1 /etc/issue | cut -f 1 -d ' ')

root@rina:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
```
```
root@mahoro:~# echo $(head -n1 /etc/issue | cut -f 1 -d ' ')

root@mahoro:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
```
```
root@shizuku:~# echo $(head -n1 /etc/issue | cut -f 1 -d '')
Welcome to Ubuntu 12.04.4 LTS (GNU/Linux 3.10.23-xxxx-std-ipv6-64 x86_64)
root@shizuku:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"
```
```
root@srv1:~# echo $(head -n1 /etc/issue | cut -f 1 -d ' ')
head: cannot open `/etc/issue' for reading: No such file or directory

root@srv1:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"
```
```
root@srv3:~# echo $(head -n1 /etc/issue | cut -f 1 -d ' ')
Ubuntu
root@srv3:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"
```

**Comment by EminezArtus** [comment]
Nothing in $(cat /etc/issue)? if so we might need to change it back to what it was :D

**Comment by joubertredrat** [comment]
@EminezArtus On Rina and Mahoro, file is empty, on Shizuku have a big welcome text, on Srv1 file doesn't exists and on Srv3 is "Ubuntu 12.04.5 LTS \n \l"

**Comment by zorrobyte** [comment]
Still an issue on 14.04 with default script. If no fix is scheduled, I'd recommend updating the Documentation. Took me a few hours to find the fix.

**Comment by KeiroD** [comment]
... Technically I have a fix for this. Technically. But it's not quite... optimal, as yet. I'll look into it and see what do.

**Comment by batailley** [comment]
Still an issue, please update install doc, everybody would save time :)
Thanks!
