### ISSUE TITLE
Не могу переустановить панель

### ISSUE THREAD

**Issue by vickrasov** [serghey-rodin/vesta#309]
За инструкцией удалил панель и хотел поставить заново, но при установке выдает такую ошибку:
df: `/var/lib/mysql/.': No such file or directory
df: no file systems processed
[FAIL] /etc/init.d/mysql: ERROR: The partition with /var/lib/mysql is too full! ... failed!

Что мне делать?

**Comment by rez0n** [comment]
Лучше конечно переустановить ОС и на чистую - поставить панель. Ибо проблем будет только прибавляться.

**Comment by skurudo** [comment]
rez0n совершенно верно заметил.

Дальнейшие обсуждения, если в них есть необходимость, предлагаю продолжить на форуме - http://forum.vestacp.com
