### ISSUE TITLE
Помогите, не могу восстановить бэкап

### ISSUE THREAD

**Issue by vickrasov** [serghey-rodin/vesta#310]
Хочу восстановить бэкап, но когда запускаю, некоторе время идет восстановление, а потом говорит такую ошибку "Error: nginx restart failed". Пробую руками перегрузить nginx, выдает ошибку "nginx: [emerg] open() "/home/admin/conf/web/apache2.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/vesta.conf:2
nginx: configuration file /etc/nginx/nginx.conf test failed" 

Что мне делать? Помогите, мне нужно срочно вернуть бэкап...

**Comment by vickrasov** [comment]
проблему помогли решить, но теперь есть другая - когда открываешь любой сайт - пишет просто success  и все

**Comment by vickrasov** [comment]
проблему решили. спасибо

**Comment by skurudo** [comment]
Отлично.
Тогда закрываем.
