### ISSUE TITLE
Email address forwards emails even it set to 'suspended'

### ISSUE THREAD

**Issue by crackdepirate** [serghey-rodin/vesta#318]
hello,

if an email account is setting up to 'suspended' and set with a forward to 'joe@fresh.com' , that email account continues to forward emails to 'joe@fresh.com'.

![image](https://cloud.githubusercontent.com/assets/10081049/6201493/87298b6c-b47b-11e4-9516-a82a3c3cce46.png)

**Comment by serghey-rodin** [comment]
Hi @crackdepirate. This is definitely a bug. We will fix it. Thanks for help!

**Comment by anton-reutov** [comment]
Tested. The problem does not fixed. Reopened

**Comment by anton-reutov** [comment]
https://bugs.vestacp.com/issues/632
