### ISSUE TITLE
Only ftp backup = backup page bug

### ISSUE THREAD

**Issue by rez0n** [serghey-rodin/vesta#319]
Привет. Если используется только удаленный (ftp) бекап - список бекапов на странице не очищается. При том, что фактически бекапы уже затерты и созданы новые - записи о старых остаются.
![image](https://cloud.githubusercontent.com/assets/725860/6205671/6f6c5b1c-b57f-11e4-9803-2d9312b113bf.png)

**Comment by serghey-rodin** [comment]
Принято, будем решать. Спасибо @rez0n
