### ISSUE TITLE
Where is Dkim public key located?

### ISSUE THREAD

**Issue by muratsplat** [serghey-rodin/vesta#320]
Hi,

Vesta panel is awsome. Good job @serghey-rodin  :+1: 

I have a problem about DKIM using multi domain on digital ocean.. 

I could not found dkim public key to record TXT record on DO dns panel.

**Comment by serghey-rodin** [comment]
Hi @muratsplat 
You can find public key here /usr/local/vesta/data/users/%username%/mail/%domain-name%.pub or you can use following command to get Bind-like output
```
v-list-mail-domain-dkim-dns  %username% %domain-name%
```

**Comment by muratsplat** [comment]
Thank you for  helping..

**Comment by warwickchapman** [comment]
@serghey-rodin please be aware that the output of v-list-mail-domain-dkim-dns  %username% %domain-name% inserts \n whereever there is a linebreak in the .pub file.  This invalidates the key.

**Comment by youradds** [comment]
@warwickchapman  - ah, now that is interesting. I was wondering why I couldn't get my DKIM to validate. I've updated my DNS now, so will wait for it to update to see if that makes the DKIM valid . Thanks for sharing 👍

**Comment by ram108** [comment]
It seems that `v-list-mail-domain-dkim-dns  %username% %domain-name%` is not working properly and a bug with '\n' is still not fixed.

**Comment by youradds** [comment]
@ram108 yeah I'm not sure why that one hasn't been fixed yet. Seems like it would be pretty simple to do?

**Comment by ram108** [comment]
The fix is easy.

Goto file:
`/usr/local/vesta/bin/v-list-mail-domain-dkim-dns`

Find:
`pub=$(echo "$pub" |sed ':a;N;$!ba;s/\n/\\n/g')`

Change to:
`pub=$(echo "$pub" |sed ':a;N;$!ba;s/\n//g')`

**Comment by ram108** [comment]
Да когда же это поправят?! Задача просто непосильна.

**Comment by ram108** [comment]
Auto patch the bug. Run in command line, this will fix the issue:
`sed -i 's/\\n\/\\\\n/\\n\//' $VESTA/bin/v-list-mail-domain-dkim-dns`

**Comment by gytisrepecka** [comment]
> The fix is easy.
> 
> Goto file:
> `/usr/local/vesta/bin/v-list-mail-domain-dkim-dns`
> 
> Find:
> `pub=$(echo "$pub" |sed ':a;N;$!ba;s/\n/\\n/g')`
> 
> Change to:
> `pub=$(echo "$pub" |sed ':a;N;$!ba;s/\n//g')`

Thanks, this solves the issue!
