### ISSUE TITLE
Error on suspend web with ssl

### ISSUE THREAD

**Issue by joubertredrat** [serghey-rodin/vesta#321]
Hi guys,

when domain is normally, suspend and suspend without problems, but, when try to suspend site with ssl, return error code 12.

This issue was tested on 3 vestacp instances on different hosts and in all have same problem

**Comment by serghey-rodin** [comment]
Hi @joubertredrat 
I will test and and let you know. Thanks for help!

**Comment by serghey-rodin** [comment]
It turns out this was a known issue and we already fixed it.
Here is temporary workaround
```
wget https://raw.githubusercontent.com/serghey-rodin/vesta/master/bin/v-suspend-web-domain -O /usr/local/vesta/bin/v-suspend-web-domain
```

**Comment by joubertredrat** [comment]
@serghey-rodin thanks for the help.

I will await next release.

Ah yes, @serghey-rodin, if I fix problems and insert new features, I can create pull request or I need to contact you before?

**Comment by serghey-rodin** [comment]
@joubertredrat Please feel free to file pull request any time. Your help  would be highly appreciated.

**Comment by joubertredrat** [comment]
@serghey-rodin,

I tested here and worked fine on all 3 vestacp instances.

Thanks again
