### ISSUE TITLE
VestaCP keep crashing the database

### ISSUE THREAD

**Issue by gdarko** [serghey-rodin/vesta#337]
Hello Serghey.

First, thank you for all your hard work on Vesta. I installed Vesta few months ago on different DigitalOcean droplets and i am very satisfied of how it work. I currently have 2GB Ram DO droplet. And on every vm i receive a weird error message that crash mysql and requires reboot. After the mail all the sites even the webmail are broken with "Error establishing connection to the database...". I have used both Debian based or Centos based. Currently i use CentOS 6.6

Please see the screenshot, when this mail come i know i have to reboot the vm.

Thanks again

<img src="http://i.imgur.com/StaCuzb.png">

**Comment by serghey-rodin** [comment]
Hi Darko,

The most common problem is that MySQL is trying to allocate more memory that it physically can. If you are running CentOS you can check /var/log/mysqld.log for more details. On debian log is located in /var/log/mysql/error.log

To start  with something I can suggest you followin settings in /etc/my.cnf
```
[mysqld]
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock
user=mysql
symbolic-links=0
skip-external-locking

key_buffer_size = 16M
max_allowed_packet = 16M
table_open_cache = 64
sort_buffer_size = 512K
net_buffer_length = 8K
read_buffer_size = 256K
read_rnd_buffer_size = 512K
myisam_sort_buffer_size = 8M

#innodb_use_native_aio = 0
innodb_file_per_table

max_connections=70
max_user_connections=30
wait_timeout=10
interactive_timeout=50
long_query_time=5

#slow_query_log=1
#slow_query_log_file=/var/log/mysql-slow-queries.log

``

**Comment by sirpros** [comment]
I got the same problem. After setting the innodb_buffer_pool_size=1G on the /etc/mysql/my.cnf file I got some relief. Still monitoring the issue.
