### ISSUE TITLE
(xx.xx.xx.xx:8083/add/firewall/banlist/) only working until server is restarted

### ISSUE THREAD

**Issue by dac777** [serghey-rodin/vesta#338]
When I follow these steps to ban a IP:
-> click in "firewall" section  (:8083/list/firewall/)
-> click in "list fail2ban" (8083/list/firewall/banlist/)
-> click the button "block ip" (8083/add/firewall/banlist/)

The firewall is working perfectly and block any ip... then, perfect.

But the problem comes if I restart or reboot all services or the server. These ip blocked before become again unbaned ip's... So I must manually ban those ip again... 

if there are two or three, there is no problem, but if there are for example 50... you loose a lot of time banning these ip again manually.

I thought the IP were still banned because in this section xx.xx.xx.xx:8083/list/firewall/banlist/
I still can see these IP, but really are not banned... then it is misleading. (just check iptables -L)

Why if any of these IP's aren't currently banned appear in the banlist?

Is there a way to ban a IP permanently using the "fail2ban -> blcok ip" feature ( xx.xx.xx.xx:8083/add/firewall/banlist/) instead of adding a rule in the firewall (:8083/add/firewall/)?

Thank you in advance :)

**Comment by serghey-rodin** [comment]
If you ban ip addresses manually they should stay blocked forever until you unblock yourself. So it's a bug. We will look into it and let you know. Thanks for report

**Comment by dac777** [comment]
Ok, thanks Serghey. 

I would like to help more , but unfortunatelly I still doesn't have enough skills with bash scripting.
If I see something more I will report again to improve this amazing and intuitive tool like VESTA.

Keep up this fantastic work !!

I Hope I can help in the future with better contributions :)
