### ISSUE TITLE
I can not access to the panel web

### ISSUE THREAD

**Issue by jonabasque** [serghey-rodin/vesta#339]
Hi, 
I have been trying to recover the admin pass, but I dont think this provokes the problem. I dont see nothing in the log too.

![captura de pantalla de 2015-02-28 09 24 16](https://cloud.githubusercontent.com/assets/1707606/6425498/ab328a3a-bf2b-11e4-8dad-875b5f255206.png)

**Comment by KeiroD** [comment]
Have you tried the following in SSH to change your admin password?:

/usr/local/vesta/bin/v-change-user-password admin CHANGED_PWD
