### ISSUE TITLE
Latest VestaCP uses insecure vsftpd setup.

### ISSUE THREAD

**Issue by KeiroD** [serghey-rodin/vesta#340]
Your configuration for vsftpd does not allow for FTPES or any other secure settings.

This needs to be resolved ASAP.

Additionally, you should enable pure-ftpd support.

**Comment by neuropass** [comment]
Is this confirmed? Can someone reply this this? Seems high priority @serghey-rodin

**Comment by nobodypb** [comment]
This is true, but as far as I know, they're switching to ProFTPD

**Comment by KeiroD** [comment]
You can also switch to pure-ftpd, it's not that difficult to do the switch.

Personally I'm using pure-ftpd.

**Comment by nobodypb** [comment]
Well, from that point of view it's not difficult to setup a webserver at all.
But we're here because we want vesta to do most of the work for us, so it shouldn't be necessary to do it manually.

**Comment by serghey-rodin** [comment]
@KeiroD thaks for pointing this out. We will add FTPES support for both vsftpd and proftpd in default  setup. Thanks
