### ISSUE TITLE
Mint 17.1 (Ubuntu) install error

### ISSUE THREAD

**Issue by R0GGER** [serghey-rodin/vesta#343]
Hello,

I would like to install VestaCP, but I get an error before the install starts...
"Error: sorry, we currently support RHEL and CentOS only"

OS
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.1 LTS"
VERSION_ID="14.04"

Please your help.

**Comment by serghey-rodin** [comment]
Hello Rogger,

Unfortunately, LinuxMit is not supported. We might add it in the future, though.

**Comment by Legun** [comment]
Try Download wget http://vestacp.com/pub/vst-install-ubuntu.sh -O vst-install-ubuntu.sh
manualy
and change this on 

# Check supported OS
#if [ "$(arch)" != 'x86_64' ]; then
#    arch='i386'
#else
    arch="amd64"
#fi
#os=$(head -n 1 /etc/issue | cut -f 1 -d ' ')
os=ubuntu
#release=$(head -n 1 /etc/issue | cut -f 2 -d ' ' )
release=14.04
#codename=$(lsb_release -cs | egrep "precise|quantal|raring|saucy|trusty")
codename=trusty
#if [ -z "$codename" ]; then
#    echo "Error: Ubuntu $(lsb_release -r|awk '{print $2}') is not supported"
#    exit 1
#fi
