### ISSUE TITLE
[Security] Installer email

### ISSUE THREAD

**Issue by EminezArtus** [serghey-rodin/vesta#347]
There is some risk with sending the username and password through email at the end of the install process.

There is no guarantee that the email will be sent via ssl connection. Therefor it is not recommended that their be an email sent from the server with such information.

Instead the user should rely on the console, or be prompted to change their password at first login, or have a https link which the user can download a txt file with such information.

**Comment by Exadra37** [comment]
:+1: 

I complete agree with that and plus the default user admin should not be used any more after the first login... we should be prompted also for a new user name to use in order to access Vesta web interface, that will mantain the same privileges.

**Comment by neuropass** [comment]
+1
