### ISSUE TITLE
user quota limits not working 

### ISSUE THREAD

**Issue by Ara4Sh** [serghey-rodin/vesta#350]
Hello Serghey 
recently i installed Vesta CP in an Ubuntu system. 
i enabled journaled quota but users still can use so much space beyond the quota limitation 
what can i do ?

**Comment by ianvanwijk** [comment]
I think you mean this...

In the `func/main.sh` file:
go to function:
`recalc_user_disk_usage()` line [423](https://github.com/serghey-rodin/vesta/blob/master/func/main.sh#L423)

scroll down to this line ([460](https://github.com/serghey-rodin/vesta/blob/master/func/main.sh#L460)):
`usage=$(grep 'U_DIR_DISK=' $USER_DATA/user.conf | cut -f 2 -d "'")`
change it to:
`usage=$(grep 'U_DISK_DIRS=' $USER_DATA/user.conf | cut -f 2 -d "'")`

If this is not what you mean, go to: `bin/v-update-user-disk` line [38](https://github.com/serghey-rodin/vesta/blob/master/bin/v-update-user-disk#L38-L39)

change line:
`dir_list=$(ls $HOMEDIR/$user/ |grep -v '^web$' | grep -v '^mail$' |\
    grep -v '^conf$')`

with:
`dir_list=$(ls -a $HOMEDIR/$user/ | grep -v '^web$' | grep -v '^mail$' |\
    grep -v '^conf$' | grep -v '^\.$' | grep -v '^\..$')`

Hope this helps... :)

Regards,
Ian

**Comment by Ara4Sh** [comment]
Thanks i will inform you about this as soon as possible
