### ISSUE TITLE
apache/wsgi template is broken

### ISSUE THREAD

**Issue by mrgrain** [serghey-rodin/vesta#356]
```
Debian 7.8
vesta 0.9.8 (amd64) 
Apache/2.2.22 (Debian)
mod_wsgi  3.3-4+deb7u1
mod_ruid2 0.9.7-1
```

Creating a WSGI application from the provided wsgi-templates terminates with the  503 - Internal Server Error "Unable to connect to WSGI daemon process", because of missing permissions for the apache2 user, when trying to connect to the wsgi daemon.

The reason for this is **not** a wrong `WSGISocketPrefix` which is a common fix for that error. On this configuration the socket is not readable because of `mod_ruid2` used by the template. `mod_ruid2` and `mod_wsgi` are just not playing well together, as stated here: https://groups.google.com/d/msg/modwsgi/lnS8UaysAnU/IOpiXhw1XfkJ

There are at least two possible fixes. Both of them not perfect.
1. **Disable `mod_ruid2` for the wsgi template**
   This would result in running the wsgi application under the default www-data user. Not sure if this adds any security risks.
2. **Create the process with chmod 0777 (via umask setting)**
   Which is obviously a security risk and  not recommended at all.

**Comment by working-name** [comment]
no that's just an old mod_wsgi, it doesn't know about `socket-user` config option.
