### ISSUE TITLE
Whmcs Module 500 Internal Error 

### ISSUE THREAD

**Issue by Ara4Sh** [serghey-rodin/vesta#357]
Hello 
In vesta whmcs module after checking out the card and first payment the user created but the problem is user redirected to a 500 internal Error page 
i dont know how to check logs about this issue i can give you access to test website and you can see the problem 
is this a bug or missconfiguration ?

**Comment by kotso** [comment]
What version of WHMCS module are you using?

In latest version from repository, I fixed multiple small errors.

Check if you use latest one, and if problem remains give more details pls. I will help you with issue if you provide details.

**Comment by kotso** [comment]
https://github.com/serghey-rodin/vesta/blob/master/install/rhel/whmcs-module.php

**Comment by Ara4Sh** [comment]
Hello i update the whmcs module and error 500 gone in order page but completely lost /admin/orders.php?status=Pending its a white page now :)

**Comment by Ara4Sh** [comment]
now after i set create completely automatic in vesta after order placed 500 is now here can you please give me your email ? i can give you my server credentials and you can test it yourself
