### ISSUE TITLE
Когда будет новая версия?

### ISSUE THREAD

**Issue by xr0m3oz** [serghey-rodin/vesta#359]
Можно ли скачать 0,9,9,1 ?

**Comment by alex-connor** [comment]
Вы видели сообщение о выходе нового релиза? Нет? Я тоже! Ответ очевиден. А насчет того, когда будет релиз, пока точно сказать невозможно...

**Comment by anton-reutov** [comment]
В течении мая выйдет новая ветка 0.9.9
