### ISSUE TITLE
Debian 8 (jessie) support

### ISSUE THREAD

**Issue by mathzol** [serghey-rodin/vesta#369]
I realy like if vesta support jessie, so i will try it on. If someone know about any issue on jessie please report by comments or anyway.

**Comment by mathzol** [comment]
Okay, I checked it, for first look there are the next issues:

1. in jessie apache 2.4 is the default
2. some package are missing: jwhois, roundcube, roundcube-mysql, roundcube-plugins
they are in testing status reported by the package tracker of debian

**Comment by anton-reutov** [comment]
We need wait some time, when Debian 8 will be stable

**Comment by mathzol** [comment]
Yeah, thats true, the missing packages arent in packports too, so thats it I think

**Comment by anton-reutov** [comment]
I think support for Debian 8 will be after few releases

**Comment by xZero707** [comment]
I trying to modify vst-install-debian.sh to support Jessie.
Also $codename is not set properly, at least in my case.
Missing packages as described by mathzol....
I'll keep trying. Regards

**Comment by OUGHT** [comment]
Jessie is now stable, btw...

**Comment by anton-reutov** [comment]
Now we are testing new installer for Debian 8/7

**Comment by salman-khaliq** [comment]
Waiting for the Debian 8 installer a bunch of servers with Debian 8 need that.!

**Comment by shahramsh** [comment]
any news on debian 8 installer?

**Comment by skurudo** [comment]
In test, bug fixes now.

**Comment by viktorix** [comment]
Any updates on this?

**Comment by anton-reutov** [comment]
new update should be on next week

**Comment by viktorix** [comment]
Thanks Anton.

**Comment by maxiorel** [comment]
Hi, any news about this?

**Comment by anton-reutov** [comment]
Hi, yes. 
Installer for Debian 8 already ready. New release with this feature will be in on this month.
Now we are testing new installer for Ubuntu 15,14,12

**Comment by maxiorel** [comment]
thanks

**Comment by arasaahov** [comment]
Is there any update regarding with Debian 8?
Thanks

**Comment by DragoSFire** [comment]
Скоро там релиз с поддержкой восьмерки?

**Comment by anton-reutov** [comment]
Скоро

**Comment by arasaahov** [comment]
can not wait for this feature

**Comment by Davy1992** [comment]
@anton-reutov There are only 3 days left, will you guys deliver the new installer in time?
I've been waiting over 2 weeks for it now :dart:

**Comment by arasaahov** [comment]
4 weeks already for me...

**Comment by arasaahov** [comment]
Is there any update, please?

**Comment by MiaP97** [comment]
Hey all, the update is out, feel free to close this issue!

**Comment by mathzol** [comment]
I tested it, on debian 8 32 bit, looks okay, installer did it with out error, I think close this issue. 
Thanks all of you
