### ISSUE TITLE
optionally secure phpmyadmin

### ISSUE THREAD

**Issue by joubertredrat** [serghey-rodin/vesta#372]
Hi,

Today VestaCP add phpmyadmin as a alias to all domains, but, in my opinion, this this can be a insecure way to a lot of attacks, as brutal force as example.

I think that optionally set phpmyadmin to open only in a hostname or ip a good idea. What do you think?

**Comment by farooqaaa** [comment]
Seconding this. This is very important. phpmyadmin is currently completely insecure.

**Comment by sman591** [comment]
+1, this would be fantastic

**Comment by KeiroD** [comment]
This should be an easy fix... there're lots of guides on securing phpmyadmin on the internets.
