### ISSUE TITLE
Roundcube database is not setup on fresh install 14.04

### ISSUE THREAD

**Issue by zorrobyte** [serghey-rodin/vesta#373]
Please see last 2 comments:
https://forum.vestacp.com/viewtopic.php?f=12&t=7065&p=26923#p26923

I have tested on 4 new installs, the database is never created/updated and roundcube out of box doesn't work

**Comment by KeiroD** [comment]
Confirmed.

Roundcube for some reason is not set up. If you attempt to `dpkg-reconfigure roundcue`, it also never tries to set up Roundcube.

`apt-get remove roundcube` and `apt-get install roundcube` does not cause roundcube to install the database.

Something went horribly wrong, here.

**Comment by superservidor** [comment]
I had the same problem after first reboot of the vps server with a fresh install of vestacp under Ubuntu 14.04 64 bits minimal. I solved the error following the steps indicated below.

# To repair that error you must run as root at console  the following command:

update-rc.d mysql disable

# then reboot the server and the problem will be solved.

**Comment by AzureusSme** [comment]
> To repair that error you must run as root at console the following command:
> 
> update-rc.d mysql disable
> 
> then reboot the server and the problem will be solved.

Doesn't work for me.
