### ISSUE TITLE
Database user cannot be created if account name is too long

### ISSUE THREAD

**Issue by jmotes** [serghey-rodin/vesta#374]
Database users cannot be added if the account name is 16+ characters long. This is because the database user is prefixed with the account name, and MySQL users themselves are limited to 16 characters. The account name should be limited to 12 characters or so to eliminate the problem.

**Comment by superservidor** [comment]
I have the same problem. I temporarily fix the problem using a shorter name for the database user.

**Comment by skurudo** [comment]
https://bugs.vestacp.com/issues/258
