### ISSUE TITLE
How to get REMOTE_ADDR ?

### ISSUE THREAD

**Issue by MrSSDD** [serghey-rodin/vesta#377]
День добрый, проблема с получением ip пользователя, $_SERVER['REMOTE_ADDR']  всегда возвращает ip сервера, читал про mod_rpaf и тд, не помогло, есть ли решение ?

**Comment by anton-reutov** [comment]
Добрый день. Укажите версию ОС, и детальнее напишите как настраивали.

**Comment by MrSSDD** [comment]
Сервер Ubuntu 14.04.1 LTS, VestaCP 0.9.8 устанавливал все по умолчанию как в инструкций http://bit.ly/1I4HjDq

**Comment by pabloko** [comment]
fix tested on ubuntu/debian: disable mod_rpaf2 and eneable mod_remoteip for apache, the use this config

```ini
<IfModule mod_remoteip.c>
RemoteIPHeader X-Real-IP
RemoteIPInternalProxy 127.0.0.1
RemoteIPInternalProxy 178.33.237.198
</IfModule>
```
