### ISSUE TITLE
Unlimited quota error with Exim and v-rebuild-mail-domains

### ISSUE THREAD

**Issue by sq2m-db** [serghey-rodin/vesta#391]
When "v-rebuild-mail-domains $USER" is run on a clean Debian/Exim VestaCP installation the quota value in /home/$USER/conf/mail/$DOMAIN/passwd gets malformed.

Error (/var/log/exim4/paniclog): Malformed value "unlimitedM" 

To fix this i added 

```
if [ "$QUOTA" = 'unlimited' ]; then
        QUOTA=0
fi
```

to rebuild_mail_domain_conf() in /usr/local/vesta/func/rebuild.sh (line 518+)

Can you confirm this issue? Thanks!

**Comment by janabimustafa** [comment]
+1 for this issue. This issue prevents local mail delivery after executing v-rebuild-mail-domains.

**Comment by RhysIT** [comment]
+1

Big issue when moving clients between servers (backing up and restoring). Had me very stumped!

**Comment by albertomario** [comment]
I have this some issue:
```
R=localuser T=local_delivery defer (-1): Malformed value "unlimitedM" (expansion of "${extract{6}{:}{${lookup{$local_part}lsearch{/etc/exim/domains/$domain/passwd}}}}M")
```
How to fix this?

**Comment by KuJoe** [comment]
Confirmed that changing "unlimited" to "0" in the passwd file fixed this problem for me also.

**Comment by RhysIT** [comment]
Hi,

Has this been fixed for the new release?

Thanks for all the work Serghey! Appreciate it.

Rhys

**Comment by FlorinMotoc** [comment]
Also confirming that changing from "unlimited" to "0" fixes the problem.
Also, you can edit the mail account from VestaCP and click again the save button (with unlimited set). This works too.

**Comment by serghey-rodin** [comment]
This bug was fixed in latest 0.9.8-15 release. Please feel to upgrade guys!

**Comment by live3d** [comment]
I was on the latest and have this bug changed to 0 waiting to see if it clears after mail rebuild on that user.

Mike

**Comment by crackdepirate** [comment]
same here. latest version at 16. 
I get that message under /var/log/exim/main.log 
R=localuser T=local_delivery defer (-1): Malformed value "unlimitedM" (expansion of "${extract{6}{:}{${lookup{$local_part}lsearch{/etc/exim/domains/$domain/passwd}}}}M")
