### ISSUE TITLE
Сброс пароля при блокировки пользователя

### ISSUE THREAD

**Issue by tabuna** [serghey-rodin/vesta#399]
Здравствуйте, при блокировании пользователя (v-suspend-user) пароль системного пользователя admin меняется и войти можно только после сброса пароля.

**Comment by anton-reutov** [comment]
Добрый день. Мы в курсе данной проблемы. Помогает также ансуспендед.
Фикс в ближайшем апдейте.

**Comment by max-sparker** [comment]
Здравствуйте. Проблема так и не решена - можно какой-нибудь патч для решения ее? На всех учетках меняются пароли после блокировки одного из них.

**Comment by anton-reutov** [comment]
Здравствуйте. Да, можно.
https://github.com/serghey-rodin/vesta/commit/8194ee854f43893b02ab199403786b263ae43682

**Comment by max-sparker** [comment]
Спасибо, Антон.
Теперь как надо все работает.
