### ISSUE TITLE
Force mail server to use only one IPv4 or IPv6 IPs.

### ISSUE THREAD

**Issue by KeiroD** [serghey-rodin/vesta#401]
On my server, Exim4 seems to like changing IPs every so often if the server has more than one IPv6 IPs.

This results in e-mails being either marked as spam or it getting through but with a spf=softfail because you'd configured your SPF record to allow for the designated IPs to send out from, only to discover the IP had changed again.

**Comment by superservidor** [comment]
Check issue # 419 has one solution

**Comment by KeiroD** [comment]
My solution was to switch to Postfix. Exim4 kept pissing me off that I decided to throw it out in favor of Postfix. At least with Postfix, the solution was easy for me to make that work.
