### ISSUE TITLE
Can't add SSL certificate with password-protected private.key

### ISSUE THREAD

**Issue by ofry** [serghey-rodin/vesta#404]
I manually did CSR as described in https://www.nic.ru/dns/service/ssl/pdf/CSR_apache.pdf

Next I correctly put in domain SSL certificate, my password-encrypted private key, and all intermediate certificate chain.

But I got error:
Error: ssl certificate key pair is not valid

My RSA private key begins from:

-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: DES-EDE3-CBC, ...

**Comment by pabloko** [comment]
just use
 ```
openssl rsa -in /path/to/originalkeywithpass.key -out /path/to/newkeywithnopass.key
```
you will be prompted for the password and will generate a the certificate without key that you can use

**Comment by ofry** [comment]
Is I need to manually repeat SSL sertificate order? If it so, I just NOT want pay twice for it :)

**Comment by KeiroD** [comment]
No, you do not need to order another ssl certificate.
