### ISSUE TITLE
enabling AutoUpdate feature after install vestacp in Ubuntu generates a 404 error

### ISSUE THREAD

**Issue by superservidor** [serghey-rodin/vesta#418]
After a successfull installation of VestaCP in a VPS with Ubuntu 14.04 64 bits with minimal install, i get the following error when I try to enable the AutoUpdate feature:

404 -- page not found is shown at the tab label in google chrome

The URL shown in address bar after clicking the AutoUpdate link is:

https://194.135.84.217:8083/add/cron/autoupdate/&token=148126215355b263c99ac512.21124690 

How can I activate the AutoUpdate feature without receiving this error?

**Comment by cdnmall** [comment]
http://forum.vestacp.com/viewtopic.php?f=16&t=8813
