### ISSUE TITLE
fail2ban don't remove ip on web interface

### ISSUE THREAD

**Issue by joubertredrat** [serghey-rodin/vesta#423]
Hi,

On old interface, remove IP on fail2ban list works normally, but on new interface not. cli command works fine on both new and old VestaCP versions.

**Comment by SysVoid** [comment]
Can you clarify your issue? It seems to be working perfectly for me on my new installation.
!!(https://i.imgur.com/mCsXcid.png)

**Comment by joubertredrat** [comment]
Hi @SysVoid,

Delete options is displayed normally, but don't work after you click on "ok" on confirm box. I only can to remove using the terminal.

My Vesta wasn't new installation, was update from old version.

**Comment by SysVoid** [comment]
I clicked "DELETE," and it removed it just fine. Maybe there was a conflict between your old version and the new one.

Are you able to reinstall?

**Comment by joubertredrat** [comment]
Hi @SysVoid 

Strange, on mine and mine friend VestaCP doesn't work, but our is update from old and not new installation.

Not, I can't reinstall because have a lot of sites on production. I'm PHP developer too, I will trace delete route to see if is working.

Thanks

**Comment by nicdnepr** [comment]
Same for me
I was ban by fail2ban for ssh
Removed my IP in vesta but still can't connect
Ubuntu 16
Vesta 0.9.8

**Comment by anton-reutov** [comment]
Write more about what happened.
Try to find your ip here 8083/list/firewall/banlist/ and remove it

v-update-firewall
