### ISSUE TITLE
Weak SSL nginx config: deploy Diffie-Hellman for TLS

### ISSUE THREAD

**Issue by tarikin** [serghey-rodin/vesta#426]
https://www.ssllabs.com/ssltest/
9 Ciphers are weak 
This server supports weak Diffie-Hellman (DH) key exchange parameters. Grade capped to B.

Solution: https://weakdh.org/sysadmin.html

**Comment by KeiroD** [comment]
Make the changes to the configs as suggested for that, do a pull request.

They will merge the changes you made to make that stronger.

**Comment by skurudo** [comment]
Sorry for interrupt, but this is tricky option. Generate dhparam on weak cpu-vps or atom server it's hell of time - too long. It can take easy 1-9 hours.

**Comment by KeiroD** [comment]
Then do it on a stronger computer, take the dhparams.pem to your server. Problem solved.

**Comment by hellodanielting** [comment]
Serghey has merged a pull request [https://github.com/serghey-rodin/vesta/pull/456] for this issue.
I believe it should now be solved.
