### ISSUE TITLE
No SPF Record Added

### ISSUE THREAD

**Issue by faizanayubi** [serghey-rodin/vesta#436]
i have added the TXT Record as instructed in DNS Vesta cPanel but when i sent email it goes to spam.
so i checked from mxtools it shows no spf record added.
![spf](https://cloud.githubusercontent.com/assets/4982023/9639741/2074454a-51cb-11e5-825b-07f9f005009a.PNG)

@serghey-rodin Please help me, i am stuck on this.
Whatever i try the mail goes to spam.

**Comment by Exadra37** [comment]
@faizanayubi 

see if issue #149 can help you.

**Comment by faizanayubi** [comment]
@Exadra37 ipv6 is not my issue
my issue is why spf record not shown valid is there syntax error in txt record

**Comment by faizanayubi** [comment]
Thanks Guyz
i solved this by removing the double quote ' " ' and then pasting the record.
