### ISSUE TITLE
ïnstall custom nginx module?

### ISSUE THREAD

**Issue by techpulse** [serghey-rodin/vesta#437]
hello, how can i add a custom nginx module to my nginx installation on vestacp, easiest way?

example module: test-cookie nginx

**Comment by skurudo** [comment]
There no easiest way, only compile nginx from source like this - https://forum.vestacp.com/viewtopic.php?f=11&t=9790

It's not a bug. Let's use forum - https://forum.vestacp.com - for topic like this.

**Comment by skurudo** [comment]
There no easiest way, only compile nginx from source like this - https://forum.vestacp.com/viewtopic.php?f=11&t=9790

It's not a bug. Let's use forum - https://forum.vestacp.com - for topic like this.

**Comment by skurudo** [comment]
There no easiest way, only compile nginx from source like this - https://forum.vestacp.com/viewtopic.php?f=11&t=9790

It's not a bug. Let's use forum - https://forum.vestacp.com - for topic like this.

**Comment by skurudo** [comment]
There no easiest way, only compile nginx from source like this - https://forum.vestacp.com/viewtopic.php?f=11&t=9790

It's not a bug. Let's use forum - https://forum.vestacp.com - for topic like this.

**Comment by skurudo** [comment]
There no easiest way, only compile nginx from source like this - https://forum.vestacp.com/viewtopic.php?f=11&t=9790

It's not a bug. Let's use forum - https://forum.vestacp.com - for topic like this.
