### ISSUE TITLE
error Installing on debian 8

### ISSUE THREAD

**Issue by Smokexyz** [serghey-rodin/vesta#438]
$ bash vst-install.sh
--2015-09-03 09:06:10--  http://vestacp.com/pub/vst-install-debian.sh
Resolving vestacp.com (vestacp.com)... 104.236.66.100
Connecting to vestacp.com (vestacp.com)|104.236.66.100|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27638 (27K) [text/plain]
Saving to: ‘vst-install-debian.sh’

vst-install-debian.sh                    100%[==================================================================================>]  26.99K  --.-KB/s   in 0.05s  

2015-09-03 09:06:10 (572 KB/s) - ‘vst-install-debian.sh’ saved [27638/27638]

vst-install-debian.sh: line 114: [: !=: unary operator expected
!!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!!

Following packages are already installed:
apache2 

It is highly recommended to remove them before proceeding.
If you want to force installation run this script with -f option:
Example: bash vst-install-debian.sh --force

!!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!!

**Comment by anton-reutov** [comment]
Debian 8 is not supported yet

**Comment by DPO84** [comment]
That being said though, you can install it on Debian 7 and upgrade to Debian 8. The problem here is that and apt-get udate & upgrade will hold a lot of packages back from then on. 

@anton-reutov: is there a testing repository that can possibly be added to the sources list? I would be happy to report bugs back to you.

Best
Pat

**Comment by didyouexpectthat** [comment]
That specific message says apache2 is already installed. Why not just apt-get purge apache2 and then try again to install? Or use a Debian 8 minimal install.

**Comment by evilebottnawi** [comment]
@anton-reutov @DPO84 :+1:

**Comment by anton-reutov** [comment]
Now we are finishing the testing installer for Debian 8/7

**Comment by anton-reutov** [comment]
Already supported
