### ISSUE TITLE
Suspending domains as normal user (not admin)

### ISSUE THREAD

**Issue by karimb79** [serghey-rodin/vesta#440]
Suspending domains works ok when loggin in as admin.

But when I log in as a normal user (tried with 2 users on 2 diffent panels), I get no error and the domain is not suspended.

Thank you

**Comment by anton-reutov** [comment]
This problem is not reproducible on our servers

**Comment by karimb79** [comment]
Hello, please, have you tried it on Centos ?
# uname -r
2.6.32-573.3.1.el6.x86_64
# cat /etc/*-release
CentOS release 6.7 (Final)
CentOS release 6.7 (Final)
CentOS release 6.7 (Final)

**Comment by anton-reutov** [comment]
Oh, confirmed. Thank you for your report
This bug will be fixed in the next release

**Comment by karimb79** [comment]
Hello, just updated to the latest version (0.9.8-15) - Released on Friday November 06, 2015 
but the problem is that when we log as a user (not admin) and we go to domains list (WEB), the button SUSPEND has disappeared !

**Comment by skurudo** [comment]
Users can't suspend domain, only admin can.
(admin can do sudo, users can't)

**Comment by karimb79** [comment]
I understand that technically, only admins can sudo but I'm talking about the function that should be available for users because they really need it. It's available in all other panels (Plesk, cPanel, ..) for simple users.
For example, users could only trigger the change status request by editing a file which would be processed by a cron that's run every minute. There are probably lots of other solutions, that was just an idea.
