### ISSUE TITLE
Cannot unsuspend via API

### ISSUE THREAD

**Issue by KuJoe** [serghey-rodin/vesta#443]
v-unsuspend-user does not work via API. I have a script to suspend and unsuspend a VestaCP user and while the v-suspend-user works, the v-unsuspend-user does not. I confirmed it was not my code by replacing "v-unsuspend-user" with "v-suspend-user" and it suspends correctly but changing it back does not unsuspend. Even though it doesn't unsuspend the user it returns with a code 0 still.

**Comment by karimb79** [comment]
It might be a privilege problem : I had a similar problem while trying to suspend a domain as a normal user (not admin) on Centos 6 64 bits. I works fine with admin but doesnt work with a normal user.

**Comment by KuJoe** [comment]
I am running it as admin.

**Comment by KuJoe** [comment]
Problem solved. My password was too long, I changed my password to one with only 22 characters and it works now. :)

**Comment by KuJoe** [comment]
I found where it's dying but I can't figure out why or how to fix it. I've tried everything without any luck. It's dying on v-check-user-password on lines 76-81 (I changed the return values and it always returns the number I put for the "Checking has" section). It's not too critical since I have a workaround but it's still very strange.

**Comment by karimb79** [comment]
Can you try it as a normal user (not admin) and tell me if it works ?
