### ISSUE TITLE
Skeleton doesn't work properly.

### ISSUE THREAD

**Issue by SCelik** [serghey-rodin/vesta#448]
https://bugs.vestacp.com/responses/skeleton-doesnt-work-properly

**Comment by SysVoid** [comment]
Hi!

The link you posted doesn't seem to work anymore.

**Comment by SCelik** [comment]
Becouse, vesta team replaced bug tracker. Nevermind, i can explain shortly..

Let's say you have skeleton files like this:

./index.php
./style.css
./favicon.ico

When a domain created with this skeleton structre, there is no problem. User can login to ftp with his own username and password and delete auto-created skeleton files.

But if you setup your skeleton structure like this:

./css
./css/style.css
./img
./img/favicon.ico
./index.php

I mean, if you use directories in skeleton structure, user can not delete those directories. Something wrong with copy function. (Permissions set wrong i think)
