### ISSUE TITLE
Misconfigured open_base_dir directives for roundcube webmail.

### ISSUE THREAD

**Issue by SCelik** [serghey-rodin/vesta#449]
https://bugs.vestacp.com/responses/misconfigured-open-base-dir-directives-for-roundcube-webmail

**Comment by KeiroD** [comment]
Yeah, this one's an annoying issue. There's also a couple other issues with regards to open_basedir or some such. I'd removed the open_basedir stuff from my server because it was a right pain in the ass to get working properly to let phpmyadmin, roundcube and other such things to work .

**Comment by SCelik** [comment]
So how do you manage script security?

**Comment by KeiroD** [comment]
@SCelik chmod, at this present time until I can figure out the appropriate security settings using open basedir. So far, it's a shitty solution but it works.
