### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by surjit** [serghey-rodin/vesta#454]
[Mon Oct 05 15:33:44.463484 2015] [mpm_itk:warn] [pid 10544] (itkmpm: pid=10544 uid=33, gid=33) itk_post_perdir_config(): initgroups(www-data, 33): Operation not permitted
[Mon Oct 05 15:33:47.468723 2015] [mpm_itk:warn] [pid 10545] (itkmpm: pid=10545 uid=33, gid=33) itk_post_perdir_config(): initgroups(www-data, 33): Operation not permitted
[Mon Oct 05 15:33:49.094129 2015] [mpm_itk:warn] [pid 10546] (itkmpm: pid=10546 uid=33, gid=33) itk_post_perdir_config(): initgroups(www-data, 33): Operation not permitted

when I reinstalled I'm getting this error, please help me to fix this

**Comment by SysVoid** [comment]
Did you reinstall on a blank server? What OS?
