### ISSUE TITLE
mysql always stopworking 

### ISSUE THREAD

**Issue by syrakozz** [serghey-rodin/vesta#455]
mysql  always stop working on the latest vesta cp , 
is there any way to auto restarted or fix

**Comment by tjebbeke** [comment]
It's not a vesta CP bug. Read forum ... http://forum.vestacp.com/viewtopic.php?f=14&t=9425&p=32434#p32434

**Comment by syrakozz** [comment]
i use vesta cp in a several server with different specification a good one, 
but i always notice this issue, 
why vestacp doesn't make a proper default configuration for mysql 5.5, so we didnt get this error every time
