### ISSUE TITLE
nginx not restarting properly

### ISSUE THREAD

**Issue by KuJoe** [serghey-rodin/vesta#460]
For the past few days I've been getting quite a few e-mails about nginx failing to restart with the following error (1.2.3.4 being the placeholder for my server's actual IP):
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] listen() to 1.2.3.4:80, backlog 511 failed (98: Address already in use)
nginx: configuration file /etc/nginx/nginx.conf test failed
nginx: [emerg] listen() to 1.2.3.4:80, backlog 511 failed (98: Address already in use)
nginx: configuration file /etc/nginx/nginx.conf test failed
```
If I try to restart the service myself I get the same error:
```
#service nginx restart
nginx: [emerg] listen() to 1.2.3.4:80, backlog 511 failed (98: Address already in use)
nginx: configuration file /etc/nginx/nginx.conf test failed
```
I confirm that nothing else is listen on port 80 except for nginx:
```
# netstat -plan | grep ":80"
tcp        0      0 1.2.3.4:80              0.0.0.0:*                   LISTEN      15179/nginx
tcp        0      0 1.2.3.4:80              5.6.7.8:80            SYN_RECV    -
```
If I check the config, it reports good:
```
# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] listen() to 1.2.3.4:80, backlog 511 failed (98: Address already in use)
nginx: configuration file /etc/nginx/nginx.conf test failed
```
And if I stop and start the service it appears to fix the issue temporarily:
```
# service nginx stop
Stopping nginx:                                            [  OK  ]
# service nginx start
Starting nginx:                                            [  OK  ]
```
I don't know why this is happening but I decided to replace line 48 in https://github.com/serghey-rodin/vesta/blob/master/bin/v-restart-proxy#L48 with the following two lines:
```
service $PROXY_SYSTEM stop >/dev/null 2>&1
service $PROXY_SYSTEM start >/dev/null 2>&1
```
I'll update this issue if my clients stop seeing the error also.

**Comment by SysVoid** [comment]
Hi

Can you send us a copy of your `/etc/nginx/nginx.conf`?

**Comment by KuJoe** [comment]
I believe this can be closed, I just checked and my v-restart-proxy file was reverted back to restart from the "stop;start" edit I made last year and I haven't seen the problem since. Thanks for the follow-up so I could re-evaluate the problem. :+1:
