### ISSUE TITLE
Site vestacp.com and all subdomains is not work

### ISSUE THREAD

**Issue by RemiZOffAlex** [serghey-rodin/vesta#461]

**Comment by bensssyde** [comment]
+1

**Comment by axd** [comment]
+1 Maybe is new version coming out finally? :+1:

**Comment by serghey-rodin** [comment]
Our DigitalOcean account was suspended because of outstanding balance. We are working on this and hopefully will get all servers online soon.

**Comment by serghey-rodin** [comment]
P.S. New version should be released on this week.

**Comment by infinitnet** [comment]
Thanks for the update, @serghey-rodin, I was just wondering why I got so many failed update alerts from cronjobs on Vesta servers and then noticed your whole site was down. Maybe use DO's new floating IP feature to do a HA setup with heartbleed? Won't help against outstanding invoices though.

**Comment by anton-reutov** [comment]
The problem is solved. I think this issue should be closed
