### ISSUE TITLE
New Alias Domain: DNS Records

### ISSUE THREAD

**Issue by RhysIT** [serghey-rodin/vesta#462]
Hi There,

As per http://forum.vestacp.com/viewtopic.php?f=10&t=9365, would it be possible that when adding an alias domain, the corresponding DNS record be automatically generated?

Thanks,
Rhys

**Comment by serghey-rodin** [comment]
Yes of course it is possible, but please note that your domain name servers should be controlled by Vesta Control Panel

**Comment by RhysIT** [comment]
Hi,

Sorry to open again! I meant that the DNS record within the Vesta CP be created :)

Rhys
