### ISSUE TITLE
vestacp filemanager

### ISSUE THREAD

**Issue by syrakozz** [serghey-rodin/vesta#464]
can you plz add an important feature , 
the file manager 
currentyl the integration of the third party file manager is difficult

**Comment by tjebbeke** [comment]
They are working on it

**Comment by anton-reutov** [comment]
This feature already completed
Will be in the new version

**Comment by marcelloinfoweb** [comment]
Very good, when it is expected the new version?

**Comment by anton-reutov** [comment]
new release will be in a few days

**Comment by leboari** [comment]
When it is expected the new version?

**Comment by syrakozz** [comment]
+1

**Comment by anton-reutov** [comment]
Now we are finishing rewrite the vestacp code
Roadmap for new release you can find here
https://bugs.vestacp.com/versions/1

**Comment by peterbrinck** [comment]
@anton-reutov 
Great to see a new roadmap, more detailed etc.

But please.... Keep things in English!

**Comment by n1trux** [comment]
>But please.... Keep things in English!

:+1:

**Comment by skurudo** [comment]
FileManager as plugin available already.
Closed.
