### ISSUE TITLE
Codebase Documentation

### ISSUE THREAD

**Issue by SysVoid** [serghey-rodin/vesta#479]
To attract and educate new developers on Vesta's codebase/structure, it might be a good idea to create a wiki of some sort for developers to learn how everything is pieced together.

Definitely low priority, but it would be extremely useful.

**Comment by KeiroD** [comment]
+1 on that, from me.

I've forked a copy of this repository... but trying to make sure services are as secure as possible here is a giant pain in the ass. It'd be nice if we could have further guides on securing the server.

Alas, I suspect that'll be a long-term goal.

**Comment by KeiroD** [comment]
@SysVoid What sort of documentation are you looking for, as a developer?

I'm almost familiar enough with VestaCP to write a rudimentary developer doc.

**Comment by SysVoid** [comment]
@KeiroD How everything is pieced together. What methods are available, where stuff is called, handled, etc.
