### ISSUE TITLE
Proxy Pass directives

### ISSUE THREAD

**Issue by KeiroD** [serghey-rodin/vesta#481]
Oi.

Can we get this stupid thing fixed? I keep trying to fix it but you have somehow made it difficult to get a working proxy pass that actually passes user IPs and not the web server's IP.

It is annoying to have my access logs be full of the server's IP and not the real client IP. And it also makes troubleshooting issues like this unnecessarily more complex.

**Comment by rivermigue** [comment]
I fixed it in an easy way on Debian 7.

I have moved /etc/apache2/mods-enabled/rpaf.conf to /etc/apache2/mods-enabled/rpaf.confold and then created a new /etc/apache2/mods-enabled/rpaf.conf with this content:
<IfModule rpaf_module>
RPAFenable On
RPAFsethostname On
RPAFproxy_ips 192.168.1.150 192.168.1.151
RPAFheader X-Forwarded-For
</IfModule>

Replace the ips 192.168.1.150 and 192.168.1.151 with the ones that you have on your server as proxy in case you have more than one just add it in the same line separated by spaces.
