### ISSUE TITLE
Cron Daemon Error

### ISSUE THREAD

**Issue by SysVoid** [serghey-rodin/vesta#485]
Not sure if this is default behaviour, but some investigation could be done.

Vesta cron emails me this every time crons are run:
/usr/local/vesta/bin/v-update-user-stats: line 70: /usr/local/vesta/data/users/history.log/user.conf: Not a directory
/usr/local/vesta/bin/v-update-user-stats: line 101: /usr/local/vesta/data/users/history.log/stats.log: Not a directory
chmod: cannot access `/usr/local/vesta/data/users/history.log/stats.log': Not a directory

**Comment by SysVoid** [comment]
@serghey-rodin

**Comment by giutrec** [comment]
For resolve this problem you can remove /usr/local/vesta/data/users/history.log file and its return to work propely

**Comment by SysVoid** [comment]
@giutrec done. Will report.
