### ISSUE TITLE
Форум

### ISSUE THREAD

**Issue by radiolip** [serghey-rodin/vesta#486]
Здравствуйте. Невозможно войти под логином на форум, forum.vestacp.com, выдает сообщение: You exceeded the maximum allowed number of login attempts. In addition to your username and password you now also have to solve the CAPTCHA below.

CAPTCHA не отображается.

С уважением!

**Comment by anton-reutov** [comment]
Здравствуйте. Ранее ответили вам через info@vestacp.com
