### ISSUE TITLE
can not log in in Debian 7 wheezy

### ISSUE THREAD

**Issue by x86fantini** [serghey-rodin/vesta#488]
Hi, i have installed vesta in a debian 7 wheezy virtual server. i have done it three time and same result:

root@magentocontrol:~# tail -f /var/log/vesta/auth.log 
2015-11-14 16:17:59 admin 127.0.0.1 failed to login
2015-11-14 16:18:18 root 127.0.0.1 failed to login
2015-11-14 16:19:41 admin 127.0.0.1 failed to login

my server is:
root@magentocontrol:~# uname -r
3.2.0-4-amd64

vesta has been setup with:
bash vst-install.sh --nginx yes --apache yes --phpfpm no --vsftpd yes --proftpd no --exim yes --dovecot no --spamassassin no --clamav no --named no --iptables yes --fail2ban yes --mysql yes --postgresql no --remi no --quota no --hostname XXXXXXX --email XXXX@XXXXX --password XXXXXXX

Debian is version 7.9

any help is apreciated

**Comment by serghey-rodin** [comment]
Two suggestions:

1) check your password in command line
```
/usr/local/vesta/bin/v-check-user-password admin p4swsw0rd
```

2) reset your password 
```
/usr/local/vesta/bin/v-change-user-password admin n3w_p4swsw0rd
```

**Comment by x86fantini** [comment]
well i i try the check-user-password i see in log:
2015-11-14 19:52:37 admin 127.0.0.1 successfully logged in

i have then reset the password as per you indication but then from the gui i can not login, and log says:
2015-11-14 19:52:52 admin 127.0.0.1 failed to login

i'm still stuck :(

**Comment by serghey-rodin** [comment]
It seems like sudo isn't working for some reason. What do you see when you run
```
su - admin
sudo /usr/local/vesta/bin/v-check-user-password admin p4swsw0rd
```

**Comment by x86fantini** [comment]
root@magentocontrol:~# su - admin
-su: /bin/ls: Permission denied
-su: /bin/ls: Permission denied

yes, seems sudo isn't working. is sudo a package installed by vesta during setup or is a prerequisite for any new base server?

do you have any suggestion on how to move on from here?
thank you very much

**Comment by x86fantini** [comment]
nothig has worked. i have reinstalled vesta in Ubuntu 14.04 LTS and everything its ok. For me, it's something related to wheezy, 3 times in a row when installing vesta on wheezy i have this issue with the login.

thank you

**Comment by serghey-rodin** [comment]
Please email me your server hostname and root account to skid at vestacp.com. I'd be happy to help you with that.

**Comment by KeiroD** [comment]
@x86fantini Try this link: http://forums.debian.net/viewtopic.php?f=16&t=84762

**Comment by skurudo** [comment]
Closed due inactivity.
