### ISSUE TITLE
Move error_reporting(NULL);

### ISSUE THREAD

**Issue by cdnmall** [serghey-rodin/vesta#491]
Can you please remove error_reporting(NULL); from the top of all the pages and place it in /inc/main.php

**Comment by skurudo** [comment]
Can you please explain a bit?

**Comment by cdnmall** [comment]
When testing scripts within vesta cp no errors are shown because of error_reporting(NULL); is at the top of every page which voids errors reporting. If this was place at the top of /inc/main.php then instead of changing every file I could simple take it out of /inc/main.php. Yes I enabled debugging within nginx and php-fpm
