### ISSUE TITLE
IUS repository

### ISSUE THREAD

**Issue by DavorSaric** [serghey-rodin/vesta#496]
Hello, can I enable IUS repo instead of REMI and after that run the install script?
I would recommend the IUS repo for more recent versions of PHP, mysql etc. It is focused on security. So basically EPEL with IUS should be enough...

**Comment by AbbyNormal** [comment]
I think you should evalute this because if I install nginx + apache with remi enabled and after I want to install php-fpm there will be a dependency problem regarding php-common from remi version... I want to use php-fpm with apache, nginx I could remove...
