### ISSUE TITLE
unknown directive "Include"

### ISSUE THREAD

**Issue by cronner** [serghey-rodin/vesta#510]
was: Include /home/admin/conf/web/snginx.conf

corrected: include /home/admin/conf/web/snginx.conf;

so "I" to "i" and missing ";"

and nginx started again

also Apache2 was installed and serving my files suddenly?

Used with install:

curl -O http://vestacp.com/pub/vst-install.sh && bash vst-install.sh --nginx yes --phpfpm yes --apache no --vsftpd yes --proftpd no --exim yes --dovecot yes --spamassassin yes --clamav yes --named no --iptables yes --fail2ban yes --mysql yes --postgresql no --remi no --quota yes --hostname MY.HOST --email MY@MAIL --password MYPASS

**Comment by d2r2net** [comment]
I have the same issue under Unbuntu 14.04

**Comment by foae** [comment]
>2015/12/30 16:34:06 [emerg] 1837#0: unexpected end of file, expecting ";" or "}" in /etc/nginx/conf.d/vesta.conf:4
2015/12/30 16:37:27 [emerg] 8844#0: unexpected end of file, expecting ";" or "}" in /etc/nginx/conf.d/vesta.conf:4
2015/12/30 16:38:02 [emerg] 8859#0: unexpected end of file, expecting ";" or "}" in /etc/nginx/conf.d/vesta.conf:4
2015/12/30 16:38:13 [emerg] 8874#0: unknown directive "Include" in /etc/nginx/conf.d/vesta.conf:3

It's a template issue. Adding a `;` and replacing the upper case `I` (Include) resolved the problem.
