### ISSUE TITLE
Request: Mail migration by using e.g. getmail

### ISSUE THREAD

**Issue by cricsus** [serghey-rodin/vesta#511]
Hey there,

I have a suggestion to add a little tool within the GUI like several mail providers offer:
To add the functionality to download old emails of the email account from the former used mail server.
By this, the old emails should be easily migrated into the new mailserver and IMAP-users wouldn't lose any mails or have the trouble to save the previous mails manually.

I think some tools like Getmail can be used for downloading the mails of the fomer mail server into the new one :)

Thanks in advance for taking this into consideration and best wishes.

**Comment by peterbrinck** [comment]
This would be really great!

+1 :+1:

**Comment by cheetooh** [comment]
I have been using imapsync but this feature will be much more convenient!

+1 :+1:

**Comment by cricsus** [comment]
## If you like this suggestion
 please _*upvote :+1: and comment* :speech_balloon:_  in the link below:

#### [ https://bugs.vestacp.com/responses/mail-migration-by-using-eg-getmail-v-imapsync ] (https://bugs.vestacp.com/responses/mail-migration-by-using-eg-getmail-v-imapsync)

Thanks :smile:
