### ISSUE TITLE
Input format for email forwarding addresses & aliases is unclear

### ISSUE THREAD

**Issue by sman591** [serghey-rodin/vesta#512]
When inputting email addresses into the "Forward To" input for email addresses, it is unclear of how multiple email addresses should be entered: each on a new line? comma-separated? The same goes for the "Alias" input.

![screenshot 2015-11-29 16 12 55](https://cloud.githubusercontent.com/assets/1441807/11460100/12b6d944-96b4-11e5-8ddb-2407d5b018bc.png)

A simple text hint could be useful, or even better, a text input for each email address ([very basic example I found](http://output.jsbin.com/ojagej/4/)).

**Comment by SysVoid** [comment]
Either works, actually.
