### ISSUE TITLE
Add server IPs to SpamAssassin

### ISSUE THREAD

**Issue by pabloko** [serghey-rodin/vesta#513]
Issue on Ubuntu 14.14 (untested on other systems) causing SA not working properly. This was flooding  /var/log/exim4/paniclog with connection rejected messages.

Seems SA need to know IPs that will connect to it, so server ips must be added in  /etc/default/spamassassin

`OPTIONS="--create-prefs --max-children 5 --helper-home-dir -A 444.333.222.111,111.222.333.0/24"`

Doing this spamd will allow exim4 connection and work properly without closing the connection unexpectedly and evaluating spam score of recieved mails.

This may be auto updated on install&changing server ips

Also it could be good to eneable by default Rule2XSBody in SA config that will perform better on cpu usage and will make email reciving quicker.

In addition to that, adding reverse IP's to the smtp banner of exim by default is needed and have to be manually done in order to have good mail rep

**Comment by n1trux** [comment]
why is this closed?
