### ISSUE TITLE
Request: HTTP/2 Support

### ISSUE THREAD

**Issue by cricsus** [serghey-rodin/vesta#521]
Hey there,

On the forum, you guys said you would implement an HTTP/2 support once both apache and nginx does support HTTP/2.

So I'd like to remind the other guy's request since nginx actually supports HTTP/2 since its release nginx 1.9.5 (22. Sept. 2015)

It would be great if you could implement this in the Decembers release since this will improve the loading speed of the hosted websites.

Thanks in advance for your great news! :)

**Comment by cricsus** [comment]
## If you like this suggestion
 please __*upvote :+1: and comment* :speech_balloon:__  in the link below:

#### [ https://bugs.vestacp.com/responses/http-2-support ] (https://bugs.vestacp.com/responses/http-2-support)

Thanks :smile:

**Comment by SysVoid** [comment]
Opening an issue and posting an idea there is weird. If you want feedback here, post here. If you want feedback there, post there.

**Comment by cricsus** [comment]
sry. realized that vesta had such a place at bugs.vestacp.com a lill later.
And on github there was no other place to find. So that is also the reason why the heading starts with "Request" in order to preserve a confusion.

But howsoever, I can for sure delete this post if youu're not comfortable with it, mate

**Comment by skurudo** [comment]
Idea on tracker -> https://bugs.vestacp.com/issues/104
Closed here.
