### ISSUE TITLE
If using CloudFlare Real Visitor Wrong IP Address

### ISSUE THREAD

**Issue by eka7a** [serghey-rodin/vesta#522]
If using CloudFlare, occurs in the wrong ip in log results.

https://www.cloudflare.com/ips/
![screencapture](https://cloud.githubusercontent.com/assets/5789807/11591656/2be134c2-9aa2-11e5-82cc-1cf6551fff5e.png)

**Comment by SysVoid** [comment]
Please follow CloudFlare's tutorial on fixing it here:
https://support.cloudflare.com/hc/en-us/articles/200170706-How-do-I-restore-original-visitor-IP-with-Nginx-

**Comment by SysVoid** [comment]
Closing issue since I've answered it.
