### ISSUE TITLE
[Request] Drop support for Ubuntu and Debian OS

### ISSUE THREAD

**Issue by ionescu-bogdan** [serghey-rodin/vesta#530]
To simplify the process of developing and qa testing please remove support for:
- Ubuntu
- Debian

These operating systems are not used for (large scale) hosting.
From another perspective, the code written by the community will be easier to implement, without bugs and surprises after every upgrade.

Thank you,
Ionescu Bogdan

**Comment by sman591** [comment]
:-1: Ubuntu is a very common OS, and is often used by many "how-to" guides as a good base OS (look at any of Digital Ocean's community tutorials). I personally use Ubuntu for all of my VMs and experimental environments for this reason, on top of having a great developer community.

**Comment by KeiroD** [comment]
Agreed, dropping support for Debian-based distros is a bad idea.

If support is dropped, I'll just fork Vesta and maintain a Vesta-based control panel after I consider what to rename Vesta to.

**Comment by skurudo** [comment]
-1
I don't like this idea. So many time to make support for debian/ubuntu distro and now remove support? Sorry, but it does not make sense. I'm against idea of remove debian/ubuntu distro support.

**Comment by hellodanielting** [comment]
Dropping support for Debian based systems is a horrible idea.
CoreOS amongst many other [popular distros](http://distrowatch.com/dwres.php?resource=major) are Debian/Ubuntu based.

**Comment by cheetooh** [comment]
-1
I only use Ubuntu. This is the best I can find so far to support all my Ubuntu machines.

**Comment by SysVoid** [comment]
:-1: DigitalOcean's entire infrastructure is running on Ubuntu (as far as I can remember).
Yeah, their hosting sucks, but they are keeping up a massive website with just Ubuntu.

**Comment by TheLastProject** [comment]
This is an absurd suggestion. Ubuntu and even moreso Debian are VERY popular server Operating Systems.

In fact, [they seem to be way more common than RedHat and CentOS](http://w3techs.com/technologies/details/os-linux/all/all). So, if anything, we should drop RedHat and CentOS support ;)

The thing is, the OSses supported by Vesta are really the most common ones and the current list is basically perfect. Changing anything about it would be a bad idea.

**Comment by trajche** [comment]
This is the most absurd request. rm -rf on this issue immediately.

**Comment by quacos** [comment]
Well, this made me laugh because I don't like Ubuntu on servers, but sounds like cutting a testicle to make the other bigger.

**Comment by serghey-rodin** [comment]
There are many users out there who love these systems. And this is good because more users = more eyes = more bugs getting found = more bugs getting fixed = better control panel for everyone.
