### ISSUE TITLE
bb-library installation

### ISSUE THREAD

**Issue by ordinaryegi** [serghey-rodin/vesta#536]
Hi
i'm new in vestacp, i want to install Boxbilling modules in vestacp, but i don't understand installation instruction, where i should put bb-library folder in vesta folder? i'd try install in /usr/local/vesta but nothing's change

i'm using centos 6.7

regards

**Comment by KeiroD** [comment]
You're not supposed to do that with Vesta. At least, not in `/usr/local/vesta`.

You're supposed to put it in `/home/username/web/domain.com/public_html`. Obviously, `username` is the user that you have that has a domain pointing at the Vesta server. So if you want to use the `admin` user, that'd be `/home/admin/web/domain.com/public_html`... where `domain.com` is your website's domain.

**Comment by ordinaryegi** [comment]
so i had to install boxbilling first?
ok i understand, thank's for explanation

regards

**Comment by KeiroD** [comment]
@ordinaryegi No... do you know how cPanel works? It's similar to how cPanel works. Basically, you're supposed to add `boxbilling` into your website's `public_html`. Much like you upload your `boxbilling` files to cPanel in the `public_html` directory. Then you go to your website's `boxbilling` install and give it the database details that you created via cPanel's `MySQL Databases` wizard.

Similar process in Vesta.

**Comment by ordinaryegi** [comment]
oh i see, ok it's clear to me know thank you so much
