### ISSUE TITLE
Mysql DB name size over limit. A user can not create DB.

### ISSUE THREAD

**Issue by rmalenko** [serghey-rodin/vesta#537]
Users can create an account with a very long name. 
Vesta adds this long name before a DB name.
MySQL has the limit of numbers of symbols to name.
A user can not create DB.

I think a solution is when a user will be allowed change/add the a prefix which will be limited of number characters on the MySQL page. This should allow to have unique DB names and avoid situations when a user can not create DB.

Regards,
Rostyslav

**Comment by KeiroD** [comment]
An easy solution to that is to simply limit the username space that Vesta will allow. And that if one wishes to change it, a note should be included to also raise the DB name length?

Just a thought, but I'm not sure how easy nor difficult it'd be to implement.

**Comment by sman591** [comment]
I submitted an issue about this back in February and even submitted a proposed solution to fix it... but since have not heard anything back. See #113

**Comment by skurudo** [comment]
https://bugs.vestacp.com/issues/258
