### ISSUE TITLE
Suggestion to use Travis CI

### ISSUE THREAD

**Issue by KeiroD** [serghey-rodin/vesta#539]
Hi, guys!

I figure that I should open an issue and suggest that you guys use [Travis CI](http://travis-ci.org).

This way you get to have automated testing for the Ubuntu platform. I'm not sure if Travis'll ever opt for other OS builds but I do know that Travis CI is kind of sorta maybe working on my fork of Vesta. I've been working on getting Vesta to work with Travis CI and vice versa.

Maybe an option similar to `bash vst-install.sh -y -e=example@domain.com -fq=domain.com` as options in order to pass along to Travis CI so the build doesn't get stopped waiting for the build to say yes to it?

**Comment by SysVoid** [comment]
Open for discussion, folks!
