### ISSUE TITLE
HTTP Strict Transport Security (HSTS) toggle

### ISSUE THREAD

**Issue by TheLastProject** [serghey-rodin/vesta#541]
Plain HTTPS can be removed by a protocol downgrade attack.

Simplified explanation of a protocol downgrade attack:
1. User connects to a WiFi network you control (laptop, for example)
2. User visits https://vestacp.com/.
3. You force the visit to use HTTP instead of HTTPS.

To properly secure websites against such attacks, we need to use HTTP Strict Transport Security (HSTS).

Luckily, this is very easy to implement, just a single line to Apache2. See [Set up HSTS in Apache2](https://raymii.org/s/tutorials/HTTP_Strict_Transport_Security_for_Apache_NGINX_and_Lighttpd.html).

It would be nice if Vesta could have a checkbox for domains having SSL support to enable HSTS. Something like this:
![HSTS option mockup](https://cloud.githubusercontent.com/assets/1885159/11767292/0ce62dee-a1a9-11e5-8758-9c94963eb83f.png)

**Comment by WeNDoRx** [comment]
bump

**Comment by d2dyno** [comment]
Would like to see this. There's an increasing need for it.

**Comment by n1trux** [comment]
nginx supports HSTS with a single config line, too:

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

Keyword `always` only works since nginx v1.7.5 – since Debian jessie and wheezy-backports only have 1.6.2, we should disable this for Debian. (other supported distributions should be checked)

Source: https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/

**Comment by iamra** [comment]
These seem like one can just add to the web engine templates. Also if you are using DNS Cloudflare, you can enable this from their side. A check box just simplfies this for someone who does not know how to edit the templates, but you can just create a separate template with your changes.
http://vestacp.com/docs/#template-description

**Comment by geolyth** [comment]
I don'u understand how to put HSTS in my server with Vesta
