### ISSUE TITLE
Website: Documentation Update

### ISSUE THREAD

**Issue by rhyswilliamsza** [serghey-rodin/vesta#542]
Hi There,

The following needs to be added to the documentation, under the "How to install ClamAV and SpamAssassin on a Debian or Ubuntu" section:

Exim configuration
sed -i "s/^#SPAMASSASSIN/SPAMASSASSIN/g" /etc/exim4/exim4.conf.template
**sed -i "s/^#SPAM_SCORE/SPAM_SCORE/g" /etc/exim4/exim4.conf.template**
sed -i "s/^#CLAMD/CLAMD/g" /etc/exim4/exim4.conf.template
service exim4 restart

Rhys

**Comment by anton-reutov** [comment]
Information on our site will be updated
Thank you
