### ISSUE TITLE
nginx bug

### ISSUE THREAD

**Issue by cronner** [serghey-rodin/vesta#543]
nginx: [emerg] "location" directive is not allowed here in /etc/nginx/conf.d/webmail.inc:1
nginx: configuration file /etc/nginx/nginx.conf test failed
Restarting nginx: nginxnginx: [emerg] "location" directive is not allowed here in /etc/nginx/conf.d/webmail.inc:1
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by trajche** [comment]
Is this on a clean install?
Check: http://stackoverflow.com/questions/20392741/nginx-errorlocation-directive-is-not-allowed-here-in-etc-nginx-nginx-conf76

Or paste the /etc/nginx/conf.d/webmail.inc contents here.
