### ISSUE TITLE
Adding custom configurations to domains 

### ISSUE THREAD

**Issue by pabloko** [serghey-rodin/vesta#548]
Vesta should be able to manage custom apache/nginx configs, the template system isnt enough to provide control on your services.

I will not ask for this and just do what i need, but i post here and commit to my fork for these people that need control of the config files 

![](http://puu.sh/lWPzg/a0ab92e47d.png)

I've used cdn ace.js that has apache_conf and nginx syntax highliters.

This needs the most basic nginx&apache templates to run

custom.tpl+stpl

```
#Apache
#custom.tpl
IncludeOptional %home%/%user%/conf/web/%web_system%.%domain%.manual.conf
#custom.stpl
IncludeOptional %home%/%user%/conf/web/s%web_system%.%domain%.manual.conf
#NGINX
#custom.tpl
include %home%/%user%/conf/web/nginx.%domain%.manual.conf;
#custom.stpl
include %home%/%user%/conf/web/snginx.%domain%.manual.conf;
```

To be fair, just with this template you can just create config files for each web. Adding the UI to panel need some modifications on /web/add|edit/index.php and /web/templates/admin|user/add|edit_web.html

Just used ajax on <select> onchange to get the configs results in place of editor, then selecting "custom" will display the editor.

The config values will be directly saved against user webconfig folder with .manual.conf extension, no backup stuff linked yet...

If theres interest on this i will make a PR, in the mean time i will upload my mods on my own fork

**Comment by jnico** [comment]
Yes interested.

**Comment by SysVoid** [comment]
Vesta's template system works fine in my opinion. Need more things in a virtual host? Make a new template. Then, if you need it again, it's just a dropdown.

**Comment by okwme** [comment]
Where is this PR?

**Comment by lazmo88** [comment]
+1
@pabloko - I could not locate the commit from your fork? Could you advise how to achieve this functionality?

**Comment by lazmo88** [comment]
@SysVoid Yes, making templates works. However if you are hosting 10 different JS/Java/whatever apps running in custom ports or just want to build custom reverse proxy pointing to a external endpoint modifying these templates again and again can be very slow. Therefore this idea should be considered again for easier access to per domain config files.

**Comment by pabloko** [comment]
@lazmo88 unfortunately i think an update smashed new files on top of those mods, so i think ive lost em. But its quite simple to do, just create some dumb config files named Custom with bare minimum conf and edit templates edit_web.html, just add some editor, ive used ace.js and watch for dropdown with selected <Custom> template to show the editor. Just write some external file included on custom conf and youre ready. I like vesta because its so simple and easy to add anything i need easily, any other panel is heavily bloated with spaggetti code.
