### ISSUE TITLE
Possible configuration error in func/main.sh

### ISSUE THREAD

**Issue by rsearle** [serghey-rodin/vesta#553]
I think main.sh line 6 should be changed from:

`BACKUP='/backup'`

... to ...

`BACKUP='/home/backup'`

Please see http://forum.vestacp.com/viewtopic.php?f=10&t=5399&p=36379#p36379

**Comment by KeiroD** [comment]
You are referring to http://forum.vestacp.com/viewtopic.php?f=10&t=5399&p=36379#p36379

Please ensure your link works properly.

**Comment by rsearle** [comment]
@KeiroD,

http://forum.vestacp.com/viewtopic.php?f=10&t=5399&p=36379#p36379 works in my clients. Can't see a problem with it. Please clarify.

**Comment by KeiroD** [comment]
Your original post showed up with http://forumvestacpcom/viewtopicphp initially.

You seem to have edited it so it appears correctly.
