### ISSUE TITLE
[Request] Configuration Backup

### ISSUE THREAD

**Issue by Secretjail** [serghey-rodin/vesta#557]
what happen if user could have a configuration backup on installation? configuration file contains firewall rules backup , hostname,plugin licenses..etc (any possible details)so user can just install using old server configuration
bash vst-install.sh --config-file configuration.txt

**Comment by KeiroD** [comment]
That would be great. It'd make server migrations much easier.

ie, if you're moving from a small server to a larger server, it'd be excellent to not have to do the initial configuration of `VestaCP`

Definitely a 1+ from me.

**Comment by sman591** [comment]
This would be great. Server migrations and stage environments would be much easier with this. +1

**Comment by Secretjail** [comment]
thank you for comments.
please vote @  https://bugs.vestacp.com/responses/request-configuration-backup

**Comment by gionniboy** [comment]
i like it :)    :+1:

**Comment by anton-reutov** [comment]
function is not in demand
