### ISSUE TITLE
простая и достаточно важная вещь

### ISSUE THREAD

**Issue by edgiru** [serghey-rodin/vesta#558]
Очень не хватает отображения даты и времени в панели. Причем на железе оно может быть свое, на вирт. сервере другое и в сети другое.

**Comment by mzf** [comment]
+1 need this feature too

**Comment by skurudo** [comment]
А в какой части и какого времени? (серверное, php, по гринвичу)
Не очень понятно, где и что нужно отображать.

**Comment by edgiru** [comment]
ну считаю не обязательно где то в основной области, а в настройках где то расположить, зашел проверил сверил с локальным все ок закрыл. в том то и смысл что бы было с чем сверять т.е. несколько 1. это интернет часы точного времени. 2. часы настроенные на железе (сервер) 3. часы в виртуальном сервере VPS. и желательно бы с настройкой часового пояса.

**Comment by Nanotraktor** [comment]
+1
Возможность отслеживать время не сервере была бы очень полезна. 
Особенно актуален вопрос при размещении на VPS. В некоторых случаях оно отстаёт/спешит очень ощутимо. 

```
mv /etc/localtime /etc/localtime.old 
ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime 
hwclock --systohc --utc
ntpdate pool.ntp.org
chkconfig --add ntpdate
```

Было бы  шикарно это дело добавить в разделе панельки ххх.ххх.ххх.ххх:8083/list/server/ отдельным пунктом. С возможностью увидеть текущее время на сервере (серверное, php) установить часовой пояс и выполнить синхронизацию (либо выбрать её периодичность).

**Comment by mzf** [comment]
Why closed?

**Comment by edgiru** [comment]
+1

**Comment by mzf** [comment]
@edgiru please translate to english your offer

**Comment by edgiru** [comment]
@mzf Зачем его переводить на английский? Я человек из России пишу как учили. Кому надо тот переведет. Не одному же мне сидеть на google translate

**Comment by anton-reutov** [comment]
Мы считаем что в этой опции нет необходимости. Для чего отображать время и дату в веб-интерфейсе панели?

**Comment by skurudo** [comment]
В основном это нужно для проверки времени -  какое и где стоит
Потому что системное время может отличаться от пхпшного.

Это важно для синхронизации, для магазинов, логов и т.д.

**Comment by anton-reutov** [comment]
В файле /usr/local/vesta/web/templates/admin/edit_server.html
После линии 78 добавьте следующий код

`<tr>
                                <td class="vst-text input-label">
                                    <?php print __('System Time');?>
                                </td>
                            </tr>
							<tr>
                                            <td>
                                                <input type="text" size="20" class="sys-time" name="v_proxy_system" value="<?php echo date('l jS \of F Y h:i:s A'); ?>" disabled>
                                                <br><br>
                                            </td>
                                        </tr>`

В файле /usr/local/vesta/web/css/styles.min.css
После линии 2438 добавьте

`.sys-time {
background-color: #fff;
border: 1px solid #cfcfcf;
font-family: Arial;
font-size: 19px;
height: 28px;
margin: 2px 6px 0 0;
padding: 7px 3px 9px 14px;
width: 385px;
font-weight: normal;
}`

В настройках сервера после Time Zone появится поле System Time c датой и текущем системным временем. Пока делал так и не смог понять что мешает посмотреть на время в часовом поясе Time Zone

**Comment by anton-reutov** [comment]
Подправил мануал.

**Comment by skurudo** [comment]
и php будет в итоге какое время отдавать? Я вот почему-то думаю, что vesta-php, а не того php, что в системе стоит :)
