### ISSUE TITLE
Can't create database user : too long

### ISSUE THREAD

**Issue by Spheerys** [serghey-rodin/vesta#569]
Hi,

Step to reproduce :
- create a new user with a long name : myverysuperlongname
- connect through myverysuperlongname
- add a new database called myverysuperlongname_sql for example, with a db user myverysuperlongname_sql

It will failed because the string of the database username is limited under mysql.

**Comment by Flatta** [comment]
#113 ?

**Comment by Spheerys** [comment]
oups !
That's it !
I switched to percona to solve my issue...

**Comment by Spheerys** [comment]
Humhum... my issue is not closed...
After switched to Percona, I tried to create a database called my-long-user-name.com_bdd with a db user called my-long-user-name.com_bdd and I still have this error :
```
Error: db_user my-long-user-name.com_bdd is not valid
```

**Comment by skurudo** [comment]
VestaCP supports Percona too? It's new to me.

Percona did not inherit features of mysql? Wow!

**Comment by skurudo** [comment]
Added idea to tracker - > https://bugs.vestacp.com/issues/258
