### ISSUE TITLE
Is there a way to specify the vesta code to install?

### ISSUE THREAD

**Issue by Neilpang** [serghey-rodin/vesta#573]
I just forked vesta code in github.   is there a way to install my own fork?

**Comment by KeiroD** [comment]
@Neilpang You'd have to hand-edit every mention of c.vestacp.com I believe it was, to your own servers or Github hosting the code.

**Comment by gionniboy** [comment]
@Neilpang you can install vestacp in classi way
then sync only the vesta/bin directory if you changed the vesta scripts
and vesta/web/   if you change the webpanel.

bye
