### ISSUE TITLE
[Request] Goaccess option as a awstats and webalizer

### ISSUE THREAD

**Issue by joubertredrat** [serghey-rodin/vesta#574]
[Goaccess](http://goaccess.io) is a log parser and have a html option as [this example](http://goaccess.io/goaccess_html_report.html?201512210000).

I think that is good idea to have Goaccess as option to analyze logs too.

**Comment by skurudo** [comment]
Nice idea!
Added to bugtracker - http://bugs.vestacp.com/issues/121

**Comment by GianlucaScarciolla** [comment]
Will this ever be built in?
