### ISSUE TITLE
phpmyAdmin Table Browse error

### ISSUE THREAD

**Issue by faizanayubi** [serghey-rodin/vesta#575]
when i click browse on any table i get this error
<img width="361" alt="screen shot 2015-12-31 at 12 36 49 pm" src="https://cloud.githubusercontent.com/assets/4982023/12062067/39e8720a-afbb-11e5-99df-1eaa27e5bf7f.png">

**Comment by Secretjail** [comment]
hello
it's simple access denied notice.
do you checked regular permission on DB and user (jthomas_hl) ?
first , make sure u assigned right permission to user.

**Comment by faizanayubi** [comment]
i have rechecked it and assigned the right permission but still getting these errors, i think it might be because table 'pma_table_uiprefs' does not exist, i dont know how to create that

**Comment by cdnmall** [comment]
This should help you https://forum.vestacp.com/viewtopic.php?f=11&t=9724&p=34553#p35092

**Comment by faizanayubi** [comment]
thanks @cdnmall Got it
