### ISSUE TITLE
Apache php-fpm process created even when choosing to install "nginx + php-fpm"

### ISSUE THREAD

**Issue by adrianofnatal** [serghey-rodin/vesta#577]
When I installed VestaCP choosing "nginx + php-fpm" as webserver, I noticed that php-fpm processes were executing with apache user.

**Comment by gionniboy** [comment]
are you sure about that???
it is www-data user. 
and this user is not the apache user.
and fpm is execute under admin user.

so... if you have apache user there are other problems.
if the user is www-data for nginx and admin for php-fpm...
you can close this issue.

bye :)

**Comment by skurudo** [comment]
@adrianofnatal any update?
