### ISSUE TITLE
Partition Sheme

### ISSUE THREAD

**Issue by dschense** [serghey-rodin/vesta#580]
Can anybody tell me a perfect partition sheme for the VestaCP setup?
Customers an Content is located in /home/$user, is this right? In this case its right to create a large /home directory?
What other partitions are right to create?

**Comment by Scorcher** [comment]
IMHO...
/ root partition enough to system, database and other things.
If it is possible you can link SSD disk to /var/lib/mysql to improve performance of mysql database. Then root partition may be smaller...

**Comment by Scorcher** [comment]
i think if i will use quota - it will be used only on /home partition. I do not know how it is managed by VestaCP.

**Comment by skurudo** [comment]
Let's discuss those on forum -> https://forum.vestacp.com
Please use github for pulls and pulls comments.

Thanks.
