### ISSUE TITLE
SFTP v-add-backup-host fails

### ISSUE THREAD

**Issue by Scorcher** [serghey-rodin/vesta#581]
VestaCP was installed by this command
```
# Run it
bash vst-install.sh --nginx yes --apache yes --phpfpm no --vsftpd no --proftpd yes \
--exim yes --dovecot yes --spamassassin yes --clamav no --named yes --iptables yes \
--fail2ban yes --mysql yes --postgresql no --remi yes --quota yes --hostname hostname.ru \
--email email@email.com --password NNNN
```

Then I want to add SFTP backup host, but it fails, because dependent utility "expect" does not installed.
```
root@vsh:~# v-add-backup-host sftp IP login password backup
Error: expect command not found
root@vsh:~# expect
The program 'expect' is currently not installed. You can install it by typing:
apt-get install expect
```

2. seems like there is no "expect" dependency in main package...

After i install utility i am trying again and get error
```
Error: can't create temp folder on the sftp host
```

If i create backup directory via FTP - last error does not happens.

2. seems like script can not create temporary directory with parents directory via SFTP protocol.

**Comment by SysVoid** [comment]
Closing & locking as this is being addressed in issue #624 and discussion can be made there.

Thank you for your help.
