### ISSUE TITLE
New domain create alias on empty field

### ISSUE THREAD

**Issue by joubertredrat** [serghey-rodin/vesta#582]
Hi guys,

When I create new domain, alias for domain is created even if I clear the field. If I edit and remove alias runs fine.

**Comment by skurudo** [comment]
Alias with main domain? It's pretty normal.

**Comment by iCPU** [comment]
Howdy, can confirm this problem. "www" alias **always** created even if alias field cleared before adding new domain. This is breaking downstream scripts that automate ssl certs for **subdomains**. 

Sorry could not see why this is happening, v-add-web-domain looks OK, so maybe something before this not passing the "none" for alias as argument.
