### ISSUE TITLE
Roundcube Security Issue

### ISSUE THREAD

**Issue by cdnmall** [serghey-rodin/vesta#586]
Access should be denied when accessing http://localhost/webmail/installer/ in some cases roundcube installation fails and the installer is open to the whole world. Also I have been wondering why you guys dont place roundcube, phpmyadmin, etc within vesta port ex. https://localhost:8083/webmail?

**Comment by malsony** [comment]
I suggest a 301 redirect script in the location where you host those apps.

**Comment by cdnmall** [comment]
I dont host these apps they come with vesta
