### ISSUE TITLE
DMARC Record Error

### ISSUE THREAD

**Issue by faizanayubi** [serghey-rodin/vesta#587]
<img width="950" alt="screen shot 2016-01-12 at 12 04 33 am" src="https://cloud.githubusercontent.com/assets/4982023/12242647/4fa3b24a-b8c0-11e5-8dc1-cb82d34e99a4.png">

I have installed vestacp on my server but my email goes to spam, when i checked it online it says DMARC invalid record or missing

how should i add DMARC record

**Comment by gionniboy** [comment]
you have to create it by yourself.
if you use the vesta dns you can create using this
https://vestacp.com/docs/#how-to-configure-srv-records
but instead a srv entry you have to create a dmarc entry
[may this can help you https://blog.returnpath.com/build-your-dmarc-record-in-15-minutes/ ]

but if you use external dns [for example hosting provider dns or something]
you have to use the manager/panel of your hosting company.

BUT as far as i know DMARC don't send you in spam....
maybe you have other issue.

in fact: you haven't rdns configured.

try here by yourself
https://mxtoolbox.com/SuperTool.aspx?action=smtp%3acloudstuff.tech&run=toolpage

you have to configure it through you hosting panel.

bye.

**Comment by faizanayubi** [comment]
i have added the DMARC Record, from the same article Thanks
<img width="874" alt="screen shot 2016-01-15 at 10 12 25 am" src="https://cloud.githubusercontent.com/assets/4982023/12345555/8310c1e2-bb70-11e5-9715-8ed9770c02db.png">

i have registered my domain with godaddy and hosting on AWS
<img width="1244" alt="screen shot 2016-01-15 at 10 01 45 am" src="https://cloud.githubusercontent.com/assets/4982023/12345570/a970341c-bb70-11e5-96f3-cc3cd61917d4.png">
At AWS i cant find the way to configure reverse DNS

i tried the MXToolBox
<img width="741" alt="screen shot 2016-01-15 at 10 05 55 am" src="https://cloud.githubusercontent.com/assets/4982023/12345562/9858aca4-bb70-11e5-83ff-c7313caf2c5d.png">

But Still i find my message in SPAM
<img width="901" alt="screen shot 2016-01-15 at 10 25 44 am" src="https://cloud.githubusercontent.com/assets/4982023/12345697/6746a33a-bb72-11e5-84fa-c0fbe0c3c135.png">

But Comes to inbox in my Gmail Account

**Comment by gionniboy** [comment]
i am not an aws user so i don't know a lot the service...
but i think you need something like that

https://aws.amazon.com/blogs/aws/reverse-dns-for-ec2s-elastic-ip-addresses/

**Comment by faizanayubi** [comment]
Thanks, for the help but i followed the same blog earlier, it does not lead me to Reverse DNS
i have to see some other reference
