### ISSUE TITLE
MTA (exim/dovecot) SSL cert for virtual hosting trouble

### ISSUE THREAD

**Issue by gionniboy** [serghey-rodin/vesta#601]
vesta cp for webdomain works good when generate certificate.
even if there are sub domains. no problems.
but for the mta it use the vesta cert without customization for every virtual host.
so you can't comunicate in tls through 587 with another smtp

[ try this http://www.checktls.com/perl/TestReceiver.pl ]
Cert NOT VALIDATED: self signed certificate
[005.939]       So email is encrypted but the domain is not verified
[005.940]       Cert Hostname DOES NOT VERIFY (mail.domain.cp != www.domain.cp)
[005.940]       So email is encrypted but the host is not verified

or logs like that
Job exception: hostname "mail.domain.cp" does not match the server certificate

a way to manage mail certificate for virtual host will be very useful.
thanks for all.

**Comment by donat1** [comment]
Is this issue fixed (because comment is closed on Feb 2017)? I have the same problem on vestacp with different virtual domains.

> [000.791] |   | Cert VALIDATED: ok
> -- | -- | --
> [000.791] |   | Cert Hostname DOES NOT VERIFY (mail.example.ch != mail.test.ch \| DNS:mail.test.ch)
> [000.791] |   | So email is encrypted but the host is not verified

What did the trick?

Thanks for any help.
