### ISSUE TITLE
Question: fpm backend configurations

### ISSUE THREAD

**Issue by demil** [serghey-rodin/vesta#603]
I need to ask why there are backend configurations for each domain? Is it going to cost performance for php-fpm to load 1000 config files? I have used php-fpm before it came with vesta bundled, and i used only global configuration.

Can you tell me what are pros, and what are cons of this approach - config per domain.

**Comment by gionniboy** [comment]
you can do it.
every virtual host has his own fpm pool.
look at /etc/php5/fpm/pool.d/
something like: vhosting1.conf vhosting2.conf ecc ecc

the global conf is for the fpm dedicated to vestacp [port 8083]
his conf file is in /usr/local/vesta/php/etc/ .

[if this answer is complete for you please close the issue, bye]
