### ISSUE TITLE
root compermized

### ISSUE THREAD

**Issue by anshu2212** [serghey-rodin/vesta#604]
I have 3 servers  one vesta cp with nginx + apache, other vesta cp with Nginx - PHP fpm and other virtualamin  with nginx-phpfpm

My server with Vesta + nginx + PHP-fpm got root comfermized 3 times and blocked by the vps provider .

i Think there is some problem and with it . All my serever has key based ssh only and none can login with passsword. more over i setup my server and left it on its on just seting up a domain . and still it got comfermized

i can attach the logs if asked. because i dont know which one to attach.

**Comment by SysVoid** [comment]
/var/log/secure might help, but I'm not too sure.

**Comment by skurudo** [comment]
> got root comfermized 3 times
How exactly?
You're sure about root nor site?

>i can attach the logs if asked
It'll be nice. You can use dropbox or dropmefiles.com

**Comment by skurudo** [comment]
And what your hoster write about your server block?

**Comment by gionniboy** [comment]
what webapp you run on to?
maybe it's a bad wordpress plugin [just to say] and after that [you have a php shell on the wordpress] a "normal" escalation.

and ssh key only mean nothing.... maybe a buggy generation of the keys?
or worst: default keys :\

more info will be useful [maybe you can close the server temporarily] and perform a deep scan.

**Comment by anshu2212** [comment]
Sorry for late reply
@SysVoid i am on ubuntu and the equivalent file is auth.log. i s that ok. should i attach the whole auth.log or by masking or just the last transections.

@skurudo because  last time i dint upload any thing installed vesta , created a user. added a domain to it , and just uploaded a html page . applied a basic authentication on the default apps. so i am sure  there was no application.

@gionniboy since its 3 times , last time i dint setup any thing . i knew something is wrong and wanted to confirm its not wordpress . or the combination of wordpress and the server setup.

i am attaching the last lines of auth.log 
![tail_f_root_old_vm](https://cloud.githubusercontent.com/assets/2157540/12344518/faa4bdc4-bb63-11e5-8181-d15a2d07503a.JPG)

**Comment by anshu2212** [comment]
@skurudo 
hoster i mean vps provider gave this excuse 
![error_details frome2e](https://cloud.githubusercontent.com/assets/2157540/12344619/1f7cce2e-bb65-11e5-9e7a-60a237ff00b4.JPG)

and the gdrive link for log file https://drive.google.com/file/d/0BwckANOI3oztTDVKNXRTellhcEE/view?usp=sharing

@gionniboy . i changed the ssh keys every  time. i dont use default keys.
thanks for the advise to close the server . i already did that .

**Comment by skurudo** [comment]
Improved security in new release:
https://vestacp.com/roadmap/#0.9.8-16
