### ISSUE TITLE
migrating from apache to php-fpm

### ISSUE THREAD

**Issue by demil** [serghey-rodin/vesta#605]
I updatet vesta but i dont have option for php-fpm, How can i migrate to php-fpm mode?

**Comment by SysVoid** [comment]
As far as I know, updates stick to your current setup.
Is PHP-FPM listed in "Servers"?

**Comment by demil** [comment]
How  can i change setup? No, there is not php-fpm listed in servers.

**Comment by SysVoid** [comment]
That's strange. What version were you previously on?
