### ISSUE TITLE
user already exists bug

### ISSUE THREAD

**Issue by kolomparrudi** [serghey-rodin/vesta#607]
Hi,

I trying to add a new user called www. The v-add-user script says, user already exists, because it check with this command:
cut -f 1 -d : /etc/passwd | grep -w "www"
It returns the built in www-data user.

Br,
Laszlo

**Comment by avaxalex** [comment]
Fix #612

**Comment by skurudo** [comment]
Fixed and merged -> https://github.com/serghey-rodin/vesta/issues/612
