### ISSUE TITLE
Domain SOA email address

### ISSUE THREAD

**Issue by kolomparrudi** [serghey-rodin/vesta#609]
Now vesta put root.domainname.com. SOA email address to the domain zone. I don't want to create root@ email address or alias for all my domain, I prefer to use a common email address for all my domains (eg. domain@mycompany.com), in the current version there is no option to do this. I had to hardcode my address to /usr/local/vesta/func/domain.sh. It would be nice to modify this value from the admin.

Br,
Laszlo

**Comment by skurudo** [comment]
Nice! Idea added to bugtracker - http://bugs.vestacp.com/issues/120
