### ISSUE TITLE
Ftp Backup error - Debian 8

### ISSUE THREAD

**Issue by rtoemail** [serghey-rodin/vesta#610]
I try add ftp backup by command:

root@#: v-add-backup-ftp-host ftp.domain.com user pass
bash: v-add-backup-ftp-host: command not found

my installation is on debian 8.2

**Comment by skurudo** [comment]
Do you have expect in your system?
`apt-get install expect`

Bugs: http://bugs.vestacp.com/issues/64
Github similar request: https://github.com/serghey-rodin/vesta/issues/624

**Comment by rtoemail** [comment]
yes, I have expect installed in my system.

for me to work, i use this commands:
cd /usr/local/vesta/bin
bash v-add-backup-host ftp remote_host remote_user pass /backup

but still not working

2016-02-01 05:14:10 Local: /backup/backupfile.2016-02-01.tar
2016-02-01 05:14:10 Remote: ftp://remote_host/backup/backupfile.2016-02-01.tar
FTP active mode is forbidden, passive mode is mandatory

**Comment by SysVoid** [comment]
Ah, the issue here is with passive/active.
