### ISSUE TITLE
"Failed nginx restart" when update domain settings

### ISSUE THREAD

**Issue by ryam4u** [serghey-rodin/vesta#611]
the error occurs because a duplicate line for the domain is created.
File: "/etc/nginx/conf.d/01_caching_pool.conf"

**Comment by raven-kg** [comment]
Same problem found in my installation. 

```
[root@deimos ~]# nginx -t
nginx: [emerg] the same path name "/var/cache/nginx/example1.com" used in /etc/nginx/conf.d/01_caching_pool.conf:1 and in /etc/nginx/conf.d/01_caching_pool.conf:2
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by skurudo** [comment]
Added a bug - https://bugs.vestacp.com/issues/148
Thanks

**Comment by coolbit** [comment]
Bug link provided is not related to the issue discussed in this page.

**Comment by skurudo** [comment]
Link fixed, sorry for this mistake.
https://bugs.vestacp.com/issues/149

**Comment by coolbit** [comment]
Thanks skurudo.
