### ISSUE TITLE
Неверный state сервиса named команды v-list-sys-services

### ISSUE THREAD

**Issue by EzheG** [serghey-rodin/vesta#614]
После отключения сервиса named через web панель статус все равно отображается как запущенный.

```
# pidof httpd
10695 10694 10692 10680 9520 8491 8490 1761 1755
# pidof named
# v-list-sys-services
NAME      STATE    CPU     MEM     RTIME
------    ------   ------  ------  ------
httpd     running  3.9     179     56
nginx     running  0.3     8       56
named     running  0.3     8       56
exim      running  0       1       41
dovecot   stopped  0       0       0
mysqld    running  0.3     2158    41
vsftpd    running  0       1       41
crond     running  0       1       56
iptables  running  0       0       0
fail2ban  running  0       36      56
# cat /etc/*-release
CentOS release 6.7 (Final)
CentOS release 6.7 (Final)
CentOS release 6.7 (Final)
# cat /proc/version
Linux version 2.6.32-573.12.1.el6.i686 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Tue Dec 15 18:25:17 UTC 2015
```

**Comment by skurudo** [comment]
+1

повторяется на CentOS 6 / CentOS 7
не повторяется на убутну и дебиане

**Comment by skurudo** [comment]
Однако подозреваю, что обновление state происходит не сразу - выключил в панели, решил проверить все, а там:
` [root@centos6 ~]# v-list-sys-services
NAME      STATE    CPU     MEM     RTIME
------    ------   ------  ------  ------
httpd     stopped  0       0       0
nginx     stopped  0       0       0
named     stopped  0       0       0
exim      stopped  0       0       0
dovecot   stopped  0       0       0
mysqld    stopped  0       0       0
vsftpd    stopped  0       0       0
crond     stopped  0       0       0
iptables  stopped  0       0       0
fail2ban  stopped  0       0       0`

**Comment by EzheG** [comment]
@skurudo многострочный код лучше в тройные апострофы заключать

**Comment by skurudo** [comment]
@EzheG угу, поправил

**Comment by skurudo** [comment]
Добавили в багтрекер - http://bugs.vestacp.com/issues/123, попробуем разобраться.
Спасибо @EzheG

**Comment by anton-reutov** [comment]
Уже решено
