### ISSUE TITLE
vestacp keep crashing mysql !!

### ISSUE THREAD

**Issue by syrakozz** [serghey-rodin/vesta#615]
i have serveral server and i always notice that my sql is stop working every couple of hours,

**Comment by skurudo** [comment]
Can I put sarcastic comment here?
Man, be a little specific. Start with server configuration, os, mysql config.

**Comment by syrakozz** [comment]
[mysqld]
  2 datadir=/var/lib/mysql
  3 socket=/var/lib/mysql/mysql.sock
  4 user=mysql
  5 symbolic-links=0
  6 max_connections=700
  7 max_user_connections=30
  8 wait_timeout=100
  9 interactive_timeout=500
 10 long_query_time=5
 11 #log-queries-not-using-indexes
 12 #log-slow-queries=/var/log/mysql/log-slow-queries.log
 13
 14 key_buffer = 106M
 15 myisam_sort_buffer_size = 302M
 16 join_buffer_size=10M
 17 read_buffer_size=10M
 18 sort_buffer_size=20M
 19 table_cache=1024
 20 thread_cache_size=286
 21 interactive_timeout=205
 22 connect_timeout=5
 23 max_allowed_packet=100M
 24 max_connect_errors=10000
 25 query_cache_limit=10M
 26 query_cache_size=80M
 27 query_cache_type=1
 28 tmp_table_size=160M
 29
 30 #innodb_use_native_aio = 0
 31 innodb_file_per_table
 32 innodb_buffer_pool_size=640M
 33 [mysqld_safe]
 34 log-error=/var/log/mysqld.log
 35 pid-file=/var/run/mysqld/mysqld.pid

**Comment by skurudo** [comment]
Settings are quite powerful. for servers with RAM, a lot of RAM. What do you have for the server? 
By the way, log errors mysql is not shown. What's in logs?

In many case problem in config or mysql request.
Use mysql tuner to tune your config.

**Comment by syrakozz** [comment]
digitalocean 
1gb ram
1 cpu
30 gb ssd,

and the mysqd.log contain 
5 mysqld_safe Starting mysqld daemon with databases from /va      r/lib/mysql
    2 151027  6:09:25 [Warning] Using unique option prefix key_buffer instead of       key_buffer_size is deprecated and will be removed in a future release. Pl      ease use the full name instead.
    3 151027  6:09:25 [Note] /usr/libexec/mysqld (mysqld 5.5.46) starting as pro      cess 12495 ...
    4 151027  6:09:25 [Note] Plugin 'FEDERATED' is disabled.
    5 151027  6:09:25 InnoDB: The InnoDB memory heap is disabled
    6 151027  6:09:25 InnoDB: Mutexes and rw_locks use GCC atomic builtins
    7 151027  6:09:25 InnoDB: Compressed tables use zlib 1.2.3
    8 151027  6:09:25 InnoDB: Using Linux native AIO
    9 151027  6:09:25 InnoDB: Initializing buffer pool, size = 128.0M
   10 151027  6:09:25 InnoDB: Completed initialization of buffer pool
   11 InnoDB: The first specified data file ./ibdata1 did not exist:
   12 InnoDB: a new database to be created!
   13 151027  6:09:25  InnoDB: Setting file ./ibdata1 size to 10 MB
   14 InnoDB: Database physically writes the file full: wait...
   15 151027  6:09:25  InnoDB: Log file ./ib_logfile0 did not exist: new to be c      reated
   16 InnoDB: Setting log file ./ib_logfile0 size to 5 MB
   17 InnoDB: Database physically writes the file full: wait...
   18 151027  6:09:25  InnoDB: Log file ./ib_logfile1 did not exist: new to be c      reated


can you plz give me a better configuration or suggestion , thank you

**Comment by tjebbeke** [comment]
Add swap file and lower the following settings:

14 key_buffer = 106M
15 myisam_sort_buffer_size = 302M
23 max_allowed_packet=100M
26 query_cache_size=80M
28 tmp_table_size=160M
32 innodb_buffer_pool_size=640M

**Comment by raven-kg** [comment]
Try theese settings
```myisam_sort_buffer_size=16M
join_buffer_size=4M
sort_buffer_size=4M
read_buffer_size=4M
read_rnd_buffer_size=2M
query_cache_size=32M
query_cache_limit=1M
query_cache_type=1
tmp_table_size=32M
max_heap_table_size=32M
key_buffer = 32M
max_allowed_packet=32M
innodb_buffer_pool_size = 256M
```

**Comment by raven-kg** [comment]
Try theese settings
```myisam_sort_buffer_size=16M
join_buffer_size=4M
sort_buffer_size=4M
read_buffer_size=4M
read_rnd_buffer_size=2M
query_cache_size=32M
query_cache_limit=1M
query_cache_type=1
tmp_table_size=32M
max_heap_table_size=32M
key_buffer = 32M
max_allowed_packet=32M
innodb_buffer_pool_size = 256M
```

**Comment by raven-kg** [comment]
Try theese settings
```myisam_sort_buffer_size=16M
join_buffer_size=4M
sort_buffer_size=4M
read_buffer_size=4M
read_rnd_buffer_size=2M
query_cache_size=32M
query_cache_limit=1M
query_cache_type=1
tmp_table_size=32M
max_heap_table_size=32M
key_buffer = 32M
max_allowed_packet=32M
innodb_buffer_pool_size = 256M
```

**Comment by gionniboy** [comment]
and maybe you can add a supervisord/runit/monit things to restart your db.
this is not a solution, you have to inspect why mysql die, but at least it restart the service.

**Comment by syrakozz** [comment]
i tried all the config in this thread, mysql still crashing, its really annoying that there is no good default config in vesta cp for mysql , 
and i will try supervisord/runit/monit method

**Comment by skurudo** [comment]
@syrakozz and nothing in logs, when mysql rashing?

**Comment by skurudo** [comment]
No answer. Closed.

It's not a bug. Let's use forum - https://forum.vestacp.com - for topic like this.
