### ISSUE TITLE
Debian 8.3 fatal install error

### ISSUE THREAD

**Issue by nephthys** [serghey-rodin/vesta#618]
Hi,

Debian 8 is supported... or not?

Because I have the following error :

> bash vst-install.sh --nginx yes --phpfpm yes --apache no --vsftpd yes --proftpd no --exim yes --dovecot yes --spamassassin yes --clamav yes --named yes --iptables yes --fail2ban yes --mysql yes --postgresql no --remi yes --quota no
> --2016-01-27 21:37:13--  http://vestacp.com/pub/vst-install-rhel.sh
> Resolving vestacp.com (vestacp.com)... 104.236.66.100
> Connecting to vestacp.com (vestacp.com)|104.236.66.100|:80... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 44148 (43K) [text/plain]
> Saving to: ‘vst-install-rhel.sh’
> 
> vst-install-rhel.sh          100%[================================================>]  43.11K   285KB/s   in 0.2s   
> 
> 2016-01-27 21:37:13 (285 KB/s) - ‘vst-install-rhel.sh’ saved [44148/44148]
> 
> cut: /etc/redhat-release: No such file or directory
> grep: /etc/redhat-release: No such file or directory
> vst-install-rhel.sh: line 20: [: : integer expression expected
> Error: No access to Vesta repository

OS : Debian 8.3

CPU : 4 Core

RAM : 8 GB

HDD : 2 TB

Two problems :

1. Debian is not detected and the script download file `vst-install-rhel.sh`
2. When I force `type="debian"`, I still see the error `No access to Vesta repository`

Thanks for your help

**Comment by skurudo** [comment]
Supported already.

Your hoster just mess up with your distro and remove from /etc/issue.

Add in  /etc/issue file version and check:
'''
"Debian GNU/Linux 8.3"
'''

**Comment by skurudo** [comment]
This mess was with OVH (often in two month with Kimsufi) - https://forum.vestacp.com/viewtopic.php?t=9639 and https://forum.vestacp.com/viewtopic.php?f=41&t=10150&p=37788

**Comment by nephthys** [comment]
Yes it's a OVH/Kimsufi server... It works now.

Thank you :)

**Comment by kriwelz** [comment]
hello,
i'm having the same error now at OVH server. i'v read the thread above, it says
`Just needed set OS and version -> "Debian GNU/Linux 8.2"`
while i still need the ubuntu not debian for the OS. 

Please help...
