### ISSUE TITLE
NS no.

### ISSUE THREAD

**Issue by dpeca** [serghey-rodin/vesta#620]
Debian 8.3
Vesta 0.9.8-15

Very fresh installation of Vesta and Debian.
Nothing changed, nothing added... I just installed it and went to see a DNS records.

This is what's happening - https://www.dropbox.com/s/15x7myxjwnv3ho8/Vesta-DNS.png?dl=0

I feel that error is in /usr/local/vesta/bin/v-add-dns-domain

Last parameter is restart=${12}

Vesta is probably calling this script this way:
v-add-dns-domain myusername mydomain.com ns1.domain.com ns2.domain.com no

Last 'no' should be restart parameter, but script see it as NS3 :)

**Comment by arcreative** [comment]
:+1: also having this issue, having to manually delete the incorrect NS with every domain added...

**Comment by anton-reutov** [comment]
Fixed
