### ISSUE TITLE
Warning in ./libraries/Util.class.php#516 (fresh install) - phpMyAdmin

### ISSUE THREAD

**Issue by AzureusSme** [serghey-rodin/vesta#622]
Fresh install:

phpMyAdmin Login Screen:
![captura de pantalla 169](https://cloud.githubusercontent.com/assets/8404410/12799118/c79928c8-ca92-11e5-9ca8-b04cc8801f26.png)

**Comment by skurudo** [comment]
@AzureusSme OS? VestaCP version? nginx+apache? PMA version? How do you open PMA?

**Comment by erdkse** [comment]
to fix that issue you need to edit "/etc/apache2/conf.d/phpmyadmin.conf" file. Find the line begins with "php_admin_value open_basedir" and add ":/usr/share/doc/phpmyadmin/" to end of the line
