### ISSUE TITLE
Depedencies to use v-add-backup-host : expect

### ISSUE THREAD

**Issue by Spheerys** [serghey-rodin/vesta#624]
To use v-add-backup-host we have to install "expect" package.
Not a big deal, but maybe we can add it to the depedencies during VestCP installation :)

**Comment by skurudo** [comment]
We add this bug here:
http://bugs.vestacp.com/issues/64

It'll be fixed in new release I think, simple and non-critical

**Comment by SysVoid** [comment]
I'm sure this has been fixed. Closing. Let me know if it needs to be re-opened.
