### ISSUE TITLE
Wrong mail config details in add_mail_acc.html

### ISSUE THREAD

**Issue by dpeca** [serghey-rodin/vesta#625]
I think there are wrong config details in /usr/local/vesta/web/templates/admin/add_mail_acc.html

There are:
IMAP port:  143
IMAP security:  STARTTLS
SMTP port:  587
SMTP security:  STARTTLS

But, on my server with Vesta, ports are different, and I didn't change the ports, it's by default, which mean it is the same on all servers with Vesta.

On my server (and probably on all servers with Vesta) ports are:
smtp = 465 / SSL
imap = 993 / SSL
pop3 = 995 / SSL

If I'm right about these ports are default on all fresh installed Vesta servers, should I make a pull request to correct this data in template?

**Comment by anton-reutov** [comment]
This problem is actual?

**Comment by anton-reutov** [comment]
@dpeca, can you create PR if the issue is still relevant?

**Comment by dpeca** [comment]
@anton-reutov, sorry, I missed your first message.
Described problem is not actually totally correct.

STARTTLS is really on port 143 and 587.
And SSL is really on 465 and 993.

Obviously I was confused, and I didn't realized that that are TWO different encryptions.

After few months I made switcher for displaying box - so it's now possible to see both STARTTLS and SSL ports :)

**Comment by dpeca** [comment]
http://mycity.tech/screenshots/smtp-imap-settings.png

@naumov-socolov fixed styling after it, and it's implemented since 2016

**Comment by anton-reutov** [comment]
Thank for the reply
