### ISSUE TITLE
SSL ERROR: NGINX SSL CONFIG

### ISSUE THREAD

**Issue by dylanharty** [serghey-rodin/vesta#626]
Here are the steps to create the error:

1.) Create a domain with SSL in the vesta control panel.
this file is updated:

Config file:
/etc/nginx/conf.d/vesta.conf 
Updated with this:
include /home/write/conf/web/nginx.conf; 
Include /home/write/conf/web/snginx.conf
The error:
Include /home/write/conf/web/snginx.conf
Someone forgot to add the ; and added a capital I to include D: 

The solution:
On SSL generation make sure that the config file updates to 
include /home/write/conf/web/nginx.conf; 
include /home/write/conf/web/snginx.conf;

Hope this information helps! Sorry wrote this late at night apologies for any spelling or grammatical errors.

**Comment by arcreative** [comment]
:+1: Please fix!!!

**Comment by n1trux** [comment]
@arcreative tell that @serghey-rodin – the fix is out, he just didn't merge it yet.

**Comment by wodCZ** [comment]
related thread: https://forum.vestacp.com/viewtopic.php?t=9743&start=10
hotfix by grenadex: 


> The problem still exist and the reason as some people have pointed out is because it adds the Apache  line to the Nginx configuration instead of detecting the webserver and use right configuration.

> To solve this, edit the following file: /usr/local/vesta/bin/v-add-web-domain-ssl starting at line 93 to 97
```
# Checking web config
web_conf="/etc/$WEB_SYSTEM/conf.d/vesta.conf"
if [ -z "$(grep "$conf" $web_conf)" ]; then
   echo "Include $conf" >> $web_conf
fi
```

> Delete those rows or comment them out and add instead

```
# Checking web config include
web_conf="/etc/$WEB_SYSTEM/conf.d/vesta.conf"
web_include=$(grep "$conf" $web_conf )
if [ -z "$web_include" ] && [ "$WEB_SYSTEM" != 'nginx' ]; then
    echo "Include $conf" >> $web_conf
fi
if [ -z "$web_include" ] && [ "$WEB_SYSTEM" = 'nginx' ]; then
    echo "include $conf;" >> $web_conf
fi
```

> For anyone wondering, these lines are drafted from the file /usr/local/vesta/bin/v-add-web-domain as starting from line 172 to 180.

> I'm not sure where to file the fix for it, so here it is anyways.
