### ISSUE TITLE
При удалении домена НЕ удалять папку с этим доменом или хотя бы спрашивать об удалении папки

### ISSUE THREAD

**Issue by kosenka** [serghey-rodin/vesta#629]
При удалении домена НЕ удалять папку с этим доменом или хотя бы спрашивать об удалении папки

**Comment by kosenka** [comment]
Но было бы здорово, все таки дать пользователю выбор:
- удалить домен и папку домена
- удалить домен, папку домена не трогать

**Comment by Erbutw** [comment]
Не совсем удачная идея.
