### ISSUE TITLE
Many apache process from one users

### ISSUE THREAD

**Issue by mfilippov** [serghey-rodin/vesta#630]
I have VestaCP.
I have one user with many (>100) processes: /usr/sbin/apache2 -k start
How can I fix it?

**Comment by n1trux** [comment]
Sure they are processes and not threads? Compare the output of the following commands:

    ps auxH | grep [a]pache | wc -l
    ps aux | grep [a]pache | wc -l

First displays the number of processes and threads, second only the number of processes.

**Comment by mfilippov** [comment]
#ps auxH | grep [a]pache | wc -l
152

**Comment by n1trux** [comment]
Yes, this is the number of processes and threads, but I told you to compare both. Please include output of the second command, too. And use quadruple-indented lines for code as it gets formatted as code. like this

    code

**Comment by thiagof** [comment]
Same here. Memory usage and apache load is scaling

```shell
$ ps auxH | grep [a]pache | wc -l
168
$ ps aux | grep [a]pache | wc -l
168
```

Does we have any attack protection?!
