### ISSUE TITLE
Feature Request :: Google Captacha on VestaCP Login Screen

### ISSUE THREAD

**Issue by darkworks** [serghey-rodin/vesta#632]
hi to avoid brute force attacks it will be good if there is Google Captacha on VestaCP Login screen , it can be added to admin settings to enable it by adding public and private keys :)

**Comment by sman591** [comment]
:-1: I wouldn't want to use a captcha every time I log into my own admin panel. If brute-force is what you're worried about, I'd add functionality that block anyone attempting a brute force (something like 5-10 failed attempts?). Two-factor auth is another option.

**Comment by Nanotraktor** [comment]
>  I'd add functionality that block anyone attempting a brute force (something like 5-10 failed attempts?)
It`s will be much better than capthca, as for me. 
Nginx with ngx_http_limit_req_module and few strings in confiig - prefect and lightweight antibot.

**Comment by darkworks** [comment]
Hmmm in Google Captcha v2  you just need one click while it verify you , it that you will be entering username and password :)  anyway currently what we have to stop user from brute force attacks ! 

this feature request mean that there should be something , Captacha or ban user for 3 hours with 5-10 failed attempts

**Comment by soysaltan** [comment]
OS : Ubuntu 14.05

/user/local/vesta/web/templates/login.html
`  <?php
  /*************************************/
session_start();
    $digit = "6";

    function generate_code($digit) {
		$random_it="";
		$letters = "abcdefghjkmnprstuxvyz23456789ABCDEFGHJKMNPRSTUXVYZ";
		for ($i=0; $i<$digit; $i++) {
			$salla .= $letters{rand(0,strlen($letters)-1)}; 
		}
		return $salla; 
	}
    $security_code = generate_code($digit);
    $_SESSION['security_code'] = $security_code;
	/*************************************/
?>     


	   <center>
            <table class="login">
                <tr>
                    <td>
                        <table>
                            <tr>
                                <td style="padding: 0 10px 0 42px; height: 280px; width: 170px;">
                                    <a href="/"><img border=0 src="/images/vesta_logo.png" alt="Vesta Control Panel" style="margin: 0 0 0 0;" /></a>
                                </td>
                                <td style="padding: 20px 0 0 0;">
                                    <form method="post" action="/login/" >
                                    <table class="login-box">
                                        <tr>
                                            <td syle="padding: 12px 0 0 2px;">
                                                <?php print __('Username');?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <input tabindex="1" type="text" size="20px" style="width:240px;" name="user" class="vst-input">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="padding: 12px 0 0 2px;">
                                                <?php print __('Password');?>
                                                <span style="padding:0 0 0 14px;">
                                                    <a tabindex="5" class="vst-advanced" href="/reset/">
                                                        <?php print __('forgot password');?>
                                                    </a>
                                                </span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <input tabindex="2" type="password" size="20px"  style="width:240px;" name="password" class="vst-input">
                                            </td>
                                        </tr>
										
										  <tr>
                                            <td height="20px">
                                            </td>
                                        </tr>
										
										 <tr>
                                            <td>
											<div>Security Code : <label style="color: #aaa;"><?php echo  $security_code;?></label></div>
                                               <input type="text" tabindex="2" name="security_code" class="vst-input" style="width:240px;"/>
                                            </td>
                                        </tr>
										
                                        <tr>
                                            <td height="28px">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td style="padding: 0 0 12px 0;">
                                                <input tabindex="3" type="submit" value="<?php print __('Log in');?>" class="button">
                                            </td>
                                        </tr>
                                    </table>
                                </form>
                            </td>
                        </tr>
                        <tr>
                            <td colspan=2>
                                <div class="login-bottom">
                                    <div style="height:20px"><?php if (isset($ERROR)) echo $ERROR ?></div>
                                    <a class="vestacp" href="http://vestacp.com" >vestacp.com</a>
                                </div>
                            </td>
                        </tr>
                    </table>
                </tr>
            </table>
        </center>
    </body>
</html>
`

/user/local/vesta/web/login/index.php
`<?php

define('NO_AUTH_REQUIRED',true);



// Main include
include($_SERVER['DOCUMENT_ROOT']."/inc/main.php");

//echo $_SESSION['request_uri'];


$TAB = 'LOGIN';

// Logout
if (isset($_GET['logout'])) {
    session_destroy();
}


// Login as someone else
if (isset($_SESSION['user'])) {
    if ($_SESSION['user'] == 'admin' && !empty($_GET['loginas'])) {
        exec (VESTA_CMD . "v-list-user ".escapeshellarg($_GET['loginas'])." json", $output, $return_var);
        if ( $return_var == 0 ) {
            $data = json_decode(implode('', $output), true);
            reset($data);
            $_SESSION['look'] = key($data);
            $_SESSION['look_alert'] = 'yes';
        }
    }
    header("Location: /");
    exit;
}


/***************************************/
$sec_key=false;
if ( isset($_POST['security_code'])) {
	if ( $_SESSION['security_code']!=$_POST['security_code'] ) {
		 $ERROR = "<a class=\"error\">Invalid code</a>";
		 $sec_key=false;
	} else {
		$sec_key=true;
	}
}
/*************************************/


// Basic auth
if (isset($_POST['user']) && isset($_POST['password'])) {
    $v_user = escapeshellarg($_POST['user']);

    // Send password via tmp file
    $v_password = exec('mktemp -p /tmp');
    $fp = fopen($v_password, "w");
    fwrite($fp, $_POST['password']."\n");
    fclose($fp);

    // Check user & password
    exec(VESTA_CMD ."v-check-user-password ".$v_user." ".$v_password." ".escapeshellarg($_SERVER['REMOTE_ADDR']),  $output, $return_var);
    unset($output);

    // Remove tmp file
    unlink($v_password);

    // Check API answer
    if ( $return_var > 0 ) {
        $ERROR = "<a class=\"error\">".__('Invalid username or password')."</a>";

    } else {
		if ( $sec_key ) {//captcha control
        // Make root admin user
        if ($_POST['user'] == 'root') $v_user = 'admin';

        // Get user speciefic parameters
        exec (VESTA_CMD . "v-list-user ".$v_user." json", $output, $return_var);
        $data = json_decode(implode('', $output), true);

        // Define session user
        $_SESSION['user'] = key($data);
        $v_user = $_SESSION['user'];

        // Get user favorites
        get_favourites();

        // Define language
        if (!empty($data[$v_user]['LANGUAGE'])) $_SESSION['language'] = $data[$v_user]['LANGUAGE'];

        // Redirect request to control panel interface
        if (!empty($_SESSION['request_uri'])) {
            header("Location: ".$_SESSION['request_uri']);
            unset($_SESSION['request_uri']);
            exit;
        } else {
            header("Location: /");
            exit;
			}
		}//sec_key
	}
}


// Check system configuration
exec (VESTA_CMD . "v-list-sys-config json", $output, $return_var);
$data = json_decode(implode('', $output), true);
$sys_arr = $data['config'];
foreach ($sys_arr as $key => $value) {
    $_SESSION[$key] = $value;
}

// Detect language
if (empty($_SESSION['language'])) {
    $output = '';
    exec (VESTA_CMD."v-list-sys-config json", $output, $return_var);
    $config = json_decode(implode('', $output), true);
    $lang = $config['config']['LANGUAGE'];

    $output = '';
    exec (VESTA_CMD."v-list-sys-languages json", $output, $return_var);
    $languages = json_decode(implode('', $output), true);
    if(in_array($lang, $languages)){
        $_SESSION['language'] = $lang;
    }
}

require_once($_SERVER['DOCUMENT_ROOT'].'/inc/i18n/'.$_SESSION['language'].'.php');
require_once('../templates/header.html');
require_once('../templates/login.html');
`

**Comment by SysVoid** [comment]
@soysaltan please make that into a [gist](https://gist.github.com/).

**Comment by soysaltan** [comment]
web/templates/login.html : https://gist.github.com/soysaltan/470f1609a9aaef95a6efcd08611af8a2
web/login/index.php         : https://gist.github.com/soysaltan/778b90088a7cb21e33f94a9d3f37d2f9

**Comment by novecode** [comment]
I think that two factor auth is the proper solution to this problem.

**Comment by anton-reutov** [comment]
@darkworks , declined

**Comment by robindirksen1** [comment]
And if you use the invisible recaptcha, would that be an option?
