### ISSUE TITLE
Vulnerability on the password change by the API PHP

### ISSUE THREAD

**Issue by rafas** [serghey-rodin/vesta#633]
Hello

I'm trying to solve a problem related to roundcube webmail, installed next to VestaCP.

I noticed that the Vesta plugin, installed on roundcube for password change, uses the php api to make the switch.

I also noticed that the API does not require authentication to make the password change, only the old password and the new, along with the e-mail to be changed.

I wanted to get the answer to a question.

**It is obvious that the API compares if the old password is really true.
But on this routine, the API does not check how many times a false password has already been entered in an attempt to a brute-force password change, and reading all the content stored on the webmail.**

I found it only in the API for changing the password of e-mail accounts. But not sure if this problem is not present in other parts of the API that are related to passwords.

EDIT: this is related to folder /web/reset/mail/

Hugs

**Comment by rafas** [comment]
Just for clarify
Note: When I refer to the "API PHP", I do not mean the API folder /web/api/ but I mean the exclusive way to email reset on the /web/reset/mail/

**Comment by dpeca** [comment]
Maybe to put some log write&check routine in /usr/share/roundcube/plugins/password/drivers/vesta.php ?
To write when was last bad attempt, and then in next init to check if last bad attempt was in last 1 hour... and to deny password check in that situation....
