### ISSUE TITLE
Feature Request: Allow only HTTPS on websites

### ISSUE THREAD

**Issue by didyouexpectthat** [serghey-rodin/vesta#634]
I'd like to be able to have https-only websites and not have something hosted on port 80. Currently, you can only add https support to existing sites.  It'd be nice to be able to disable the port 80 listener for a site and only use 443.

**Comment by tjebbeke** [comment]
You can simply redirect your users by a .htaccess file or some config changes. I think that it isn't a good idea to completely disable port 80 (HTTP).
- What were you going to do when you forgot to renew your certificate? (Or if there goes something wrong with the renew.)
- What were you going to do white devices that don't support your certificate or configuration? (SNI, FS, DH parameters, ...)

**Comment by didyouexpectthat** [comment]
I wouldn't want to completely disable port 80, but just not have a listening server for that config. 
I did consider using an .htaccess file like I already do on some sites I run on Vesta.  How about an option in Vesta to apply the correct apache2 config to forward to HTTPS instead of .htaccess? 


-My certificates are all managed through LetsEncyrpt so I am not worried about expiring certificates. As a backup, I also have wildcard certificates for the domains from StartSSL; having the certificates was not the issue.
-I have some subdomains that benefit me and really only need to benefit me, and devices I use all understand LetsEncrypt and StartSSL certificates and haven't had any complaints from browsers or the different OS I use.

**Comment by SysVoid** [comment]
You have to make a force HTTPS NGINX config.

I did this by looking up "VestaCP custom nginx template"

**Comment by didyouexpectthat** [comment]
@SysVoid Thank you for providing that. Using the nginx template seems like it would meet my needs by allowing me to choose this on creation and not with some after-established config.

Maybe VestaCP can consider adding this into the structure rather than just documenting the manual process at https://vestacp.com/docs/#how-to-force-https ??

**Comment by SysVoid** [comment]
Feel free to make a commit. :D

**Comment by didyouexpectthat** [comment]
I will add it to my list of things to do. :)
