### ISSUE TITLE
Named/NGINX Sharing Status

### ISSUE THREAD

**Issue by SysVoid** [serghey-rodin/vesta#636]
On `/list/server/`, both `named` and `nginx` share their on/off status. NGINX seems to be the one controlling.

Steps to reproduce:
Turn off NGINX via web interface
-> named off
Turn on NGINX via web interface
-> named on

**Comment by skurudo** [comment]
We have some sort but with state service.. It's on centos?

**Comment by SysVoid** [comment]
Yeah, CentOS 6.

I took a look at the code, but couldn't find the issue - otherwise I'd have made a PR.

**Comment by skurudo** [comment]
@SysVoid thanks, it's was message on russian 

Issue: https://github.com/serghey-rodin/vesta/issues/614
Bug: https://bugs.vestacp.com/issues/123
