### ISSUE TITLE
v-add-web-domain-alias restart = yes, return 500.

### ISSUE THREAD

**Issue by miftasoft** [serghey-rodin/vesta#642]
Hello

I noticed when I add a new domain alias via web api always return 500 if restart parameter is YES.

v-add-web-domain-alias example example.com alias.com yes

Thank you :)

**Comment by SysVoid** [comment]
Try running the Vesta commands in this bit of code:
[Vesta Commands](https://github.com/serghey-rodin/vesta/blob/master/bin/v-add-web-domain-alias#L103-L112)
