### ISSUE TITLE
Attempt to automate build

### ISSUE THREAD

**Issue by KeiroD** [serghey-rodin/vesta#647]
Hi,

So, I'm still working on figuring out the best way to automate building Vesta and seeing if it'll pass or fail.

If you look at my [fork](https://github.com/EidolonHost/vesta), you will notice that the build status says it's erroring or failing. This is because it errors while waiting for someone to press yes and to provide details to the Vesta installer.

I'm assuming I'll need to add -e example@exampledomain.com to the installer, yes?

Also, how in the name of fuck are we going to get around the issue of saying yes/no to the installer?

As long as `Would you like to continue [y/n]:` is here, I cannot make the build pass because it expects an answer from Travis CI which can't give it the answer... and I thought --force was supposed to make it install anyway?

Gah. I'm frustrated with trying to get the build process to WORK.

Edit: Damn, I thought I had it. >:| It seems like the installer is just straight up ignoring the options I give it in the .travis.yml that I have in the repository.

Edit2: Fuck it, I have no idea how to get around the `Would you like to continue [y/n]:` issue. It blocks me from trying to get an automated build going for us so we have some form of testing code.

**Comment by n1trux** [comment]
I feel your frustration, man. Maybe the installer should have some testing flags first. I think it's a really huge install script and should rather be bundled in a sane way of packaging.

So probably before starting to automate build you could look at the installer and refactor its code?

**Comment by KeiroD** [comment]
Yeah, I'm thinking I'm going to have to work on the installer code because it's simply ignoring the force install option. And it shouldn't be. So something here is wrong.

If one looks at all the [options](https://github.com/serghey-rodin/vesta/blob/master/install/vst-install-ubuntu.sh), you'll notice there seems to be a few that might work, such as:

```
# Defining help function
help() {
    echo "Usage: $0 [OPTIONS]
  -a, --apache            Install Apache        [yes|no]  default: yes
  -n, --nginx             Install Nginx         [yes|no]  default: yes
  -w, --phpfpm            Install PHP-FPM       [yes|no]  default: no
  -v, --vsftpd            Install Vsftpd        [yes|no]  default: yes
  -j, --proftpd           Install ProFTPD       [yes|no]  default: no
  -k, --named             Install Bind          [yes|no]  default: yes
  -m, --mysql             Install MySQL         [yes|no]  default: yes
  -g, --postgresql        Install PostgreSQL    [yes|no]  default: no
  -d, --mongodb           Install MongoDB       [yes|no]  unsupported
  -x, --exim              Install Exim          [yes|no]  default: yes
  -z, --dovecot           Install Dovecot       [yes|no]  default: yes
  -c, --clamav            Install ClamAV        [yes|no]  default: yes
  -t, --spamassassin      Install SpamAssassin  [yes|no]  default: yes
  -i, --iptables          Install Iptables      [yes|no]  default: yes
  -b, --fail2ban          Install Fail2ban      [yes|no]  default: yes
  -q, --quota             Filesystem Quota      [yes|no]  default: no
  -l, --lang              Default language                default: en
  -y, --interactive       Interactive install   [yes|no]  default: yes
  -s, --hostname          Set hostname
  -e, --email             Set admin email
  -p, --password          Set admin password
  -f, --force             Force installation
  -h, --help              Print this help
  Example: bash $0 -e demo@vestacp.com -p p4ssw0rd --apache no --phpfpm yes"
    exit 1
}
```
I tried the --force and -f option, as well as -y, which assumes yes. Unfortunately, it seems to not be working as intended.

I'll be also taking a look at the other OS installers to see if they have the same problem... and if so, we really need to fix it because the way it works right now, VestaCP is broken.

**Comment by n1trux** [comment]
Do you need help or do you think it's better to work on the installer code refactoring alone? Maybe make it more modular so you don't have the same code multiple times?

**Comment by KeiroD** [comment]
@n1trux Yeah, I do. I'd like to have other eyes taking a look at my attempts to automate the build process.

I'll add you to my fork so you can take a look and be able to make changes, as well. The more eyes on this, the better in helping VestaCP automate the builds and catch bugs before people who're running production servers with VestaCP gets them.

My fork of VestaCP's @ https://github.com/EidolonHost/vesta

**Comment by TheLastProject** [comment]
Have you tried `--interactive no`?

**Comment by KeiroD** [comment]
@TheLastProject Yep. See [this build log](https://travis-ci.org/EidolonHost/vesta/builds/111568081).

**Comment by SysVoid** [comment]
Try running this command before you install:

    sed -i "s/read -p 'Would you like to continue [y/n]: ' answer/answer = 'Y';/g" ./install/vst-install-ubuntu.sh

That should replace

    read -p 'Would you like to continue [y/n]: ' answer

with

    answer = 'Y';

**Comment by KeiroD** [comment]
@SysVoid Negative, [log](https://travis-ci.org/EidolonHost/vesta/builds/111636810).

Also, your suggested edit is proving to be a pain in the arse to get working via before_script.

Adding you to the repository with RW access.

**Comment by n1trux** [comment]
Testing shouldn't break the installer. Rather rewrite the installer so -y/--interactive actually does something.

I don't know why we have a lot of duplicate code in the installers, too. imho we should refactor the whole routine so we could potentially create a DEB or RPM out of it.

**Comment by KeiroD** [comment]
You know what?

I'm going to go ahead and rewrite the installers. I've also been wondering about this for some time, myself... especially as there're other control panels that have already figured out how to handle multiple OSes with a single installer.

What's that control panel? Webmin, of course! I even know where their OS detection script is in Webmin that we might be able to crib from to reduce duplicate code.

This will take some time to refactor, though.

**Comment by SysVoid** [comment]
```
sed -i "s/read -p 'Would you like to continue [y/n]: ' answer/answer = 'Y';//g" ./install/vst-install-ubuntu.sh
```
