### ISSUE TITLE
How to make fail2ban work with CentOS 7

### ISSUE THREAD

**Issue by blare** [serghey-rodin/vesta#648]
Hello,

I have a clean CentOS 7 installation, with latest Vesta Version:0.9.8 (x86_64) Release:15.

I noticed that fail2ban is installed automatically and it seems to work correctly, but there is something strange with vesta. Vesta is not showing the fail2ban information in the web-backend, nor using vesta commands line ( v-list-firewall-ban ).

After searching on internet, I fixed this issue, was just install fail2ban-systemd, (as mentioned here: https://forum.vestacp.com/viewtopic.php?t=9727&start=10 )

**yum install fail2ban-systemd**

and that's it, is working perfect.

Hope it helps

**Comment by SysVoid** [comment]
Sweet, thanks.
I'll make a commit and it'll be available soon.

**Comment by blare** [comment]
Thanks @SysVoid

**Comment by SysVoid** [comment]
No problem. :)

**Comment by blare** [comment]
Hi again,

Following, this issue, after installing **fail2ban-systemd**, it seems to work fine, but I can see some **NOTICE**s in **/var/log/fail2ban.log** file while rebooting the fail2ban service. I don't really know if is important or not, but these are the messages:
```
fail2ban.filtersystemd  [11844]: NOTICE  Jail started without 'journalmatch' set. Jail regexs will be checked against all journal entries, which is not advised for performance reasons.
fail2ban.jail           [11844]: INFO    Jail 'exim-iptables' started
fail2ban.jail           [11844]: INFO    Jail 'dovecot-iptables' started
fail2ban.filtersystemd  [11844]: NOTICE  Jail started without 'journalmatch' set. Jail regexs will be checked against all journal entries, which is not advised for performance reasons.
fail2ban.jail           [11844]: INFO    Jail 'vesta-iptables' started
```
Reading fail2ban documentation somewhere, I read that configuring the file **/etc/fail2ban/jail.d/00-systemd.conf** to **backend=auto** (instead of backend=systemd) may workaround this problem. After this changing and rebooting service it logs no **NOTICE**s :)
```
fail2ban.jail           [12642]: INFO    Jail 'exim-iptables' started
fail2ban.jail           [12642]: INFO    Jail 'dovecot-iptables' started
fail2ban.jail           [12642]: INFO    Jail 'vesta-iptables' started
```
Is this some kind of bug with default configuration in CentOS 7 + Vesta? Something to do here?

Thanks a lot!

**Comment by adnanebrahimi** [comment]
when i start vestacp installation on my fresh centos 7 vps in middle of installation when we proceed to installing fail2ban and starting service, fail2ban cannot start and show error:
Job for fail2ban.service failed because the control process exited with error code.
and vestacp installation stops.

**Comment by dpeca** [comment]
```
tailf /var/log/messages

Feb 17 19:40:27 localhost systemd: Cannot add dependency job for unit microcode.service, ignoring: Unit is not loaded properly: Invalid argument.
Feb 17 19:40:27 localhost systemd: Starting Fail2Ban Service...
Feb 17 19:40:27 localhost fail2ban-client: ERROR  There is no directory /var/run/fail2ban to contain the socket file /var/run/fail2ban/fail2ban.sock.
Feb 17 19:40:27 localhost systemd: fail2ban.service: control process exited, code=exited status=255
Feb 17 19:40:27 localhost systemd: Failed to start Fail2Ban Service.
Feb 17 19:40:27 localhost systemd: Unit fail2ban.service entered failed state.
Feb 17 19:40:27 localhost systemd: fail2ban.service failed.
Feb 17 19:40:27 localhost systemd: fail2ban.service holdoff time over, scheduling restart.
```
and it goes in infinite loop...

**Comment by dpeca** [comment]
`mkdir /var/run/fail2ban`
solved the problem.

I'll test tomorrow if this will fix the problem if we put it in installation script... or it needs to be added is systemd fail2ban script.

**Comment by dpeca** [comment]
Just to help others to not confuse himself - dont read messages from 2016 in this thread.
This is completly new issue, started to happen today.

**Comment by dpeca** [comment]
To not to confuse the people - I created separated issue - https://github.com/serghey-rodin/vesta/issues/1086
Solution is also there.
