### ISSUE TITLE
Problem with connection to phpMyAdmin

### ISSUE THREAD

**Issue by JhoanHD** [serghey-rodin/vesta#650]
The phpMyAdmin configuration storage is not completely configured, some extended features have been deactivated ,has a much  warnings with the database

**Comment by SysVoid** [comment]
Be sure to provide system information and vesta version.

**Comment by skurudo** [comment]
We made fix for this error -> https://forum.vestacp.com/viewtopic.php?f=14&t=10307
It'll be in VestaCP by default, but not now.. in .17 or .18 release.
