### ISSUE TITLE
NS records are not properly created

### ISSUE THREAD

**Issue by JhoanGamarra** [serghey-rodin/vesta#652]
DNS won't propagate , you have add directly to server, because if you don't do it this, don't function

fresh install with ubuntu 14.4 , cent os , ubunut 15.0

**Comment by SysVoid** [comment]
Make sure that you also register your nameservers at your registrar. Here's a guide for Namecheap:
[Guide](https://www.namecheap.com/support/knowledgebase/article.aspx/768/10/how-do-i-register-personal-nameservers-for-my-domain)
