### ISSUE TITLE
v-add-mail-domain-dkim not working fine

### ISSUE THREAD

**Issue by blare** [serghey-rodin/vesta#654]
Hello,

Trying to set up DKIM for my domain, I realized that VESTA has a cli command called **v-add-mail-domain-dkim**, but I think that there is some mistake in the verification part of the script.

Using:
`
v-add-mail-domain-dkim USER MYDOMAIN.COM
`
Always returned:
`Error: DKIM=yes (not empty)`

After reviewing the script **vesta/bin/v-add-mail-domain-dkim** , I realized that **is_object_value_empty** was returning this error.

So, I modified **vesta/func/main.sh** line 272, from
`if [ ! -z "$value" ] && [ "$value" != 'no' ]; then`
to
`if [ -z "$value" ] && [ "$value" != 'no' ]; then`

Now both records of DKIM are correctly added in the domain. I need to do some more tests to check if DKIM verification is passing correctly.

If someboody can check/update repo will be appreciated!

Regards

**Comment by SysVoid** [comment]
Please create a PR, then you get a spot on the collaborators page. :)
