### ISSUE TITLE
Deleting website deletes domain and mail accounts

### ISSUE THREAD

**Issue by arcreative** [serghey-rodin/vesta#656]
This is a huuuuuge issue, IMO.  I had created a website that did NOT have DNS and mail checked, and when I deleted it in troubleshooting, it happily deleted the DNS and mail records without saying a word.  This is CATASTROPHIC--my DNS records had tons and tons of A records, and was set up as an authoritative nameserver through my registrar, so the ensuing mayhem went on for a while.  If I had any mail in those accounts, it would have been gone forever as well.

Please allow the option to delete the website without deleting the associated DNS and mail records!

**Comment by SysVoid** [comment]
Thanks for this. I'll see if I can implement it.

**Comment by arcreative** [comment]
.....did you fix it?

**Comment by arcreative** [comment]
@anton-reutov
