### ISSUE TITLE
nginx logrotate user

### ISSUE THREAD

**Issue by arcreative** [serghey-rodin/vesta#659]
Looks like logrotate is failing for nginx, at least on my installation.  I get the following email when my daily cron runs:

```
/etc/cron.daily/logrotate:
error: nginx:8 unknown user 'nginx'
error: found error in /var/log/nginx/*log /var/log/nginx/domains/*log , skipping
```

I was able to fix the issue by changing the line in `/etc/logrotate.d/nginx` from `create 640 nginx adm` to `create 640 www-data adm`

not sure if this is a Vesta issue or not, but I haven't run into it on other systems with nginx.

**Comment by SysVoid** [comment]
What distro?

**Comment by arcreative** [comment]
Ubuntu 15.10

**Comment by SysVoid** [comment]
Marking as a bug but I'm not entirely sure if we're covering these types of issues.
