### ISSUE TITLE
VestaCP DNS issue

### ISSUE THREAD

**Issue by rinkuyadav999** [serghey-rodin/vesta#660]
Hi

I have do all these carefully:

How to set up own Name Servers (vanity/private/child nameservers)
If you want to manage DNS zones using Vesta Control Panel, you will have to create 2 dns records, point them to server IP address and use them as a nameservers for the domain. In this example, we will use ns1.yourdomain.com and ns2.yourdomain.com.

Domain registrar
Every domain registrar has a different method of setting up private name servers. Below you will find instructions on how to create record in GoDaddy Account Manager.
1. Log in to your GoDaddy account manager
2. Next to domains, click launch
3. Click on the yourdomain.com
4. In the settings tab, click manage next to host names
5. Click add hostname
6. Enter the ns1
7. Enter the IP address of your server
8. Click add
9. Repeat above for the ns2
10. Change name servers for yourdomain.com to ns1.yourdomain.com and ns2.yourdomain.com

Vesta Control Panel
Once the private nameservers registration is complete, you need to configure Vesta Control Panel.
1. Add domain yourdomain.com (leave DNS Support mark checked)
2. Go to DNS menu
3. Click on edit under yourdomain.com
4. Change template to child-ns
5. Go to Packages menu
6. Edit package called default
7. Set ns1.yourdomain.com and ns2.yourdomain.com as nameservers

After you have done all steps, you can now set all of your domain names to use ns1.yourdomain.com and ns2.yourdomain.com. Please note that it may take up to 24 hours while dns records will start working.

I have added host names ns1 to IP and ns2 to IP. and i have added both name servers in GoDaddy.
I have added domain and selected child-ns but domain is not pointing to server. i have checked then more than 5 times but i think it is a issue in VestaCP.

Please help.

**Comment by rinkublog** [comment]
I solved it using:

sudo apt-get install apparmor-utils
sudo aa-complain usr.sbin.named
sudo /etc/init.d/apparmor stop
sudo /etc/init.d/apparmor start
service bind9 restart


@ https://forum.vestacp.com/viewtopic.php?f=13&t=10455&sid=72505f25deb23cadc58d979b64bed72f

after wasting much time. i hope it will fix in next update!!

**Comment by sacredwebsite** [comment]
I am still having issues with DNS server not responding. I can test disabling AppArmour, but would love to know where this bug is caused so that we can continue to use it. Best regards.

**Comment by adnanebrahimi** [comment]
I have same problem in centos 7 but i don't have armor in centos,  any suggestions?

**Comment by anton-reutov** [comment]
On centos 7 this problem is not reproducible. 
I think you don't correctly configure the dns on your server

**Comment by adnanebrahimi** [comment]
One VPS with a Single IP and two name server: ns1.example.com ns2.example.com,  template set as child-ns  set name servers of default package as my name servers
