### ISSUE TITLE
Recursive adding of prefix during FTP account creation

### ISSUE THREAD

**Issue by aidjek** [serghey-rodin/vesta#665]
Vesta is latest release (15). 

When I try to create a new FTP user, prefix is adding automatically, but every attempt to Save configuration made new prefix recursive and show an error:
![image](https://cloud.githubusercontent.com/assets/2297356/13665002/f4332bc2-e6b2-11e5-8749-e1cd9e71b19c.png)

**Comment by Skamasle** [comment]
I cant reproduce this.

**Comment by aidjek** [comment]
It's real strange. 

I have tried to reproduce this on my testing and production server (here this bug has appeared) without any success. Before this I have run `yum update`.

So I guess we can close this issue.
