### ISSUE TITLE
Why file update-exim4.conf.conf has this double extension ?

### ISSUE THREAD

**Issue by Spheerys** [serghey-rodin/vesta#666]
Hi,

I have to make a specific configuration on Exim and I have found this conf file : 
```
/etc/exim4/update-exim4.conf.conf
```
Is there a reason why this file is not named update-exim4.conf ?

**Comment by Skamasle** [comment]
Hi

This no is a vesta bug, this is standard:

https://wiki.debian.org/Exim

As you can read there

`dpkg-reconfigure exim4-config`

`This writes the configuration to /etc/exim4/update-exim4.conf.conf. `
