### ISSUE TITLE
PhpMyAdmin display blank page

### ISSUE THREAD

**Issue by rinkublog** [serghey-rodin/vesta#679]
When i turn on display_errors and display_startup_errors in php.ini then PhpMyAdmin display blank page.

More @ http://forum.vestacp.com/viewtopic.php?f=14&t=10892

**Comment by ttcttctw** [comment]
I think that's phpMyAdmin's problem, there are nothing Vesta really can do

**Comment by skurudo** [comment]
Let's discuss on forum.

I like this answer: "Vesta is setup for production. Turning on display_errors and display_startup_errors, violates phpmyadmin's security. Which is why you see a blank page."
