### ISSUE TITLE
Login error (vesta.conf / login/index.php)

### ISSUE THREAD

**Issue by SS88UK** [serghey-rodin/vesta#681]
On my system of a fresh install of VestaCP. If my vesta.conf file does not contain an extra line break in the configuration file at the end, it refuses to let me login and produces this error:

`2016/04/16 15:20:37 [error] 31049#0: *543 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/local/vesta/web/login/index.php on line 92" while reading response header from upstream"`

Example of broken vesta.conf:

```
DNS_SYSTEM='bind9'
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
BACKUP_SYSTEM='local,ftp'
LANGUAGE='en'
VERSION='0.9.8'
DISK_QUOTA='no'
BACKUP_GZIP='9'
MAIL_SYSTEM='exim4'
```

/usr/local/vesta/web/login/index.php

```
exec (VESTA_CMD . "v-list-sys-config json", $output, $return_var);
$data = json_decode(implode('', $output), true);
```

json_decode does not work unless a line break is at the end of vesta.conf

**Comment by qinwanguk** [comment]
vesta.conf in /usr/local/vesta/conf
happened after PHP upgraded  to 7
