### ISSUE TITLE
Security Bug: Session files for admin is saved in /tmp

### ISSUE THREAD

**Issue by varuzam** [serghey-rodin/vesta#692]
Hi

VestaCP save session files in /tmp that is visible anyone in system. 

```
# ll /tmp/sess_pt28j0j6odug9sfhf0kb926kb1
-rw------- 1 admin admin 445 May 12 21:08 /tmp/sess_pt28j0j6odug9sfhf0kb926kb1
```
Then everyone may to get PHPSESSID and admin privileges.

**Comment by Skamasle** [comment]
Hi, there is no problem, that file as you can see is owened by admin whit permisions 600 so, only admin can read an write it.

Create new user in vesta, conect whit it try read that file, you dont have permisions to do it.

**Comment by varuzam** [comment]
Anyone may read NAME of THAT FILE!!!
PHPSESSID = name without "sess_"

**Comment by skurudo** [comment]
Thanks for your notice.
Vesta have separate folder for sessions.

Resolved and Closed, I think.
