### ISSUE TITLE
mail goes to spam [[fix]]

### ISSUE THREAD

**Issue by ganganimaulik** [serghey-rodin/vesta#693]
I recently switched to vestacp and love it!

but one problem I encountered is that:: in [mailterster](https://www.mail-tester.com) I got score of only 6.5

so I changed this dns record in vestaCp and added v=DMARC1 which wasn't there already and it fixed issue for me.
"k=rsa; **v=DMARC1;** p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC9cQr9NA3z67blSY5Ll3WS3Xw/ZsRNKLgs0w5FiyFPjqFF9zht/k9HFMHWXZEGZcNn6U+ETLH/w1D20CrdEf9Cs402CmgWD8pQ1ux88OMLaL4Wv8988fD3ZLs29lDdhFQcI0Z5sAwKHNxhEeYf/BPXLWHKla1QG9G/Za/OoaGdUwIDAQAB"

I also had to disable dmarc support and then re-enable it to get this dmarc record in dns so it would be great if someone fix this so we don't have to place v=DMARC1 & re-enable dkim support(via vestacp) each n  every-time. 

Thank You.

**Comment by DjYXA** [comment]
Check if you have enabled IPv6... Its a know issue from other panels

**Comment by dpeca** [comment]
In /etc/exim4/exim4.conf.template add:
disable_ipv6=true
and restart Exim4.

GMail everything sent from ipv6 consider as a spam.
Weird logic.

**Comment by DjYXA** [comment]
@dpeca disable it on network too

**Comment by SysVoid** [comment]
Not a bug, but keeping open for discussion. I can't currently find any issue adding DMARC as a default bit of that record. Anyone able to?

**Comment by dpeca** [comment]
I don't have any problems if IPv6 stay ON on system.
Exim4 ipv6 disable is enough.
Eventually delete AAAA record in DNS that is pointing to your server hostname.
