### ISSUE TITLE
wrong ownership/permission to public_html folder when creating website in VestaCP

### ISSUE THREAD

**Issue by baijianpeng** [serghey-rodin/vesta#694]
Today I made a test on fresh installation of CentOS 7 64-bit minimal and VestaCP, on my Virtualbox machine.

Steps to reproduce this issue:

1. installation of VestaCP

2. I created a new website via VestaCP web panel. create a new database for this website.

3. uploaded the Joomla 3.5.1 core installation package to the public_html folder of that domain via FTP. 

4.  Unzip this package (zip format) via SSH (unzip command).

5. Visit that domain in browser, I saw the "install Joomla" wizard.

6. input required information, go next and next.

7. on the FINAL step of Joomla installation, there is a button "delete the installation folder", if clicked , got "can not delete the installation folder" warning.

Yes, this is the bug I want to report. I think VestaCP should allow me to delete that folder.

How to fix?

I learned this from this topic:  http://forum.vestacp.com/viewtopic.php?f=11&t=11418

Just run this command ( replace "admin" with your username, and "gate.com" with your domain) :

`# chown -R admin:admin /home/admin/web/gate.com/public_html`

Then click that button again, you will be told it was deleted successfully.

I think this is a bug of VestaCP. My suggestion: **When creating a new website, VestaCP should AUTOMATICALLY assign correct ownership and permission to related folder of that domain**.

Thank you.

**Comment by baijianpeng** [comment]
not a bug. I was wrong. sorry.

**Comment by lukapaunovic** [comment]
https://forum.vestacp.com/viewtopic.php?f=20&t=15671
