### ISSUE TITLE
Ubuntu 16.04 support

### ISSUE THREAD

**Issue by deanpcmad** [serghey-rodin/vesta#697]
Hey, I'm just wondering when Vesta will support Ubuntu 16.04?
When running the install script I just get this error:

```shell
Error: No access to Vesta repository
```

**Comment by anton-reutov** [comment]
After few releases, maybe in the next

**Comment by vannkorn** [comment]
I also have the same issue installing Vesta in Ubuntu 16.04. Any quick fix?

**Comment by Bechrissed** [comment]
i'm waiting for 16.04 support too! It's the second most requested issue on their own bug tracker but not even in progress yet so I suppose it won't be supported anytime soon. If somebody knows of a workaround let us know :)

**Comment by elliot-labs** [comment]
I am interested in updating the support myself and have pulled it to my desktop for editing. What needs done to support 16.04?

Thanks!

**Comment by anton-reutov** [comment]
Support for Ubuntu 16 will be in the next release

**Comment by elliot-labs** [comment]
@anton-reutov Thanks for the heads up!

**Comment by skurudo** [comment]
Target version: 0.9.8-17
https://bugs.vestacp.com/issues/211

Dirty hacks and cool guide (as is):
https://forum.vestacp.com/viewtopic.php?f=10&t=11288&p=49981#p49940
