### ISSUE TITLE
MySQL Server stopped working on KUbuntu16.04

### ISSUE THREAD

**Issue by swatilodha** [serghey-rodin/vesta#702]
I use Mariadb from a long time. Yesterday, it suddenly stopped working. Receiving the following error:

`swati@swati-HP-Pavilion-15-Notebook-PC:~$ mysql -u root
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
`
To know, I didn't set a password for root user. (Also, I can't. I need root without password for work.)
It has been working without root password for a long time.

Also, I searched web a lot and found making changes to etc/mysql/my.cnf file. Unfortunately, this file doesn't open on my system. It says:
`This file is a link and doesn't have permissions`

Please help. I've been stuck on this for more than a day.

Thank you.

**Comment by anton-reutov** [comment]
Ubuntu 16x is not supported yet

**Comment by swatilodha** [comment]
But I'm using it for a month and MariDb seems to work fine on it. It suddenly started causing errors. 

Please look and help.

**Comment by swatilodha** [comment]
Should I switch back to a previous version of KUbuntu? 

please tell. I've been stuck on this for days.

**Comment by anton-reutov** [comment]
VestaCP does not support Ubuntu 16 so we can't provide support in this direction

**Comment by anton-reutov** [comment]
ubuntu 16x will be in 0.9.8-17
https://bugs.vestacp.com/issues/211
