### ISSUE TITLE
Firewall IP CIDR format not accepted

### ISSUE THREAD

**Issue by drsdre** [serghey-rodin/vesta#713]
Using VestaCP 0.9.8 (amd64)	 Release:16, I'm unable to specify all CIDR formats in the IP address field:
10.10.0.1/0 works
10.10.0.1/8 works
10.10.0.1/16 => Error: invalid ip format :: 10.10.0.1/16
10.10.0.1/24 => Error: invalid ip format :: 10.10.0.1/24

It almost seems like it interpretes CIDR address as IPv6 address.

**Comment by SysVoid** [comment]
Can confirm this is a bug on the latest version.

**Comment by anton-reutov** [comment]
Already fixed
https://bugs.vestacp.com/issues/324
