### ISSUE TITLE
Missing translation "Generate"

### ISSUE THREAD

**Issue by slmcncb** [serghey-rodin/vesta#717]
add_cron.html : https://github.com/serghey-rodin/vesta/blob/master/web/templates/admin/add_cron.html#L59

edit_cron.html : https://github.com/serghey-rodin/vesta/blob/master/web/templates/admin/add_cron.html#L59

@serghey-rodin I would add to what line of the file named `tr.php` or `en.php`?

**Comment by naumov-socolov** [comment]
it already presents in all lang files, but you are right, it should be named with leading small letter in templates - "generate", like it is written in all lang files. 
So just fix template files, and translation will work properly.

**Comment by slmcncb** [comment]
@naumov-socolov Yes, just fix template files.

Sorry, my english is bad. 

I want to create pull request, but I would add to what line? [Line 89](https://github.com/serghey-rodin/vesta/blob/master/web/inc/i18n/en.php#L89) or [line 645](https://github.com/serghey-rodin/vesta/blob/master/web/inc/i18n/en.php#L645) ?

**Comment by naumov-socolov** [comment]
you have to change only template files.

add_cron.html : https://github.com/serghey-rodin/vesta/blob/master/web/templates/admin/add_cron.html#L59

edit_cron.html : https://github.com/serghey-rodin/vesta/blob/master/web/templates/admin/add_cron.html#L59

change:  
"<?=__('Generate')?>" 
to 
"<?=__('generate')?>"

translaion files already have "generate" 
https://github.com/serghey-rodin/vesta/blob/master/web/inc/i18n/en.php#L88
https://github.com/serghey-rodin/vesta/blob/master/web/inc/i18n/tr.php#L89

**Comment by slmcncb** [comment]
"Generate" and "generator" is not equal. The letters should not be small.

"Generate" to add more sense right?

**Comment by naumov-socolov** [comment]
I've fixed css, so letter "C" would be large thanks to css.
We should not have 2 simirar translations with just capitalized letter.

**Comment by slmcncb** [comment]
@naumov-socolov thanks. It's very logical to use CSS. :+1:
