### ISSUE TITLE
Cannot add more nameservers on default plan.

### ISSUE THREAD

**Issue by superservidor** [serghey-rodin/vesta#727]
Hi Rodin

I just installed vestacp v16 on a new vps server with Ubuntu on14.04 64 Bits - 512 MB Ram - 20 GB hard disk, then I login to the control panel and tried to add more dns servers inside the default plan as admin user but I can't  did this. The link does not work.

On previous vestacp version 15 I was able to do it with no problems.

Could it be an error on this new version?

**Comment by SysVoid** [comment]
What link exactly is broken? Can you paste the 404 link here?

**Comment by superservidor** [comment]
![image](https://cloud.githubusercontent.com/assets/11233964/16537255/ed49bd5e-3fcb-11e6-8772-da624218e530.png)

The link is called "ADD ONE MORE NAME SERVER" on this page:
https://hostingcompartido.superservidor.cl:8083/edit/package/?package=default

**Comment by SysVoid** [comment]
Works for me. Can you check the console by pressing F12?

**Comment by iammegamohan** [comment]
Same problem here.

I've installed vestacp just today and "ADD ONE MORE NAME SERVER" link not working while i was up-to to add one more nameserver there in default package.

Another problem is same as with "Add Website". There is checkbox "Additional FTP" under Advanced Options while adding new web. But didn't shows any input box asking for ftp details. :(

I think javascript problem is there.

As my console log shows this :
`
ReferenceError: $ is not defined
 web:138:17
ReferenceError: GLOBAL is not defined
 web:444:9
ReferenceError: App is not defined
 add.web.js:1:1
Templator work templates.js:229:9
splitting tpls templates.js:239:9
freezing tpl keys templates.js:255:9
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery-1.7.2.min.js:3:7108
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! web
TypeError: App.Actions.WEB.toggle_additional_ftp_accounts is not a function
`

Screenshot : 
![screenshot](https://cloud.githubusercontent.com/assets/11788765/16544293/496b0e96-411e-11e6-9997-5b1ecdb17648.png)

Please help me!!!

**Comment by WRedMedia** [comment]
![15fbcee3f4fedc2df95778689a7188a9](https://cloud.githubusercontent.com/assets/8059351/16657927/5cb6d642-4475-11e6-812a-a9502125edec.png)
Can't create new ftp, or modify existing after last update of vestacp

**Comment by SysVoid** [comment]
Error is clear to us, someone will inspect. :)

**Comment by lukascellar** [comment]
![snimka obrazovky 2016-08-02 o 16 04 01](https://cloud.githubusercontent.com/assets/4516374/17331365/d1ff6982-58ca-11e6-857d-04270750cb06.png)
Same problem with FTP

**Comment by WRedMedia** [comment]
yum update vesta

**Comment by SysVoid** [comment]
Is this still happening?

**Comment by anton-reutov** [comment]
Already fixed
