### ISSUE TITLE
translate error messages into spanish language

### ISSUE THREAD

**Issue by superservidor** [serghey-rodin/vesta#728]
Hi Guys

I need to translate the following erros to spanish language:

→ Error: DNS_DOMAINS limit is reached :: upgrade user package

→ Error: WEB_DOMAINS limit is reached :: upgrade user package

Where can I do this?
Which files must I change?

Thanks

**Comment by SysVoid** [comment]
Seems like these are hard-coded.
https://github.com/serghey-rodin/vesta/blob/0dd88f9244b6ba51f77bfe3eab3858ccb02b6e14/func/main.sh
