### ISSUE TITLE
Cannot add license key due to jQuery error

### ISSUE THREAD

**Issue by andryyy** [serghey-rodin/vesta#745]
Hi,

in `web/templates/admin/edit_server.html` you define this...

```
<script>
    $(document).ready(function(){
        $('select[name=v_filemanager]').change(function(){
            if($(this).val() == 'yes'){
                $('.filemanager.description').show();
            } else {
                $('.filemanager.description').hide();
            }
        });

        $('select[name=v_sftp]').change(function(){
            if($(this).val() == 'yes'){
                $('.sftp.description').show();
            } else {
                $('.sftp.description').hide();
            }
        });
     });
</script>

```

... before the footer with jQuery is being loaded. `$` is undefinied then and the input fields do not show. Maybe you move it to the footer template or something? :-)

Bye,
André

**Comment by andryyy** [comment]
Oh, same for the apps.js include and additional ftp accounts. As a workaround I moved the footer script includes to the headers file.

**Comment by louislam** [comment]
They broken the template in this commit.

https://github.com/serghey-rodin/vesta/commit/40b5aac821abc9b488de6f1a0ad9426da032e324#commitcomment-18098845

And surprisingly, if you install VestaCP recently, it will install this broken template. Developer team should be careful with this.

**Comment by franciscopaniskaseker** [comment]
Confirmed: I moved javascript to header and now is working.

**Comment by andryyy** [comment]
Crazy they didn't fix it already, this is critical, isn't it?

**Comment by anton-reutov** [comment]
closed

**Comment by anton-reutov** [comment]
Fixed
