### ISSUE TITLE
Additional FTP option not working

### ISSUE THREAD

**Issue by franciscopaniskaseker** [serghey-rodin/vesta#746]
With fresh install I can not add FTP accounts in web interface.

I saw that is also reported here:
- http://forum.vestacp.com/viewtopic.php?f=16&t=11943
- http://forum.vestacp.com/viewtopic.php?f=16&t=11952
- https://forum.vestacp.com/viewtopic.php?f=44&t=11975

I am using updated CentOS 7 x86_64.

**Comment by skurudo** [comment]
Thanks for report
Fix will be in 0.9.8-17

https://bugs.vestacp.com/issues/276
