### ISSUE TITLE
Error: invalid mx_record format

### ISSUE THREAD

**Issue by quacos** [serghey-rodin/vesta#747]
Adding an MX record seems broken on 0.9.8-16

I had to downgrade to 0.9.8-15

**Comment by Skamasle** [comment]
There is a bug, when validator send mx or cname record, try this fix: https://github.com/serghey-rodin/vesta/pull/756

**Comment by anton-reutov** [comment]
This bug will be fixed in the next release

**Comment by skurudo** [comment]
https://bugs.vestacp.com/issues/283
