### ISSUE TITLE
Не работает php на субдоменах или DocumentRoot

### ISSUE THREAD

**Issue by MrSSDD** [serghey-rodin/vesta#767]
День добрый.

На многих проектах использую VestaCp все работает как часы спасибо авторам, но тут установил на одну из vps последний билд все как обычно.

```
domain.com - DocumentRoot /home/user/web/domian.com/public_html/frontend/web/
ad.domain.com - DocumentRoot /home/user/web/domian.com/public_html/backend/web/
api.domain.com - DocumentRoot /home/user/web/domian.com/public_html/api/web/
```

На основном домене domain.com php все работает, на субдоменах не работает php ошибка 500

Вот лог
```
PHP Fatal error:  Unknown: Failed opening required '/home/user/web/domian.com/public_html/api/web/index.php'  (include_path='.:/usrr/share/php:/usr/share/pear') in Unknown on line 0
```

хотя там есть файлы php, попробовал перейти по адресу http://api.domain.com/robots.txt открывается дефолтный файл весты

```
vestacp autogenerated robots.txt
User-agent: *
Crawl-delay: 10
```

Получается что то с DocumentRoot ???, пробовал на Ubuntu 14.04.4 LTS и Ubuntu 15.10

**Comment by MrSSDD** [comment]
Хелп кто нибудь.

**Comment by skurudo** [comment]
Обсуждение перенесено на форум:
https://forum.vestacp.com/viewtopic.php?f=28&t=12161
