### ISSUE TITLE
Issue with Private Folder

### ISSUE THREAD

**Issue by MikeP1990** [serghey-rodin/vesta#770]
Hi,

On a current server I have setup, we are utilising the private folder (/home/user/web/domain/private) for folders that should be inaccessible to the public.  This has worked fine for a long time.  We have now needed to move onto a new server (this has also worked in the past), we've taken a backup from the old vesta server for the user in question and then just restored said user, changed DNS and away we go.

On this occasion, we are using WHMCS (as previous), when we try to launch WHMCS it returns an error saying the templates_c folder needs to be writable 777 which it is.  It seems this time around that for some reason, the public_html folder is unable to read the ../private folder.

Any ideas on how to resolve this?

Thanks,

Mike

**Comment by SysVoid** [comment]
Hi!

WHMCS won't be able to read outside of public_html by default because of how security has been implemented. Is it possible to use a different location, perhaps with a `.htaccess` file denying access?

    deny from all
