### ISSUE TITLE
v-add-letsencrypt-domain: Authorizations for these names not found or expired

### ISSUE THREAD

**Issue by runelaenen** [serghey-rodin/vesta#771]
This is the full command

```
v-add-letsencrypt-domain koffieEnMoor koffie-en-moor.be www.koffie-en-moor.be,koffieenmoor.be,www.koffieenmoor.be
```

After a few minutes, it gives this output:

```
Error: Error:  Authorizations for these names not found or expired: koffie-en-moor.be
```

**Comment by pcfreak30** [comment]
The rsa key length needs to be `4096` not `2048`

**Comment by dotMastaz** [comment]
Hello,

Same error :
Error: Error:  Authorizations for these names not found or expired: domain.com

And i replace 2048 by 4096...

Any idea ?
Thanks !

**Comment by pcfreak30** [comment]
Verify dns and delete your user ssl data folder in $VESTA/data/USER/ssl.

**Comment by SysVoid** [comment]
Has this been resolved?

**Comment by insound** [comment]
I have the same bug
