### ISSUE TITLE
Мультиверсионность php на сервере с VestaCP CentOS 7

### ISSUE THREAD

**Issue by Vladusha94** [serghey-rodin/vesta#780]
После выполнения скрипта из этой темы https://forum.vestacp.com/viewtopic.php?f=19&t=10854  появляются новые шаблоны sk-php56 и т.д. Но после их применения httpd не стартует. Версия Vesta последняя 16, система CentOS 7.2.1511 (Последняя)

**Comment by anton-reutov** [comment]
Веста не поддерживает мульти php
Обратитесь к автору скрипта
