### ISSUE TITLE
file manager cant save

### ISSUE THREAD

**Issue by chipzidar** [serghey-rodin/vesta#788]
fle manager cant save after editing, displays "Error while saving file"
![5434535](https://cloud.githubusercontent.com/assets/20638018/17095259/767f7078-524b-11e6-90df-c7986de9921d.JPG)

**Comment by naumov-socolov** [comment]
what permissions does the file have?
I think the problem could be caused by permissions not allowng to write file

**Comment by SysVoid** [comment]
Marking as a non-bug because I too believe this is a permission problem with the one server. File manager works fine for me.

**Comment by oquidave** [comment]
Surprised why this was marked as "not a bug". Yes it's a permission issue, but what's the solution? Change the very permissions that VestaCP created for particular user?
