### ISSUE TITLE
web.conf not rebiuilds

### ISSUE THREAD

**Issue by AVert** [serghey-rodin/vesta#789]
Debian 8
after add new templates and assign to user 
execute v-rebuld-user and see no config files changes 
find what web.conf - not updates after i change packages of user

**Comment by ibrahimuslu** [comment]
I opended an issue about this but later I saw  this issue. This is beacuse they left this code buggy

**Comment by ibrahimuslu** [comment]
So this is not a production control panel. Its really annoying.

**Comment by SysVoid** [comment]
@serghey-rodin

**Comment by rroethof** [comment]
problem is here too (on debian 8)

v-change-web-domain-sslhome  'rroethof' 'roethof.net' 'single' 'no'

root@s001:/usr/local/vesta/log# cat /home/rroethof/conf/web/sapache2.conf | grep roethof.net | grep DocumentRoot
    DocumentRoot /home/rroethof/web/roethof.net/public_html

i specificly stated public_shtml as the docroot in panel AND via v-change-web-domain-sslhome..

**Comment by metro2030** [comment]
Also affects CentOS 7
