### ISSUE TITLE
possible security issue

### ISSUE THREAD

**Issue by AVert** [serghey-rodin/vesta#790]
when im logged in other user 
is possible create subdomain of domain of other user

**Comment by anton-reutov** [comment]
This is not a bug, so conceived

**Comment by Skamasle** [comment]
There is a third party patch in forum to prevent this

**Comment by AVert** [comment]
Thank you

**Comment by SysVoid** [comment]
Would be nice to get this disabled.

**Comment by SysVoid** [comment]
@serghey-rodin

**Comment by robindirksen1** [comment]
@SysVoid is it possible to define it in the system settings or in the template? This way we can let some user do this and others don't. Hope you understand it..
