### ISSUE TITLE
How to Upgrade PHP from v5.4 to v5.6 under CentOS 7

### ISSUE THREAD

**Issue by superservidor** [serghey-rodin/vesta#806]
During the setup process of VestaCP last version under CentOS 7  at scaleway, I got the following warning:

WARNING : PHP 5.4 have reached its "End of Life".
Even, if this package includes some security fix, backported from 5.5,
The upgrade to a maintained version is very strongly recommended.
WARNING : These php-* RPMs are not official Fedora / Red Hat build and
overrides the official ones. Don't file bugs on Fedora Project nor Red Hat.
Use dedicated forum at http://forum.remirepo.net/

Anyway, I have successfully managed to upgrade the PHP version from 5.4 to 5.6 

STEPS

1.  Add new repositories:

rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm

2. We need to install the yum replace plugin:

yum install yum-plugin-replace -y

3.  Replace the actual PHP 5.4 version with the new PHP 5.6 version:

yum replace php-common --replace-with=php56w-common

Here It will likely give you a message “WARNING: Unable to resolve all providers …”. This is normal, and you can continue by tying “y“. You will be given a chance to see what packages will be installed and removed before again being given a chance to confirm.

4. Restart Vesta services and Webservers:

service vesta restart
service httpd restart
service nginx restart

DONE !!!

My Server Info before the PHP update:
===================================================
HTTPD STATUS
Server Version: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.4.45
Server MPM: prefork
Server Built: Dec 15 2014 17:32:43

My Server Info after the PHP update:
===================================================
Server Version: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.6.24
Server MPM: prefork
Server Built: Dec 15 2014 17:32:43

My webistes works OK under this new PHP version.

Thanks VestaCP Team for so great piece of software !!!

**Comment by pcfreak30** [comment]
Hmm, revert back and get rid of `webtatic.com` version. See `http://blog.remirepo.net/pages/Config-en`.

**Comment by Skamasle** [comment]
I prefer this using remi:

yum update php --enablerepo=remi
And then
yum update php --enablerepo=remi --enablerepo=remi-php56

**Comment by SysVoid** [comment]
Closing as this is not an issue. Feel free to continue discussion though, I added a guide tag. :+1:
