### ISSUE TITLE
Change tpl no re-run sh template

### ISSUE THREAD

**Issue by gcdsm12** [serghey-rodin/vesta#815]
I created php709.tpl and php709.sh with execute permission. When I change one domain to the template php709 not run php709.sh .When v-rebuild-web-domains perform functions normally.

I use this template to change the version of php by fcgid + phpfarm.

**Comment by Skamasle** [comment]
My custom templates working fine

have you stpl also ?

You use apache or nginx ?

**Comment by gcdsm12** [comment]
without stpl 
only tpl + sh
I use apache

**Comment by gcdsm12** [comment]
for me not work.

I need to rerun the sh template and re-creating /home/user/web/mydomain/cgi-bin/fcgi-starter however the fcgi-starter file is not modified. the file fcgi-started only is recreated if I run 'v-rebuild-web-domain user domain'

**Comment by Skamasle** [comment]
stpl is needed,

but in v16 sometimes not working fine, I check it this days,

You need fixed fastcgi in domain.sh, maybe is your problem -> https://github.com/serghey-rodin/vesta/pull/759

**Comment by gcdsm12** [comment]
it does not solve. in tests if I run two times the command to change the tpl fcgi-starter file is changed.

v-change-web-domain-tpl  'admin' 'phpfarm.com' 'php709' 'yes'
v-change-web-domain-tpl  'admin' 'phpfarm.com' 'php709' 'yes'
