### ISSUE TITLE
Add Caddy webserver support

### ISSUE THREAD

**Issue by pcfreak30** [serghey-rodin/vesta#817]

**Comment by SysVoid** [comment]
Don't think it's really important right now.

**Comment by pcfreak30** [comment]
@SysVoid added the issue as i plan on adding it in my free time, think it would be cool.

**Comment by sacredwebsite** [comment]
Maybe submit to the Ideas category in the Bug/Issue tracker?
https://bugs.vestacp.com/projects/vesta-control-panel/issues?set_filter=1&tracker_id=2

**Comment by pcfreak30** [comment]
@sacredwebsite as I stated before this is mainly a placeholder for me to do work on thin in the future since I named branches based on issue numbers (git flow).

**Comment by skurudo** [comment]
@pcfreak30 
added https://bugs.vestacp.com/issues/372

Let's add ideas on bugs tracker and here pulls? )

**Comment by nevf** [comment]
+1 I am using Caddy with VestCP and would very much like to see it supported natively in Vesta. Caddy is so much easier to setup and use than Apache and it's automatic HTTPS and LetsEncrypt support is excellent.
