### ISSUE TITLE
Empty lists after Vesta core updates

### ISSUE THREAD

**Issue by petervavro** [serghey-rodin/vesta#818]
There are no items in lists in USER, WEB, DNS, MAIL, CRON, BACKUP ... What to do ?

![screen shot 2016-08-20 at 11 39 34](https://cloud.githubusercontent.com/assets/4742672/17832558/5ba529a2-66cb-11e6-996b-eba8dacde877.png)
![screen shot 2016-08-20 at 11 39 45](https://cloud.githubusercontent.com/assets/4742672/17832559/5ba93b78-66cb-11e6-80f5-306e42b982bb.png)
![screen shot 2016-08-20 at 11 40 29 1](https://cloud.githubusercontent.com/assets/4742672/17832560/5bad34a8-66cb-11e6-9185-8a6d3252cb4f.png)

**Comment by SysVoid** [comment]
Please try reinstalling VestaCP.

**Comment by SysVoid** [comment]
Marked as bug for now. This obviously needs investigation.

**Comment by anton-reutov** [comment]
`ln -s /proc/self/fd /dev/fd`
