### ISSUE TITLE
Error in validation when adding DNS record.

### ISSUE THREAD

**Issue by mzf** [serghey-rodin/vesta#820]
mx.yandex.net dont valid
![Image of Yaktocat](https://i.gyazo.com/82c2d053554f576a884906fe1a5a805b.png)

**Comment by minimarek** [comment]
This bug will be fixed in the next release - https://github.com/serghey-rodin/vesta/pull/756

**Comment by mzf** [comment]
Error was because i have another MX record.
Error information not clear
