### ISSUE TITLE
Wrong day value when edit cron job

### ISSUE THREAD

**Issue by mzf** [serghey-rodin/vesta#839]
When edit  cron job day value is equal hour value.
I think input value same in this fields
### Operating System (OS/VERSION):

CentOS 7.2.1511

### VestaCP Version:

Release 0.9.8-16

**Comment by dpeca** [comment]
It's fixed on github -  https://github.com/serghey-rodin/vesta/commit/91a5d401dca7626f1e328960418b0bc23c3d9253

This fix will be available in v17

**Comment by mzf** [comment]
Good.
