### ISSUE TITLE
[NFR] Need console method for creating package via parameters. Need for API using

### ISSUE THREAD

**Issue by mzf** [serghey-rodin/vesta#840]
Now we need create file with package description. And then add it with some name.
But very offen needed (e.g. when using VestaCP via API) creating package via parameters.

```
v-add-user-package packagename WEB_TEMPLATE=default PROXY_TEMPLATE=default
```

If some parameters not existed, copy it from default package.

**Comment by SysVoid** [comment]
I don't completely understand what you are requesting. Can you explain more?

---
[https://github.com/serghey-rodin/vesta/blob/master/bin/v-add-user-package](v-add-user-package)

**Comment by mzf** [comment]
One question. 
For example i need package with 100 domain and 100 databases. How i can create package with needed parameters via API?

**Comment by SysVoid** [comment]
Add `WEB_DOMAIN=100` and `DATABASES=100` maybe?

**Comment by mzf** [comment]
1) v-add-user-package has only 2 parameters -   PKG_DIR PACKAGE. There is no other parameters.
2) What is it PKG_DIR? Why in general the nobility, about the folder with packages?
It is very inconvenient call of API.
Simple way - ``v-add-user-package PACKAGE_NAME WEB_DOMAIN=999 ...``
If parameter not exists, it undertakes from an default package
