### ISSUE TITLE
Question: Supported browsers?

### ISSUE THREAD

**Issue by Flatta** [serghey-rodin/vesta#842]
There seems to be no information about which browsers are supported by Vesta.
I think we should provide it in order to make developing easier for us and contributors.

**Comment by dpeca** [comment]
I can't see any relation between control panel (that uses standard HTML+CSS+JS) and browsers?
Standard HTML+CSS+JS works on every modern browser, even on old browsers too.

**Comment by Flatta** [comment]
Yes, all modern browsers should be supported, but what are 'modern browsers'?
There are several technologies which are implemented by modern browsers recently, such as `<input type="email, number, ...">`, Flexbox and ES6.
So if we clarify which browser to support, it'll be easy to judge whether we can use them.

**Comment by dpeca** [comment]
Vesta is probably not using those new implementation, just simple HTML+CSS+JS, so, basicaly, it should work even with 10 years old browser, such as Firefox 1.0 :)

**Comment by dpeca** [comment]
Exceptions are mobile browsers, because design is not responsive, I checked now :/

**Comment by SpaHost** [comment]
Lets Encrypt SSL isnt be supported in older browsers... you will be carefull using this, but dont worry, that's "optional"
