### ISSUE TITLE
Vesta cp doesn't work in Ubuntu 16.04 droplet for Digital ocean.

### ISSUE THREAD

**Issue by patricmutwiri** [serghey-rodin/vesta#847]
### Operating System (OS/VERSION):

Linux Mint 18
### VestaCP Version:

0.9.8-16
### Installed Software (what you got with the installer):

php-fpm, apache, nginx, mysql
### Steps to Reproduce:

bash vst-install.sh
### Related Issues/Forum Threads:

Found anything that might be related to this? It might help us find the cause.
### Other Notes:

A solution would really help me here.

**Comment by anton-reutov** [comment]
Ubuntu 16x is not supported by VestaCP

**Comment by udanpe** [comment]
Most popular OS not supported. Perfect.

**Comment by anton-reutov** [comment]
**udanpe,** for example ?

**Comment by anton-reutov** [comment]
https://bugs.vestacp.com/issues/211

**Comment by udanpe** [comment]
This bugs created 5 month ago. Fri Apr 22, 2016. 16.04 LTS. You have many message on forum how to fix this.

**Comment by SlavikCA** [comment]
Issue seems to be resolved in Redmine:
https://bugs.vestacp.com/issues/211

But I don't see any related commits,,,
I want to test it. Please let me know, when it is there.

**Comment by skurudo** [comment]
16.04 was implemented with release 0.9.8-17
Tested on DO, if you have some problems, let's reopen this issue.
Closed for now.

**Comment by patricmutwiri** [comment]
on my way to install.. :)
