### ISSUE TITLE
Failed to fetch http://apt.vestacp.com/jessie/dists/jessie/Release.gpg  Unable to connect to apt.vestacp.com

### ISSUE THREAD

**Issue by philip-sorokin** [serghey-rodin/vesta#856]
### Operating System (OS/VERSION):

Debian 8
### VestaCP Version:

0.9.8 (amd64)
### Installed Software (what you got with the installer):

Nginx + php-fpm + all packages available + remi
### Steps to Reproduce:

When my system runs this command with CRON `v-update-sys-vesta-all`, I recieve the following messages:

> Failed to fetch http://apt.vestacp.com/jessie/dists/jessie/Release.gpg  Unable to connect to apt.vestacp.com:http:
> W: Failed to fetch http://apt.vestacp.com/jessie/dists/jessie/vesta/i18n/Translation-en  Unable to connect to apt.vestacp.com:http:
> W: Failed to fetch http://apt.vestacp.com/jessie/dists/jessie/vesta/binary-amd64/Packages  Unable to connect to apt.vestacp.com:http:
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> W: Failed to fetch http://apt.vestacp.com/jessie/dists/jessie/Release.gpg  Unable to connect to apt.vestacp.com:http:
> W: Failed to fetch http://apt.vestacp.com/jessie/dists/jessie/vesta/i18n/Translation-en  Unable to connect to apt.vestacp.com:http:
> W: Failed to fetch http://apt.vestacp.com/jessie/dists/jessie/vesta/binary-amd64/Packages  Unable to connect to apt.vestacp.com:http:
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> W: Failed to fetch http://apt.vestacp.com/jessie/dists/jessie/Release.gpg  Unable to connect to apt.vestacp.com:http:
> W: Failed to fetch http://apt.vestacp.com/jessie/dists/jessie/vesta/i18n/Translation-en  Unable to connect to apt.vestacp.com:http:
> W: Failed to fetch http://apt.vestacp.com/jessie/dists/jessie/vesta/binary-amd64/Packages  Unable to connect to apt.vestacp.com:http:
> E: Some index files failed to download. They have been ignored, or old ones used instead. W:

What does it mean and how I can fix that?

**Comment by SysVoid** [comment]
For some reason apt is unable to connect to apt.vestacp.com.

**Comment by philip-sorokin** [comment]
When I disable IPTables (standard configuration), it works, as expected. Maybe the Vesta mantainers should consider turning off the firewall when update process starts, and then it can be enabled again.

**Comment by SysVoid** [comment]
@philip-sorokin that's strange. Can you provide the output of `iptables -L`?

**Comment by philip-sorokin** [comment]
```
Chain INPUT (policy DROP)
target     prot opt source               destination
fail2ban-WEB  tcp  --  anywhere             anywhere             multiport dports http,https
fail2ban-MAIL  tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission,2525,pop3,pop3s,imap2,imaps
fail2ban-FTP  tcp  --  anywhere             anywhere             tcp dpt:ftp
fail2ban-SSH  tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     all  --  zaxvatu.net          anywhere
ACCEPT     all  --  localhost.localdomain  anywhere
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             multiport dports http,https
ACCEPT     tcp  --  anywhere             anywhere             multiport dports ftp,12000:12100
ACCEPT     tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission,2525
ACCEPT     tcp  --  anywhere             anywhere             multiport dports pop3,pop3s
ACCEPT     tcp  --  anywhere             anywhere             multiport dports imap2,imaps
ACCEPT     icmp --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain fail2ban-FTP (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain fail2ban-MAIL (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain fail2ban-SSH (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain fail2ban-WEB (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain vesta (0 references)
target     prot opt source               destination

```

**Comment by philip-sorokin** [comment]
I resolved this issue by modifying a cron task:
`sudo /usr/local/vesta/bin/v-stop-firewall && sudo /usr/local/vesta/bin/v-update-sys-vesta-all && sudo /usr/local/vesta/bin/v-update-firewall`
After this change the error messages are gone.

**Comment by brunoaferreira** [comment]
Hello,
I'm having the same problem with bitbucket:

> fatal: unable to access 'https://brunoaferreira@bitbucket.org/brunoaferreira/brunoaferreira.git/': Could not resolve host: bitbucket.org

I tried @philip-sorokin fix, but I had no success.

**Comment by skurudo** [comment]
Guys, do you use OpenVZ VPS?
With new release do you have this error?
