### ISSUE TITLE
Editing Cron Job - Hour Field duplicates over Day Field - In UI Web Panel

### ISSUE THREAD

**Issue by iamra** [serghey-rodin/vesta#858]
### Operating System (OS/VERSION):

Debian 8.5 64 Jessie

### VestaCP Version:

0.9.18 16

### Installed Software (what you got with the installer):

Default on 8GB server - nginx, apache, named, clamd + spamassasin, mysql, dovecot, exim4

### Steps to Reproduce:

1. Create a Cron Job or Use an Existing Entry
![screenshot from 2016-10-07 09-31-08](https://cloud.githubusercontent.com/assets/6845602/19193832/49f70592-8c71-11e6-99e9-be0d93d0f0b4.png)

2. Edit Cron Job:
When in Editing Cron Job screen, the Value of the Hour field, is shown/duplicated in the Day field, even though the Day field has a different original value or none/wildcard. This means you have to manually correct before save or the duplicate value takes over the original value.
![screenshot from 2016-10-07 09-31-29](https://cloud.githubusercontent.com/assets/6845602/19193857/5fb3f688-8c71-11e6-99f2-7ce4ab8274bf.png)

### Related Issues/Forum Threads:

None, not aware of any.

### Other Notes:

Vesta is THE BEST hosting control panel :)

**Comment by dpeca** [comment]
This issue is already fixed on GitHub.
https://github.com/serghey-rodin/vesta/commit/91a5d401dca7626f1e328960418b0bc23c3d9253

Fix will be available in next release.
