### ISSUE TITLE
Missing _

### ISSUE THREAD

**Issue by SysVoid** [serghey-rodin/vesta#863]
I'm unable to fix this right now.

![Image](https://vgy.me/Q3oOXk.png)

Missing an `_`.

**Comment by Flatta** [comment]
Seems to have problems [here](https://github.com/serghey-rodin/vesta/blob/35092c640667f6049a94eb6aee58bbb3939fbdcd/web/templates/admin/add_web.html#L389-L390) (compared with [this](https://github.com/serghey-rodin/vesta/blob/e343bf62a043159994ef811b551a10c99f0d5875/web/templates/admin/edit_web.html#L516) or [this](https://github.com/serghey-rodin/vesta/blob/e343bf62a043159994ef811b551a10c99f0d5875/web/templates/user/edit_web.html#L450)).
I can't check it now either.

**Comment by naumov-socolov** [comment]
nice catch, @Flatta 
I'll fix it

**Comment by Flatta** [comment]
Closed via fa2ece8
