### ISSUE TITLE
Mysql service issue

### ISSUE THREAD

**Issue by rinkuyadav999** [serghey-rodin/vesta#867]
### Operating System (OS/VERSION):

Ubuntu 14.04

### VestaCP Version:

latest

### Installed Software (what you got with the installer):

php, apache, mysql, bind9, exim4, dovecot, vsftpd, cron, iptables, fail2ban

### Steps to Reproduce:

Service of mysql is stopping again and again. it will better, we check "is mysql running", if not, start mysql service. may be, we can add this optional option in vestacp admin panel.

Right now, i am running a cron job to do same.

NOTE: we know it happens due to system memory. but auto restarting will really help.

**Comment by demlasjr** [comment]
Why don't you use Upstart to do that ?

**Comment by SysVoid** [comment]
Find out why it's stopping. Check logs somewhere around /var/log/mysql*

**Comment by dpeca** [comment]
He already said: "we know it happens due to system memory".
I had similiar situation on VPS with small RAM... kernel kills mysql to free RAM.
I wroted PHP script (run by cron) that check process list and reboot server if MySQL is not active.

**Comment by SysVoid** [comment]
Whoops, missed that.

**Comment by pabloko** [comment]
OpenVZ's procwatch kills it by pid as exceeds asignated ram, it's dumb to rely on restarting the process when this happens instead saving memory, optimizing processes and queryes and removing software you can't afford on that setup, it will end up in data loss and dabatase corruption.

But it's dumber to post that as a control panel issue, there's no one closing those kind of issues?

**Comment by rinkuyadav999** [comment]
This is related to VestaCP issue because it do not happens when we use WHM/cPanel. i do not know, how WHM/cPanel handle it. i know, how to play with these types of issues but if VestaCP can handle these issues, it will really help VestaCP users.
Anyway VestaCP is better than other free CP. Nice work team !!
