### ISSUE TITLE
Exim paniclog, DKIM, unable to open private key file for reading

### ISSUE THREAD

**Issue by iamra** [serghey-rodin/vesta#874]
### Operating System (OS/VERSION):

Debian 8.5
### VestaCP Version:

0.9.8 16
### Installed Software (what you got with the installer):

Large instance default.
### Steps to Reproduce:

I recently migrated servers and did a backup on the vesta user accounts on the old server, then v-restore-user on the new.
I Noticed error message in the Exim paniclog which was "unable to open private key file for reading".
Seems ownership for the domains dkim.pem was root:mail so I changed them to Debian-exim:mail. 

Other user in the forum ref below states they got this error after v-change-domain-owner. Not sure right now if  v-restore-user uses a similar code func.

Still testing out if this is corrected, and I am still trying to track down the exact cause of this issue.
However I am submitting this issue in order to give heads up to anyone getting this error, and hopeful track down its cause.
### Related Issues/Forum Threads:

https://forum.vestacp.com/viewtopic.php?f=12&t=11364

**Comment by dpeca** [comment]
Related bug report: https://bugs.vestacp.com/issues/349

**Comment by dpeca** [comment]
Confirmed.
Wrong file owner, extracted as root, should be Debian-exim.

I'll see what's going on in v-restore script, if someone else doesn't do it before me.

**Comment by dpeca** [comment]
Fixed - https://github.com/serghey-rodin/vesta/commit/7815539e915ec8f779c7158891261bdfaff41ee7
