### ISSUE TITLE
Deprecated Function : split()

### ISSUE THREAD

**Issue by 0x3buffer** [serghey-rodin/vesta#878]
The function split() is deprecated    

index.php:line40    list($ip,$chain) = split(":",$value);
index.php:line64    $backup_types = split(",",$_SESSION['BACKUP_SYSTEM']);
index.php:line114    $db_types = split(',', $_SESSION['DB_SYSTEM']);

split() is deprecated as of PHP 5.3.0. preg_split() is the suggested alternative to this function. If you don't require the power of regular expressions, it is faster to use explode(), which doesn't incur the overhead of the regular expression engine.

**Comment by dpeca** [comment]
Any example how it can be abused? (because you said it's dangerous)

**Comment by SysVoid** [comment]
This isn't dangerous - just deprecated.

**Comment by mzf** [comment]
Need replace anyway. Bugs possible
