### ISSUE TITLE
Friewall Page - Invalid IP format Error for CIDR addresses

### ISSUE THREAD

**Issue by Term1nal** [serghey-rodin/vesta#879]
### Operating System (OS/VERSION):

Ubuntu 14.04.5 LTS x64

### VestaCP Version:

0.9.8 r16

### Installed Software (what you got with the installer):

php-fpm, apache, nginx, mysql

### Steps to Reproduce:

Go to firewall page, edit or add a firewall entry, type in an IP address in CIDR format (eg: 0.0.0.0/0 ), and receive the error: `Error: invalid ip format :: 0.0.0.0/0`

### Related Issues/Forum Threads:

Same issue as (no replies):
https://forum.vestacp.com/viewtopic.php?t=11903

**Comment by anton-reutov** [comment]
https://bugs.vestacp.com/issues/324
resolved. Fix will be in 17
