### ISSUE TITLE
Roundcube password driver

### ISSUE THREAD

**Issue by SteveTan86** [serghey-rodin/vesta#88]
Hi,

I'm encountering an issue when trying to change email account password from within Roundcube.

> PHP Notice:  Password plugin: Broken driver: /var/lib/roundcube/plugins/password/drivers/vesta.php in /usr/share/roundcube/program/include/main.inc on line 2366, referer: http://overturelabs.com/webmail/?_task=settings&_action=plugin.password

Running Vesta on Ubuntu 13.04 x64, vesta 0.9.8-6. Any help would be greatly appreciated!

**Comment by showcheap** [comment]
Same issue, i've upgrade roundcube to latest version

**Comment by serghey-rodin** [comment]
@showcheap in order to upgrade roundcube driver run this command as root
```
wget http://c.vestacp.com/0.9.8/ubuntu/roundcube-driver-new.php -O /usr/share/roundcube/plugins/password/drivers/vesta.php
```

**Comment by phongb2b** [comment]
I have to updated the selfsigned SSL cert as following:

echo -n | openssl s_client -connect ns1.test.com:8083 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'| tee '/usr/local/share/ca-certificates/ns1.test.com.crt' && update-ca-certificates

and update the password/config.inc.php to :+1: 

$rcmail_config['password_vesta_host'] = 'ns1.test.com';
