### ISSUE TITLE
DokuWiki doesn't work with SSL

### ISSUE THREAD

**Issue by n1trux** [serghey-rodin/vesta#894]
I'll probably fix this myself, nginx template issue.

### Operating System (OS/VERSION):

Debian GNU/Linux 8

### VestaCP Version:

0.9.8-16

### Installed Software (what you got with the installer):

php-fpm, nginx, mysql

### Steps to Reproduce:

enable SSL for DokuWiki site

### fix

remove the following from `snginx.conf`

    location ^~ /lib/ {
        expires 30d;
    }

**Comment by n1trux** [comment]
I think we should replace the code block I mentioned above with this:

    location ^~ /lib/(.*)!(\.php) { expires 30d; }

**Comment by n1trux** [comment]
Why is this closed? The issue still persists, I can't see any images with the current expiration settings.

**Comment by anton-reutov** [comment]
You can create PR with this changes
