### ISSUE TITLE
banlist can't add ip (CIDR format)

### ISSUE THREAD

**Issue by LiMoon** [serghey-rodin/vesta#895]
### Operating System (OS/VERSION):

CentOS 7.2

### VestaCP Version:

0.9.8-16

### Installed Software (what you got with the installer):

apache+nginx, mysql

### Steps to Reproduce:

add ip value in "150.1.1.0/24" but Error: invalid ip format
then, CentOS 6.7 and VESTA 0.9.8-15 to ip add "150.1.1.0/24" is ok, no error.

### Related Issues/Forum Threads:

banlist add ip bug? https://forum.vestacp.com/viewtopic.php?f=10&t=13007

**Comment by anton-reutov** [comment]
Already fixed. Fix will be in v.17
