### ISSUE TITLE
Nginx fails to restart after enabling SSL Support and website goes down

### ISSUE THREAD

**Issue by rajbdilip** [serghey-rodin/vesta#900]
### Operating System (OS/VERSION): 

Debian x64 8.6

### VestaCP Version:

core package	Version:0.9.8 (amd64) Release:16

### Installed Software (what you got with the installer):

- Nginx Web Server
- Apache Web Server (as backend)
- Bind DNS Server
- Exim mail server
- Dovecot POP3/IMAP Server
- MySQL Database Server
- Vsftpd FTP Server
- Iptables Firewall + Fail2Ban
- Roundcube mail client

### Steps to Reproduce:

After Enabling SSL Support and entering required keys, and then hitting Save, the settings get saved but the site goes down and nginx fails to restart.

Nginx error log gives the following:

```
2016/11/02 18:59:29 [emerg] 8687#8687: bind() to 104.131.90.2:443 failed (98: Address already in use)
2016/11/02 18:59:29 [emerg] 8687#8687: bind() to 104.131.90.2:443 failed (98: Address already in use)
2016/11/02 18:59:29 [emerg] 8687#8687: bind() to 104.131.90.2:443 failed (98: Address already in use)
2016/11/02 18:59:29 [emerg] 8687#8687: still could not bind()
2016/11/02 18:59:54 [emerg] 8922#8922: bind() to 104.131.90.2:443 failed (98: Address already in use)
2016/11/02 18:59:54 [emerg] 8922#8922: bind() to 104.131.90.2:443 failed (98: Address already in use)
2016/11/02 18:59:54 [emerg] 8922#8922: bind() to 104.131.90.2:443 failed (98: Address already in use)
2016/11/02 18:59:54 [emerg] 8922#8922: bind() to 104.131.90.2:443 failed (98: Address already in use)
2016/11/02 18:59:54 [emerg] 8922#8922: bind() to 104.131.90.2:443 failed (98: Address already in use)
2016/11/02 18:59:54 [emerg] 8922#8922: still could not bind()

```

BUT if I reboot the server, Nginx starts up and I can access the site with both 'http' and with 'https' (certificate is successfully installed) but I get 500 Internal Server on the page and 502 Bad Gateway in browser console. This error goes away if I disable the SSL support from VestaCP panel and reboot the server.

**Comment by dpeca** [comment]
I never had that problem on Debian8 :/
Where you 'enabled SSL', on web edit page?
And how it's possible to install both three services - you said `php-fpm, apache, nginx`

**Comment by rajbdilip** [comment]
@dpeca I did standard VestaCP installation. As far as I remember it's Nginx with PHP-FPM. Apache is used to serve static content I guess.

**Comment by dpeca** [comment]
In ''nginx + php-fpm'' combination, there is no Apache at all, believe me.

Is this only error you find in logs?

**Comment by dpeca** [comment]
Maybe  you see ''php-fpm'' in proccess list, but it's a php-fpm for Vesta admin panel only, not for public and not for sites :) In that case your combination is default ''nginx+apache''.

**Comment by rajbdilip** [comment]
@dpeca I suppose so. In that case, what could be causing this issue?

**Comment by rajbdilip** [comment]
@dpeca I suppose so. In that case, what could be causing this issue?

**Comment by rajbdilip** [comment]
And yes, I enabled SSL on Web Edit page. Actually, I used https://github.com/interbrite/letsencrypt-vesta to automate the process.

**Comment by rajbdilip** [comment]
@dpeca I have updated the issue. Please have a look at it. 

Can this be because of of corrupt configuration or anything? I haven't manually modified any vesta configurations but I did use `https://github.com/interbrite/letsencrypt-vesta` script once to install LetsEncrypt certificate. Is there a way to reinstall VestaCP without affecting website files/SQL databases and VestaCP settings (DNS, Mail and everything)?

**Comment by dpeca** [comment]
I feel something other is using your 443 port, so nging can't bind it.
When it happen try to run:
`netstat -tuapen | grep 443`

However, I'm sure this is not VestaCP issue, and I'll close this ticket.
Send me a private message via forum (username is the same: dpeca) when you figure out what is using your 443 port.
It could be letsencrypt-vesta script.

**Comment by anton-reutov** [comment]
Try to kill all nginx processes and start nginx again

`killall nginx`
`service nginx start`

**Comment by rajbdilip** [comment]
@anton-reutov I did that. (Before I was rebooting, it had the same effect.) Doing that would put the site up, get both `http` and `https` working but the page shows *500 Internal Server Error* (*502 Bad Gateway* on browser console). @dpeca `netstat -tuapen | grep 443` at this point gives:

```
tcp        0      0 104.131.90.2:443        0.0.0.0:*               LISTEN      0          22290       4453/nginx.conf
```

**Comment by rajbdilip** [comment]
@dpeca @anton-reutov Insight on this?

**Comment by philippe-tellier** [comment]
@rajbdilip I happen to have the exact same issue... Di you resolve it on your server?

**Comment by rajbdilip** [comment]
@philippe-tellier No. I haven't been able to work on the issue since then.

**Comment by rajbdilip** [comment]
@philippe-tellier Did you resolve?

**Comment by philippe-tellier** [comment]
@rajbdilip I just fixed it.

I commented out the 3 IPs that were using port 443 in my "/etc/apache2/ports.conf" file, restarted apache and nginx, and everything is working fine right now.

I don't really know why there were entries in "ports.conf", but it seems that it was useless for my setup.

I hope it helps!

**Comment by rajbdilip** [comment]
@philippe-tellier
Hi. Great that you worked out a convenient solution. I had to do a fresh install. But hopefully this will help someone in the future. Thank you. :)

**Comment by bologer** [comment]
@philippe-tellier, dude, thank you very much. It worked for me :+1:

**Comment by artyficialnet** [comment]
Yeah, after the whole nigth to comment those lines fix it! Thank you! #
