### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by Rhyswilliamsza** [serghey-rodin/vesta#904]
**Version:**
Latest Github Release

**Issue**
Links are inactive for both PHP administration (:8083/edit/server/apache2/, clicking 'CONFIGURE PHP.INI'), as well as any nginx configuration. The PHP directory that is points to is no longer 'php', but rather 'php5-fpm' or 'php-fpm'. Nginx config files have not yet been created at all.

I can try fix it and try make a push.

Rhys

**Comment by anton-reutov** [comment]
we don't recommend using the code from github
You need to wait for the official release

**Comment by Rhyswilliamsza** [comment]
Install running on a test server :) Was checking the stability when I came across the issues :)

**Comment by anton-reutov** [comment]
editor for Apache config is not ready yet
it will be ready soon

**Comment by skurudo** [comment]
Fixed in 0.9.8-17
