### ISSUE TITLE
vestacp install mariadb 

### ISSUE THREAD

**Issue by darkworks** [serghey-rodin/vesta#908]
### Operating System (OS/VERSION):

Type here, e.g. CentOS 7

### VestaCP Version:

Type here, e.g. 3.14159

### Installed Software (what you got with the installer):

Type here, e.g. php-fpm, apache, nginx, maraidb

with new vestacp installation noticed that mariadb get installed , but strange thing its old 5.5 version , if installing mariadb then why not just get latest version , 5.5 is old , also got php 5.4

**Comment by core01** [comment]
On CentOS you must need to install remi repo for the latest version of php/mariadb:
`wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`
`wget http://rpms.remirepo.net/enterprise/remi-release-7.rpm`
`rpm -Uvh remi-release-7.rpm epel-release-latest-7.noarch.rpm`

**Comment by mzf** [comment]
@core01 why this not in vesta?

**Comment by core01** [comment]
@mzf 

> There are several repositories provided by CentOS and other 3rd party developers that offer software packages that are not included in the default base and updates repositories. While no list can be 100% complete, as anyone may announce an archive, it represents some major efforts and provides a summary of what each repository offers. These repositories have varying levels of stability, support and cooperation within the CentOS community. 

https://wiki.centos.org/AdditionalResources/Repositories

**Comment by xjlin0** [comment]
Just a off-topic side note:  The installed database varies, it depends on OS.

On Debian 8.6 as of now, VestaCP install MySQL 5.5 by default.  Thus I follow the steps in the VestaCP official document to add Percona official repo and install Percona 5.6 or 5.7, it works great.  

https://vestacp.com/docs/#how-to-install-percona-rhel-centos
https://vestacp.com/docs/#how-to-install-percona-debian-ubuntu
