### ISSUE TITLE
Change password Vesta  | RounCube 1.2.2 on Centos 6.8 

### ISSUE THREAD

**Issue by sagoyanfisic** [serghey-rodin/vesta#909]
I want to change the password of my roundcube but it does not allow me to do, I followed several tutorials on how to correct it but still can not, somebody could help me please

[Click img](https://lh3.googleusercontent.com/-lxeIiVnPrWA/WCXOuwstGII/AAAAAAAAAVo/07WknRVChpAHwnkO3I0YBMvMA1Fbzf_jgCL0B/h324/2016-11-11.png)

**Comment by dpeca** [comment]
1. Open /usr/share/roundcubemail/plugins/password/config.inc.php
2. Find: $rcmail_config['password_vesta_host'] = 'localhost';
3. Change localhost to your server hostname (if you are not sure what is your hostname, open /etc/hostname file)

4. Get new source code from https://github.com/serghey-rodin/vesta/blob/master/install/rhel/6/roundcube/vesta.php
5. With that new code overwrite file /usr/share/roundcubemail/plugins/password/drivers/vesta.php

6. Run: chmod -R a=rwx /var/log/roundcubemail

**Comment by sagoyanfisic** [comment]
The error continues, even so. I'm using VestaCP 0.9.8

**Comment by dpeca** [comment]
Please provide here error log from /var/log/roundcubemail folder.

**Comment by dpeca** [comment]
Is your Vesta on port 8083 ?

**Comment by sagoyanfisic** [comment]
yeah, problem?

**Comment by sagoyanfisic** [comment]
If it is the port that I use, is there any problem in using it?

**Comment by dpeca** [comment]
No, it should be 8083.
What is your hostname and is that hostname public available? (you can answer to this message via private message on forum, my forum username is the same: **dpeca**)
I can not find the problem by reading the logs... maybe only solution will be to send me (of course if you want) SSH credentials via private message, so I can take a closer look to this issue.

**Comment by dpeca** [comment]
try this - https://github.com/serghey-rodin/vesta/commit/e44db3d2b04f128eba60ec74d867f5ee5982d3fa
