### ISSUE TITLE
Incorrect DNS IP Upon Saving

### ISSUE THREAD

**Issue by Rhyswilliamsza** [serghey-rodin/vesta#919]
### Operating System (OS/VERSION):

Debian 8

### VestaCP Version:

Github HEAD 22/11/2016

--------

Hi All,

When saving a domain under "Web", the system reverts the IP address of the domain under "DNS" to the **internal ip**, not the **NAT ip**, of the domain.

Hope that makes sense...

This only happens when the vesta control panel is running behind a NAT.

Rhys

**Comment by dpeca** [comment]
I fixed that bug on github, fix will be available in next version.
You can solve it by running in SSH:
```ip=$(ip addr|grep 'inet '|grep global|head -n1|awk '{print $2}'|cut -f1 -d/)
pub_ip=$(curl -s vestacp.com/what-is-my-ip/)
v-change-sys-ip-nat $ip $pub_ip```

...  and apply this fix -> https://github.com/serghey-rodin/vesta/commit/8df1d74ae33cdb2622db872b93c1ed32e4e9f539

**Comment by Rhyswilliamsza** [comment]
Sorry to reopen,

I just double checked, and I am definitely running on a commit which includes the above fix. Still same issue though :/

**Comment by dpeca** [comment]
Run:
```
ip=$(ip addr|grep 'inet '|grep global|head -n1|awk '{print $2}'|cut -f1 -d/)
grep NAT /usr/local/vesta/data/ips/$ip
```

and give me output here.
(mask IP if output prints IP of your server)

**Comment by Rhyswilliamsza** [comment]
NAT='{EXTIP}'

**Comment by Rhyswilliamsza** [comment]
EDIT:

Seems after it's been reset once, it doesn't reset again O_o

**Comment by dpeca** [comment]
What is reseted?
Is it working now?

Conf is OK as I can see.

**Comment by Rhyswilliamsza** [comment]
Absolutely no idea what changed, but it seems to be working now hahaha,

Thanks!

**Comment by roncooletz** [comment]
Hi, I am still experiencing the dns change from public ip to lan ip. When a user adds let's encrypt I can see that on the vesta logs it reverts back to lan ip before adding let's encrypt cert on the web gui. I am running on the latest version of vesta. Thanks.
