### ISSUE TITLE
Empty mail._domainkey

### ISSUE THREAD

**Issue by rakinzon** [serghey-rodin/vesta#949]
### Operating System (OS/VERSION):

Debian 8

### VestaCP Version:

newest git clone

### Installed Software (what you got with the installer):

Type here, e.g. php-fpm, apache, nginx, mysql

### Steps to Reproduce:

Aktivate DKIM on the mail tab and then look at the dns settings for this domain.

### Other Notes:

Anything else?

**Comment by dpeca** [comment]
I can cofirm this.
v16 worked fine with DKIM.
I will take a look tomorrow for this bug, but I will apriciete if someone else look for this bug, because I dont have too much time tomorrow.

**Comment by dpeca** [comment]
```
 # v-add-dns-record  'testnalog' 'qzebra.com' 'mail._domainkey.qzebra.com' 'TXT' '"k=rsa\; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCelUwOn0xfIuWo0ODym91RgJdRFIGb9oghKbVD1MA9abzkachrJdOzwH4ItjzpVVe7ZAwOPgefqn1+1IeZnk3z65FYfs6WNhH164cFU7CzyFXpcwNz2ZrzIsIQemv+c/H2mmSQU+t0SSd755QhN3j1Ri+qHm4bYkTd9yqKQWnFJwIDAQAB"'

idn: idna_to_ascii_4z: Output would be too large or too small
```

what is generating this error?

**Comment by dpeca** [comment]
I think this commit made a problem - https://github.com/serghey-rodin/vesta/commit/0c98233f2e4ae5316988b1b14aa9b965ded5e037

@serghey-rodin

**Comment by dpeca** [comment]
Yes, if I revert `-a` to `-u` in `v-add-dns-record` everything is working fine again.
So, it's that commit.

**Comment by Rhyswilliamsza** [comment]
+1

       -a, --idna-to-ascii
              Convert to ACE according to IDNA (default)

       -u, --idna-to-unicode
              Convert from ACE according to IDNA

Evidently issue arises with ascii v. unicode.

**Comment by dpeca** [comment]
Good catch @rainzon :)
Thank you a lot.
