### ISSUE TITLE
webmail issue 

### ISSUE THREAD

**Issue by darkworks** [serghey-rodin/vesta#953]
### Operating System (OS/VERSION):

Debian 8.3 (x86_64)

### VestaCP Version:

0.9.8.17

### Installed Software (what you got with the installer):

Type here, e.g. php-fpm, apache, nginx, maria

issue

when click on webmail ,   serverip/webmail 

it open default website , rather loading webmail

**Comment by dpeca** [comment]
And what about http://serverhostname/webmail/ ?

**Comment by darkworks** [comment]
same default website load with 404 page .

**Comment by SpaHost** [comment]
PHP 7 ? or PHP 5 ?
If you have installed PHP7 you have to reconfigure again all, Pear, RoundCube (have to install it manually, if you install or upgrade from apt it will crash)

**Comment by darkworks** [comment]
i have php 5

**Comment by core01** [comment]
@darkworks show yours nginx.conf/snignx.conf in /home/YOURUSERNAME/conf/web/

**Comment by darkworks** [comment]
@core01 ok here is nginx.conf file :: https://privnote.com/mZpYWt5t#wc1RyfcHl

**Comment by core01** [comment]
@darkworks you need to include this rows https://github.com/serghey-rodin/vesta/blob/master/install/debian/8/templates/web/nginx/php5-fpm/wordpress.tpl#L46-L48 in your tpm in /usr/local/vesta/data/templates/web/nginx/php-fpm or php5-fpm

**Comment by darkworks** [comment]
these three rows are already in wordpress.tpl it my side ...
also i should tell that my primary site which is https://www.w3db.xyz is not wordpress site , its custom php

```
server {
    listen      %ip%:%web_port%;
    server_name %domain_idn% %alias_idn%;
    root        %docroot%;
    index       index.php index.html index.htm;
    access_log  /var/log/nginx/domains/%domain%.log combined;
    access_log  /var/log/nginx/domains/%domain%.bytes bytes;
    error_log   /var/log/nginx/domains/%domain%.error.log error;

    location / {

        location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|css|js)$ {
            expires     max;
        }

        location ~ [^/]\.php(/|$) {
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            if (!-f $document_root$fastcgi_script_name) {
                return  404;
            }

            fastcgi_pass    %backend_lsnr%;
            fastcgi_index   index.php;
            include         /etc/nginx/fastcgi_params;
        }
    }

    error_page  403 /error/404.html;
    error_page  404 /error/404.html;
    error_page  500 502 503 504 /error/50x.html;

    location /error/ {
        alias   %home%/%user%/web/%domain%/document_errors/;
    }

    location ~* "/\.(htaccess|htpasswd)$" {
        deny    all;
        return  404;
    }

    include     /etc/nginx/conf.d/phpmyadmin.inc*;
    include     /etc/nginx/conf.d/phppgadmin.inc*;
    include     /etc/nginx/conf.d/webmail.inc*;

    include     %home%/%user%/conf/web/nginx.%domain%.conf*;
}

```

**Comment by Youssef20000** [comment]
> PHP 7 ? or PHP 5 ?
> If you have installed PHP7 you have to reconfigure again all, Pear, RoundCube (have to install it manually, if you install or upgrade from apt it will crash)

How Can I Do It
