### ISSUE TITLE
php-fpm pool doesn't exist - php7.0-fpm

### ISSUE THREAD

**Issue by danimalweb** [serghey-rodin/vesta#956]
### Operating System (OS/VERSION):

Debian 8

### VestaCP Version:

R17 - Fresh Install

### Installed Software (what you got with the installer):

php-fpm, nginx, mysql

### Steps to Reproduce:

I've installed PHP-7.0-fpm, everything is going great, I've created the templates, updated vesta.conf with the new backend name, all good. I can stop / start / restart the service.

When I create the domain name I get the error message:

"php-fpm pool doesn't exist"

Looking at the domain.sh line 87 I see:

```
pool=$(find /etc/php* -type d \( -name "pool.d" -o -name "*fpm.d" \))
    if [ ! -e "$pool" ]; then
        check_result $E_NOTEXIST "php-fpm pool doesn't exist"
    fi
```

Running ``$(find /etc/php* -type d \( -name "pool.d" -o -name "*fpm.d" \))`` on my system I get ``bash: /etc/php/7.0/fpm/pool.d: Is a directory``

Any idea why Vesta cannot find the pool?

Running ``service php7.0-fpm status`` shows everything is working fine.

Edit: I also updated: ``/usr/local/vesta/data/templates/web/php7.0-fpm/socket.tpl``

From ``/var/run/php5-%backend%.sock`` to ``/var/run/php/php7.0-%backend%.sock``

Thanks.

**Comment by anton-reutov** [comment]
Where are you find php7 on Debian 8 ?
php 5.6 installing by default on this version of Debian. This is not a bug, because this is your changes.
We can't be responsible for your actions

**Comment by danimalweb** [comment]
It was just a question about a specific part of the code. I figured this would be the best place to ask, sorry to have bothered.

**Comment by anton-reutov** [comment]
You can ask about this on our oficial forum
https://forum.vestacp.com/

**Comment by NikaYoda** [comment]
Why are you so mad? he just asked how to fix it, he changed it because he needs php7 maybe? is it bad? or why you had so bad reaction? vesta has so many bugs, people should never use this but still using and trust your code and I don't think it's normal to answer people like that.

**Comment by ninjao** [comment]
lol, talk about thread necromancy? Either way.. I feel like no-one here sounded angry or mad?

**Comment by bsbudhwar** [comment]
If you have multiple PHP then make change in that code like /etc/php/7.* or /etc/php/8.* so that vesta will look for specific version only.

otherwise vesta look for /etc/php* so that all versions of PHP is detected and vestacp don't know which version to be used.

So it's a small trick.
