### ISSUE TITLE
Error: LetsEncrypt account registration 400

### ISSUE THREAD

**Issue by dennisleussink** [serghey-rodin/vesta#957]
### Operating System (OS/VERSION):

 Centos 7 (64 bits)

### VestaCP Version:

Vesta 0.9.8-17

### Installed Software (what you got with the installer):

Default packages

### Steps to Reproduce:

1. Edit domain in web gui
2. Tick the SSL Support box
3. Tick the  Lets Encrypt Support box
4. Click save

Error: LetsEncrypt account registration 400

**Comment by Estilate** [comment]
Try executing **yum install vim-common**. After doing it it's now working for me :)

https://forum.vestacp.com/viewtopic.php?t=13179

**Comment by safirstudio** [comment]
i have the same error, vim already installed

**Comment by ja9adeesh** [comment]
try `reboot`. it worked for me on `Debian 8.7 VPS`
