### ISSUE TITLE
v-restore-user won't create MySQL user under Ubuntu 16.04

### ISSUE THREAD

**Issue by fengkaijia** [serghey-rodin/vesta#959]
### Operating System (OS/VERSION):

Ubuntu 16.04

### VestaCP Version:

0.9.8-17

### Installed Software (what you got with the installer):

bash vst-install.sh --nginx yes --apache yes --phpfpm no --vsftpd yes --proftpd no --exim yes --dovecot yes --spamassassin no --clamav no --named no --iptables no --fail2ban no --mysql yes --postgresql yes --remi no --quota no

### Steps to Reproduce:

1. Run ```v-backup-user xyz``` on a Debian 8.0 instance;
2. SCP the file to the new Ubuntu 16.04 instance;
3. ```v-restore-user xyz xyz.2016-11-26.tar```
4. MySQL ```SELECT * FROM mysql.user``` will found no entry start with xyz

### Other Notes:

If I go to https://vestacp:8083/edit/db/?database=xyz_abc, I can view and edit the password for the missing user, and then the user appear again.

**Comment by Skamasle** [comment]
I found a bug for this one, will report this night

**Comment by anton-reutov** [comment]
We wil check this problem on our test servers

**Comment by Skamasle** [comment]
Hi I check this and do some code changes as a hot fix for some servers if you want test until a vesta official solution check it here -> https://forum.vestacp.com/viewtopic.php?f=20&t=13239

In topic a try explain bug and all afected options, I not detect any more yet.
