### ISSUE TITLE
Document errors not included 

### ISSUE THREAD

**Issue by ianklemm** [serghey-rodin/vesta#974]
### Operating System (OS/VERSION):

Debian 8
### VestaCP Version:

Vesta 0.9.8-17

### Installed Software (what you got with the installer):

WEB Server:     apache2
Web Stats:      webalizer, awstats
FTP Server:     proftpd
Mail Server:    exim4 + dovecot + spamassassin
Database:       mysql
DNS server:     bind9
CRON:           cron
Firewall:       iptables+ fail2ban

### Steps to Reproduce:

When using the default hosting template, the document error templates are not included in the vHost.

**Comment by ianklemm** [comment]
push

**Comment by madeITBelgium** [comment]
I guess #994 fix this

**Comment by ianklemm** [comment]
Awesome, but I only fixed it for Debian 8 based systems, on other systems the error still occurs

**Comment by madeITBelgium** [comment]
On centOS the error documents are in the [httpd.conf](https://github.com/serghey-rodin/vesta/blob/master/install/rhel/6/httpd/httpd.conf). Maybe we can use this way to implement it in all the versions.

**Comment by ianklemm** [comment]
Yes, I think that would be the easiest way to do it.
