### ISSUE TITLE
mysql username must be =< 16 char

### ISSUE THREAD

**Issue by madhifallah** [serghey-rodin/vesta#977]
### Operating System (OS/VERSION): 

Centos 7.2 x64

### VestaCP Version: 

Vesta 0.9.8-17

### Installed Software (what you got with the installer):

ALL

### Steps to Reproduce:

username more than 16char are accepted in the UI but mysql ban them, so in vesta, you see it as existing and operational but mysql side it's not, without any error.

### Related Issues/Forum Threads:

Found anything that might be related to this? It might help us find the cause.

### Other Notes:

Just make sure the mysql username field is restricted to 16char and less

**Comment by Skamasle** [comment]
You can check this discussion ->  https://github.com/serghey-rodin/vesta/issues/860

**Comment by madhifallah** [comment]
IMHO a warning should be displayed in the frontend, and prevent the user form choosing a db name larger than 16char for if mysql is the db engine.

**Comment by SysVoid** [comment]
Continue discussion in the other thread.
