### ISSUE TITLE
Does LetsEncrypt support automatically renew?

### ISSUE THREAD

**Issue by DaniWinter** [serghey-rodin/vesta#978]
### Operating System (OS/VERSION):

CentOS 7

### VestaCP Version:

0.9.8 release 17

### Installed Software (what you got with the installer):

Default packages

### Steps to Reproduce:

Domain > SSL Support > Lets Encrypt Support

### Other Notes:

I have several subdomains, can I use 1 Let's Encrypt certificate for that?

**Comment by rakinzon** [comment]
Yes, there is an cronjob (/usr/local/vesta/bin/v-update-sys-queue letsencrypt and /usr/local/vesta/bin/v-update-letsencrypt-ssl) that should renew your certificates

**Comment by didyouexpectthat** [comment]
I can confirm that `v-update-letsencrypt-ssl` shows up for me automatically after adding letsencrypt to a domain, but `v-update-sys-queue letsencrypt` was not added to cron. Should this be automated too?
