### ISSUE TITLE
DKIM public key

### ISSUE THREAD

**Issue by rakinzon** [serghey-rodin/vesta#981]
### Operating System (OS/VERSION):

Debian 8

### VestaCP Version:

0.9.8-17

### Steps to Reproduce:

Enable DKIM on a mail domain

Mailscore tester says, that the public dkim key could not be loaded.

**Comment by dpeca** [comment]
What do you get when  you run  from console:
`dig @0 -t txt mail._domainkey.yourdomain.com`

**Comment by rakinzon** [comment]
I get the following output (but in the Vesta DNS settings I have a txt mail._domainkey entry):
; <<>> DiG 9.8.3-P1 <<>> @0 -t txt mail._domainkey.MYDOMAIN
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached


The problem occurs with multiple domains

**Comment by dpeca** [comment]
I can confirm this, something strange is happening here for NEWLY added domain.
I see DKIM key in DNS editor, and even in .db file.
But...
Bind writes in syslog this:
`Dec  6 23:19:27 fountain named[869]: zone test.com/IN: 'test.com' found SPF/TXT record but no SPF/SPF record found, add matching type SPF record`

Lines in /home/test/conf/dns/test.com.db looks fine:
```@       14400   IN      TXT             "v=spf1 a mx ip4:MYIP ~all"
_domainkey      14400   IN      TXT             "t=y; o=~;"
mail._domainkey 14400   IN      TXT             "k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDR106sVryDNKfftNh0fImWTHWioenQNcLDZRI90TMzp672fhI3985z6qb0uzgcU/Cm1VjxQHfIOGQhaIjUaA20DxJlThIpFAN9vtXc8knT7Cp5xcwYR6ir+KTm/2OgwszZ6ugK2csqn01SmcMoa+DVVMzoxulV4cGinMiBk//g+wIDAQAB"
```

With `dig` I can see TXT for `test.com` - but I can't see TXT record `mail._domainkey.test.com`

For old domain (added befor 2 months, probably before v17) everything works fine, I can `dig` mail._domainkey for those domains.

What a hell...  ?

**Comment by dpeca** [comment]
Something other is happening here.

If I just `touch` .db file and reload bind, everything begin to works fine.

```
# touch /home/test/conf/dns/test2.com.db
# service bind9 reload
```

It looks like bind is not reloading zone after DKIM is added.

**Comment by dpeca** [comment]
... probably because file is altered (with DKIM) in the same second when bind already loaded that file (when zone is created), and that's why bind don't see that zone file is altered.

**Comment by rakinzon** [comment]
Also after "touching" die .db file and reloading the bind9 service I get the message, that the mailscore tester could not get my public key.

**Comment by dpeca** [comment]
But do you can get it via `dig` command?

**Comment by rakinzon** [comment]
; <<>> DiG 9.10.3-P4-Ubuntu <<>> @0 -t txt mail._domainkey.DOMAIN
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 26791
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;mail._domainkey.DOMAIN.        IN      TXT

;; AUTHORITY SECTION:
DOMAIN.de.         180     IN      SOA     MYDNS.de. root.DOMAIN.de. 2016120602 7200 3600 1209600 180

;; Query time: 161 msec
;; SERVER: 127.0.0.1#53(0.0.0.0)
;; WHEN: Thu Dec 08 13:43:56 CET 2016
;; MSG SIZE  rcvd: 119

**Comment by rakinzon** [comment]
Yes I´ve tried that from my Vesta server.
From my home pc I get the "same old error":
; <<>> DiG 9.8.3-P1 <<>> @0 -t txt mail._domainkey.MYDOMAIN
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

Restarting bind9 do not bring anything

**Comment by dpeca** [comment]
Yes, but you can use @0 when you use dig from PC.
Anyway, it's bad that dig on Vesta server does not return result.

Do you can see DKIM in DNS editor?

**Comment by rakinzon** [comment]
I´ve found the error! On some Domains (from testing around Bug #949) the full domain name stands in the .db file
