### ISSUE TITLE
mysqld dead but subsys locked

### ISSUE THREAD

**Issue by robindirksen1** [serghey-rodin/vesta#987]
### Operating System (OS/VERSION):

Centos 6.5

### VestaCP Version:

0.9.8-17

### Installed Software (what you got with the installer):

standard installation

### Steps to Reproduce:

161208 17:58:18 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
161208 17:58:19 [Note] /usr/libexec/mysqld (mysqld 5.5.51) starting as process 22679 ...
161208 17:58:19 [Note] Plugin 'FEDERATED' is disabled.
161208 17:58:19 InnoDB: The InnoDB memory heap is disabled
161208 17:58:19 InnoDB: Mutexes and rw_locks use GCC atomic builtins
161208 17:58:19 InnoDB: Compressed tables use zlib 1.2.3
161208 17:58:19 InnoDB: Using Linux native AIO
161208 17:58:19 InnoDB: Initializing buffer pool, size = 128.0M
InnoDB: mmap(137363456 bytes) failed; errno 12
161208 17:58:19 InnoDB: Completed initialization of buffer pool
161208 17:58:19 InnoDB: Fatal error: cannot allocate memory for the buffer pool
161208 17:58:19 [ERROR] Plugin 'InnoDB' init function returned error.
161208 17:58:19 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
161208 17:58:19 [ERROR] Unknown/unsupported storage engine: InnoDB
161208 17:58:19 [ERROR] Aborting

161208 17:58:19 [Note] /usr/libexec/mysqld: Shutdown complete

161208 17:58:19 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
161208 17:58:23 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
161208 17:58:23 [Note] /usr/libexec/mysqld (mysqld 5.5.51) starting as process 23341 ...
161208 17:58:23 [Note] Plugin 'FEDERATED' is disabled.
161208 17:58:23 InnoDB: The InnoDB memory heap is disabled
161208 17:58:23 InnoDB: Mutexes and rw_locks use GCC atomic builtins
161208 17:58:23 InnoDB: Compressed tables use zlib 1.2.3
161208 17:58:23 InnoDB: Using Linux native AIO
161208 17:58:23 InnoDB: Initializing buffer pool, size = 128.0M
InnoDB: mmap(137363456 bytes) failed; errno 12
161208 17:58:23 InnoDB: Completed initialization of buffer pool
161208 17:58:23 InnoDB: Fatal error: cannot allocate memory for the buffer pool
161208 17:58:23 [ERROR] Plugin 'InnoDB' init function returned error.
161208 17:58:23 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
161208 17:58:23 [ERROR] Unknown/unsupported storage engine: InnoDB
161208 17:58:23 [ERROR] Aborting

161208 17:58:23 [Note] /usr/libexec/mysqld: Shutdown complete

161208 17:58:23 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended

### Other Notes:

service mysqld status = mysqld dead but subsys locked

The problem came after the update to vestacp 0.9.8-17 from 0.9.8-16

**Comment by dpeca** [comment]
`161208 17:58:19 InnoDB: Fatal error: cannot allocate memory for the buffer pool`

I can't see how this can be related to VestaCP.
Your server just dont have a free space in RAM.... I believe the case is not related to v17.
