### ISSUE TITLE
Bug! SSL cert not changeble on tipical installation from repo!

### ISSUE THREAD

**Issue by phpcodepro** [serghey-rodin/vesta#988]
### Operating System (OS/VERSION):
Debian 7

### VestaCP Version:

0.9.8-17

### Installed Software (what you got with the installer):

php-fpm, apache, nginx, mysql

### Steps to Reproduce:

curl -O http://vestacp.com/pub/vst-install.sh
bash vst-install.sh

### Related Issues/Forum Threads:
----

### Other Notes:
Package: http://apt.vestacp.com/wheezy/pool/vesta/v/vesta/vesta_0.9.8-17_i386.deb

File: ./usr/local/vesta/bin/v-list-sys-vesta-ssl Line: 102

Find:
key=$(cat $VESTA/ssl/certificate.crt |sed ':a;N;$!ba;s/\n/\\n/g')

Replace:
key=$(cat $VESTA/ssl/certificate.key |sed ':a;N;$!ba;s/\n/\\n/g')

**Comment by Skamasle** [comment]
This was fixed -> https://github.com/serghey-rodin/vesta/pull/980
