### ISSUE TITLE
API - PHP change email password.

### ISSUE THREAD

**Issue by junglewp** [serghey-rodin/vesta#997]
Hello Guys,

It have been months now since I am searching how to change emails passwords with PHP-API,
I really need your help on this :)

I already found out how to create an email account using the code below, it works perfectly so far : 

<p><?php</p>

// Server credentials
$vst_hostname = 'server.vestacp.com';
$vst_username = 'admin';
$vst_password = 'p4ssw0rd';
$vst_returncode = 'yes';
$vst_command = 'v-add-mail-account';

// New Account
$username = 'admin';
$domain = 'yourdomain.com';
$acount = 'info'; //info@yourdomain.com
$password = 'emailpassword';

// Prepare POST query
$postvars = array(
    'user' => $vst_username,
    'password' => $vst_password,
    'returncode' => $vst_returncode,
    'cmd' => $vst_command,
    'arg1' => $username,
    'arg2' => $domain,
    'arg3' => $acount,
    'arg4' => $password
);
$postdata = http_build_query($postvars);

// Send POST query via cURL
$postdata = http_build_query($postvars);
$curl = curl_init();
curl_setopt($curl, CURLOPT_URL, 'https://' . $vst_hostname . ':8083/api/');
curl_setopt($curl, CURLOPT_RETURNTRANSFER,true);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_POSTFIELDS, $postdata);
$answer = curl_exec($curl);

// Check result
if($answer == 0) {
    echo "User account has been successfuly created\n";
} else {
    echo "Query returned error code: " .$answer. "\n";
}
?>

Best regards

**Comment by sigfriedseldeslachts** [comment]
Hi!

Could you tidy up your code so I can take a better look tomorrow.

Greetings

**Comment by junglewp** [comment]
Hello Sigfried,

Thanks so much for your answer it is so much appreciated! I added the paragraph tag and it seems to be better.

**Comment by fgth** [comment]
Hi guys,
any update about this question ? I have the same need based on a simple php script allowing a mail user to change his password.
Thank you,
Frank

**Comment by madeITBelgium** [comment]
You need to use this command: https://github.com/serghey-rodin/vesta/blob/master/bin/v-change-mail-account-password
